unpackaged/main/default/objects/Pricebook2/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/Service_Level_Price__c.object-meta.xml
<CustomObject>
    <label>Service Level Price</label>
    <nameField>
        <displayFormat>LvlSP-{000000000}</displayFormat>
        <label>Service Level Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Level Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Discount_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Discount_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount Schedule</label>
    <referenceTo>SBQQ__DiscountSchedule__c</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <label>Lower Bound</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Maximum_Price__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Price__c</fullName>
    <inlineHelpText>In the case of Excess Charge for a Product with Excess Pricing Method Type equals to 'Capped', it is necessary to fill a Maximum Price on the Charge Service Level Price Records OR a Product Maximum Quantity.</inlineHelpText>
    <label>Maximum Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/RegularPrice__c.field-meta.xml
<CustomField>
    <fullName>RegularPrice__c</fullName>
    <label>Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Sales_Purposes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purposes__c</fullName>
    <label>Sales Purposes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <label>Service Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <label>Upper Bound</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/recordTypes/Block_Pricing.recordType-meta.xml
<RecordType>
    <fullName>Block_Pricing</fullName>
    <active>true</active>
    <label>Block Pricing</label>
</RecordType>

unpackaged/main/default/objects/Service_Level_Price__c/recordTypes/List_Pricing.recordType-meta.xml
<RecordType>
    <fullName>List_Pricing</fullName>
    <active>true</active>
    <label>List Pricing</label>
</RecordType>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/DuplicateServiceLevelPrice.cls
/**
* @description       : 
* @author            : Keshav Matabadul
* @group             : 
* @last modified on  : 05-09-2022
* @last modified by  : Keshav Matabadul
**/
public with sharing class DuplicateServiceLevelPrice {
    
    public static final String STANDARDPRICEBOOKID = getStdPriceBook();
    
    //Can Input Multiple Variable at once in a flow 
    public class flowInputs {
        @InvocableVariable
        public Service_Level_Price__c objServiceLevelPrice;
        
        @InvocableVariable
        public String productRT;
    }
    
    public static Id getStdPriceBook() {
        return [select Id, Name, IsActive from PriceBook2 where IsStandard=True LIMIT 1].Id;   
    }
    
    @InvocableMethod(label='Insert SLP' description='Insert SLP for all Pricebook which is not standard')
    public static void CreateServiceLevelPrice(List<flowInputs> inputVariables) {
        
        set<String> setSalesPurpose = new set<String>();
        Set<Id> setProductIds = new set<Id>();
        map<Id,string> mapPB = new map<Id,string>();
        Set<Decimal> setLowerBound = new Set<Decimal>();
        Set<Decimal> setUpperBound = new Set<Decimal>();
        Set<String> setServiceLevel = new Set<String>();
        List<Service_Level_Price__c> listInsertSLP = new List<Service_Level_Price__c>();
        String productRecordType;
        String rtDevelopername;
        String pricebookId;
        Set<Id> setPriceBook = new Set<Id>();
        
        
        for(DuplicateServiceLevelPrice.flowInputs valuesFromFlow:inputVariables){
            
            productRecordType = valuesFromFlow.productRT;
            pricebookId = valuesFromFlow.objServiceLevelPrice.Price_Book__c;
            setProductIds.add(valuesFromFlow.objServiceLevelPrice.Product__c);
            setLowerBound.add(valuesFromFlow.objServiceLevelPrice.Lower_Bound__c);
            setUpperBound.add(valuesFromFlow.objServiceLevelPrice.Upper_Bound__c);
            setServiceLevel.add(valuesFromFlow.objServiceLevelPrice.Service_Level__c);
            
            if(valuesFromFlow.objServiceLevelPrice.Sales_Purposes__c.contains(';')){
                list<String> listSalesPurpose = valuesFromFlow.objServiceLevelPrice.Sales_Purposes__c.split(';');
                for (String str:listSalesPurpose){
                    setSalesPurpose.add(str);
                }
                
            }else{
                setSalesPurpose.add(valuesFromFlow.objServiceLevelPrice.Sales_Purposes__c);
            }
            
        }
        
        if(pricebookId == STANDARDPRICEBOOKID){
            for(PricebookEntry PE:[SELECT Id,Pricebook2Id,Name,Pricebook2.Currency__c, pricebook2.Name FROM PricebookEntry 
                                   WHERE Product2Id IN:setProductIds AND Pricebook2Id =:STANDARDPRICEBOOKID AND IsActive = true]){
                                       mapPB.put(PE.Pricebook2Id,PE.Pricebook2.Currency__c);
                                   }
        }else{//Get other non-standard pricebooks 01s1t0000048XiVAAU
            for(PricebookEntry PE:[SELECT Id,Pricebook2Id,Name,Pricebook2.Currency__c, pricebook2.Name FROM PricebookEntry 
                                   WHERE Product2Id IN:setProductIds AND Pricebook2Id !=:STANDARDPRICEBOOKID AND IsActive = true]){
                                       mapPB.put(PE.Pricebook2Id,PE.Pricebook2.Currency__c);
                                   }
        }
        
        //Query all Currency 
        Map<String,CurrencyType> mapAllCurrency = new Map<String,CurrencyType>();
        if(mapPB.size()>0){
            for(CurrencyType ct:[SELECT Id,ConversionRate,IsoCode,IsActive FROM CurrencyType WHERE IsActive = true AND IsoCode IN:mapPB.values()]){
                mapAllCurrency.put(ct.IsoCode, ct);
            }
        }
        
        
        //Set RecordType
        if(productRecordType =='Block'){
            rtDevelopername = 'Block_Pricing';
        }else{
            rtDevelopername = 'List_Pricing';
        }
        
        for(String str:setSalesPurpose){
            for(String pb:mapPB.keySet()){
                for(DuplicateServiceLevelPrice.flowInputs valuesFromFlow:inputVariables){
                    Service_Level_Price__c slp = new Service_Level_Price__c();
                    if(productRecordType =='Block'){
                        slp.Upper_Bound__c = valuesFromFlow.objServiceLevelPrice.Upper_Bound__c;
                        slp.Lower_Bound__c = valuesFromFlow.objServiceLevelPrice.Lower_Bound__c;
                    }else{
                        slp.Discount_Schedule__c = (valuesFromFlow.objServiceLevelPrice.Discount_Schedule__c != null?valuesFromFlow.objServiceLevelPrice.Discount_Schedule__c:null);
                    }
                   
                    slp.Service_Level__c = valuesFromFlow.objServiceLevelPrice.Service_Level__c;
                    slp.Price_Book__c =  pb;
                    slp.Product__c = valuesFromFlow.objServiceLevelPrice.Product__c;
                    slp.Sales_Purpose__c = str;
                    slp.recordTypeId = Schema.SObjectType.Service_Level_Price__c.getRecordTypeInfosByDeveloperName().get(rtDevelopername).getRecordTypeId();
                    slp.Sales_Purposes__c = null;
                    slp.RegularPrice__c = (valuesFromFlow.objServiceLevelPrice.RegularPrice__c != null?valuesFromFlow.objServiceLevelPrice.RegularPrice__c:0) * mapAllCurrency.get(mapPB.get(pb)).ConversionRate;                    
                    slp.Maximum_Price__c = valuesFromFlow.objServiceLevelPrice.Maximum_Price__c;
                    slp.CurrencyIsoCode = mapPB.get(pb);
                    listInsertSLP.add(slp);
                }
            }
        }
        
        if(listInsertSLP.size()>0){
            insert listInsertSLP;
        }
    }
    
    
    
}