unpackaged/main/default/objects/BillingPlan__c/BillingPlan__c.object-meta.xml
<CustomObject>
    <description>Use to define a billing plan on quote</description>
    <label>Billing Plan</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Billing Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BillingPlan__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Billing Plans</relationshipLabel>
    <relationshipName>Billing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/BillingTransaction__c.object-meta.xml
<CustomObject>
    <description>Child object of Billing Plan used to manage related transactions</description>
    <label>Billing Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BillingTransaction__c/fields/BillingPlan__c.field-meta.xml
<CustomField>
    <fullName>BillingPlan__c</fullName>
    <label>Billing Plan</label>
    <referenceTo>BillingPlan__c</referenceTo>
    <relationshipLabel>Billing Transactions</relationshipLabel>
    <relationshipName>Billing_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/EstimatedDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDate__c</fullName>
    <label>Estimated Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/MaxDate__c.field-meta.xml
<CustomField>
    <fullName>MaxDate__c</fullName>
    <label>Max Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <inlineHelpText>Allowed values : "1", "1.1", ".1"</inlineHelpText>
    <label>Step</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/BillingPlan__c.field-meta.xml
<CustomField>
    <fullName>BillingPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Plan</label>
    <referenceTo>BillingPlan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Package.recordType-meta.xml
<RecordType>
    <fullName>Package</fullName>
    <active>true</active>
    <label>Package</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/classes/VFC05_getBillingTransactions_TEST.cls
/**
* @author Moganaden C - Comforth
* @date 2023-04-12
* @description VFC05_getBillingTransactions_TEST          
*/
@isTest
public class VFC05_getBillingTransactions_TEST {
    
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static final String PRIMARY_CONTACT_EMAIL = 'primarycontact@email.com';
    @testSetup static void setup(){
        System.runAs(adminUser){ 
            Insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True); 

            Test.startTest();
            //create account
            List<Account> listAcc = new List<Account>();
            for(Integer i=0; i<1;i++ ){
                listAcc.add( new UTIL_TestFactory.AccountFactory().createAccountWithNature(i));
            }
            insert listAcc;

            //create contact
            Contact primaryContact = new UTIL_TestFactory.ContactFactory().createContact(listAcc[0].Id);
            primaryContact.Email = PRIMARY_CONTACT_EMAIL;
            insert primaryContact;

            PriceBook2 standardPricebook = new UTIL_TestFactory.PricebookFactory().activateStdPriceBook();

            //create opportunity
            List<Opportunity> listOpp = new List<Opportunity>();
            for(Integer i=0; i<1;i++){
                listOpp.add(new UTIL_TestFactory.OpportunityFactory().createOpportunity(listAcc[i].Id, false, false));
            }
            insert listOpp;
        
            //create product2
            List<Product2> listProduct = new List<Product2>{
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost'),
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost'),
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost')
            };
            insert listProduct;

            List<PricebookEntry> listPBE = new List<PricebookEntry>{
                new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(standardPricebook.id, listProduct[0].id)
            };
            insert listPBE; 

            //create quote in mass (cannot create more than that because of SOQL & CPU limit exceeded from CPQ SBQQ package)
            List<SBQQ__Quote__c> listQuotes = new List<SBQQ__Quote__c>();
            for(Integer i=0; i<1;i++ ){
                listQuotes.add(new UTIL_TestFactory.SBQQ_QuoteFactory().createSBQQ_QuoteV2(listOpp[i].Id, listAcc[i].Id, primaryContact.Id, listAcc[i].Id));
            }
            insert listQuotes;
            
            
            //create BillingPlan
            List<BillingPlan__c> listBillingPlan = new List<BillingPlan__c>{
                new BillingPlan__c(Quote__c=listQuotes[0].Id)
            };
            insert listBillingPlan;

 			//create BillingTransaction
            List<BillingTransaction__c> listBillingTransaction = new List<BillingTransaction__c>{
                new BillingTransaction__c(Name='Order',Step__c='1',EstimatedDate__c = date.today(),MaxDate__c = date.today(),BillingPlan__c = listBillingPlan[0].Id,Percentage__c = 2 )
            };
            insert listBillingTransaction;
            
        	Test.stopTest();

        }//end RunAs
    }//end setup
    
    
    
    static testMethod void test_init() {
		System.runAs(adminUser){
			SBQQ__Quote__c QuoteId = [SELECT Id FROM SBQQ__Quote__c limit 1];
            
            Test.startTest(); 
            
			PageReference pageRef = Page.VFP05_getBillingTransactions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('qid',QuoteId.id);
            
            VFC05_getBillingTransactions vfc05 = new VFC05_getBillingTransactions();
            vfc05.init();
            Test.stopTest();
             
         }
     }

}