unpackaged/main/default/objects/BillingPlan__c/BillingPlan__c.object-meta.xml
<CustomObject>
    <description>Use to define a billing plan on quote</description>
    <label>Billing Plan</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Billing Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BillingPlan__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Billing Plans</relationshipLabel>
    <relationshipName>Billing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/BillingPlan__c/fields/QuoteTotal__c.field-meta.xml
<CustomField>
    <fullName>QuoteTotal__c</fullName>
    <formula>Quote__r.QuoteTotalXRPProducts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Total (XRP products)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/BillingTransaction__c.object-meta.xml
<CustomObject>
    <description>Child object of Billing Plan used to manage related transactions</description>
    <label>Billing Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BillingTransaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Percentage__c *  BillingPlan__r.QuoteTotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/BillingPlan__c.field-meta.xml
<CustomField>
    <fullName>BillingPlan__c</fullName>
    <label>Billing Plan</label>
    <referenceTo>BillingPlan__c</referenceTo>
    <relationshipLabel>Billing Transactions</relationshipLabel>
    <relationshipName>Billing_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/EstimatedDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDate__c</fullName>
    <label>Estimated Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/MaxDate__c.field-meta.xml
<CustomField>
    <fullName>MaxDate__c</fullName>
    <label>Max Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <inlineHelpText>Allowed values : "1", "1.1", ".1"</inlineHelpText>
    <label>Step</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BillingTransaction__c/fields/StepNumber__c.field-meta.xml
<CustomField>
    <fullName>StepNumber__c</fullName>
    <formula>VALUE(Step__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Step Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/BillingPlan__c.field-meta.xml
<CustomField>
    <fullName>BillingPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Plan</label>
    <referenceTo>BillingPlan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/Service_Level_Price__c.object-meta.xml
<CustomObject>
    <label>Service Level Price</label>
    <nameField>
        <displayFormat>LvlSP-{000000000}</displayFormat>
        <label>Service Level Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Level Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/VFC05_getBillingTransactions.cls
/**
* @author Moganaden C - Comforth Karoo
* @date 20213-04-12
* @description Trigger handler class for Service_Level_Price__c
*/
public class VFC05_getBillingTransactions {
    public String quoteId {get;set;}
    public String currencyCode {get;set;}
    public Double totalTransaction {get;set;}
    public List<BillingTransaction__c> lstBillingTransaction {get;set;}
    
    public void init(){
       quoteId =  ApexPages.currentPage().getParameters().get('qid');
       List<BillingPlan__c> lstBillingPlan = [SELECT id,QuoteTotal__c,CurrencyIsoCode,Quote__c,(SELECT id,Step__c,Name,EstimatedDate__c,Percentage__c,MaxDate__c
                                                                  ,Description__c,Amount__c
                                                         FROM Billing_Transactions__r ORDER BY StepNumber__c ASC) 
                                              FROM BillingPlan__c 
                                              WHERE Quote__c =: quoteId 
                                              ORDER BY createdDate DESC
                                              LIMIT 1];
        
       lstBillingTransaction = lstBillingPlan[0].Billing_Transactions__r;
       totalTransaction = lstBillingPlan[0].QuoteTotal__c;
       currencyCode = lstBillingPlan[0].CurrencyIsoCode;
       system.debug('MCU lstBillingTransaction: ' + lstBillingTransaction);

    }

}