unpackaged/main/default/objects/B2B_Settings__c/B2B_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store global params for B2B CEGID Store</description>
    <label>B2B Settings</label>
</CustomObject>

unpackaged/main/default/objects/B2B_Settings__c/fields/StoreDomain__c.field-meta.xml
<CustomField>
    <fullName>StoreDomain__c</fullName>
    <defaultValue>"https://store.cegid.com"</defaultValue>
    <label>Store domain</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StripePublishableKey__c.field-meta.xml
<CustomField>
    <fullName>StripePublishableKey__c</fullName>
    <defaultValue>"pk_test_51J3G9THyPvQW0JfV0OddzUOOkYQM50uC8wzPfzckGqqCNVKVo4vJssOcNTZIRnksbloJZBHc4AIv2m1nEKU7TAeA00xLWtdquz"</defaultValue>
    <description>Populate with the value of the publishable key in the Stripe Dashboard</description>
    <inlineHelpText>Populate with the value of the publishable key in the Stripe Dashboard</inlineHelpText>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/B2B_HostedPaymentController.cls
/**
 * @description       : Controller for the Hosted iFrame solution to return the LE Domain and Stripe Publishable Key
 * @author            : Gulshan DOORGAH gulshan.doorgah@comforth-karoo.eu
 * @group             : B2B
 * @last modified on  : 2021-11-30
 * @last modified by  : Gulshan DOORGAH gulshan.doorgah@comforth-karoo.eu
**/
public with sharing class B2B_HostedPaymentController {
    private static final B2B_Settings__c SETTINGS = B2B_Settings__c.getOrgDefaults();

    public String lexOrigin {
        get {
            //Populate with the value of the domain of the LE Community
            return SETTINGS.StoreDomain__c;
        }
        set;
    }
    
    public String stripeId {
        get {
            //Populate with the value of the publishable key in the Stripe Dashboard 
            return SETTINGS.StripePublishableKey__c;
        }
        set;
    }

	//Returns the Visualforce URL to leverage in the LWC
    @AuraEnabled(cacheable=true)
    public static String getVisualforceURL() {
        //return URL.getOrgDomainUrl().toExternalForm().split('\\.')[0] + '--c.visualforce.com';
        return SETTINGS.StoreDomain__c;
    }
}