unpackaged/main/default/objects/B2B_Settings__c/B2B_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store global params for B2B CEGID Store</description>
    <label>B2B Settings</label>
</CustomObject>

unpackaged/main/default/objects/B2B_Settings__c/fields/StoreDomain__c.field-meta.xml
<CustomField>
    <fullName>StoreDomain__c</fullName>
    <defaultValue>"https://store.cegid.com"</defaultValue>
    <label>Store domain</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StripePublishableKey__c.field-meta.xml
<CustomField>
    <fullName>StripePublishableKey__c</fullName>
    <defaultValue>"pk_test_51J3G9THyPvQW0JfV0OddzUOOkYQM50uC8wzPfzckGqqCNVKVo4vJssOcNTZIRnksbloJZBHc4AIv2m1nEKU7TAeA00xLWtdquz"</defaultValue>
    <description>Populate with the value of the publishable key in the Stripe Dashboard</description>
    <inlineHelpText>Populate with the value of the publishable key in the Stripe Dashboard</inlineHelpText>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/B2B_HostedPaymentController_TEST.cls
/**
 * @description       : Test class for B2B_HostedPaymentController
 * @author            : Gulshan DOORGAH gulshan.doorgah@comforth-karoo.eu
 * @group             : B2B
 * @last modified on  : 2021-11-29
 * @last modified by  : Gulshan DOORGAH gulshan.doorgah@comforth-karoo.eu
**/
@IsTest
private class B2B_HostedPaymentController_TEST {
    private static final B2B_Settings__c SETTINGS = B2B_Settings__c.getOrgDefaults();

    @isTest(SeeAllData=true) static void testLexOrigin() {
        B2B_HostedPaymentController controller = new B2B_HostedPaymentController();
        System.assertEquals(SETTINGS.StoreDomain__c, controller.lexOrigin, 'Domain not correct');
    }

    @isTest(SeeAllData=true) static void testGetVisualforceURL() {
        System.assertEquals(SETTINGS.StoreDomain__c, B2B_HostedPaymentController.getVisualforceURL(), 'Domain not correct');
    }

    @isTest(SeeAllData=true) static void testStripeId() {
        B2B_HostedPaymentController controller = new B2B_HostedPaymentController();
        System.assertEquals(SETTINGS.StripePublishableKey__c, controller.stripeId, 'Key not correct');
    }
}