unpackaged/main/default/objects/B2B_Settings__c/B2B_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store global params for B2B CEGID Store</description>
    <label>B2B Settings</label>
</CustomObject>

unpackaged/main/default/objects/B2B_Settings__c/fields/StoreLoginURL__c.field-meta.xml
<CustomField>
    <fullName>StoreLoginURL__c</fullName>
    <label>Store Login URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CartItem/fields/TECH_SessionCode__c.field-meta.xml
<CustomField>
    <fullName>TECH_SessionCode__c</fullName>
    <description>US W-001812 BtoB_USXX_Affichage des dates de sessions pour un produit de formation vendu unitairement</description>
    <label>Session Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CartItem/fields/TECH_SessionDate__c.field-meta.xml
<CustomField>
    <fullName>TECH_SessionDate__c</fullName>
    <description>US W-001812 BtoB_USXX_Affichage des dates de sessions pour un produit de formation vendu unitairement</description>
    <label>Session Date</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/B2BOrder__c.field-meta.xml
<CustomField>
    <fullName>B2BOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to differentiate between an Order created from the Store VS one created from CPQ.
US W-001599 - BtoB_US28_mail de confirmation de commande</description>
    <inlineHelpText>Set to TRUE if the Order is created from the Store.</inlineHelpText>
    <label>B2B Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>VMO 20211007: Created LOOKUP on Cart to get CartItem Information in apex to create the Training Session records using the fields Session Date and Session Code that are saved on the CartItem when user adds a Product to his Cart.</description>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>34</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/New_IBAN__c.field-meta.xml
<CustomField>
    <fullName>New_IBAN__c</fullName>
    <label>IBAN</label>
    <length>34</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/TECH_AccountName__c.field-meta.xml
<CustomField>
    <fullName>TECH_AccountName__c</fullName>
    <description>US W-001599 - BtoB_US28_mail de confirmation de commande</description>
    <formula>Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/TECH_CreatedDateFrench__c.field-meta.xml
<CustomField>
    <fullName>TECH_CreatedDateFrench__c</fullName>
    <description>US W-001599 - BtoB_US28_mail de confirmation de commande</description>
    <formula>TEXT(DAY(DATEVALUE(CreatedDate))) 
+ ' ' 
+ CASE(TEXT(MONTH(DATEVALUE(CreatedDate))), 
"1", "janv.", 
"2", "févr.",
"3", "mars",
"4", "avr.",
"5", "mai",
"6", "juin",
"7", "juil.",
"8", "août",
"9", "sept.",
"10", "oct.",
"11", "nov.",
"12", "déc.",
null) 
+ ' ' 
+ TEXT(YEAR(DATEVALUE(CreatedDate)))</formula>
    <label>Created Date (French)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/TECH_ProductName__c.field-meta.xml
<CustomField>
    <fullName>TECH_ProductName__c</fullName>
    <description>US W-001599 - BtoB_US28_mail de confirmation de commande</description>
    <formula>Product2.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Participant__c/fields/CartItemId__c.field-meta.xml
<CustomField>
    <fullName>CartItemId__c</fullName>
    <label>CartItemId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Civilite__c.field-meta.xml
<CustomField>
    <fullName>Civilite__c</fullName>
    <label>Civilité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>Prénom</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/TrainingSession__c.object-meta.xml
<CustomObject>
    <description>W-001277 : Training sessions related to quote line with training products</description>
    <label>Training Session</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Training Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TrainingSession__c/fields/B2BOrder__c.field-meta.xml
<CustomField>
    <fullName>B2BOrder__c</fullName>
    <formula>Order__r.B2BOrder__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>B2B Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>W-001277 Order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Training Sessions</relationshipLabel>
    <relationshipName>TrainingSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Training Sessions</relationshipLabel>
    <relationshipName>Training_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/ParticipantEmail__c.field-meta.xml
<CustomField>
    <fullName>ParticipantEmail__c</fullName>
    <description>Training participant email address</description>
    <label>Participant Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/ParticipantFirstName__c.field-meta.xml
<CustomField>
    <fullName>ParticipantFirstName__c</fullName>
    <description>Training participant first name</description>
    <label>Participant First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/ParticipantLastName__c.field-meta.xml
<CustomField>
    <fullName>ParticipantLastName__c</fullName>
    <description>Training participant last name</description>
    <label>Participant Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/ParticipantSalutation__c.field-meta.xml
<CustomField>
    <fullName>ParticipantSalutation__c</fullName>
    <description>Participant salutation</description>
    <label>Participant Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/SessionCode__c.field-meta.xml
<CustomField>
    <fullName>SessionCode__c</fullName>
    <label>Session Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrainingSession__c/fields/SessionDate__c.field-meta.xml
<CustomField>
    <fullName>SessionDate__c</fullName>
    <label>Session Date</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/B2B_OrderConfirmationEmail.cls
/**
 * @author Varun Molla - Comforth Karoo
 * @date 2021-09-15
 * @modified 
 * @group B2B
 * @description US W-001599 - BtoB_US28_mail de confirmation de commande   
*/
public without sharing class B2B_OrderConfirmationEmail {

    private static final B2B_Settings__c B2B_SETTINGS = B2B_Settings__c.getOrgDefaults();
    private static final OrgWideEmailAddress owa = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address = 'noreply@cegid.com'];

    @InvocableMethod(label='Create Training Session Records' description='Creates training session records from the list of Participants x the number of cart items' category='Order')
    public static void createTrainingSessionRecords(List<CartCheckoutSession> listMainCheckoutSession){
        //System.debug('>>> B2B_OrderConfirmationEmail listMainCheckoutSession: ' + listMainCheckoutSession);

        CartCheckoutSession mainCheckoutSession = listMainCheckoutSession[0];

        String orderId = '';

        for(CartCheckoutSession ccs : [SELECT Id, OrderId FROM CartCheckoutSession WHERE Id = :mainCheckoutSession.Id]){
            orderId = ccs.OrderId;
        }

        String strQueryOrder = '';
        Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Order.fields.getMap();
        for (String fieldName : schemaFieldMap.keySet()) {
            if(schemaFieldMap.get(fieldName).getDescribe().isAccessible()){
                strQueryOrder += (strQueryOrder == '') ? 'SELECT ' + fieldName : ', ' + fieldName;
            }
        }
        strQueryOrder += ' FROM Order where Id =: orderId';

        Order order = Database.query(strQueryOrder);

        //System.debug('>> order ID: ' + order);

        if(order.B2BOrder__c){
            Map<String, Id> mapOrderIdProductId_WithOrderItemId = new Map<String, Id>();

            //System.debug('>> OrderItem Perm: ' + Schema.sObjectType.OrderItem.isAccessible());

            List<Orderitem> listOrderItem = new List<Orderitem>();

            for(OrderItem orderItem : [SELECT Id, OrderId, Product2Id, TECH_ProductName__c FROM OrderItem WHERE OrderId = :order.Id]){
                mapOrderIdProductId_WithOrderItemId.put(orderItem.OrderId + ':' +orderItem.Product2Id, orderItem.Id);
                listOrderItem.add(orderItem);
            }

            //System.debug('>> mapOrderIdProductId_WithOrderItemId: ' + mapOrderIdProductId_WithOrderItemId);
            //System.debug('>> listOrderItem: ' + listOrderItem);

            List<CartItem> listCartItem = new List<CartItem>();
            Set<Id> setCartItemIds = new Set<Id>();

            for(WebCart cart : [SELECT Id, (SELECT Id, Product2Id, TECH_SessionDate__c, TECH_SessionCode__c FROM CartItems) FROM WebCart WHERE Id = :order.Cart__c]){
                listCartItem = cart.CartItems;
                /* for(CartItem cartItem : cart.CartItems){
                    setCartItemIds.add(cartItem.Id);
                } */
            }

            //System.debug('>> listCartItem: ' + listCartItem);

            for(CartItem cartItem : listCartItem){
                setCartItemIds.add(cartItem.Id);
            }

            //System.debug('>> setCartItemIds: ' + setCartItemIds);

            Map<Id, List<Participant__c>> mapCartItemId_WithListParticipant = new Map<Id, List<Participant__c>>();

            for(Participant__c participant : [SELECT Id, CartItemId__c, Civilite__c, EmailAddress__c, Prenom__c, Nom__c, Name FROM Participant__c WHERE CartItemId__c IN :setCartItemIds]){
                if(mapCartItemId_WithListParticipant.containsKey(participant.CartItemId__c)){
                    mapCartItemId_WithListParticipant.get(participant.CartItemId__c).add(participant);
                }else{
                    mapCartItemId_WithListParticipant.put(participant.CartItemId__c, new List<Participant__c>{participant});
                }
            }

            //System.debug('>> mapCartItemId_WithListParticipant: ' + mapCartItemId_WithListParticipant);

            List<TrainingSession__c> listTrainingSessionToInsert = new List<TrainingSession__c>();

            for(CartItem cartItem : listCartItem){
                if(mapCartItemId_WithListParticipant.containsKey(cartItem.Id)){
                    for(Participant__c participant : mapCartItemId_WithListParticipant.get(cartItem.Id)){
                        TrainingSession__c trainingSession = new TrainingSession__c();
                        trainingSession.Order__c = order.Id;
                        trainingSession.Order_Product__c = mapOrderIdProductId_WithOrderItemId.containsKey(order.Id + ':' + cartItem.Product2Id) ? mapOrderIdProductId_WithOrderItemId.get(order.Id + ':' + cartItem.Product2Id) : null;
                        trainingSession.ParticipantSalutation__c = participant.Civilite__c;
                        trainingSession.ParticipantFirstName__c = participant.Name;
                        trainingSession.ParticipantLastName__c = participant.Prenom__c;
                        trainingSession.ParticipantEmail__c = participant.EmailAddress__c;
                        trainingSession.SessionCode__c = cartItem.TECH_SessionCode__c;
                        trainingSession.SessionDate__c = cartItem.TECH_SessionDate__c;
                        listTrainingSessionToInsert.add(trainingSession);
                    }
                }
            }

            //System.debug('>> listTrainingSessionToInsert: ' + listTrainingSessionToInsert);

            if(listTrainingSessionToInsert.size() > 0){
                Database.insert(listTrainingSessionToInsert);
            }

            if(String.isNotBlank(order.IBAN__c) || String.isNotBlank(order.New_IBAN__c)){
                sendEmailAndMandatSEPAToClient(order, listOrderItem);
            }else{
                sendEmailToClientUsedCreditCard(order, listOrderItem);
            }
        }
    }

    @TestVisible
    private static void sendEmailAndMandatSEPAToClient(Order order, List<Orderitem> listOrderItem){
        String orderId = order.Id;

        PageReference mandatSEPA_PDF = Page.B2B_MandatSEPA;
        mandatSEPA_PDF.getParameters().put('Id', order.Id);

        String pdfName = 'Commande ' + order.OrderNumber + ' Mandat SEPA.pdf';

        Attachment attach = new Attachment();
        Blob body;
        
        try{
            body = mandatSEPA_PDF.getContentAsPDF();
        }catch(VisualforceException e){
            body = Blob.valueOf('ERROR');
        }

        try{
            EmailTemplate emailTemplate = [SELECT Id, Subject, Description, HtmlValue, DeveloperName, Body FROM EmailTemplate WHERE DeveloperName = 'B2B_Order_Confirmation_Mail_Mandat_SEPA_To_Client'];

            Messaging.EmailFileAttachment attach1 = new Messaging.EmailFileAttachment();
            attach1.setContentType('application/pdf');
            attach1.setFileName(pdfName);
            attach1.setInline(false);
            attach1.Body = body;
            
            //Will now send the real email
            Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
            emailToSend.setUseSignature(false);
            emailToSend.setToAddresses(new List<String>{UserInfo.getUserEmail()});

            String productInformation = '';
            String emailBody = emailTemplate.HtmlValue;

            /* for(Order order1 : [SELECT Id, (SELECT Id, TECH_ProductName__c, Product2Id FROM OrderItems) FROM Order WHERE Id = :order.Id]){
                Map<OrderItem, String> mapOrderItem_WithPublicLink = findTrainingProgramFileAndGeneratePublicLink(order1.OrderItems);
                System.debug('>> mapOrderItem_WithPublicLink: ' + mapOrderItem_WithPublicLink);
                for(OrderItem orderItem : mapOrderItem_WithPublicLink.keySet()){
                    if(mapOrderItem_WithPublicLink.containsKey(orderItem)){
                        productInformation += emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>').replace('<productNameFromApex>', orderItem.TECH_ProductName__c).replace('ProgrammeDeFormationLinkFromApex', mapOrderItem_WithPublicLink.get(orderItem));
                    }
                }
            } */

            Map<OrderItem, String> mapOrderItem_WithPublicLink = findTrainingProgramFileAndGeneratePublicLink(listOrderItem);

            //System.debug('>> mapOrderItem_WithPublicLink: ' + mapOrderItem_WithPublicLink);

            for(OrderItem orderItem : listOrderItem){
                if(mapOrderItem_WithPublicLink.containsKey(orderItem)){
                    productInformation += emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>').replace('<productNameFromApex>', orderItem.TECH_ProductName__c).replace('ProgrammeDeFormationLinkFromApex', mapOrderItem_WithPublicLink.get(orderItem));
                }else{
                    String strSentenceLink = emailBody.substringBetween('<noPublicLink>', '</noPublicLink>');
                    productInformation += emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>').replace('<productNameFromApex>', orderItem.TECH_ProductName__c).replace(strSentenceLink, '');
                }
            }

            emailToSend.setTargetObjectId(UserInfo.getUserId()); 
            //emailToSend.setSenderDisplayName('CEGID'); 
            emailToSend.setReplyTo('noreply@cegid.com');
             
            emailBody = emailBody.replace('{!User.Name}', UserInfo.getName());
            emailBody = emailBody.replace('{!Order.OrderNumber}', order.OrderNumber);
            emailBody = emailBody.replace('{!Order.TECH_CreatedDateFrench__c}', order.TECH_CreatedDateFrench__c);
            emailBody = emailBody.replace('{!Order.TECH_AccountName__c}', order.TECH_AccountName__c);
            emailBody = emailBody.replace('StoreLoginURL__c', B2B_SETTINGS.StoreLoginURL__c);
            emailBody = emailBody.replace(emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>'), productInformation);
            emailToSend.setHtmlBody(emailBody);
            emailToSend.setSaveAsActivity(false);
            emailToSend.setSubject(emailTemplate.Subject);
            emailToSend.setTemplateID(emailTemplate.Id); 
            emailToSend.setWhatId(orderId);
            emailToSend.setOrgWideEmailAddressId(owa.Id);//VMO 2021-11-17
            emailToSend.setFileAttachments(new Messaging.EmailFileAttachment[]{
                attach1
            });
            
            if (!Test.isRunningTest()) {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { emailToSend });
            }
        }catch(Exception ex){
            Messaging.SingleEmailMessage[] listEmailMsgs = new List <Messaging.SingleEmailMessage>();
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            String errorMsg = String.valueOf(ex) + '\n\n';
            errorMsg += 'StackTraceString : ' + ex.getStackTraceString() + '\n';
            mail.setSubject('CEGID - Exception : ' + ex.getStackTraceString());
            mail.setPlainTextBody(errorMsg);
            mail.setToAddresses(new List <String>{
               'varun.molla@comforth-karoo.eu'
            });
            listEmailMsgs.add(mail);
            if (!Test.isRunningTest()){
                Messaging.SendEmailResult[] emailResults = Messaging.sendEmail(listEmailMsgs);
            }
        }
    }

    @TestVisible
    private static void sendEmailToClientUsedCreditCard(Order order,  List<Orderitem> listOrderItem){
        String orderId = order.Id;

        try{
            EmailTemplate emailTemplate = [SELECT Id, Subject, Description, HtmlValue, DeveloperName, Body FROM EmailTemplate WHERE DeveloperName = 'B2B_Order_Confirmation_Mail_Credit_Card_To_Client'];
            
            //Will now send the real email
            Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
            emailToSend.setUseSignature(false);
            emailToSend.setToAddresses(new List<String>{UserInfo.getUserEmail()});

            String productInformation = '';
            String emailBody = emailTemplate.HtmlValue;

            /* for(Order order1 : [SELECT Id, (SELECT Id, TECH_ProductName__c, Product2Id FROM OrderItems) FROM Order WHERE Id = :order.Id]){
                Map<OrderItem, String> mapOrderItem_WithPublicLink = findTrainingProgramFileAndGeneratePublicLink(order1.OrderItems);
                for(OrderItem orderItem : mapOrderItem_WithPublicLink.keySet()){
                    if(mapOrderItem_WithPublicLink.containsKey(orderItem)){
                        productInformation += emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>').replace('<productNameFromApex>', orderItem.TECH_ProductName__c).replace('ProgrammeDeFormationLinkFromApex', mapOrderItem_WithPublicLink.get(orderItem));
                    }
                }
            } */

            Map<OrderItem, String> mapOrderItem_WithPublicLink = findTrainingProgramFileAndGeneratePublicLink(listOrderItem);

            //System.debug('>> mapOrderItem_WithPublicLink: ' + mapOrderItem_WithPublicLink);

            for(OrderItem orderItem : listOrderItem){
                if(mapOrderItem_WithPublicLink.containsKey(orderItem)){
                    productInformation += emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>').replace('<productNameFromApex>', orderItem.TECH_ProductName__c).replace('ProgrammeDeFormationLinkFromApex', mapOrderItem_WithPublicLink.get(orderItem));
                }else{
                    String strSentenceLink = emailBody.substringBetween('<noPublicLink>', '</noPublicLink>');
                    productInformation += emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>').replace('<productNameFromApex>', orderItem.TECH_ProductName__c).replace(strSentenceLink, '');
                }
            }

            emailToSend.setTargetObjectId(UserInfo.getUserId()); 
            //emailToSend.setSenderDisplayName('CEGID'); 
            emailToSend.setReplyTo('noreply@cegid.com');
             
            emailBody = emailBody.replace('{!User.Name}', UserInfo.getName());
            emailBody = emailBody.replace('{!Order.OrderNumber}', order.OrderNumber);
            emailBody = emailBody.replace('{!Order.TECH_CreatedDateFrench__c}', order.TECH_CreatedDateFrench__c);
            emailBody = emailBody.replace('{!Order.TECH_AccountName__c}', order.TECH_AccountName__c);
            emailBody = emailBody.replace('StoreLoginURL__c', B2B_SETTINGS.StoreLoginURL__c);
            emailBody = emailBody.replace(emailBody.substringBetween('<OrderProductInfo>', '</OrderProductInfo>'), productInformation);
            emailToSend.setHtmlBody(emailBody);
            emailToSend.setSaveAsActivity(false);
            emailToSend.setSubject(emailTemplate.Subject);
            emailToSend.setTemplateID(emailTemplate.Id); 
            emailToSend.setWhatId(orderId);
            emailToSend.setOrgWideEmailAddressId(owa.Id);//VMO 2021-11-17
            
            if (!Test.isRunningTest()) {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { emailToSend });
            }
        }catch(Exception ex){
            Messaging.SingleEmailMessage[] listEmailMsgs = new List <Messaging.SingleEmailMessage>();
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            String errorMsg = String.valueOf(ex) + '\n\n';
            errorMsg += 'StackTraceString : ' + ex.getStackTraceString() + '\n';
            mail.setSubject('CEGID - Exception : ' + ex.getStackTraceString());
            mail.setPlainTextBody(errorMsg);
            mail.setToAddresses(new List <String>{
               'varun.molla@comforth-karoo.eu'
            });
            listEmailMsgs.add(mail);
            if (!Test.isRunningTest()){
                Messaging.SendEmailResult[] emailResults = Messaging.sendEmail(listEmailMsgs);
            }
        }
    }

    @TestVisible
    private static Map<OrderItem, String> findTrainingProgramFileAndGeneratePublicLink(List<OrderItem> ListOrderItem){
        Set<Id> setProductIds = new Set<Id>();
        Set<Id> setOrderItemIds = new Set<Id>();
        Map<OrderItem, String> mapOrderItem_WithPublicLink = new Map<OrderItem, String>();
        Map<Id, List<ContentDocumentLink>> mapProductId_WithListCDL = new Map<Id, List<ContentDocumentLink>>();
        Map<Id, Id> mapContentDocID_WithContentVersionId = new Map<Id, Id>();
        Map<Id, ContentVersion> mapContentVersionID_WithContentVersion = new Map<Id, ContentVersion>();
        Map<Id, String> mapContentVersionID_WithPublicLink = new Map<Id, String>();

        for(OrderItem orderItem : ListOrderItem){
            setProductIds.add(orderItem.Product2Id);
        }

        Set<Id> setCDLIds = new Set<Id>();

        //('>> setProductIds: '+setProductIds);

        for(ContentDocumentLink cdl : [SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :setProductIds]){
            setCDLIds.add(cdl.ContentDocumentId);

            if(mapProductId_WithListCDL.containsKey(cdl.LinkedEntityId)){
                mapProductId_WithListCDL.get(cdl.LinkedEntityId).add(cdl);
            }else{
                mapProductId_WithListCDL.put(cdl.LinkedEntityId, new List<ContentDocumentLink>{cdl});
            }
        }

        //System.debug('>> mapProductId_WithListCDL: '+mapProductId_WithListCDL);

        for(ContentVersion cv : [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId IN :setCDLIds AND Title LIKE '%Programme De Formation%']){
            mapContentDocID_WithContentVersionId.put(cv.ContentDocumentId, cv.Id);
            mapContentVersionID_WithContentVersion.put(cv.Id, cv);
        }

        for(ContentDistribution contentDist : [SELECT Id, DistributionPublicUrl, ContentVersionId FROM ContentDistribution WHERE ContentVersionId IN :mapContentDocID_WithContentVersionId.values()]){
            mapContentVersionID_WithPublicLink.put(contentDist.ContentVersionId, String.isNotBlank(contentDist.DistributionPublicUrl) ? contentDist.DistributionPublicUrl : '');
        }

        //System.debug('>> mapContentDocID_WithContentVersionId (1): '+mapContentDocID_WithContentVersionId);

        List<ContentDistribution> listContentDistributionToInsert = new List<ContentDistribution>();

        //if(mapContentVersionID_WithPublicLink.isEmpty()){
            for(Id cvId : mapContentVersionID_WithContentVersion.keySet()){
                if(!mapContentVersionID_WithPublicLink.containsKey(cvId) && mapContentVersionID_WithContentVersion.containsKey(cvId)){
                    ContentDistribution cdist = new ContentDistribution();
                    cdist.Name = mapContentVersionID_WithContentVersion.get(cvId).Title;
                    cdist.ContentVersionId = cvId;
                    cdist.PreferencesAllowViewInBrowser = true;
                    //insert cdist;
                    listContentDistributionToInsert.add(cdist);

                    //List<ContentDistribution> listContentDist = [SELECT Id, DistributionPublicUrl FROM ContentDistribution WHERE ContentVersionId = :cvId];
                }
            }

            insert listContentDistributionToInsert;

            for(ContentDistribution cdist : [SELECT Id, DistributionPublicUrl, ContentVersionId FROM ContentDistribution WHERE ContentVersionId = :mapContentVersionID_WithContentVersion.keySet()]){
                mapContentVersionID_WithPublicLink.put(cdist.ContentVersionId, String.isNotBlank(cdist.DistributionPublicUrl) ? cdist.DistributionPublicUrl : '');
            }
        //}

        //System.debug('>> mapContentDocID_WithContentVersionId (2): '+mapContentDocID_WithContentVersionId);
        //System.debug('>> mapContentVersionID_WithContentVersion: '+mapContentVersionID_WithContentVersion);
        //System.debug('>> mapContentVersionID_WithPublicLink: '+mapContentVersionID_WithPublicLink);

        for(OrderItem orderItem : ListOrderItem){
            if(mapProductId_WithListCDL.containsKey(orderItem.Product2Id)){
                for(ContentDocumentLink cdl : mapProductId_WithListCDL.get(orderItem.Product2Id)){
                    if(mapContentDocID_WithContentVersionId.containsKey(cdl.ContentDocumentId)){
                        String contentVersionId = mapContentDocID_WithContentVersionId.get(cdl.ContentDocumentId);
                        String publicLink = mapContentVersionID_WithPublicLink.get(contentVersionId);
                        mapOrderItem_WithPublicLink.put(orderItem, publicLink);
                        break;
                    }
                }
            }
        }

        return mapOrderItem_WithPublicLink;
    }
}