unpackaged/main/default/objects/B2B_Settings__c/B2B_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store global params for B2B CEGID Store</description>
    <label>B2B Settings</label>
</CustomObject>

unpackaged/main/default/objects/B2B_Settings__c/fields/AccessTokenClientID__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenClientID__c</fullName>
    <label>Access Token Client ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/AccessTokenClientSecret__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenClientSecret__c</fullName>
    <label>Access Token Client Secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/AccessTokenURL__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenURL__c</fullName>
    <label>Access Token URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/CommunityId__c.field-meta.xml
<CustomField>
    <fullName>CommunityId__c</fullName>
    <description>The id of the community. Used in SSO Auto provisioning.</description>
    <label>Community Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/DefaultBuyerGroup__c.field-meta.xml
<CustomField>
    <fullName>DefaultBuyerGroup__c</fullName>
    <description>Default Buyer Group to assign Buyer account during auto-provisioning</description>
    <inlineHelpText>Default Buyer Group to assign Buyer account during auto-provisioning</inlineHelpText>
    <label>Default Buyer Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/GetUnitaryProductSessionsURL__c.field-meta.xml
<CustomField>
    <fullName>GetUnitaryProductSessionsURL__c</fullName>
    <label>Get Unitary Product Sessions URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StoreDomain__c.field-meta.xml
<CustomField>
    <fullName>StoreDomain__c</fullName>
    <defaultValue>"https://store.cegid.com"</defaultValue>
    <label>Store domain</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StoreLoginURL__c.field-meta.xml
<CustomField>
    <fullName>StoreLoginURL__c</fullName>
    <label>Store Login URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StripePublishableKey__c.field-meta.xml
<CustomField>
    <fullName>StripePublishableKey__c</fullName>
    <defaultValue>"pk_test_51J3G9THyPvQW0JfV0OddzUOOkYQM50uC8wzPfzckGqqCNVKVo4vJssOcNTZIRnksbloJZBHc4AIv2m1nEKU7TAeA00xLWtdquz"</defaultValue>
    <description>Populate with the value of the publishable key in the Stripe Dashboard</description>
    <inlineHelpText>Populate with the value of the publishable key in the Stripe Dashboard</inlineHelpText>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Activité (niveau 3)</description>
    <label>StructureLevel3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StructureLevel2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel3</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <description>Numéro de référence du produit</description>
    <formula>IF(CONTAINS(ProductID__c , 'GENERIC'), ProductID__c, IF(RecordType.DeveloperName = 'Package', 'K'+ ReferenceSequence__c, Left(RecordType.DeveloperName,1)+ ReferenceSequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <label>Article</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/classes/B2B_AssociatedProducts_TEST.cls
/**
 * @author Varun Molla - Comforth Karoo
 * @date Creation 2021-11-11
 * @description Test class for apex class B2B_AssociatedProducts
 *              
*/
@isTest
private class B2B_AssociatedProducts_TEST {

    private static User adminUser =  new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    @isTest static void getProducts_Test(){ 
        System.runAs(adminUser){ 
            List<Product2> listProductList = new List<Product2>{
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'List')
            };
            listProductList[0].Name = 'test ProductArticle';
            //listProductList[0].Reference_Number__c = 'A0001053';
            insert listProductList;

            List<Product2> listArticle = new List<Product2>{
                new UTIL_TestFactory.ProductFactory().createProduct('Article', '')
            };
            insert listArticle;
    
            List<SBQQ__ProductOption__c> listProductArticle = new List<SBQQ__ProductOption__c>{
                new UTIL_TestFactory.ProductOptionFactory().createProductOption(listArticle[0].Id, listProductList[0].Id)
            };
            //listProductArticle[0].Reference_Number__c = 'A0001053';          
            insert listProductArticle;

            B2B_Settings__c settings = new B2B_Settings__c();
            settings.StoreLoginURL__c = 'Test';
            settings.CommunityId__c = 'Test';
            settings.DefaultBuyerGroup__c  = 'Test';
            settings.StoreDomain__c = 'Test';
            settings.StripePublishableKey__c = 'Test';
            settings.AccessTokenURL__c = 'cegid-oauth-provider';
            settings.AccessTokenClientID__c = 'Test';
            settings.AccessTokenClientSecret__c = 'Test';
            settings.GetUnitaryProductSessionsURL__c = 'trainings';
            insert settings;
    
            Test.startTest();
                B2B_AssociatedProducts.getProducts(listProductList[0].Id, null);
            Test.stopTest();
        } 
    }

    @isTest static void getProductCategoryLabel_Test(){ 
        System.runAs(adminUser){ 
            List<Product2> listProductList = new List<Product2>{
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'List')
            };
            //listProductList[0].Category__c = '505';
            listProductList[0].Name = 'test ProductArticle';
            //listProductList[0].Reference_Number__c = 'A0001053';
            insert listProductList;
    
            Test.startTest();
                B2B_AssociatedProducts.getProductCategoryLabel(listProductList[0].Id);
            Test.stopTest();
        } 
    }
}