unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/User/fields/BypassPB__c.field-meta.xml
<CustomField>
    <fullName>BypassPB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass PB</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass VR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassWF__c.field-meta.xml
<CustomField>
    <fullName>BypassWF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass WF</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/List_of_VR_to_By_Pass__c.field-meta.xml
<CustomField>
    <fullName>List_of_VR_to_By_Pass__c</fullName>
    <label>List of VR to By Pass</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CustomProductLayoutFieldsNotEditable</fullName>
            </value>
            <value>
                <fullName>VR_024_User_cant_edit_Custom_Name</fullName>
            </value>
            <value>
                <fullName>VR_025_User_cant_add_Special_Comment</fullName>
            </value>
            <value>
                <fullName>VR_Contact_Invalid_Email_Rules</fullName>
            </value>
            <value>
                <fullName>VR_Contact004_Email_format_Validation</fullName>
            </value>
            <value>
                <fullName>VR_Contact05_Name</fullName>
            </value>
            <value>
                <fullName>VR_Contact06_PhoneMandatory</fullName>
            </value>
            <value>
                <fullName>VR_Contact07_NoNameEmptying</fullName>
            </value>
            <value>
                <fullName>VR_Lead005_IndCodeMandatoryForConversion</fullName>
                <isActive>false</isActive>
                <label>VR_Lead005_IndCodeMandatoryForConversion</label>
            </value>
            <value>
                <fullName>VR_Lead007_NoAssignmentToSales</fullName>
            </value>
            <value>
                <fullName>VR_Lead008_NoNewLeadWithoutPermSet</fullName>
                <isActive>false</isActive>
                <label>VR_Lead008_NoNewLeadWithoutPermSet</label>
            </value>
            <value>
                <fullName>VR_Lead009_StatusClosedConverted</fullName>
                <isActive>false</isActive>
                <label>VR_Lead009_StatusClosedConverted</label>
            </value>
            <value>
                <fullName>VR_Lead010_NoAssignmentUsersWithPS</fullName>
            </value>
            <value>
                <fullName>VR_Lead011_PRM_Owner_Change</fullName>
            </value>
            <value>
                <fullName>VR_Lead012_NonPRMSalesCantChangeOwner</fullName>
            </value>
            <value>
                <fullName>VR_Oppty01_LeadSource</fullName>
            </value>
            <value>
                <fullName>VR_Oppty09_NoGStageForSales</fullName>
            </value>
            <value>
                <fullName>VR_Oppty11_NoChangeOnClosed</fullName>
            </value>
            <value>
                <fullName>VR_Oppty17_DecisionMakerMandatOnStageD</fullName>
            </value>
            <value>
                <fullName>VR_Oppty18_ForbiddenChangesOnClosed</fullName>
            </value>
            <value>
                <fullName>VR_Oppty19_NoInactivePACOnChange</fullName>
            </value>
            <value>
                <fullName>VR_Oppty20_LeadSourceValuesForSales</fullName>
            </value>
            <value>
                <fullName>VR_Oppty21_NoChangeLeadSourceForSales</fullName>
            </value>
            <value>
                <fullName>VR_Oppty22_NoNewOppyForMarketing</fullName>
            </value>
            <value>
                <fullName>VR_Oppty23_CheckMQL_Open</fullName>
            </value>
            <value>
                <fullName>VR_Oppty28_Contact_Compliance</fullName>
            </value>
            <value>
                <fullName>VR_Quote_016_Contact_Compliance</fullName>
            </value>
            <value>
                <fullName>VR_Stage_D_or_higher_Booking_not_Blank</fullName>
                <isActive>false</isActive>
                <label>VR_Stage_D_or_higher_Booking_not_Blank</label>
            </value>
            <value>
                <fullName>VR003_Email_format_Validation</fullName>
            </value>
            <value>
                <fullName>VR007_NationalId_Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OppTagAddcontentDocumentTest.cls
@istest
public class OppTagAddcontentDocumentTest {
    @isTest
    static void unitTest() {
        Profile p = [SELECT Id FROM Profile WHERE Name='IM Partner']; 
        /*User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id,List_of_VR_to_By_Pass__c	='VR007_NationalId_Exception', 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduserimpartnet@testorg.com');
*/
        
        
         User userImPartner= new User(
                alias = 'Test',
                email = 'test.sales@example.com',
                emailencodingkey = 'UTF-8',
                BypassPB__c = true,
                BypassVR__c = true,
                BypassWF__c = true,
                lastname = 'testsales',
                languagelocalekey = 'fr',
                localesidkey = 'fr_FR',
                profileid = p.id,
                timezonesidkey = 'Europe/Paris',
                username = 'test.sales' + System.now().millisecond()
                + UserInfo.getOrganizationId() + '@example.com'
            );
        insert userImPartner;
        System.runAs(userImPartner) {        
        
        
        List<Opportunity> listOppConverted = new List<Opportunity>(); 
        List<Opportunity> listOppAutoCreate = new List<Opportunity>();
        Account acc = new UTIL_TestFactory.AccountFactory().createAccount();
                insert acc;
         Opportunity opp = new UTIL_TestFactory.OpportunityFactory().createOpportunity(acc.Id, false, false);
                insert opp;
 
ContentVersion conVer = new ContentVersion();
conVer.ContentLocation = 'S'; 
conVer.PathOnClient = 'testing.txt'; 
conVer.Title = 'Testing Files'; 
conVer.VersionData = Blob.valueOf('Test Content');
insert conVer;    
        
Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
ContentDocumentLink conDocLink = New ContentDocumentLink();
conDocLink.LinkedEntityId = opp.Id; 
conDocLink.ContentDocumentId = conDoc;  
conDocLink.shareType = 'V';
insert conDocLink;
        }      
        
    }
}