unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Cegid Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cegid Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entity__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/ICS__c.field-meta.xml
<CustomField>
    <fullName>ICS__c</fullName>
    <label>ICS</label>
    <length>115</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Cegid_Entity__c.field-meta.xml
<CustomField>
    <fullName>Cegid_Entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cegid Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Entity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Product Line is inactive.</errorMessage>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Level_Price__c/Service_Level_Price__c.object-meta.xml
<CustomObject>
    <label>Service Level Price</label>
    <nameField>
        <displayFormat>LvlSP-{000000000}</displayFormat>
        <label>Service Level Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Level Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM021_UpdateServiceLevelPrice_TEST.cls
/**
* @author Keshav M - Comforth
* @date 2021-07-05
* @description SM021_UpdateServiceLevelPrice_TEST          
*/
@isTest
public class SM021_UpdateServiceLevelPrice_TEST {
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static final String PRIMARY_CONTACT_EMAIL = 'primarycontact@email.com';
    @testSetup static void setup(){
        System.runAs(adminUser){ 
            Insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
            Test.startTest();

            List<Product_Line__c> listProductLine = new List<Product_Line__c>{
                new UTIL_TestFactory.ProductLineFactory().createProductLinePrice('ProductLineTest', 'tyhjy')
           };
           insert listProductLine;

           //Entity
            Entity__c entity = new Entity__c(
            Active__c = true,
            name ='CEGID SA',
            ICS__c = 'FR14ZZZ497659',
            Street__c = '52, quai Sedallian',
            City__c = 'Lyon',
            Postal_Code__c = '69009',
            Country__c = 'France'
            );
            insert entity;

            //PriceBook
            Pricebook2 customPB = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true, Cegid_Entity__c = entity.Id );
            insert customPB;

            Pricebook2 customPBv2 = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true, Cegid_Entity__c = entity.Id );
            insert customPBv2;

            
            PriceBook2 standardPricebook = new UTIL_TestFactory.PricebookFactory().activateStdPriceBook();
            
            //create product2
            List<Product2> listProduct = new List<Product2>{
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost'),
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost'),
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost')
            };

            listProduct[2].Product_Line__c = listProductLine[0].Id;
            listProduct[2].Name = 'Test Product line ';
            insert listProduct;

            system.debug('listProduct '+ listProduct[2]);
            
            List<PricebookEntry> listPBE = new List<PricebookEntry>{
                new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(standardPricebook.id, listProduct[0].id),
                new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(standardPricebook.id, listProduct[2].id)
            };
            insert listPBE; 

            List<PricebookEntry> listPBECustomPriceBook = new List<PricebookEntry>{
                new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(customPB.id, listProduct[2].id),
                new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(customPBv2.id, listProduct[2].id)
            };
            insert listPBECustomPriceBook; 
            
            //create Discount Schedule
            List<SBQQ__DiscountSchedule__c> listDiscountSCH = new List<SBQQ__DiscountSchedule__c>{
                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage'),
                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage'),
                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage'),
                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage'),
                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage'),
                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage'),
                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage')
            };
            insert listDiscountSCH;
            
            //Create SLP
            Service_Level_Price__c slp = new UTIL_TestFactory.ServiceLevelPriceFactory().createServiceLevelPrice(listProduct[0].Id,standardPricebook.Id,'List Pricing',listDiscountSCH[0].Id);
            insert slp;
            Test.stopTest();
        }
    }
    
    static testMethod void testServiceLevelInsert(){
        product2 pro = [Select Id from Product2 limit 1];
        PriceBook2 priceBook = [Select Id from PriceBook2 limit 1];
        SBQQ__DiscountSchedule__c discountSch = [Select Id from SBQQ__DiscountSchedule__c limit 1];
        Service_Level_Price__c slp = new UTIL_TestFactory.ServiceLevelPriceFactory().createServiceLevelPrice(pro.Id,priceBook.Id,'List Pricing',discountSch.Id);
        insert slp;
    }
    
    static testMethod void testServiceLevelDelete(){        
        Service_Level_Price__c slp = [SELECT Id from Service_Level_Price__c Limit 1];
        delete slp;
    }

    @isTest static void testProductLine(){
        System.runAs(adminUser){
            product2  pro= [SELECT id FROM Product2 WHERE Name='Test Product line' limit 1]; 
            Pricebook2 pb = [SELECT id FROM pricebook2 WHERE name = 'Standard Price Book 2009' limit 1];
            SBQQ__DiscountSchedule__c discount = [SELECT id FROM SBQQ__DiscountSchedule__c limit 1];
            Test.startTest();
            Service_Level_Price__c slp = new UTIL_TestFactory.ServiceLevelPriceFactory().createServiceLevelPrice(pro.Id,pb.Id,'List Pricing',discount.Id);
            insert slp;
            Test.stopTest();
        }
        
    }
}