unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Offer__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Offer__c/fields/Generate_Sheet_in_PS_Context__c.field-meta.xml
<CustomField>
    <fullName>Generate_Sheet_in_PS_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Sheet in PS Context</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/StructureLevel1__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel1__c</fullName>
    <description>Used to retrieve the line Product's 'StructureLevel1'</description>
    <label>StructureLevel1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StructureLevel1</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Offer</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Offer_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Offer_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Package.recordType-meta.xml
<RecordType>
    <fullName>Package</fullName>
    <active>true</active>
    <label>Package</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Qualification_Sheet__c/Qualification_Sheet__c.object-meta.xml
<CustomObject>
    <label>Qualification Sheet</label>
    <nameField>
        <label>Qualification Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualification Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Qualification_Sheet__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Qualification Sheets</relationshipLabel>
    <relationshipName>Qualification_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/StructureLevel1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>Licenses</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>Maintenance</label>
    </customValue>
    <customValue>
        <fullName>130</fullName>
        <label>Saas</label>
    </customValue>
    <customValue>
        <fullName>140</fullName>
        <label>Professional services</label>
    </customValue>
    <customValue>
        <fullName>190</fullName>
        <label>Hardware</label>
    </customValue>
    <customValue>
        <fullName>400</fullName>
        <isActive>false</isActive>
        <label>Prestation Distributeur</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Assistance Progiciel</label>
    </customValue>
    <customValue>
        <fullName>550</fullName>
        <isActive>false</isActive>
        <label>Assistance Système</label>
    </customValue>
    <customValue>
        <fullName>750</fullName>
        <isActive>false</isActive>
        <label>Location</label>
    </customValue>
    <customValue>
        <fullName>800</fullName>
        <isActive>false</isActive>
        <label>Outsourcing</label>
    </customValue>
    <customValue>
        <fullName>900</fullName>
        <isActive>false</isActive>
        <label>Divers</label>
    </customValue>
    <customValue>
        <fullName>M01</fullName>
        <isActive>false</isActive>
        <label>Marketing - Cegid Planning</label>
    </customValue>
    <customValue>
        <fullName>700</fullName>
        <isActive>false</isActive>
        <label>Consommable</label>
    </customValue>
    <customValue>
        <fullName>300</fullName>
        <isActive>false</isActive>
        <label>Prestation Editeur</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <isActive>false</isActive>
        <label>Logiciel</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <isActive>false</isActive>
        <label>Progiciel</label>
    </customValue>
    <customValue>
        <fullName>000</fullName>
        <isActive>false</isActive>
        <label>Matériel</label>
    </customValue>
    <customValue>
        <fullName>Hardware and Other</fullName>
        <isActive>false</isActive>
        <label>Hardware and Other</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>StructureLevel1</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM025_QualificationQuoteCreation_TEST.cls
/**
* @author Easyfront Consulting
* @date 2022/09
* @description Test class for SM025_QualificationQuoteCreation          
*/
@isTest
public class SM025_QualificationQuoteCreation_TEST {
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static final String PRIMARY_CONTACT_EMAIL = 'primarycontact@email.com';
    @testSetup static void setup(){
        System.runAs(adminUser){ 
            Insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True); 
            
            Test.startTest();
            //create account
            List<Account> listAcc = new List<Account>();
            for(Integer i=0; i<1;i++ ){
                listAcc.add( new UTIL_TestFactory.AccountFactory().createAccountWithNature(i));
            }
            insert listAcc;
            
            //create contact
            Contact primaryContact = new UTIL_TestFactory.ContactFactory().createContact(listAcc[0].Id);
            primaryContact.Email = PRIMARY_CONTACT_EMAIL;
            insert primaryContact;
            
            PriceBook2 standardPricebook = new UTIL_TestFactory.PricebookFactory().activateStdPriceBook();
            
            //create opportunity
            List<Opportunity> listOpp = new List<Opportunity>();
            for(Integer i=0; i<1;i++){
                listOpp.add(new UTIL_TestFactory.OpportunityFactory().createOpportunity(listAcc[i].Id, false, false));
            }
            insert listOpp;
            
            
            //create product2
            List<Product2> listProduct = new List<Product2>{
                new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost'),
                    new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost'),
                    new UTIL_TestFactory.ProductFactory().createProduct('Product', 'Cost')
                    };
                        insert listProduct;
            
            List<PricebookEntry> listPBE = new List<PricebookEntry>{
                new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(standardPricebook.id, listProduct[0].id)
                    };
                        insert listPBE; 
            
            //create oppline item
            List<OpportunityLineItem> listOppLineItem = new List<OpportunityLineItem>{
                new UTIL_TestFactory.OpportunityFactory().createOppLineItem(listOpp[0].Id, listPBE[0].Id),
                    new UTIL_TestFactory.OpportunityFactory().createOppLineItem(listOpp[0].Id, listPBE[0].Id),
                    new UTIL_TestFactory.OpportunityFactory().createOppLineItem(listOpp[0].Id, listPBE[0].Id)
                    };
                        insert listOppLineItem;
            
            //create quote in mass (cannot create more than that because of SOQL & CPU limit exceeded from CPQ SBQQ package)
            List<SBQQ__Quote__c> listQuotes = new List<SBQQ__Quote__c>();
            for(Integer i=0; i<1;i++ ){
                listQuotes.add(new UTIL_TestFactory.SBQQ_QuoteFactory().createSBQQ_QuoteV2(listOpp[i].Id, listAcc[i].Id, primaryContact.Id, listAcc[i].Id));
            }
            insert listQuotes;
            
            listOpp[0].SBQQ__PrimaryQuote__c = listQuotes[0].Id;
            update listOpp;
            
            //Create Quote Line
            Offer__c off = new Offer__c(Name = 'Offer Test', API_Name__c='APINameTest__c', Generate_Sheet_in_PS_Context__c = true);
            insert off;
            SBQQ__QuoteLine__c qutLine= new UTIL_TestFactory.SBQQ_QuoteFactory().createSBQQ_QuoteLine(listQuotes[0].Id, listProduct[0].Id);
            qutLine.StructureLevel1__c = '140';
            qutLine.Offer_Lookup__c = off.Id;
            insert qutLine;

            //Create Qualification Sheet
            List<Qualification_Sheet__c> listQS = UTIL_TestFactory.createQualificationSheetOnQuote(listQuotes);
            
            For(Qualification_Sheet__c qs:listQS){
                qs.Offer__c = off.Id;
            }
            insert listQS;
            
            Test.stopTest();
        }
    }
    
    //Test method for qualificationsheetsCreationUpdated
    static testMethod void qualificationsheetsCreationUpdated_Test(){
        List<SBQQ__Quote__c> listQuotes = [SELECT Id FROM SBQQ__Quote__c];
        Set<Id> quoteIds = new Set<Id>();
        For(SBQQ__Quote__c q:listQuotes){
            quoteIds.add(q.Id);
        }
        SM025_QualificationQuoteCreation.qualificationsheetsCreationUpdated(quoteIds);
    }
    
    //Test method for qualificationQuoteCreation
    static testMethod void qualificationQuoteCreation_Test(){
        List<SBQQ__Quote__c> listQuotes = [SELECT Id FROM SBQQ__Quote__c];
        Set<Id> quoteIds = new Set<Id>();
        For(SBQQ__Quote__c q:listQuotes){
            quoteIds.add(q.Id);
        }
        SM025_QualificationQuoteCreation.qualificationQuoteCreation(quoteIds);
    }
}