unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/FlagHasOnSiteArticle__c.field-meta.xml
<CustomField>
    <fullName>FlagHasOnSiteArticle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable trigger update of Tech_HasOnSiteArticle__c on product2 (US W-001172)</description>
    <label>Flag Has OnSite Article</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Catalog__c.field-meta.xml
<CustomField>
    <fullName>Catalog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Catalog</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Max_Trainee__c.field-meta.xml
<CustomField>
    <fullName>Max_Trainee__c</fullName>
    <label>Max Trainee</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/OPCA_Eligible__c.field-meta.xml
<CustomField>
    <fullName>OPCA_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPCA Eligible</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Realization_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Realization_Conditions__c</fullName>
    <label>Realization Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Schedulable__c.field-meta.xml
<CustomField>
    <fullName>Schedulable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Planifiable</description>
    <label>Schedulable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Term__c.field-meta.xml
<CustomField>
    <fullName>Service_Term__c</fullName>
    <description>Modalité de la prestation</description>
    <label>Service Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Term</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tech_HasOnSiteArticle__c.field-meta.xml
<CustomField>
    <fullName>Tech_HasOnSiteArticle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>W-001172 - if true, replicate Tech_HasOnSiteArticle__c from SBQQ__ProductOption__c  onto product2</description>
    <label>Tech_HasOnSiteArticle</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <label>Article</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Package.recordType-meta.xml
<RecordType>
    <fullName>Package</fullName>
    <active>true</active>
    <label>Package</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/globalValueSets/Service_Term.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Days</fullName>
    </customValue>
    <customValue>
        <fullName>Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Fee</fullName>
    </customValue>
    <masterLabel>Service Term</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM007_FlagProductHasOnSiteArticle_TEST.cls
/**
 * @author Shamina M - Comforth Karoo
 * @date 2020-09-15
 * @description Test class for SM007_FlagProductHasOnSiteArticle
*/
@isTest
private class SM007_FlagProductHasOnSiteArticle_TEST {
    
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static final String PRIMARY_CONTACT_EMAIL = 'flagonsite@email.com';

    @TestSetup static void setup(){    
        //testing as admin because of issues with CPQ rights when testing as Cegid sales
        System.runAs(adminUser){             
            Test.startTest(); //to prevent SOQL limits from SBQQ package
                //create account
                Account acc = new UTIL_TestFactory.AccountFactory().createAccount();
                insert acc;

                //create contact
                Contact primaryContact = new UTIL_TestFactory.ContactFactory().createContact(acc.Id);
                primaryContact.Email = PRIMARY_CONTACT_EMAIL;
                insert primaryContact;

                PriceBook2 standardPricebook = new UTIL_TestFactory.PricebookFactory().activateStdPriceBook();

                //create opportunity
                Opportunity opp = new UTIL_TestFactory.OpportunityFactory().createOpportunity(acc.Id, false, false);
                opp.Pricebook2Id = standardPricebook.Id; 
                insert opp;

                //create product2
                List<Product2> listProduct = new List<Product2>();
                for(Integer i=0; i<10;i++ ){
                    Product2 prod = new UTIL_TestFactory.ProductFactory().createProduct('Product', 'List');
                    Product2 article = new UTIL_TestFactory.ProductFactory().createProduct('Article', 'List');
                    article.Realization_Conditions__c = 'On Site';

                    //alternate value for StructureLevel1/ family
                    if(math.mod(i, 2) == 0){
                        prod.family = '140';
                        article.Catalog__c = true;
                        article.OPCA_Eligible__c =true;
                    }
                    else{
                        prod.family = '130';
                        article.Catalog__c = false;
                        article.OPCA_Eligible__c =false;
                    }

                    listProduct.add(prod);
                    listProduct.add(article);
                }
                insert listProduct;

                
            Test.stopTest();
        }
        
    }

    /*
    * @author Shamina M - Comforth Karoo
    * @created 2020-09-15
    * @description Generic method to create test data for product options
    */
    private static List<SBQQ__ProductOption__c> createProductOptions(){
        List<SBQQ__ProductOption__c> listProdOpt = new List<SBQQ__ProductOption__c>();
        List<Product2> listProd2Product = [SELECT Id from Product2 where RecordType.DeveloperName = 'Product'];
        List<Product2> listProd2Article = [SELECT Id from Product2 where RecordType.DeveloperName = 'Article'
                                                        AND Realization_Conditions__c = 'On Site'];

        for(Integer i=0; i<10;i++ ){
            SBQQ__ProductOption__c prodOpt = new UTIL_TestFactory.ProductOptionFactory().createProductOption(listProd2Article[i].Id,listProd2Product[i].Id);
            prodOpt.SBQQ__Number__c = i;
            prodOpt.SBQQ__Quantity__c =1;
            listProdOpt.add(prodOpt);
        }

        return listProdOpt;
    }

    /*
    * @author Shamina M - Comforth Karoo
    * @created 2020-09-15
    * @description Test insert product option
    */
    @isTest static void testInsertProductOption() {
        System.runAs(adminUser){
            List<SBQQ__ProductOption__c> listProdOpt = createProductOptions();

            Test.startTest();                
                insert listProdOpt;
            Test.stopTest();

            for(Product2 prodConfSKU: [SELECT Id,Tech_HasOnSiteArticle__c,Family,Catalog__c,OPCA_Eligible__c
                                        FROM Product2 
                                        WHERE RecordType.DeveloperName = 'Product']){
                if(prodConfSKU.family == '140'){
                    System.assertEquals(true, prodConfSKU.Tech_HasOnSiteArticle__c, 'Tech_HasOnSiteArticle__c true');
                    System.assertEquals(true, prodConfSKU.Catalog__c, 'Catalog__c true');
                    System.assertEquals(true, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c true');
                }else{
                    System.assertEquals(false, prodConfSKU.Tech_HasOnSiteArticle__c, 'Tech_HasOnSiteArticle__c false');
                    System.assertEquals(false, prodConfSKU.Catalog__c, 'Catalog__c false');
                    System.assertEquals(false, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
                }
            }

        }
    }

    /*
    * @author Shamina M - Comforth Karoo
    * @created 2020-09-15
    * @description Test delete all product option
    */
    @isTest static void testDeleteAllProductOption() {
        System.runAs(adminUser){
            List<SBQQ__ProductOption__c> listProdOpt = createProductOptions();
            insert listProdOpt;

            Test.startTest(); 
                delete listProdOpt;               
            Test.stopTest();

            for(Product2 prodConfSKU: [SELECT Id,Tech_HasOnSiteArticle__c,Family,Catalog__c, OPCA_Eligible__c
                                         from Product2 where RecordType.DeveloperName = 'Product']){
                //System.assertEquals(false, prodConfSKU.Tech_HasOnSiteArticle__c, 'Tech_HasOnSiteArticle__c false');
                //System.assertEquals(false, prodConfSKU.Catalog__c, 'Catalog__c false');
                //System.assertEquals(false, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
            }

        }
    }

    /*
    * @author Shamina M - Comforth Karoo
    * @created 2020-09-15
    * @description Test update product option
    */
    @isTest static void testUpdateProductOption() {
        System.runAs(adminUser){
            List<SBQQ__ProductOption__c> listProdOpt = createProductOptions();
            insert listProdOpt;

            List<Product2> listProd2 = new List<Product2>();
            List<Product2> listProd2Product = new List<Product2>();
            List<Product2> listProd2Article= new List<Product2>();

            for(Integer i=0; i<10;i++ ){
                Product2 prod = new UTIL_TestFactory.ProductFactory().createProduct('Product', 'List');
                prod.family = '130';
                listProd2Product.add(prod);

                Product2 article = new UTIL_TestFactory.ProductFactory().createProduct('Article', 'List');
                article.Realization_Conditions__c = 'Remote';
                listProd2Article.add(article);
            }

            listProd2.addAll(listProd2Product);
            listProd2.addAll(listProd2Article);
            insert listProd2;

            for(Integer i=0; i<listProdOpt.size();i++ ){
                listProdOpt[i].SBQQ__ConfiguredSKU__c = listProd2Product[i].Id;
                listProdOpt[i].SBQQ__OptionalSKU__c = listProd2Article[i].Id;
            } 
            
            Test.startTest();
                update listProdOpt;               
            Test.stopTest();

            for(Product2 prodConfSKU: [SELECT Id,Tech_HasOnSiteArticle__c,Family,Catalog__c, OPCA_Eligible__c,
                                       (Select ID,Tech_HasOnSiteArticle__c,Catalog__c,OPCA_Eligible__c,SBQQ__OptionalSKU__c,Schedulable__c,Service_Term__c,Duration__c,Max_Trainee__c,Realization_Conditions__c 
                                        FROM SBQQ__Options__r 
                                        WHERE  SBQQ__ConfiguredSKU__r.Family = '140' 
                                        LIMIT 1
                                       ) 
                                       FROM Product2  
                                       WHERE RecordType.DeveloperName = 'Product']){
                                           if(listProd2Product.contains(prodConfSKU)){
                                               if(prodConfSKU.SBQQ__Options__r.size()> 0){
                                                   for(SBQQ__ProductOption__c prodOpt: prodConfSKU.SBQQ__Options__r){
                                                       System.assertEquals(prodOpt.Tech_HasOnSiteArticle__c, prodConfSKU.Tech_HasOnSiteArticle__c, 'updated Tech_HasOnSiteArticle__c false');
                                                       System.assertEquals(prodOpt.Catalog__c, prodConfSKU.Catalog__c, 'Catalog__c false');
                                                       System.assertEquals(prodOpt.OPCA_Eligible__c, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
                                                   }
                                               }else{
                                                   system.debug('------prodConfSKU'+ prodConfSKU);
                                                   System.assertEquals(false, prodConfSKU.Tech_HasOnSiteArticle__c, 'updated Tech_HasOnSiteArticle__c false');
                                                   System.assertEquals(false, prodConfSKU.Catalog__c, 'Catalog__c false');
                                                   System.assertEquals(false, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
                                               }
                                           }
                                       }

        }
    }

    /*
    * @author Shamina M - Comforth
    * @created 2020-08-31
    * @description Test Bypass trigger
    */
    @isTest static void testBypassTrigger() {
        System.runAs(adminUser){
            BypassTrigger__c byPass = new BypassTrigger__c(SetupOwnerId =adminUser.Id,FlagHasOnSiteArticle__c = true );
            insert byPass;
            
            List<SBQQ__ProductOption__c> listProdOpt = createProductOptions();

            Test.startTest();                
                insert listProdOpt;
            Test.stopTest();

            for(Product2 prodConfSKU: [SELECT Id,Tech_HasOnSiteArticle__c,Family,Catalog__c, OPCA_Eligible__c
                                         from Product2 where RecordType.DeveloperName = 'Product']){
                //trigger not fired
                System.assertEquals(false, prodConfSKU.Tech_HasOnSiteArticle__c, 'Bypass enabled, checkbox not updated');
                System.assertEquals(false, prodConfSKU.Catalog__c, 'Catalog__c false');
                System.assertEquals(false, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
            }

        }
    }

    /*
    * @author Shamina M - Comforth Karoo
    * @created 2020-11-06
    * @description Test update flags on article products
    */
    @isTest static void testUpdateArticleProducts() {
        System.runAs(adminUser){
            List<SBQQ__ProductOption__c> listProdOpt = createProductOptions();
            insert listProdOpt;

            for(Product2 prodConfSKU: [SELECT Id,Tech_HasOnSiteArticle__c,Family,Catalog__c,OPCA_Eligible__c
                                        FROM Product2 
                                        WHERE RecordType.DeveloperName = 'Product']){
                if(prodConfSKU.family == '140'){
                    System.assertEquals(true, prodConfSKU.Tech_HasOnSiteArticle__c, 'Tech_HasOnSiteArticle__c true');
                    System.assertEquals(true, prodConfSKU.Catalog__c, 'Catalog__c true');
                    System.assertEquals(true, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c true');
                }else{
                    System.assertEquals(false, prodConfSKU.Tech_HasOnSiteArticle__c, 'Tech_HasOnSiteArticle__c false');
                    System.assertEquals(false, prodConfSKU.Catalog__c, 'Catalog__c false');
                    System.assertEquals(false, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
                }
            }

            List<Product2> listArticleProd = new List<Product2>();
            for(Product2 prod: [SELECT Id from Product2 where RecordType.DeveloperName = 'Article']){
                prod.Realization_Conditions__c = 'Remote';  
                prod.Catalog__c = false;
                prod.OPCA_Eligible__c = false; 
                listArticleProd.add(prod);                 
            }

            Test.startTest();  
                update listArticleProd;
            Test.stopTest();

            for(Product2 prodConfSKU: [SELECT Id,Tech_HasOnSiteArticle__c,Family,Catalog__c,OPCA_Eligible__c,
                                       		(Select ID,Tech_HasOnSiteArticle__c,Catalog__c,OPCA_Eligible__c,SBQQ__OptionalSKU__c,Schedulable__c,Service_Term__c,Duration__c,Max_Trainee__c,Realization_Conditions__c 
                                        	FROM SBQQ__Options__r 
                                        	WHERE  SBQQ__ConfiguredSKU__r.Family = '140' 
                                        	LIMIT 1) 
                                       FROM Product2 
                                       WHERE RecordType.DeveloperName = 'Product']){
                                           if(prodConfSKU.SBQQ__Options__r.size() == 0){
                                               System.assertEquals(false, prodConfSKU.Tech_HasOnSiteArticle__c, 'Tech_HasOnSiteArticle__c false');
                                               System.assertEquals(false, prodConfSKU.Catalog__c, 'Catalog__c false');
                                               System.assertEquals(false, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
                                           }
            }

        }
    }

    /*
    * @author Shamina M - Comforth Karoo
    * @created 2020-11-06
    * @description Test delete article products
    */
    @isTest static void testDeleteArticleProducts() {
        System.runAs(adminUser){
            List<SBQQ__ProductOption__c> listProdOpt = createProductOptions();
            insert listProdOpt;

            List<Product2> listArticleProd = [SELECT Id from Product2 where RecordType.DeveloperName = 'Article'];

            Test.startTest();  
                delete listArticleProd;
            Test.stopTest();

            for(Product2 prodConfSKU: [SELECT Id,Tech_HasOnSiteArticle__c,Family,Catalog__c,OPCA_Eligible__c
                                        FROM Product2 
                                        WHERE RecordType.DeveloperName = 'Product']){
                System.assertEquals(false, prodConfSKU.Tech_HasOnSiteArticle__c, 'Tech_HasOnSiteArticle__c false');
                System.assertEquals(false, prodConfSKU.Catalog__c, 'Catalog__c false');
                System.assertEquals(false, prodConfSKU.OPCA_Eligible__c, 'OPCA_Eligible__c false');
            }

        }
    }
}