unpackaged/main/default/objects/Account/fields/Amount_of_delay_0_1_month__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_delay_0_1_month__c</fullName>
    <label>Amount of delay 0-1 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Amount_of_delay_12_months__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_delay_12_months__c</fullName>
    <formula>Amount_of_delay_over_24_months__c + Amount_of_delay_12_24_months__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount of delay &gt; 12 months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Amount_of_delay_1_month__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_delay_1_month__c</fullName>
    <formula>Amount_of_delay_3_months__c + Amount_of_delay_1_3_months__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount of delay &gt; 1 month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Amount_of_delay_3_months__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_delay_3_months__c</fullName>
    <formula>Amount_of_delay_6_months__c + Amount_of_delay_3_6_months__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount of delay &gt; 3 months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Amount_of_delay_6_months__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_delay_6_months__c</fullName>
    <formula>Amount_of_delay_12_months__c + Amount_of_delay_6_12_months__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount of delay &gt; 6 months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Amount_of_delay_over_24_months__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_delay_over_24_months__c</fullName>
    <label>Amount of delay over 24 months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CodeFollowedBy__c.field-meta.xml
<CustomField>
    <fullName>CodeFollowedBy__c</fullName>
    <label>Code Followed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CPA_Sector__c.field-meta.xml
<CustomField>
    <fullName>CPA_Sector__c</fullName>
    <inlineHelpText>Choose other sector for consulting companies, lawyers and legal activities</inlineHelpText>
    <label>CPA Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGC</fullName>
            </value>
            <value>
                <fullName>Certified Public Accountant</fullName>
            </value>
            <value>
                <fullName>Instance</fullName>
            </value>
            <value>
                <fullName>OGA</fullName>
            </value>
            <value>
                <fullName>Other CPA Sector</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Decision_center__c.field-meta.xml
<CustomField>
    <fullName>Decision_center__c</fullName>
    <label>Decision center</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/DGE_Group__c.field-meta.xml
<CustomField>
    <fullName>DGE_Group__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DGE Group</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email_e_Billing__c.field-meta.xml
<CustomField>
    <fullName>Email_e_Billing__c</fullName>
    <label>Email e-Billing</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fiscal_Year_End_Month__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_End_Month__c</fullName>
    <label>Fiscal Year End Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>TEXT(Industry_Code__r.Industry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Code</label>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Maturity_Level__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Level__c</fullName>
    <label>Maturity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avant-garde</fullName>
            </value>
            <value>
                <fullName>Modern / Ex modern</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Nature</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_companies__c.field-meta.xml
<CustomField>
    <fullName>No_of_companies__c</fullName>
    <description>Number of companies</description>
    <label>No. of companies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_establishments__c.field-meta.xml
<CustomField>
    <fullName>No_of_establishments__c</fullName>
    <description>Number of establishments</description>
    <label>No. of Establishments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Folders__c.field-meta.xml
<CustomField>
    <fullName>No_of_Folders__c</fullName>
    <label>No. of Folders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Subsidiaries__c.field-meta.xml
<CustomField>
    <fullName>No_of_Subsidiaries__c</fullName>
    <description>No. of Subsidiaries</description>
    <label>No. of Subsidiaries</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Parent_Account_Nature__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account_Nature__c</fullName>
    <formula>TEXT(Parent.Nature__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Account Nature</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Payslips_per_month__c.field-meta.xml
<CustomField>
    <fullName>Payslips_per_month__c</fullName>
    <description>Payslips per month</description>
    <label>Payslips per month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ReferentCode__c.field-meta.xml
<CustomField>
    <fullName>ReferentCode__c</fullName>
    <label>Referent Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/RegisteredwiththeOrderofCharteredA__c.field-meta.xml
<CustomField>
    <fullName>RegisteredwiththeOrderofCharteredA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order of Chartered Accounts Registered</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Retail_Sector__c.field-meta.xml
<CustomField>
    <fullName>Retail_Sector__c</fullName>
    <label>Retail Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Retail_Sector</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <label>Risk Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/SedentaryCode__c.field-meta.xml
<CustomField>
    <fullName>SedentaryCode__c</fullName>
    <label>Sedentary Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECH_Lead_conversion__c.field-meta.xml
<CustomField>
    <fullName>TECH_Lead_conversion__c</fullName>
    <label>TECH Lead conversion</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECH_oppy_byPass_US1705__c.field-meta.xml
<CustomField>
    <fullName>TECH_oppy_byPass_US1705__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH oppy byPass US1705</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHFollowedByCodeToBeCalculated__c.field-meta.xml
<CustomField>
    <fullName>TECHFollowedByCodeToBeCalculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Followed By Code To Be Calculated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Amount_of_delay__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_delay__c</fullName>
    <formula>Amount_of_delay_0_1_month__c +  Amount_of_delay_1_month__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount of delay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Yearofregistration__c.field-meta.xml
<CustomField>
    <fullName>Yearofregistration__c</fullName>
    <label>Year of registration</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Industry__c/Industry__c.object-meta.xml
<CustomObject>
    <label>Industry</label>
    <nameField>
        <label>Industry Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Industry__c/fields/Default_NAF__c.field-meta.xml
<CustomField>
    <fullName>Default_NAF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default NAF</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Industry__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Code</label>
    <referenceTo>Industry__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Nature</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_Companies__c.field-meta.xml
<CustomField>
    <fullName>No_of_Companies__c</fullName>
    <label>No. of Companies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_establishments__c.field-meta.xml
<CustomField>
    <fullName>No_of_establishments__c</fullName>
    <label>No. of Establishments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Payslips_per_month__c.field-meta.xml
<CustomField>
    <fullName>Payslips_per_month__c</fullName>
    <label>Payslips per month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Retail_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Retail_Segmentation__c</fullName>
    <label>Retail Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Retail_Segmentation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/TECH_Lead_conversion__c.field-meta.xml
<CustomField>
    <fullName>TECH_Lead_conversion__c</fullName>
    <description>Tech field to avoid field permission trigger during lead conversion</description>
    <formula>'true'</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Lead conversion</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Nature.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PRO</fullName>
        <default>true</default>
        <label>PROSPECT</label>
    </customValue>
    <customValue>
        <fullName>CLI</fullName>
        <label>CUSTOMER</label>
    </customValue>
    <customValue>
        <fullName>EXCLI</fullName>
        <label>EX CUSTOMER</label>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
        <isActive>false</isActive>
        <label>Client</label>
    </customValue>
    <customValue>
        <fullName>Ex-Client</fullName>
        <isActive>false</isActive>
        <label>Ex-Client</label>
    </customValue>
    <masterLabel>Account Nature</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accommodation / Restauration food</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting / Legal / Operation</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture / Aquaculture and Fishing</fullName>
    </customValue>
    <customValue>
        <fullName>Art / Show / Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
    </customValue>
    <customValue>
        <fullName>Automobile / Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>Banking / Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Beverage industry</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry industry</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing / Textile industry</fullName>
    </customValue>
    <customValue>
        <fullName>Editing / Media / Communication</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity / Gas / Water</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic industry</fullName>
    </customValue>
    <customValue>
        <fullName>Employment</fullName>
    </customValue>
    <customValue>
        <fullName>Environment / Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Food industry</fullName>
    </customValue>
    <customValue>
        <fullName>Furniture manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Health / social</fullName>
    </customValue>
    <customValue>
        <fullName>Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Information services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>IT activities</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure / Sport</fullName>
    </customValue>
    <customValue>
        <fullName>Machinery and equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Metallurgy</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Paper and Carton industry</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceutical industry</fullName>
    </customValue>
    <customValue>
        <fullName>Plastic product</fullName>
    </customValue>
    <description>List of Industries (Cegid grouping)</description>
    <masterLabel>Industry</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Retail_Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Ladieswear</fullName>
    </customValue>
    <customValue>
        <fullName>Footwear</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty &amp; Cosmetics</fullName>
    </customValue>
    <customValue>
        <fullName>Sportswear</fullName>
    </customValue>
    <customValue>
        <fullName>Jewelry Watches</fullName>
    </customValue>
    <customValue>
        <fullName>Childrenswear</fullName>
    </customValue>
    <customValue>
        <fullName>Menswear</fullName>
    </customValue>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Home linens</fullName>
    </customValue>
    <customValue>
        <fullName>Lingerie</fullName>
    </customValue>
    <customValue>
        <fullName>Specialty foods</fullName>
    </customValue>
    <customValue>
        <fullName>Culture and Entertainement</fullName>
    </customValue>
    <customValue>
        <fullName>Leather Goods</fullName>
    </customValue>
    <customValue>
        <fullName>General Merchandise</fullName>
    </customValue>
    <customValue>
        <fullName>Marriage birth nursery</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts &amp; Gadgets</fullName>
    </customValue>
    <customValue>
        <fullName>Furniture</fullName>
    </customValue>
    <customValue>
        <fullName>Do it yourself and Gardening</fullName>
    </customValue>
    <customValue>
        <fullName>Decoration and objects</fullName>
    </customValue>
    <customValue>
        <fullName>Museum</fullName>
    </customValue>
    <customValue>
        <fullName>Toys</fullName>
    </customValue>
    <customValue>
        <fullName>Art of entertaining</fullName>
    </customValue>
    <customValue>
        <fullName>Optical</fullName>
    </customValue>
    <customValue>
        <fullName>Household Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Duty free</fullName>
    </customValue>
    <customValue>
        <fullName>Telephony IT</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Hotel and Resorts</fullName>
    </customValue>
    <masterLabel>Retail Sector</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Retail_Segmentation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>XS</fullName>
    </customValue>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>M</fullName>
    </customValue>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>XL</fullName>
    </customValue>
    <masterLabel>Retail Segmentation</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_Account.cls
/**
 * @File Name          : TH_Account
 * @Description        : Update Account Values with territory  
 * @Author             : SRA   
 * @Group              : Comforth-Karoo
 * @Modification Log   : 
 * Ver       Date            Author                 Modification
 * ---    -----------       -------           ------------------------ 
 * 1.0    30/10/2020         SRA              Initial Version
 * ---    -----------       -------           ------------------------ 
 * 1.5    16/09/2021         BCR              add checkAccPermissionUpdate method
 * ---    -----------       -------           ------------------------ 
**/

public without sharing class TH_Account extends TriggerHandler {

    /***BCR W-001709 ***/
    public override void beforeInsert() {
        System.debug('TH_Account beforeInsert');
        checkAdminCompliance(Trigger.new);
        emailEbilingManage(Trigger.new);
        System.debug('End TH_Account beforeInsert');
    }
    /***FIN BCR W-001709 ***/ 
    
    /**
* @author
* @date
* @description Handler Method for before Update Event
* @return void
*/
    public override void beforeUpdate() {
        system.debug('TH_Account beforeUpdate');
        Map<Id, Account> accsToBeProcess = (Map<Id, Account>)CheckRecursivCall.checkRunOnce(Trigger.newMap, System.TriggerOperation.BEFORE_UPDATE);
        
        if(accsToBeProcess.isEmpty()) {//Control recursiv call from trigger
            System.debug('No Acc to be processed');
        } else {
            //All trigger logic should be here
            set<Id> setAccId = new set<Id>();
            List<Account> listAcc = new List<Account>();
            Map<Id,Id> mapAccountIdOwnerId = new Map<Id,Id>();
            
            for(Account acc: accsToBeProcess.values()){
                Account oldAcc = (Account)Trigger.oldMap.get(acc.Id);
                system.debug('accID before Update' + acc.Id);
                system.debug('acc.OwnerId'+acc.OwnerId);
                if(oldAcc.OwnerId != acc.OwnerId || (oldAcc.TECHFollowedByCodeToBeCalculated__c!= acc.TECHFollowedByCodeToBeCalculated__c && acc.TECHFollowedByCodeToBeCalculated__c)){
                    system.debug('Trigger Account');
                    listAcc.add(acc);
                    mapAccountIdOwnerId.put(acc.Id, acc.OwnerId);
                    acc.TECHFollowedByCodeToBeCalculated__c = false; // reset flag
                }
            } 
            system.debug('mapAccountIdOwnerId'+mapAccountIdOwnerId);
            if(listAcc.size()>0){
                //SM001_Account.setAccountTerritoryCode(listAcc);
                SM001_Account.setAccountTerritoryCode(listAcc, mapAccountIdOwnerId);
            }
            checkAccPermissionUpdate(accsToBeProcess.values());
            checkAdminCompliance(accsToBeProcess.values());
            emailEbilingManage(accsToBeProcess.values());
            setIndustryCode(accsToBeProcess.values(), (Map<Id, Account>)Trigger.oldMap);
        }
        
        system.debug('TH_Account End beforeUpdate');
    }

    

	// US 2273
    // Insert Defautl IndustryCode - Lead Qualification
    private void setIndustryCode(List<Account> accs, Map<Id, Account> oldMap) {

        Map<String, List<Id>> mapIndustryToAccounts = new Map<String, List<Id>>();

        List<Account> accsUpdate = new List<Account>();

        System.debug(accs);

        for(Account acc: accs) {
            Account oldAcc = oldMap.get(acc.Id);

            if(acc.Industry != null && acc.Industry != oldAcc.Industry) {
                if(mapIndustryToAccounts.containsKey(acc.Industry)) {
                    List<Id> lstTmp = mapIndustryToAccounts.get(acc.Industry);
                    lstTmp.add(acc.Id);
                    mapIndustryToAccounts.put(acc.Industry, lstTmp);
                } else {
                    mapIndustryToAccounts.put(acc.Industry, new List<Id>{acc.Id});
                }
				accsUpdate.add(acc);
            }
        }

        System.debug(mapIndustryToAccounts);

        Map<String, Id> mapIndsNameToId = new Map<String, Id>();
        List<Industry__c> inds = [SELECT Id, Industry__c FROM Industry__c WHERE Default_NAF__c = true AND Industry__c IN :mapIndustryToAccounts.keySet()];
        
        System.debug(inds);

        for(Industry__c ind: inds) {
            mapIndsNameToId.put(ind.Industry__c, ind.Id);
        }

        System.debug(mapIndsNameToId);

        for(Account acc: accsUpdate) {
			System.debug(mapIndsNameToId.get(acc.Industry));
			acc.Industry_Code__c = mapIndsNameToId.get(acc.Industry);

			System.debug(acc);
        }

    }
    
    /**
     * 
     *
    public static Boolean check_Email_privilege_edition(List<Account> listNewValuesAccout, List<Account> listOldValuesAccout) {

        Id Curentuser =   UserInfo.getUserId();
       
        List<User> users = [ SELECT id, Profile.name  FROM user where id = UserInfo.getUserId() ];
        for (User user : users) {
            if ((user.Profile.Name =='System Administrator' ) || (user.Profile.Name =='Cegid Business Suppor' ))
            return true ;
        }

        for (Account newAccount : listNewValuesAccout) {
            if (newAccount.ReferentCode__c ==null || newAccount.SedentaryCode__c ==null) {
                return false ;
            }
           for (Account oldAccount : listOldValuesAccout) {
              if (newAccount.id != oldAccount.id )  continue ;
              if ((oldAccount.Email_e_Billing__c != null ) && ( oldAccount.Email_e_Billing__c <> newAccount.Email_e_Billing__c)) {
                  return false ;
              }
               
           }             
        }
        return true ;  
    }*/

    public override void beforeDelete() {
        User u = [SELECT Id, Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];
        if(u.Profile.Name == 'CEGID Sales' || u.Profile.Name =='Cegid Sales Assistant' || u.Profile.Name == 'Cegid Telemarketing') {
            for(Account acc : (List<Account>) Trigger.old) {
                acc.addError('You don\'t have permission to delete Account');
            }
        }
    }

    public override void afterInsert() {
        system.debug('TH_Account afterInsert');        
        /** AZI W-001713**/
        if(System.IsBatch() == false && System.isFuture() == false) {        
            //IsAccountOwnerInRightTerritory(Trigger.newMap.keySet()); //B-1403 provisoire
        }
         /**BCR B-1570 start */
        Set<Id> accIds = new Set<Id>();
        List<Account> accs = new List<Account>();
        Map<Id,Id> mapAccountIdOwnerId = new Map<Id,Id>();
            
        for(Account acc: (List<Account>)Trigger.new){
            accIds.add(acc.Id);
            mapAccountIdOwnerId.put(acc.Id, acc.OwnerId);
        }
            
        accs = [SELECT Id, OwnerId, CodeFollowedBy__c, ReferentCode__c, SedentaryCode__c, TECHFollowedByCodeToBeCalculated__c FROM Account WHERE Id IN: accIds];
            
        system.debug('mapAccountIdOwnerId'+mapAccountIdOwnerId);
        if(accs.size() > 0) {
            SM001_Account.setAccountTerritoryCode(accs, mapAccountIdOwnerId);
            update accs;
        }
        
        /**BCR B-1570 end */
        system.debug('End TH_Account afterInsert');      
        /** End AZI W-001713**/
    }

    
    public override void afterUpdate() {
            
        
        System.debug('TH_Account afterUpdate');   
        Map<Id, Account> accsToBeProcess = (Map<Id, Account>)CheckRecursivCall.checkRunOnce(Trigger.newMap, System.TriggerOperation.AFTER_UPDATE);     
        /** AZI W-001713**/
        if(accsToBeProcess.isEmpty()) {//Control recursiv call from trigger
            System.debug('No Acc to be processed');
        } else {
            //All trigger logic should be here
            if(System.IsBatch() == false && System.isFuture() == false) {
            	//IsAccountOwnerInRightTerritory(accsToBeProcess.keySet()); //B-1403 provisoire
        	}

            if(isBypassed('TH_AccountbeforeUpdate')){
                return;
        	}

            set<Id> setAccountIds = new set<Id>();

            for(Account acc : accsToBeProcess.values()){
                Account oldAcc = (Account)Trigger.oldMap.get(acc.Id);

                if(acc.Amount_of_delay_0_1_month__c != oldAcc.Amount_of_delay_0_1_month__c || 
                acc.Amount_of_delay_1_month__c != oldAcc.Amount_of_delay_1_month__c ||
                acc.Amount_of_delay_3_months__c != oldAcc.Amount_of_delay_3_months__c ||
                acc.Amount_of_delay_6_months__c != oldAcc.Amount_of_delay_6_months__c ||
                acc.Amount_of_delay_12_months__c != oldAcc.Amount_of_delay_12_months__c || 
                acc.Amount_of_delay_over_24_months__c != oldAcc.Amount_of_delay_over_24_months__c ||
                acc.Total_Amount_of_delay__c != oldAcc.Total_Amount_of_delay__c || acc.Risk_Level__c != oldAcc.Risk_Level__c || acc.Nature__c != oldAcc.Nature__c            
                ) {
                    setAccountIds.add(acc.Id);
                }
            }

            if(setAccountIds.size()>0){
                SM004_QuoteService.rccApprovalCalculationFromAccount(setAccountIds);
            }

            bypass('TH_AccountbeforeUpdate');
        }
        
        /** End AZI W-001713**/
        System.debug('End TH_Account afterUpdate');        
    }

    /***BCR  W-001705 B-1344 ***/
    @TestVisible
    private void checkAccPermissionUpdate(List<Account> accs) {
        System.debug('checkAccPermission');
        User connectedUser = [SELECT Id, Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];
        
                                                           
       if((connectedUser.Profile.Name == 'CEGID Sales' || connectedUser.Profile.Name == 'CEGID Sales Assistant')) {
        List<PermissionSetAssignment> permissions = [SELECT Id,
                                                            PermissionSet.Name,
                                                            PermissionSet.ProfileId,
                                                            PermissionSet.Profile.Name,
                                                            AssigneeId, Assignee.Name 
                                                            FROM PermissionSetAssignment 
                                                            WHERE PermissionSet.Name = 'Sales_Ops'
                                                            AND AssigneeId =: connectedUser.Id];

           Set<Id> accIds = new Set<Id>();
           Set<Id> terrUserIds = new Set<Id>();
           Set<Id> accIdNoRestriction = new Set<Id>();

           for(Account acc: accs) {
               accIds.add(acc.Id); 
           }

           List<UserTerritory2Association> userTerritory2Associations = [SELECT Territory2Id FROM UserTerritory2Association WHERE UserId =: connectedUser.Id];
           
           if(!userTerritory2Associations.isEmpty()) {
                for(UserTerritory2Association usrTerrAsso : userTerritory2Associations) {
                    terrUserIds.add(usrTerrAsso.Territory2Id);
                }
                
                Map<Id, Set<Id>> accWithTerritoriesHieriarchy = extractSObjectTerritoryHierarchy(accIds);
    
                for(Id accId : accWithTerritoriesHieriarchy.keySet()) {
                    System.debug(accWithTerritoriesHieriarchy.get(accId));
                    System.debug(terrUserIds);
                    if(accWithTerritoriesHieriarchy.get(accId).removeAll(terrUserIds)) {
                        accIdNoRestriction.add(accId);  
                    }
                }
           }
           
           Integer nbFieldNotPassed;
           Map<String, Schema.SObjectField> fieldApiName = Schema.SObjectType.Account.fields.getMap();
           for(Account acc : accs) {
               nbFieldNotPassed = 0;
               if(acc.TECH_oppy_byPass_US1705__c) {

                acc.TECH_oppy_byPass_US1705__c = false;

               } else if(!accIdNoRestriction.contains(acc.Id) && Trigger.oldMap.get(acc.Id).get('OwnerId') != connectedUser.Id && acc.TECH_Lead_conversion__c == null) { //BCR US-1776
                    for(String field : fieldApiName.keySet())
                    { 
						if(!fieldApiName.get(field).getDescribe().isCalculated()) {
                            if(field !='Decision_center__c' &&
                               field !='ParentId' &&
                               field !='Parent_Account_Nature__c' &&
                               field !='DGE_Group__c' &&
                               field !='No_of_establishments__c' &&
                               field !='No_of_Subsidiaries__c' &&
                               field !='No_of_companies__c' &&
                               field !='Payslips_per_month__c' &&
                               field !='Phone' &&
                               field !='Website' &&
                               field !='Fiscal_Year_End_Month__c' &&
                               field !='Retail_Sector__c' &&
                               field !='No_of_Stores__c' &&
                               field !='Retail_Segmentation__c' &&
                               field !='RegisteredwiththeOrderofCharteredA__c' &&
                               field !='Yearofregistration__c' &&
                               field !='No_of_Folders__c' &&
                               field !='CPA_Sector__c' &&
                               field !='Maturity_Level__c' &&
                               field !='CPA_Number_of_users__c' &&
                               field !='Academy__c' &&
                               field !='School_Type__c' &&
                               field !='School_Level__c' &&
                               field !='To_Be_Deleted__c' &&
                               field !='National_ID__c' &&
                               field !='Email_e_Billing__c' &&
                               field !='AccountSource' &&
                               field !='Country_Scope__c' &&
                               field !='No_of_POS__c' &&
                               field !='Public_Administration__c' &&
                               field !='Customer_External_ID__c' &&
                               field !='Risk_of_Churn_Comment__c' &&
                               field !='Risk_of_Churn__c' &&
                               
                               //Technical Fields
                               field !='Infolegale_conn__Override_Account_Synchronisation_Rule__c' &&
                               field !='Infolegale_conn__Account_Synchronisation__c' &&
                               field !='TECH_NumberOfOpenOpties__c' &&
                               field !='Tech_Contact_Direct__c' &&
                               field !='Tech_Nb_Contact__c' &&
                               field !='CodeFollowedBy__c' &&
                               field !='ReferentCode__c' &&
                               acc.get(field) != Trigger.oldMap.get(acc.Id).get(field)) {
                                   if(!permissions.isEmpty()) {
                                       if(field != 'OwnerId' &&
                                          field != 'Mkto_account_owner_Role__c' &&
                                          field != 'Mkto_account_owner_job_title__c' &&
                                          field != 'Mkto_account_owner_Profile__c' &&
                                          field != 'Mkto_account_owner_Phone__c' &&
                                          field != 'sedentarycode__c' &&
                                          field !='Manual_Sync_TS__c') {
                                              nbFieldNotPassed++;
                                              system.debug('Field not passed '+field);
                                              system.debug('Old value '+Trigger.oldMap);
                                              system.debug('Old value '+Trigger.oldMap.get(acc.Id));
                                              system.debug('Old value '+Trigger.oldMap.get(acc.Id).get(field));
                                              system.debug('New value '+acc.get(field));
                                        }
                                    } else {
                                        nbFieldNotPassed++;
                                        system.debug('Field not passed '+field);
                                        system.debug('Old value '+Trigger.oldMap);
                                        system.debug('Old value '+Trigger.oldMap.get(acc.Id));
                                        system.debug('Old value '+Trigger.oldMap.get(acc.Id).get(field));
                                        system.debug('New value '+acc.get(field));
                                    }
                                }
                        }
                    }
						
					 
                    if(nbFieldNotPassed > 0) {
                        acc.addError(System.Label.VR_accountFieldsLocked);
                    }
               } else if (acc.TECH_Lead_conversion__c == 'true') { //BCR US-1776
                   System.debug('Lead conversion');
                   acc.TECH_Lead_conversion__c = null;
               }
           }
       }
    }

    public Map<Id, Set<Id>> extractSObjectTerritoryHierarchy(Set<Id> sobjIds) {
        //Extract all Territories
        Map<Id, Territory2> allOrgTerritories = new Map<Id, Territory2>([SELECT Id, ParentTerritory2Id, Name FROM Territory2 LIMIT 9800]);

        //Extract all account Territories associations
        List<ObjectTerritory2Association> sObjTerrAssos = [SELECT ObjectId, Territory2Id FROM ObjectTerritory2Association WHERE ObjectId IN: sobjIds];
        
         //Build result Map
        Map<Id, Set<Id>> mapSObjectTerritories = new Map<Id, Set<Id>>();
        //Extract all account Territories Id
        for(ObjectTerritory2Association sObjTerrAsso : sObjTerrAssos) {
            if(!mapSObjectTerritories.containsKey(sObjTerrAsso.ObjectId)) {
                mapSObjectTerritories.put(sObjTerrAsso.ObjectId, new Set<Id>());
            }
            mapSObjectTerritories.get(sObjTerrAsso.ObjectId).add(sObjTerrAsso.Territory2Id);
        }
       
        Territory2 tmp;
        for(Id SObjectId : mapSObjectTerritories.keySet()) {
            
            for(Id territoryId : mapSObjectTerritories.get(SObjectId)) {
                tmp = allOrgTerritories.get(territoryId);
                System.debug(tmp.Name);
                while (tmp.ParentTerritory2Id != null) {
                    tmp = allOrgTerritories.get(tmp.ParentTerritory2Id);
                    mapSObjectTerritories.get(SObjectId).add(tmp.Id);
                    System.debug(tmp.Name);
                }
            }
        }
        return mapSObjectTerritories;  
    }


    /***FIN BCR W-001705 B-1344 ***/ 

    /***BCR W-001709 ***/
    @TestVisible
    private void checkAdminCompliance(List<Account> accs) {
        for(Account acc : accs) {
            if(String.isBlank(acc.ERP_Number__c) || 
               String.isBlank(acc.Phone) ||
               String.isBlank(acc.BillingStreet) ||
               String.isBlank(acc.BillingPostalCode) ||
               String.isBlank(acc.BillingCity) ||
               !(acc.Status__c == 'Validated') ||
               !acc.Tech_Contact_Direct__c) {

                acc.TECH_Administrative_Compliance__c = false;
                
            } else if((acc.BillingCountryCode == 'FR') && 
                      (String.isBlank(acc.National_ID__c) ||
                       String.isBlank(acc.IntercommunityVATnumber__c))) {

                        acc.TECH_Administrative_Compliance__c = false;
        
            } else if(acc.BillingCountryCode == 'MC' &&
                      String.isBlank(acc.National_ID__c) &&
                      String.isBlank(acc.IntercommunityVATnumber__c) ) {
                          
                        acc.TECH_Administrative_Compliance__c = false;

            } else if ((acc.BillingCountryCode == 'BE' ||
                        acc.BillingCountryCode == 'ES' ||
                        acc.BillingCountryCode == 'PT' ||
                        acc.BillingCountryCode == 'IT' ||
                        acc.BillingCountryCode == 'DE' ||
                        acc.BillingCountryCode == 'GB' ||
                        acc.BillingCountryCode == 'AT' ||
                        acc.BillingCountryCode == 'BG' ||
                        acc.BillingCountryCode == 'CY' ||
                        acc.BillingCountryCode == 'HR' ||
                        acc.BillingCountryCode == 'DK' ||
                        acc.BillingCountryCode == 'EE' ||
                        acc.BillingCountryCode == 'FI' ||
                        acc.BillingCountryCode == 'GR' ||
                        acc.BillingCountryCode == 'HU' ||
                        acc.BillingCountryCode == 'IE' ||
                        acc.BillingCountryCode == 'LV' ||
                        acc.BillingCountryCode == 'LT' ||
                        acc.BillingCountryCode == 'LU' ||
                        acc.BillingCountryCode == 'MT' ||
                        acc.BillingCountryCode == 'NL' ||
                        acc.BillingCountryCode == 'PL' ||
                        acc.BillingCountryCode == 'CZ' ||
                        acc.BillingCountryCode == 'RO' ||
                        acc.BillingCountryCode == 'SK' ||
                        acc.BillingCountryCode == 'SI' ||
                        acc.BillingCountryCode == 'SE' ) &&
                        String.isBlank(acc.IntercommunityVATnumber__c )) {

                    acc.TECH_Administrative_Compliance__c = false;

            } else if(!(acc.BillingCountryCode == 'FR' ||
                        acc.BillingCountryCode == 'MC' ||
                        acc.BillingCountryCode == 'BE' ||
                        acc.BillingCountryCode == 'ES' ||
                        acc.BillingCountryCode == 'PT' ||
                        acc.BillingCountryCode == 'IT' ||
                        acc.BillingCountryCode == 'DE' ||
                        acc.BillingCountryCode == 'GB' ||
                        acc.BillingCountryCode == 'AT' ||
                        acc.BillingCountryCode == 'BG' ||
                        acc.BillingCountryCode == 'CY' ||
                        acc.BillingCountryCode == 'HR' ||
                        acc.BillingCountryCode == 'DK' ||
                        acc.BillingCountryCode == 'EE' ||
                        acc.BillingCountryCode == 'FI' ||
                        acc.BillingCountryCode == 'GR' ||
                        acc.BillingCountryCode == 'HU' ||
                        acc.BillingCountryCode == 'IE' ||
                        acc.BillingCountryCode == 'LV' ||
                        acc.BillingCountryCode == 'LT' ||
                        acc.BillingCountryCode == 'LU' ||
                        acc.BillingCountryCode == 'MT' ||
                        acc.BillingCountryCode == 'NL' ||
                        acc.BillingCountryCode == 'PL' ||
                        acc.BillingCountryCode == 'CZ' ||
                        acc.BillingCountryCode == 'RO' ||
                        acc.BillingCountryCode == 'SK' ||
                        acc.BillingCountryCode == 'SI' ||
                        acc.BillingCountryCode == 'SE' ) &&
                        String.isBlank(acc.National_ID__c)) {
                    
                        acc.TECH_Administrative_Compliance__c = false;
            } else {
                acc.TECH_Administrative_Compliance__c = true;
            }
                  
        }
        
    }
    /***FIN BCR W-001709 ***/

    @future //BCR B-1403
    public static void IsAccountOwnerInRightTerritory(Set<Id> accsId){ 
        system.debug('IsAccountOwnerInRightTerritory');   
        List<Account> accounts = [SELECT Id, Name, IsOwnerInRightTerritory__c, OwnerId FROM Account WHERE Id IN :accsId];
        
        List<Id> ownersId =  new List<Id>();
        List<Account> accsUpdated = new List<Account>();

        for (Account acc: accounts) {
            ownersId.add(acc.OwnerId);
            //break;
        }
               System.debug('IsAccountOwnerInRightTerritory ownersId ' + ownersId.size());   

               List<ObjectTerritory2Association> objectTerritory2AssociationList = 
                      [SELECT Territory2Id, ObjectId FROM  ObjectTerritory2Association  WHERE IsDeleted = false AND ObjectId in :accsId];

               System.debug('IsAccountOwnerInRightTerritory :: objectTerritory2AssociationList.size ' +objectTerritory2AssociationList.size() );

                List<UserTerritory2Association> usersTerr = 
                                   [SELECT UserId, Territory2Id FROM UserTerritory2Association WHERE isActive = true AND UserId in :ownersId];

                System.debug('IsAccountOwnerInRightTerritory :: usersTerr.size ' +usersTerr.size() );


                for (Account acc: accounts) {
                    boolean userFound  = false;
                    acc.IsOwnerInRightTerritory__c = true;
                    
                    for(ObjectTerritory2Association objectTerritory2Association: objectTerritory2AssociationList){
                        if(objectTerritory2Association.ObjectId.equals(acc.Id)){
                            for(UserTerritory2Association userTerr : usersTerr){                                    
                                if (userTerr.Territory2Id.equals(objectTerritory2Association.Territory2Id) && userTerr.UserId.equals(acc.OwnerId)){
                                    userFound = true;  
                                    break; 
                                }                                                                                                                 
                            } 
                        }                                                                         
                    }       
    
            System.debug('IsAccountOwnerInRightTerritory userFound  : ' + userFound+' For Account  : ' + acc.Name);   
                if(!userFound){
                   acc.IsOwnerInRightTerritory__c = false;                   
                }
                accsUpdated.add(acc);
            } 
            
            if(accsUpdated.size()>0){
                update accsUpdated;
            }                
            System.debug('IsAccountOwnerInRightTerritory');   
    }

    private void emailEbilingManage(List<Account> accs) {
        for(Account acc : accs) {
            if(acc.Invoice_Sending_Mode__c != 'Email') {
                acc.Email_e_Billing__c = null;
            }
        }
    }        
}