unpackaged/main/default/objects/Account/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <description>BIC</description>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>IBAN</description>
    <label>IBAN</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Cegid Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cegid Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entity__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>Entity_Code__c</fullName>
    <label>Entity Code</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/ICS__c.field-meta.xml
<CustomField>
    <fullName>ICS__c</fullName>
    <label>ICS</label>
    <length>115</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entity__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Cegid_Entity__c.field-meta.xml
<CustomField>
    <fullName>Cegid_Entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cegid Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Entity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Entity_ICS__c.field-meta.xml
<CustomField>
    <fullName>Entity_ICS__c</fullName>
    <formula>Cegid_Entity__r.ICS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity ICS</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <default>true</default>
        <label>Direct</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Mixed</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Partner</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Influencing Organization</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/B2B_QuoteGetMandatSepa_TEST.cls
/***
* @author      : Trilochnah - Comforth Karoo
* @date		   : 26/10/21
* @description : Test class for B2B_QuoteGetMandatSepa
***/
@isTest
public class B2B_QuoteGetMandatSepa_TEST {
    private static User adminUser =  new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static User testUser;
    static WebCart webcart1;
    static Account acc1;
    static WebStore Ws1;
    static CartItem cartItem1;
    static CartDeliveryGroup cartDeliveryGroup1;
    static Pricebook2 pricebook2;
    static Entity__c entityc;
    
    static{       
        System.runAs(adminUser){
            // Insert Account
            acc1 = new Account(
                Name = 'Acc1',
                Type__c='001',
                BillingStreet = 'Test',
                BillingCity = 'Test',
                BillingCountry = 'Italy',
                BillingPostalCode = '12345',
                National_ID_Exception__c='Creation In progress',
                ERP_Number__c='ERP_000004'
                
            );
            insert acc1;
            
            //Insert Webstore
            ws1= new WebStore(
                Name='wstest'
            );
            insert ws1;
            
            // Insert WebCart
            webcart1 = new WebCart(
                Name = 'Cart1',
                Status='Closed',
                AccountId=acc1.id,
                WebStoreId=ws1.Id
                // Bank_City__c='bankcity',
                // Bank_Name__c='neuflize paris',
                // BIC__c='NSMBFRPPXXX',
                // IBAN__c='FR7630788009000134418000167',
                // UMR__c='++0019839008560300'
            );
            insert webcart1;   
            // Insert cartDeliveryGroup
            cartDeliveryGroup1 = new CartDeliveryGroup(
                Name='Default Delivery',
                CartId=webcart1.Id
            );
            insert cartDeliveryGroup1;
            
            //Insert cart item
            CartItem cartItem1 = new CartItem(
                CartId=webcart1.Id, 
                Sku='SKU_Test1', 
                Quantity=3.0, 
                Type='Product', 
                Name='TestProduct', 
                CartDeliveryGroupId=cartDeliveryGroup1.Id
            );
            insert cartItem1;

            //Insert entity
            // entityc= new Entity__c(
            //     Name='testentityc',
            //     City__c ='Lyon', 
            //     Country__c='France', 
            //     ICS__c='123', 
            //     Postal_Code__c='69009', 
            //     Street__c='52 quai Paul Sedallian',
            //     Entity_code__c = '1002'
            // );
            // insert entityc;

            Entity__c  CegidEntity =  new UTIL_TestFactory.EntityFactory().createEntity();
            insert CegidEntity; 
            
            //Insert Pricebook2
            pricebook2 pb= new Pricebook2(
                Name='TestPricebook',
                Cegid_Entity__c= CegidEntity.id,
                //Entity_ICS__c='To be defined',
                IsActive = true
                
            );
            insert pb;
            
           
            
        }
    }
    /***
    * @author      : Trilochnah - Comforth Karoo
    * @date		   : 27/10/21
    * @description : 
    ***/
    static testMethod void testGetData(){
        
        System.runAs(adminUser){
            
            List<Id> listWebCart= new List<Id>();
            for(WebCart wc:[SELECT Id,AccountId,Account.Name,WebStore.Name,WebStoreId,Owner.Name  FROM WebCart 
            where Name = 'Cart1']){
                listWebCart.add(wc.Id);
            }
        
            Test.setMock(HttpCalloutMock.class, new  QuoteGetMandatSepa_Mock());   
            Test.startTest();
                B2B_QuoteGetMandatSepa.getData(listWebCart);       
            Test.stopTest();  
   
        }
            
    }

    static testMethod void testWSError() {
        List<Id> listWebCart= new List<Id>();
        for(WebCart wc:[SELECT Id,AccountId,Account.Name,WebStore.Name,WebStoreId,Owner.Name  FROM WebCart 
        where Name = 'Cart1']){
            listWebCart.add(wc.Id);
        }
        
        Test.setMock(HttpCalloutMock.class, new MockErrorResponse());   
        Test.startTest();         
           Map<String, Object> mapResp = B2B_QuoteGetMandatSepa.getData(listWebCart); 
        Test.stopTest();        
    }

    private class MockErrorResponse implements HttpCalloutMock {  
        public HTTPResponse respond(HTTPRequest req){
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"error": {"errorCode": 500, "errorDateTime": "2020-08-14T02:38:54", "errorMessage": "Pas de retour sur cette sélection", "errorDescription": "Pas de retour sur cette sélection"} }');
            res.setStatusCode(500);
            return res;
        }
    }
    
}