unpackaged/main/default/objects/Account/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <description>BIC</description>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>IBAN</description>
    <label>IBAN</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/B2B_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store global params for B2B CEGID Store</description>
    <label>B2B Settings</label>
</CustomObject>

unpackaged/main/default/objects/B2B_Settings__c/fields/CommunityId__c.field-meta.xml
<CustomField>
    <fullName>CommunityId__c</fullName>
    <description>The id of the community. Used in SSO Auto provisioning.</description>
    <label>Community Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/DefaultBuyerGroup__c.field-meta.xml
<CustomField>
    <fullName>DefaultBuyerGroup__c</fullName>
    <description>Default Buyer Group to assign Buyer account during auto-provisioning</description>
    <inlineHelpText>Default Buyer Group to assign Buyer account during auto-provisioning</inlineHelpText>
    <label>Default Buyer Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StoreDomain__c.field-meta.xml
<CustomField>
    <fullName>StoreDomain__c</fullName>
    <defaultValue>"https://store.cegid.com"</defaultValue>
    <label>Store domain</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StoreLoginURL__c.field-meta.xml
<CustomField>
    <fullName>StoreLoginURL__c</fullName>
    <label>Store Login URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2B_Settings__c/fields/StripePublishableKey__c.field-meta.xml
<CustomField>
    <fullName>StripePublishableKey__c</fullName>
    <defaultValue>"pk_test_51J3G9THyPvQW0JfV0OddzUOOkYQM50uC8wzPfzckGqqCNVKVo4vJssOcNTZIRnksbloJZBHc4AIv2m1nEKU7TAeA00xLWtdquz"</defaultValue>
    <description>Populate with the value of the publishable key in the Stripe Dashboard</description>
    <inlineHelpText>Populate with the value of the publishable key in the Stripe Dashboard</inlineHelpText>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CartItem/fields/TECH_SessionCode__c.field-meta.xml
<CustomField>
    <fullName>TECH_SessionCode__c</fullName>
    <description>US W-001812 BtoB_USXX_Affichage des dates de sessions pour un produit de formation vendu unitairement</description>
    <label>Session Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CartItem/fields/TECH_SessionDate__c.field-meta.xml
<CustomField>
    <fullName>TECH_SessionDate__c</fullName>
    <description>US W-001812 BtoB_USXX_Affichage des dates de sessions pour un produit de formation vendu unitairement</description>
    <label>Session Date</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/B2BOrder__c.field-meta.xml
<CustomField>
    <fullName>B2BOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to differentiate between an Order created from the Store VS one created from CPQ.
US W-001599 - BtoB_US28_mail de confirmation de commande</description>
    <inlineHelpText>Set to TRUE if the Order is created from the Store.</inlineHelpText>
    <label>B2B Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>VMO 20211007: Created LOOKUP on Cart to get CartItem Information in apex to create the Training Session records using the fields Session Date and Session Code that are saved on the CartItem when user adds a Product to his Cart.</description>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>34</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Participant__c/fields/CartItemId__c.field-meta.xml
<CustomField>
    <fullName>CartItemId__c</fullName>
    <label>CartItemId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Civilite__c.field-meta.xml
<CustomField>
    <fullName>Civilite__c</fullName>
    <label>Civilité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>Prénom</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <default>true</default>
        <label>Direct</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Mixed</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Partner</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Influencing Organization</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/B2B_OrderConfirmationEmail_TEST.cls
/**
 * @author Varun Molla - Comforth Karoo
 * @date Creation 2021-11-11
 * @description Test class for apex class B2B_OrderConfirmationEmail
 *              
*/
@isTest
private class B2B_OrderConfirmationEmail_TEST {

    private static User adminUser =  new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static User testUser;
    static WebCart webcart1;
    static Account acc1;
    static Participant__c participant1;
    static CartItem cartItem1;
    static CartDeliveryGroup cartDeliveryGroup1;
    static BypassTrigger__c bypasstrigger;
    static WebStore webStore1;
    
    static{       
        System.runAs(adminUser){
            //Insert BypassTrigger__c
            bypasstrigger = new BypassTrigger__c(
                Activatetrigger__c=true,
                SetupOwnerId=Userinfo.getOrganizationId()
            );
            insert bypasstrigger;

            B2B_Settings__c settings = new B2B_Settings__c();
            settings.StoreLoginURL__c = 'Test';
            settings.CommunityId__c = 'Test';
            settings.DefaultBuyerGroup__c  = 'Test';
            settings.StoreDomain__c = 'Test';
            settings.StripePublishableKey__c = 'Test';
            insert settings;
            
            // Insert Account
            acc1 = new Account(
                Name = 'Acc1',
                Type__c='001',
                BillingStreet = 'Test',
                BillingCity = 'Test',
                BillingCountry = 'Italy',
                BillingPostalCode = '12345',
                National_ID_Exception__c='Creation In progress'
                
            );
            insert acc1;
            
            //Insert webstore
            webStore1 = new WebStore(
                Name='testwebstore'
                
            );
            insert webStore1;
            
            // Insert WebCart
            webcart1 = new WebCart(
                Name = 'Cart1',
                Status='Checkout',
                AccountId=acc1.id,
                WebStoreId= webStore1.Id         
            );
            insert webcart1;  
            
            // Insert cartDeliveryGroup
            cartDeliveryGroup1 = new CartDeliveryGroup(
                Name='Default Delivery',
                CartId=webcart1.Id
            );
            insert cartDeliveryGroup1;
            
            //Insert cart item
            CartItem cartItem1 = new CartItem(
                CartId=webcart1.Id, 
                Sku='SKU_Test1', 
                Quantity=3.0,
                SalesPrice=400,
                Type='Product', 
                Name='TestProduct', 
                CartDeliveryGroupId=cartDeliveryGroup1.Id,
                TECH_SessionDate__c = '25/10/2021 09h00 - 10h30',
                TECH_SessionCode__c = 'PRU117'
            );
            insert cartItem1;
            
            //Insert participants
            participant1 = new Participant__c(
                Name='testP1',
                Civilite__c ='Mr',
                Prenom__c = 'Test',
                EmailAddress__c='test1@test.test', 
                CartItemId__c=cartItem1.Id          
            );
            insert participant1;
        }
    }

    @isTest static void createTrainingSessionRecords_Test(){ 
        System.runAs(adminUser){ 
            Account acct = new Account(Name='tAccount');
            insert acct;

            Product2 pd = new Product2(Name='Pord A',isActive=true);
            pd.IsActive = true;
            insert pd;

            Product2 p = new Product2();
            p.Name = ' Test Product ';
            p.Description='Test Product Entry 1';
            p.productCode = 'ABC';
            p.isActive = true;
            insert p;

            ContentVersion cv=new Contentversion();
            cv.title='ABC';
            cv.PathOnClient ='test';
            Blob b=Blob.valueOf('Unit Test Attachment Body');
            cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
            insert cv;

            ContentDocumentLink contentlink=new ContentDocumentLink();
            contentlink.LinkedEntityId=p.id;
            contentlink.contentdocumentid=[SELECT contentdocumentid FROM contentversion WHERE Id = :cv.id].contentdocumentid;
            contentlink.ShareType = 'I';
            contentlink.Visibility = 'AllUsers'; 
            insert contentlink;

            //PriceBook2 pb2Standard = [SELECT Id FROM Pricebook2 WHERE isStandard=true];
            Id standardPriceBookId = Test.getStandardPricebookId();

            PricebookEntry standardPrice = new PricebookEntry();
            standardPrice.Pricebook2Id = standardPriceBookId;
            standardPrice.Product2Id = p.Id;
            standardPrice.UnitPrice = 1;
            standardPrice.IsActive = true;
            standardPrice.UseStandardPrice = false;
            insert standardPrice;

            Order od = new Order();
            od.Name = '14TPE000001';
            od.AccountId = acct.Id;
            od.EffectiveDate = Date.Today();
            od.Status = 'Draft';
            od.BIC__c = 'CDEFGHIJ';
            od.IBAN__c = 'CDEFGHIJABCDEFGHIJABCDEFG';
            od.Pricebook2Id = standardPriceBookId;
            od.B2BOrder__c = true;
            od.Cart__c = webcart1.Id;
            insert od;

            PricebookEntry pbe = new PricebookEntry(Pricebook2Id=standardPriceBookId, Product2Id=pd.Id, UnitPrice=99, isActive=true);
            insert pbe;
            Product2 p2ex = [SELECT Name FROM Product2 WHERE Id = :pd.Id];

            OrderItem ordPd = new OrderItem(PriceBookEntryId=standardPrice.Id, OrderId=od.Id, Quantity=1, UnitPrice=99, Product2Id = p.Id);
            insert ordPd;

            CartCheckoutSession ccs = new CartCheckoutSession();
            ccs.OrderId = od.Id;
            ccs.WebCartId = webcart1.Id;
            ccs.Name = 'TestCCS';
            ccs.State='InProcessing';
            insert ccs;

            List<CartCheckoutSession> listMainCheckoutSession = new List<CartCheckoutSession>{ccs};

            Test.startTest();
                B2B_OrderConfirmationEmail.createTrainingSessionRecords(listMainCheckoutSession);
            Test.stopTest();
        }   
    }

    @isTest static void createTrainingSessionRecords_Test_CreditCard(){ 
        System.runAs(adminUser){ 
            Account acct = new Account(Name='tAccount');
            insert acct;

            Product2 pd = new Product2(Name='Pord A',isActive=true);
            pd.IsActive = true;
            insert pd;

            Product2 p = new Product2();
            p.Name = ' Test Product ';
            p.Description='Test Product Entry 1';
            p.productCode = 'ABC';
            p.isActive = true;
            insert p;

            //PriceBook2 pb2Standard = [SELECT Id FROM Pricebook2 WHERE isStandard=true];
            Id standardPriceBookId = Test.getStandardPricebookId();

            PricebookEntry standardPrice = new PricebookEntry();
            standardPrice.Pricebook2Id = standardPriceBookId;
            standardPrice.Product2Id = p.Id;
            standardPrice.UnitPrice = 1;
            standardPrice.IsActive = true;
            standardPrice.UseStandardPrice = false;
            insert standardPrice;

            Order od = new Order();
            od.Name = '14TPE000001';
            od.AccountId = acct.Id;
            od.EffectiveDate = Date.Today();
            od.Status = 'Draft';
            od.BIC__c = 'CDEFGHIJ';
            od.Pricebook2Id = standardPriceBookId;
            od.B2BOrder__c = true;
            od.Cart__c = webcart1.Id;
            insert od;

            PricebookEntry pbe = new PricebookEntry(Pricebook2Id=standardPriceBookId, Product2Id=pd.Id, UnitPrice=99, isActive=true);
            insert pbe;
            Product2 p2ex = [SELECT Name FROM Product2 WHERE Id = :pd.Id];

            OrderItem ordPd = new OrderItem(PriceBookEntryId=standardPrice.Id, OrderId=od.Id, Quantity=1, UnitPrice=99);
            insert ordPd;

            CartCheckoutSession ccs = new CartCheckoutSession();
            ccs.OrderId = od.Id;
            ccs.WebCartId = webcart1.Id;
            ccs.Name = 'TestCCS';
            ccs.State='InProcessing';
            insert ccs;

            List<CartCheckoutSession> listMainCheckoutSession = new List<CartCheckoutSession>{ccs};

            Test.startTest();
                B2B_OrderConfirmationEmail.createTrainingSessionRecords(listMainCheckoutSession);
            Test.stopTest();
        }   
    }
}