unpackaged/main/default/objects/Account/fields/CodeFollowedBy__c.field-meta.xml
<CustomField>
    <fullName>CodeFollowedBy__c</fullName>
    <label>Code Followed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ReferentCode__c.field-meta.xml
<CustomField>
    <fullName>ReferentCode__c</fullName>
    <label>Referent Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/SedentaryCode__c.field-meta.xml
<CustomField>
    <fullName>SedentaryCode__c</fullName>
    <label>Sedentary Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHFollowedByCodeToBeCalculated__c.field-meta.xml
<CustomField>
    <fullName>TECHFollowedByCodeToBeCalculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Followed By Code To Be Calculated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Cegid_solution__c.field-meta.xml
<CustomField>
    <fullName>Cegid_solution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cegid solution</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <defaultValue>"005"</defaultValue>
    <description>Used for Additionnal Order - W-002451</description>
    <label>Channel</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TerritoryCode__c.field-meta.xml
<CustomField>
    <fullName>TerritoryCode__c</fullName>
    <label>Territory Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Territory2/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/TerritoryCode__c.field-meta.xml
<CustomField>
    <fullName>TerritoryCode__c</fullName>
    <label>Territory Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>CASE( 
    TEXT(Agency__c),
'112', 'CPA',
'113', 'CPA',
'114', 'CPA',
'115', 'CPA',
'217', 'RETAIL',
'290', 'RETAIL',
'320', 'CPA',
'340', 'CPA',
'392', 'FINANCE',
'393', 'FINANCE',
'394', 'FINANCE',
'395', 'FINANCE',
'396', 'FINANCE',
'397', 'FINANCE',
'410', 'CPA',
'411', 'CPA',
'412', 'CPA',
'470', 'CPA',
'530', 'Other',
'549', 'RETAIL',
'550', 'RETAIL',
'552', 'RETAIL',
'555', 'RETAIL',
'556', 'RETAIL',
'557', 'RETAIL',
'560', 'RETAIL',
'563', 'HCM',
'583', 'RETAIL',
'585', 'HCM',
'714', 'HCM',
'715', 'HCM',
'800', 'FINANCE',
'803', 'SB',
'804', 'SB',
'805', 'FINANCE',
'808', 'FINANCE',
'809', 'RETAIL',
'810', 'FINANCE',
'811', 'FINANCE',
'812', 'HCM',
'813', 'HCM',
'814', 'FINANCE',
'815', 'FINANCE',
'816', 'FINANCE',
'818', 'CPA',
'819', 'FINANCE',
'822', 'FINANCE',
'823', 'HCM',
'824', 'HCM',
'825', 'HCM',
'826', 'HCM',
'829', 'CPA',
'830', 'CPA',
'831', 'SB',
'832', 'HCM',
'834', 'HCM',
'835', 'HCM',
'836', 'HCM',
'837', 'HCM',
'838', 'HCM',
'839', 'HCM',
'841', 'HCM',
'842', 'HCM',
'840', 'HCM',
'843', 'OTHER',
'844', 'RETAIL',
'845', 'FINANCE',
'846', 'FINANCE',
'847', 'FINANCE',
'849', 'FINANCE',
'850', 'FINANCE',
'852', 'FINANCE',
'853', 'FINANCE',
'854', 'FINANCE',
'855', 'HCM',
'856', 'SB',
'857', 'HCM',
'858', 'HCM',
'Not Assigned'
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <label>Direct Sales Force</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect Sales Force</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Inside Sales</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Consultants</label>
    </customValue>
    <customValue>
        <fullName>006</fullName>
        <label>C.A.T.</label>
    </customValue>
    <customValue>
        <fullName>007</fullName>
        <label>Non-activity sales</label>
    </customValue>
    <customValue>
        <fullName>008</fullName>
        <label>Intra-group sales</label>
    </customValue>
    <customValue>
        <fullName>009</fullName>
        <label>Interactive sales</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM001_Account_GDH_TEST.cls
@isTest
public class SM001_Account_GDH_TEST {
/**
 * @File Name          : SM001_Account_GDH_TEST
 * @Description        : Update fileds when owner is changed in account and territories are added or removed
 * @Author             : SRA   
 * @Group              : Comforth-Karoo
 * @Last Modified By   : SRA
 * @Last Modified On   : 30/10/2020
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * ---    -----------       -------           ------------------------ 
 * 1.0    30/10/2020         SRA              Initial Version
 * ---    -----------       -------           ------------------------ 
**/
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static User adminUser2 = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static Territory2 t = new Territory2();
    
    @testSetup static void setup(){
        System.runAs(adminUser){       
            
            Territory2Model territoryModel = [select Id,Name From Territory2Model];

            Territory2Type territoryType = [select Id,MasterLabel From Territory2Type where MasterLabel='Hierarchy Territory'];
            
            insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
                
            Test.startTest();
            List<Account> listAcc = new List<Account>();
            List<Contact> listCon = new List<Contact>();
            List<Opportunity> listOppConverted = new List<Opportunity>();
            List<Opportunity> listOppAutoCreate = new List<Opportunity>();
            List<ObjectTerritory2Association> listOTA = new List<ObjectTerritory2Association>();
            List<Territory2> listTerritory = [Select Id , Expertise__c from Territory2 where  Expertise__c='200']; 
            
            t.Name = 'Cegid Test';
            t.TerritoryCode__c ='3441';
            t.DeveloperName= 'Cegid_Test';
            t.Territory2ModelId=territoryModel.Id;
            t.BU__c='302';
            t.Channel__c='001';
            t.Territory2TypeId=territoryType.Id;

            insert t;
            system.System.debug('t'+t);
            
            listAcc.add(new UTIL_TestFactory.AccountFactory().createAccount());
            listAcc[0].National_ID_Exception__c ='Empty on loading';
            listAcc[0].BillingPostalCode ='75008';
            listAcc[0].BillingCountry ='France';
            listAcc[0].BillingCity ='Paris';
            listAcc[0].No_of_Employees_Group__c =12;
            listAcc[0].No_of_Stores__c =2;
            listAcc[0].NumberOfEmployees =12;
            insert listAcc;
            
            Account acc = new Account();
            acc.Name= 'Test';
            acc.National_ID_Exception__c ='Empty on loading';
            acc.BillingPostalCode ='75009';
            acc.BillingCountry ='France';
            acc.BillingCity ='Paris';
            acc.No_of_Employees_Group__c =15;
            acc.No_of_Stores__c =7;
            acc.NumberOfEmployees =14;
            acc.OwnerId=adminUser.Id;

            insert acc;
            
            Account_Expertise__c accShare = new Account_Expertise__c();
            accShare.Account__c=listAcc[0].Id;
            accShare.Expertise__c='200';
            accShare.Cegid_solution__c=true;
            insert accShare;
            
            
            listOTA.add(new UTIL_TestFactory.ObjectTerritory2AssociationFactory().createObjectTerritory2Association(listAcc[0].Id,listTerritory[0].Id));
            listOTA.add(new UTIL_TestFactory.ObjectTerritory2AssociationFactory().createObjectTerritory2Association(acc.Id,t.Id));
            listOTA.add(new UTIL_TestFactory.ObjectTerritory2AssociationFactory().createObjectTerritory2Association(listAcc[0].Id,listTerritory[1].Id));
            listOTA.add(new UTIL_TestFactory.ObjectTerritory2AssociationFactory().createObjectTerritory2Association(listAcc[0].Id,listTerritory[2].Id));
            listOTA.add(new UTIL_TestFactory.ObjectTerritory2AssociationFactory().createObjectTerritory2Association(listAcc[0].Id,listTerritory[3].Id));
            Insert listOTA;
            
            Test.stopTest();
        }
    }
    
    static testMethod void testPackage() {
        
        List<Account> listAcc = [SELECT id from Account];
        listAcc[0].TECHFollowedByCodeToBeCalculated__c=true;
        
        System.runAs(adminUser) {
            Test.startTest();
            update listAcc;
            Test.stopTest();
        }
    }
    
        //Owner avec un territoire et compte sans territoire
    static testMethod void testing_AccNoTerritory() {
        system.debug('testing_AccNoTerritory');

        List<Account> listAcc = [SELECT id,TECHFollowedByCodeToBeCalculated__c,OwnerId,ReferentCode__c,SedentaryCode__c,CodeFollowedBy__c from Account where Name LIKE '%Test%'];
        User accountOwner=[select id,Name from User where Name LIKE '%Willy Bocquet%'];
        system.debug('listAcc ***'+listAcc[0].TECHFollowedByCodeToBeCalculated__c);
        system.debug('listAcc ***'+listAcc[0].OwnerId);
        system.debug('accountOwnerId'+accountOwner);
        listAcc[0].TECHFollowedByCodeToBeCalculated__c = True;
        listAcc[0].OwnerId=accountOwner.Id;
        
        system.debug('listAcc2 ***'+listAcc[0].TECHFollowedByCodeToBeCalculated__c);
        system.debug('listAcc2 ***'+listAcc[0].OwnerId);

        UserTerritory2Association uts3 = [SELECT Id, RoleInTerritory2, Territory2Id, UserId FROM UserTerritory2Association where UserId=:accountOwner.Id];
        
        System.runAs(adminUser) {
            Test.startTest();
            update listAcc;
            Test.stopTest();
        }
        
        Territory2 territory = [SELECT Id,TerritoryCode__c FROM Territory2 WHERE Id=:uts3.Territory2Id];
        List<Account> listAcc2 = [SELECT id,TECHFollowedByCodeToBeCalculated__c,OwnerId,ReferentCode__c,SedentaryCode__c,CodeFollowedBy__c from Account where Name LIKE '%Test%'];
        

        system.debug('listAcc'+listAcc2[0].TECHFollowedByCodeToBeCalculated__c);
        system.debug('listAcc ReferentCode'+listAcc2[0].ReferentCode__c);

        System.assertEquals(territory.TerritoryCode__c,listAcc2[0].ReferentCode__c);
        System.assertEquals(null,listAcc2[0].SedentaryCode__c);
        System.assertEquals(territory.TerritoryCode__c,listAcc2[0].CodeFollowedBy__c);
    }
}