unpackaged/main/default/objects/Account/fields/CodeFollowedBy__c.field-meta.xml
<CustomField>
    <fullName>CodeFollowedBy__c</fullName>
    <label>Code Followed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ReferentCode__c.field-meta.xml
<CustomField>
    <fullName>ReferentCode__c</fullName>
    <label>Referent Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/SedentaryCode__c.field-meta.xml
<CustomField>
    <fullName>SedentaryCode__c</fullName>
    <label>Sedentary Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHFollowedByCodeToBeCalculated__c.field-meta.xml
<CustomField>
    <fullName>TECHFollowedByCodeToBeCalculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Followed By Code To Be Calculated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Function__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>Used to calculate the Buynig persona used to target Campaigns</description>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID Exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>Controlilng field to select Fonction</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Function.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting recoverings contact</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>After-Sales Service Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business app Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business Development Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Career Planning Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Directors</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Management</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Supervisory Board</fullName>
    </customValue>
    <customValue>
        <fullName>Chartered accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Accounting Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Digital Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Information Officer</fullName>
    </customValue>
    <customValue>
        <fullName>General Services Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Personnel Dir.</fullName>
    </customValue>
    <masterLabel>Function</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finance and accounting</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Affairs</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and communication</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Representative</fullName>
    </customValue>
    <customValue>
        <fullName>Transversal</fullName>
    </customValue>
    <customValue>
        <fullName>NR</fullName>
        <isActive>false</isActive>
        <label>NR</label>
    </customValue>
    <masterLabel>Service</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM011_Contact_TEST.cls
@isTest
public class SM011_Contact_TEST {
/**
 * @File Name          : SM011_Contact_TEST
 * @Description        : Convert Lead if contact has same email 
 * @Author             : SRA   
 * @Group              : Comforth-Karoo
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * ---    -----------       -------           ------------------------ 
 * 1.0    03/12/2020         SRA              Initial Version
 * ---    -----------       -------           ------------------------ 
**/
    
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static User adminUser2 = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static List<Account> listAcc = new List<Account>();
    static Contact con = new Contact();
    
    @testSetup static void setup(){
        System.runAs(adminUser){       
            
            insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
                
            Test.startTest();
            
            listAcc.add(new UTIL_TestFactory.AccountFactory().createAccount());
            listAcc[0].National_ID_Exception__c ='Empty on loading';
            listAcc[0].BillingPostalCode ='75008';
            listAcc[0].BillingCountry ='France';
            listAcc[0].BillingCity ='Paris';
            listAcc[0].No_of_Employees_Group__c =12;
            listAcc[0].No_of_Stores__c =2;
            listAcc[0].NumberOfEmployees =12;
            insert listAcc;
            
            Lead l = new Lead();
            l.FirstName='Test1111';
            l.LastName='Test1111';
            l.Service__c='HR';
            l.Function__c='Personnel Dir.';
            l.Status='Assigned';
            l.Company='test';
            l.Email='TestContact1111@test.com';
            //l.OwnerId='00G1w000002aZGb';
            
            insert l;
            
            Lead lead2 = new Lead();
            lead2.FirstName='Test11';
            lead2.LastName='Test11';
            lead2.Service__c='HR';
            lead2.Function__c='Personnel Dir.';
            lead2.Status='New';
            lead2.Company='testing';
            lead2.Email='TestContact11@test.com';
            //lead2.OwnerId='00G1w000002aZGb';
            
            insert lead2;
            
            
            Test.stopTest();
        }
    }
    
    static testMethod void testErrorMessage() {

        System.runAs(adminUser) {
            Test.startTest();

            List<Account> listAcc = [SELECT id,TECHFollowedByCodeToBeCalculated__c,OwnerId,ReferentCode__c,SedentaryCode__c,CodeFollowedBy__c from Account where Name LIKE '%Test%'];

            con.FirstName='TestContact';
            con.LastName='Trigger';
            con.Email='TestContact1111@test.com';
            con.AccountId=listAcc[0].Id;
            con.CurrencyIsoCode='EUR';
            con.Function__c='General Services Mgr.';
            con.Service__c='Purchasing';
            
            try {
                insert con;
            } catch(DmlException e) {
                System.debug('The contact you\'re trying to create had already a lead being currently processed by the telemarketing team, please contact them.' + e.getMessage());
            }
            
            Test.stopTest();
        }
    }
    
        static testMethod void testConversionLead() {

        System.runAs(adminUser) {
            Test.startTest();

            List<Account> listAcc = [SELECT id,TECHFollowedByCodeToBeCalculated__c,OwnerId,ReferentCode__c,SedentaryCode__c,CodeFollowedBy__c from Account where Name LIKE '%Test%'];

            con.FirstName='TestContact';
            con.LastName='Trigger';
            con.Email='TestContact11@test.com';
            con.AccountId=listAcc[0].Id;
            con.CurrencyIsoCode='EUR';
            con.Function__c='General Services Mgr.';
            con.Service__c='Purchasing';
            
            insert con;
            
            Test.stopTest();
        }
    }
}