unpackaged/main/default/objects/Account/fields/Collaborative_Portal__c.field-meta.xml
<CustomField>
    <fullName>Collaborative_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Collaborative Portal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Nature</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <label>Risk Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Competitor__c/Account_Competitor__c.object-meta.xml
<CustomObject>
    <label>Account Competitor</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Account Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Competitor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Competitors</relationshipLabel>
    <relationshipName>Account_Competitors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AccountCoreBusiness__c/AccountCoreBusiness__c.object-meta.xml
<CustomObject>
    <label>Account Core Business</label>
    <nameField>
        <displayFormat>ACB-{000000}</displayFormat>
        <label>Account Core Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Core Business</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AccountCoreBusiness__c/fields/AccountExpertise__c.field-meta.xml
<CustomField>
    <fullName>AccountExpertise__c</fullName>
    <label>Account Expertise</label>
    <referenceTo>Account_Expertise__c</referenceTo>
    <relationshipLabel>Account Core Business</relationshipLabel>
    <relationshipName>Account_Core_Business</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <formula>Account.ERP_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ERP Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Target_Accounts__c/Target_Accounts__c.object-meta.xml
<CustomObject>
    <label>PAC / Accounts</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Target Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAC / Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Target_Accounts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PAC / Accounts</relationshipLabel>
    <relationshipName>Plan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Target_Accounts__c/fields/Targeting_Plan__c.field-meta.xml
<CustomField>
    <fullName>Targeting_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Targeting Plan</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>PAC inactif</errorMessage>
        <filterItems>
            <field>Targeting_Plan__c.End_Date__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>Targeting_Plan__c.Date_du_jour__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Targeting_Plan__c</referenceTo>
    <relationshipLabel>PAC / Accounts</relationshipLabel>
    <relationshipName>Plan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Targeting_Plan__c/Targeting_Plan__c.object-meta.xml
<CustomObject>
    <description>Plans d'action commerciaux</description>
    <label>Targeting Plan</label>
    <nameField>
        <label>Targeting Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targeting Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Account_Nature.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PRO</fullName>
        <default>true</default>
        <label>PROSPECT</label>
    </customValue>
    <customValue>
        <fullName>CLI</fullName>
        <label>CUSTOMER</label>
    </customValue>
    <customValue>
        <fullName>EXCLI</fullName>
        <label>EX CUSTOMER</label>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
        <isActive>false</isActive>
        <label>Client</label>
    </customValue>
    <customValue>
        <fullName>Ex-Client</fullName>
        <isActive>false</isActive>
        <label>Ex-Client</label>
    </customValue>
    <masterLabel>Account Nature</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LTN006_AccMassAssignment.cls
/**
* @author Jeetesh- Comforth
* @date 18/06/20
* @description Controller for LWC accMassAssignmentAccountList and accMassAssignmentFilters
*/
public with sharing class LTN006_AccMassAssignment {

    /**
    * @author Jeetesh- Comforth
    * @date 22/06/20
    * @description Retrieves list of filtered accounts
    * @param string strFilter, string strFilterAccExp, string strFilterAccCom, string strFilterAccCoreBus
    * @return list lstAcc
    */
    @AuraEnabled(cacheable=true)
    public static List<Account> getFilteredAccs(string strFilter, string strFilterAccExp, string strFilterAccCom, string strFilterAccCoreBus) {

        list<Account> lstAcc = new list<Account>();
        list<Account_Expertise__c> lstAccExp = new list<Account_Expertise__c>();
        list<Account_Competitor__c> lstAccCom = new list<Account_Competitor__c>();
        list<AccountCoreBusiness__c> lstAccCoreBus = new list<AccountCoreBusiness__c>();

        set<Id> setAccExpId = new set<Id>();
        set<Id> setAccComId = new set<Id>();
        set<Id> setAccCoreBusId = new set<Id>();

        string sQueryAccExp;
        string sQueryAccCom;
        string sQueryAccCoreBus;

        string queryLineAcc = '';
        string queryLineAccExp = '';
        string queryLineAccCom = '';
        string queryLineAccCoreBus = '';

        system.debug('##strFilter: ' + strFilter);
        system.debug('##strFilterAccExp: ' + strFilterAccExp);
        system.debug('##strFilterAccCom: ' + strFilterAccCom);
        system.debug('##strFilterAccCoreBus: ' + strFilterAccCoreBus);

        // Check Account query
        if(strFilter != ''){
            queryLineAcc = ' WHERE ' + strFilter;
        }
        
        system.debug('##queryLineAcc: ' + queryLineAcc);

        // Check Account Core Business query
        if(strFilterAccCoreBus != ''){
            sQueryAccCoreBus = 'SELECT AccountExpertise__c'
                            + ' FROM AccountCoreBusiness__c'
                            + ' WHERE '
                            + strFilterAccCoreBus;

            lstAccCoreBus = (List <AccountCoreBusiness__c>) Database.query(sQueryAccCoreBus);

            for(AccountCoreBusiness__c accCoreBus : lstAccCoreBus){
                setAccCoreBusId.add(accCoreBus.AccountExpertise__c);
            }
            
        	system.debug('##setAccCoreBusIdSize: ' + setAccCoreBusId.size());
            queryLineAccCoreBus = 'Id IN :setAccCoreBusId';
        }

        // Check Account Expertise query
        if(strFilterAccExp != '' || strFilterAccCoreBus != ''){

            if(strFilterAccExp != ''){
                sQueryAccExp = 'SELECT Account__c'
                                + ' FROM Account_Expertise__c'
                                + ' WHERE '
                                + strFilterAccExp;
    
                if(queryLineAccCoreBus != ''){
                    sQueryAccExp = sQueryAccExp
                                    + ' AND '
                                    + queryLineAccCoreBus;
                }
            }

            else if(strFilterAccExp == '' && queryLineAccCoreBus != ''){
                sQueryAccExp = 'SELECT Account__c'
                                + ' FROM Account_Expertise__c'
                                + ' WHERE '
                                + queryLineAccCoreBus;
            }
            
            system.debug('##sQueryAccExp: ' + sQueryAccExp);

            lstAccExp = (List <Account_Expertise__c>) Database.query(sQueryAccExp);

            for(Account_Expertise__c accExp : lstAccExp){
                setAccExpId.add(accExp.Account__c);
            }

            if(queryLineAcc == ''){
                queryLineAccExp = ' WHERE Id IN :setAccExpId';
            }

            else{
                queryLineAccExp = ' AND Id IN :setAccExpId';
            }

        }

        // Check Account Competitor query
        if(strFilterAccCom != ''){
            sQueryAccCom = 'SELECT Account__c'
                        + ' FROM Account_Competitor__c'
                        + ' WHERE '
                        + strFilterAccCom;

            lstAccCom = (List <Account_Competitor__c>) Database.query(sQueryAccCom);

            for(Account_Competitor__c accCom : lstAccCom){
                setAccComId.add(accCom.Account__c);
            }

            if(queryLineAcc == '' && queryLineAccExp == ''){
                queryLineAccCom = ' WHERE Id IN :setAccComId';
            }
            else{
                queryLineAccCom = ' AND Id IN :setAccComId';
            }
        }
        
        String sQuery = 'SELECT Id,'
                        + ' Name,'
                        + ' ERP_Number__c,'
                        + ' toLabel(Nature__c),'
                        + ' BillingPostalCode,'
                        + ' AnnualRevenue,'
                        + ' Risk_Level__c,'
                        + ' NumberOfEmployees,'
                        + ' No_of_Stores__c,'
                        + ' Retail_Segmentation__c,'
                        + ' Collaborative_Portal__c,'
                        + ' ( SELECT toLabel(Expertise__c) FROM Account_Expertises__r )'
                        + ' FROM Account'
                        + queryLineAcc
                        + queryLineAccExp
                        + queryLineAccCom
                        + ' ORDER BY Name ASC';

        lstAcc = (List <Account>) Database.query(sQuery);
        system.debug('##sQuery' + sQuery);

        return lstAcc;
    }

    /**
    * @author Jeetesh- Comforth
    * @date 30/06/20
    * @description Create PAC Accounts
    * @param List<String> accIds, String targetingPlan, String pacAccOwner
    * @return void
    */
    @AuraEnabled
    public static void createPacAccs(List<String> accIds, String targetingPlan, String pacAccOwner) {

        string splitStr;
        string msg;
        string tarAccErrId;
        set<Id> setAccIds = new set<Id>();
        list<Target_Accounts__c> listTargetAcc = new list<Target_Accounts__c>();
        Target_Accounts__c tarAccErr;
        
        system.debug('##accIds: ' + accIds);
		system.debug('##targetingPlan: ' + targetingPlan);
        
        // Remove / from list
        for(string s : accIds){
            string accId = s.remove('/');

            Target_Accounts__c targetAcc = new Target_Accounts__c(
                Account__c = accId,
                Targeting_Plan__c = targetingPlan,
                OwnerId = pacAccOwner
            );
            listTargetAcc.add(targetAcc);
        }

        if(listTargetAcc.size() > 0){
            try{
                insert listTargetAcc;
            }

            catch (DMLException e) {
                msg = string.valueOf(e.getDmlMessage(0));
                //system.debug('##msgId: ' + msg);

                if(msg.contains(Label.LBL_ErrorMsgDuplicateValueFound)){
                    tarAccErrId = msg.right(15);
                    system.debug('##tarAccErrId: ' + tarAccErrId);

                    tarAccErr = [SELECT Account__r.Name FROM Target_Accounts__c WHERE Id = :tarAccErrId];

                    throw new AuraHandledException(Label.LBL_ErrorMsgDuplicate + ' ' + tarAccErr.Account__r.Name);
                }
                else{
                    throw new AuraHandledException(Label.LBL_ErrorMsgOther + ' ' + e.getMessage());
                }
            }
        
            catch (Exception e) {
                throw new AuraHandledException(Label.LBL_ErrorMsgOther + ' ' + e.getMessage());
            }
        }
    }
}