unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IntercommunityVATnumber__c.field-meta.xml
<CustomField>
    <fullName>IntercommunityVATnumber__c</fullName>
    <inlineHelpText>A tax Number or taxpayer identification number, also known as a TIN for short, is a number issued to organizations to track tax obligations and payments they make
Do not enter any spaces in the field.</inlineHelpText>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Siren_Siret__c.field-meta.xml
<CustomField>
    <fullName>Siren_Siret__c</fullName>
    <description>Siren / Siret</description>
    <label>Siren/Siret</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/Utility_TEST.cls
@IsTest
public with sharing class Utility_TEST {

    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    @TestSetup
    static void makeData() {
        insert adminUser;
    }

    @isTest static void mentionTextPostTest() {

        Account acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.National_Id__c = '32345545656769';
        acc.BillingCountryCode = 'FR';
        acc.ERP_Number__c = 'TESTER';
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test';
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON';
        acc.IntercommunityVATnumber__c = 'TESTVAT';
        acc.Siren_Siret__c = '';
        
        insert acc;

        Test.startTest();
            Utility.mentionTextPost(adminUser.Id, 'Test mention', acc.Id, 'body test mention');
        Test.stopTest();
    }

    @isTest static void createBatchInputTest() {

        Account acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.National_Id__c = '32345545656769';
        acc.BillingCountryCode = 'FR';
        acc.ERP_Number__c = 'TESTER';
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test';
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON';
        acc.IntercommunityVATnumber__c = 'TESTVAT';
        acc.Siren_Siret__c = '';
        

        insert acc;
        Test.startTest();
            Utility.createBatchInput(adminUser.Id, acc.Id, 'body test batch input');
        Test.stopTest();
    }

    @isTest static void isEmptyTest() {
        String testStr = '';
        Test.startTest();
            Boolean resultStr = Utility.isEmpty(testStr);
        Test.stopTest();
        System.assertEquals(true, resultStr, 'string is empty result should be true');
    }
}