unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IntercommunityVATnumber__c.field-meta.xml
<CustomField>
    <fullName>IntercommunityVATnumber__c</fullName>
    <inlineHelpText>A tax Number or taxpayer identification number, also known as a TIN for short, is a number issued to organizations to track tax obligations and payments they make
Do not enter any spaces in the field.</inlineHelpText>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Siren_Siret__c.field-meta.xml
<CustomField>
    <fullName>Siren_Siret__c</fullName>
    <description>Siren / Siret</description>
    <label>Siren/Siret</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BatchIsOwnerInRightTerrSchedule_TEST.cls
@isTest
private class BatchIsOwnerInRightTerrSchedule_TEST {

    public static String CRON_EXP = '0 0 0 3 9 ? 2042';

    @testSetup
    static void setup() {
        List<Account> accs = new List<Account>();
        Account acc; 
        for(Integer i = 0; i < 5; i++) {
            acc = new UTIL_TestFactory.AccountFactory().createAccount();
            acc.National_Id__c = '3234554565676'+i;
            acc.BillingCountryCode = 'FR';
            acc.ERP_Number__c = 'TESTER'+i;
            acc.Phone = '0143434543';
            acc.BillingStreet = 'Rue du Test'+i;
            acc.BillingPostalCode = '69007';
            acc.BillingCity = 'LYON'+i;
            acc.IntercommunityVATnumber__c = 'TESTVAT';
            acc.Siren_Siret__c = '';
            accs.add(acc);
        }

        //BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
    
        //insert salesUser;

        List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5];
        //UserTerritory2Association usrTerrAsso = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=allOrgTerritories[2].Id);
        insert accs;
            //insert usrTerrAsso;
        
        
    }
    @isTest static void testScheduleBatch() {

        Test.startTest();
        String jobId = System.schedule('BatchIsOwnerInRightTerritorySchedule',
        CRON_EXP, 
         new BatchIsOwnerInRightTerritorySchedule());
        Test.stopTest();
        // after the testing stops, assert records were updated properly
    }
}