unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IntercommunityVATnumber__c.field-meta.xml
<CustomField>
    <fullName>IntercommunityVATnumber__c</fullName>
    <inlineHelpText>A tax Number or taxpayer identification number, also known as a TIN for short, is a number issued to organizations to track tax obligations and payments they make
Do not enter any spaces in the field.</inlineHelpText>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Validated</fullName>
                <default>true</default>
                <label>To Be Validated</label>
            </value>
            <value>
                <fullName>In Progress Validation</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>To Be Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_Contact_Direct__c.field-meta.xml
<CustomField>
    <fullName>Tech_Contact_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech_Contact_Direct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ATTRILTSource__c.field-meta.xml
<CustomField>
    <fullName>ATTRILTSource__c</fullName>
    <label>Last Touch Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Lead_s_Chosen_Solution__c.field-meta.xml
<CustomField>
    <fullName>Lead_s_Chosen_Solution__c</fullName>
    <label>Chosen Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chosen_Solution</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <label>Marketing Campaign</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Marketing_Status__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Status__c</fullName>
    <label>Marketing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marketing_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>Amount of your defined budget</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Availability1__c.field-meta.xml
<CustomField>
    <fullName>Availability1__c</fullName>
    <description>MANACT field</description>
    <label>Availability</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Availability2__c.field-meta.xml
<CustomField>
    <fullName>Availability2__c</fullName>
    <label>Availability</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Buffer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buffer_Name__c</fullName>
    <label>Buffer Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>HCM Canada - USA</fullName>
            </value>
            <value>
                <fullName>HCM Iberia</fullName>
            </value>
            <value>
                <fullName>HCM Iberia - Latam</fullName>
                <isActive>false</isActive>
                <label>HCM Iberia - Latam</label>
            </value>
            <value>
                <fullName>HCM Latam</fullName>
            </value>
            <value>
                <fullName>HCM Time Management Rest of the world</fullName>
            </value>
            <value>
                <fullName>HCM Visual Time</fullName>
            </value>
            <value>
                <fullName>Partner Marketing leads - ERP</fullName>
            </value>
            <value>
                <fullName>Partner Marketing leads – HCM</fullName>
            </value>
            <value>
                <fullName>Partner Marketing leads - Retail</fullName>
            </value>
            <value>
                <fullName>Retail International</fullName>
            </value>
            <value>
                <fullName>SDR CPA France</fullName>
            </value>
            <value>
                <fullName>SDR Finance France</fullName>
            </value>
            <value>
                <fullName>SDR HCM France</fullName>
            </value>
            <value>
                <fullName>SDR HCM International</fullName>
            </value>
            <value>
                <fullName>SDR Leads</fullName>
                <isActive>false</isActive>
                <label>SDR Leads</label>
            </value>
            <value>
                <fullName>SDR Notilus</fullName>
            </value>
            <value>
                <fullName>SDR Retail France</fullName>
            </value>
            <value>
                <fullName>SDR StorIQ</fullName>
            </value>
            <value>
                <fullName>Talentsoft Benelux</fullName>
            </value>
            <value>
                <fullName>Talentsoft DACH</fullName>
            </value>
            <value>
                <fullName>Talentsoft Nordics</fullName>
            </value>
            <value>
                <fullName>TAX Spain</fullName>
            </value>
            <value>
                <fullName>Telemarketing France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Last_Touch_Source_Telemarketing__c.field-meta.xml
<CustomField>
    <fullName>Last_Touch_Source_Telemarketing__c</fullName>
    <label>Last Touch Source Telemarketing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>List_Touch_Source_Telemarketing</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lead_s_Chosen_Solution__c.field-meta.xml
<CustomField>
    <fullName>Lead_s_Chosen_Solution__c</fullName>
    <label>Lead's Chosen Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chosen_Solution</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <defaultValue>IF( $RecordType.Name  = 'Lead Telemarketing',  $Label.Default_Marketing_Campaign_For_telemark, "")</defaultValue>
    <label>Marketing Campaign</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Marketing_Status__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Status__c</fullName>
    <defaultValue>IF($Permission.Lead_field_modify_for_telemark, $Label.Default_Marketing_Status_For_Telemark,
				IF($User.LastName = 'Impartner',   $Label.Default_Marketing_Status_For_PRM, null)
		)</defaultValue>
    <label>Marketing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marketing_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Project_s_associated_contact_1__c.field-meta.xml
<CustomField>
    <fullName>Project_s_associated_contact_1__c</fullName>
    <label>Project's associated contact 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Project_s_associated_contact_2__c.field-meta.xml
<CustomField>
    <fullName>Project_s_associated_contact_2__c</fullName>
    <label>Project's associated contact 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Role_in_decision_1__c.field-meta.xml
<CustomField>
    <fullName>Role_in_decision_1__c</fullName>
    <label>Role in decision 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_in_Decision</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Role_in_decision_2__c.field-meta.xml
<CustomField>
    <fullName>Role_in_decision_2__c</fullName>
    <label>Role in decision 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_in_Decision</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/TECH_Is_Fusion__c.field-meta.xml
<CustomField>
    <fullName>TECH_Is_Fusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Is Fusion</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/TECH_Marketing_Campaign_Tmp__c.field-meta.xml
<CustomField>
    <fullName>TECH_Marketing_Campaign_Tmp__c</fullName>
    <label>TECH Marketing Campaign Tmp</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/TECH_Marketing_Status_Tmp__c.field-meta.xml
<CustomField>
    <fullName>TECH_Marketing_Status_Tmp__c</fullName>
    <description>Ce champ sert de tampon dans le processus de fusion des Lead par le télémarketing</description>
    <label>TECH Marketing Status Tmp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Expertise__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TECH_New_oppy_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>TECH_New_oppy_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New oppy From Lead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Line__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product_Line__c/fields/Marketing_Status__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Status__c</fullName>
    <label>Marketing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marketing_Status_Product</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassPB__c.field-meta.xml
<CustomField>
    <fullName>BypassPB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass PB</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass VR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassWF__c.field-meta.xml
<CustomField>
    <fullName>BypassWF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass WF</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Chosen_Solution.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing Industry</fullName>
    </customValue>
    <customValue>
        <fullName>TPE &amp; Association</fullName>
    </customValue>
    <masterLabel>Chosen Solution</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/List_Touch_Source_Telemarketing.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BBCM</fullName>
    </customValue>
    <customValue>
        <fullName>Call-out</fullName>
    </customValue>
    <customValue>
        <fullName>CCM Performance</fullName>
    </customValue>
    <customValue>
        <fullName>Celge</fullName>
    </customValue>
    <customValue>
        <fullName>Croissance V</fullName>
    </customValue>
    <customValue>
        <fullName>Fb Performance</fullName>
    </customValue>
    <customValue>
        <fullName>IBD</fullName>
    </customValue>
    <customValue>
        <fullName>Infolegale</fullName>
    </customValue>
    <customValue>
        <fullName>ITFacto</fullName>
    </customValue>
    <customValue>
        <fullName>Leadeo</fullName>
    </customValue>
    <customValue>
        <fullName>Markess</fullName>
    </customValue>
    <customValue>
        <fullName>Marketo</fullName>
    </customValue>
    <customValue>
        <fullName>Nomination</fullName>
    </customValue>
    <customValue>
        <fullName>Percy Miller</fullName>
    </customValue>
    <customValue>
        <fullName>Poivre &amp; Sell</fullName>
    </customValue>
    <customValue>
        <fullName>Rafale</fullName>
    </customValue>
    <customValue>
        <fullName>SDR</fullName>
    </customValue>
    <customValue>
        <fullName>Sparklane</fullName>
    </customValue>
    <customValue>
        <fullName>SQL Partner</fullName>
    </customValue>
    <customValue>
        <fullName>SRC</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Uniprospects</fullName>
    </customValue>
    <customValue>
        <fullName>Visiblee</fullName>
    </customValue>
    <customValue>
        <fullName>Linkli</fullName>
    </customValue>
    <customValue>
        <fullName>Europhone</fullName>
    </customValue>
    <masterLabel>List Touch Source Telemarketing</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Marketing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cold</fullName>
    </customValue>
    <customValue>
        <fullName>Warm</fullName>
    </customValue>
    <customValue>
        <fullName>AQL</fullName>
    </customValue>
    <customValue>
        <fullName>TAL</fullName>
    </customValue>
    <customValue>
        <fullName>MQL</fullName>
    </customValue>
    <customValue>
        <fullName>SAL</fullName>
    </customValue>
    <customValue>
        <fullName>SQL</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Recycled</fullName>
    </customValue>
    <customValue>
        <fullName>Competition</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder</fullName>
    </customValue>
    <customValue>
        <fullName>Student</fullName>
    </customValue>
    <customValue>
        <fullName>To Be Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Software Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
        <isActive>false</isActive>
        <label>Influencer</label>
    </customValue>
    <description>Used for Leads and Contacts</description>
    <masterLabel>Marketing Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Marketing_Status_Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketable</fullName>
    </customValue>
    <customValue>
        <fullName>Non_marketable</fullName>
        <default>true</default>
        <label>Non-marketable</label>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Marketing Status Product</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Role_in_Decision.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Decision Maker</fullName>
    </customValue>
    <customValue>
        <fullName>Economic Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Signatory</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Buyer</fullName>
        <isActive>false</isActive>
        <label>Technical Buyer</label>
    </customValue>
    <customValue>
        <fullName>Décideur</fullName>
        <isActive>false</isActive>
        <label>Décideur</label>
    </customValue>
    <customValue>
        <fullName>Business User</fullName>
        <isActive>false</isActive>
        <label>Business User</label>
    </customValue>
    <customValue>
        <fullName>Economic Decision Maker</fullName>
        <isActive>false</isActive>
        <label>Economic Decision Maker</label>
    </customValue>
    <customValue>
        <fullName>Evaluator</fullName>
        <isActive>false</isActive>
        <label>Evaluator</label>
    </customValue>
    <customValue>
        <fullName>Apporteur d&apos;affaire</fullName>
        <isActive>false</isActive>
        <label>Apporteur d&apos;affaire</label>
    </customValue>
    <masterLabel>Role in Decision</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/TH_Lead_TEST.cls
@isTest
public with sharing class TH_Lead_TEST {
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();        
    private static final String TELEMARKETING_PROFILE_NAME = 'Cegid Telemarketing';

    @isTest static void createLeadTest() {
        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
        Account acc = new Account(Name='Test');
        
        List<Contact> cts = new List<Contact>();
        List<Lead> lds = new List<Lead>();
        
        for(Integer i = 0; i < 21; i++) {
            lds.add(new UTIL_TestFactory.LeadFactory().createLead('Test'));
        }

        lds[0].Lead_s_Chosen_Solution__c = 'CPA';
        lds[1].Lead_s_Chosen_Solution__c = 'Retail'; 
        lds[2].Lead_s_Chosen_Solution__c = 'HR'; 
        lds[3].Lead_s_Chosen_Solution__c = 'HR'; 
        lds[4].Lead_s_Chosen_Solution__c = 'Manufacturing Industry'; 
        lds[5].Lead_s_Chosen_Solution__c = 'TPE & Association';  
        lds[6].Lead_s_Chosen_Solution__c = 'HR';

        lds[7].ImpartnerPRM__IsDealRegistration__c = true;
        lds[8].ImpartnerPRM__IsDealRegistration__c = true;
        lds[9].ImpartnerPRM__IsDealRegistration__c = true;
        lds[10].ImpartnerPRM__IsDealRegistration__c = true;

        lds[11].Email = 'test1@test1.fr';
        lds[12].Email = 'test2@test2.fr';
        lds[13].Email = 'test3@test3.fr';
        lds[14].Email = 'test4@test4.fr'; 
        lds[15].Email = 'test5@test5.fr';
                
        System.runAs(adminUser) {
            insert acc;
        }

        lds[16].ImpartnerPRM__IsDealRegistration__c = true;
        lds[16].ImpartnerPRM__PartnerAccount__c = acc.Id;
        lds[17].ImpartnerPRM__PartnerAccount__c = acc.Id;
        lds[18].ImpartnerPRM__PartnerAccount__c = acc.Id;
        lds[19].ImpartnerPRM__PartnerAccount__c = acc.Id;
        lds[20].ImpartnerPRM__PartnerAccount__c = acc.Id;

        for(Integer i = 0; i < 5; i++) {
            cts.add(new UTIL_TestFactory.ContactFactory().createContact(acc.Id));
            cts[i].Email = 'test'+i+'@test'+i+'.fr';
        }

        System.runAs(adminUser) {
            insert cts;
            insert bypass;
        }

        List<Lead> contactLeads;
        List<Lead> leads;
        Test.startTest();
        System.runAs(adminUser) {
            List<Database.SaveResult> results = Database.insert(lds, false);
        }
        Test.stopTest();
    }

    @isTest static void updateLeadTest() {
        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
    
        List<Lead> lds = new List<Lead>();
        
        for(Integer i = 0; i < 17; i++) {
            lds.add(new UTIL_TestFactory.LeadFactory().createLead('Test'));
        }

        lds[0].Lead_s_Chosen_Solution__c = 'CPA';
        lds[1].Lead_s_Chosen_Solution__c = 'Retail'; 
        lds[2].Lead_s_Chosen_Solution__c = 'HR'; 
        lds[3].Lead_s_Chosen_Solution__c = 'HR'; 
        lds[4].Lead_s_Chosen_Solution__c = 'Manufacturing Industry'; 
        lds[5].Lead_s_Chosen_Solution__c = 'TPE & Association';  
        lds[6].Lead_s_Chosen_Solution__c = 'HR';

        lds[7].ImpartnerPRM__IsDealRegistration__c = true;
        lds[8].ImpartnerPRM__IsDealRegistration__c = true;
        lds[9].ImpartnerPRM__IsDealRegistration__c = true;
        lds[10].ImpartnerPRM__IsDealRegistration__c = true;

        lds[11].Email = 'test1@test1.fr';
        lds[12].Email = 'test2@test2.fr';
        lds[13].Email = 'test3@test3.fr';
        lds[14].Email = 'test4@test4.fr';
        lds[15].Email = 'test5@test5.fr';
                
        lds[16].ImpartnerPRM__IsDealRegistration__c = true;
    
        System.runAs(adminUser) {
            insert bypass;
        }

        insert lds;

        for(Integer i = 0 ; i < lds.size() ; i++) {
            lds[i].LastName = 'TestN'+i;
        }
        
        List<Lead> leads;
        Test.startTest();
        
        List<Database.SaveResult> results = Database.update(lds, false);
        
        Test.stopTest();
    }

    @isTest static void createTelemarkLeadTest() {
        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
        List<Lead> lds = new List<Lead>();
        
        for(Integer i = 0; i < 2; i++) {
            lds.add(new UTIL_TestFactory.LeadFactory().createLead('Test'));
            lds[i].ImpartnerPRM__IsDealRegistration__c = true;
        }

        lds[0].Status = 'New';
        lds[1].Status = 'Closed - Not Converted';

        System.runAs(adminUser) {
            insert bypass;
        }

        User telemarkUser = createUserTelemarketing();

        Test.startTest();
        System.runAs(telemarkUser) {
            List<Database.SaveResult> results = Database.insert(lds, false);
            System.debug(results);
        }
        Test.stopTest();

    }

   

    private static User createUserTelemarketing() {
        /**
        * @description Crée un utilisateur de Telemarketeur
        */     
        User userUsrTelemark = new User(
            alias = 'TestTele',
            email = 'testTele.sales@example.com',
            emailencodingkey = 'UTF-8',
            BypassPB__c = true,
            BypassVR__c = true,
            BypassWF__c = true,
            lastname = 'testsales',
            languagelocalekey = 'fr',
            localesidkey = 'fr_FR',
            profileid = [
                SELECT Id
                FROM Profile
                WHERE Name = :TELEMARKETING_PROFILE_NAME
                LIMIT 1
            ][0].Id,
            timezonesidkey = 'Europe/Paris',
            username = 'test.telemarketing' + System.now().millisecond()
            + UserInfo.getOrganizationId() + '@example.com'
        );
        return userUsrTelemark;
    }

    @isTest static void switchTest() {
        
        Test.startTest();
            String result1 = TH_Lead.switch('CPA');
            String result2 = TH_Lead.switch('Retail');
            String result3 = TH_Lead.switch('HR');
            String result4 = TH_Lead.switch('Finance');
            String result5 = TH_Lead.switch('Manufacturing Industry');
            String result6 = TH_Lead.switch('TPE & Association');
            String result7 = TH_Lead.switch('Key null');
        Test.stopTest();
        System.assertEquals('110', result1, 'result should be 110');
        System.assertEquals('200', result2, 'result should be 200');
        System.assertEquals('320', result3, 'result should be 320');
        System.assertEquals('315', result4, 'result should be 315');
        System.assertEquals('340', result5, 'result should be 340');
        System.assertEquals('100', result6, 'result should be 100');
        System.assertEquals(null, result7, 'result should be null');
        
    }


    @isTest static void mergeLeadFieldForTelemarkTest() {
        List<Lead> lds = new List<Lead>();

        for(Integer i = 0;i < 4;i++) {
            if(math.mod(i,2) == 0) {
                lds.add(new Lead(TECH_Is_Fusion__c = true,
                                 Last_Touch_Source_Telemarketing__c = 'IBD',
                                 TECH_Marketing_Status_Tmp__c = 'AQL',
                                 TECH_Marketing_Campaign_Tmp__c = 'TEST MKT' +i));
            } else {
                lds.add(new Lead(TECH_Is_Fusion__c = false));
            }
            
        }

        Test.startTest();
            TH_Lead th = new TH_Lead();

            System.runAs(adminUser) {
                System.debug(UserInfo.getProfileId());
                List<PermissionSetAssignment> permissions = [SELECT Id,
                                                            PermissionSet.Name,
                                                            PermissionSet.ProfileId,
                                                            PermissionSet.Profile.Name,
                                                            AssigneeId, Assignee.Profile.Name 
                                                            FROM PermissionSetAssignment
                                                            WHERE AssigneeId =: UserInfo.getUserId()];
                User us = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
                th.mergeLeadFieldForTelemark(lds, us, permissions);
            }
        Test.stopTest();

        System.assertEquals(false, lds[0].TECH_Is_Fusion__c);
        System.assertEquals('AQL', lds[0].Marketing_Status__c);
        System.assertEquals('TEST MKT0', lds[0].Marketing_Campaign__c);
        System.assertEquals('IBD', lds[0].ATTRILTSource__c);

        System.assertEquals(false, lds[1].TECH_Is_Fusion__c);
        System.assertEquals(null, lds[1].Marketing_Status__c);
        System.assertEquals(null, lds[1].Marketing_Campaign__c);
        System.assertEquals(null, lds[1].ATTRILTSource__c);
    }

    @isTest static void beforeUpdate() {
        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
        List<Lead> lds = new List<Lead>();
        
        for(Integer i = 0; i < 3; i++) {
            lds.add(new UTIL_TestFactory.LeadFactory().createLead('Test'));
            lds[i].ImpartnerPRM__IsDealRegistration__c = true;
        }

        lds[1].Status = 'New';
        lds[2].Status = 'Closed - Not Converted';

        System.runAs(adminUser) {
            insert bypass;
            insert lds;
        }

        User telemarkUser = createUserTelemarketing();

        for(Lead ld : lds) {
            ld.TECH_Is_Fusion__c = true;
            ld.Last_Touch_Source_Telemarketing__c = 'IBD';
            ld.TECH_Marketing_Status_Tmp__c = 'AQL';
            ld.TECH_Marketing_Campaign_Tmp__c = 'TEST MKT';
        }

        Test.startTest();
        System.runAs(telemarkUser) {
            List<Database.SaveResult> results = Database.update(lds, false);
            System.debug(results);
        }
        Test.stopTest();
    }

    @isTest static void leadOppyMergeTraitementTest() {
        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
        List<Lead> lds = new List<Lead>();
        Account acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.ERP_Number__c = 'TESTERP';
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test';
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON';
        acc.Status__c = 'Validated';
        acc.National_Id__c = '32345545656767';
        acc.IntercommunityVATnumber__c = 'Test';
        acc.Tech_Contact_Direct__c = true;

        insert acc;

        List<Opportunity> opps = new List<Opportunity>();
        
        for(Integer i = 0; i < 5; i++) {
            Opportunity opp = new UTIL_TestFactory.OpportunityFactory().createOpportunity(acc.Id, true, false);
            opp.Sales_Purpose__c = '111';
            opp.Expertise__c = '110';
            opp.Product_Line__c = '292';

            if(math.mod(i,2) == 0) {
                opp.TECH_New_oppy_From_Lead__c = true;
            }
            opps.add(opp);
        }

        System.debug(adminUser);
        System.runAs(adminUser) {
            insert opps;
        }
        

        
        for(Integer i = 0; i < 5; i++) {
            Lead ld = new UTIL_TestFactory.LeadFactory().createLead('Test');
            
            
            ld.IsConverted = true;
            ld.ConvertedAccountId = acc.Id;
            ld.ConvertedOpportunityId = opps[i].Id;
            ld.Amount__c = 235698;

            if(math.mod(i,2) == 0) {
                ld.Project_s_associated_contact_2__c = 'Test assoc contact 2';
                ld.Role_in_decision_2__c = 'partner';
                ld.Availability2__c = 'Test availability contact 2';
            } else {
                ld.Project_s_associated_contact_1__c = 'Test assoc contact 1';
                ld.Role_in_decision_1__c = 'partner';
                ld.Availability1__c = 'Test availability contact 1';
            }

            
               
            lds.add(ld);

        }

        System.runAs(adminUser) {
            insert bypass;
            insert lds;
        }
        Map<Id, Lead> mapLds = new Map<Id, Lead>(lds);
        TH_Lead th = new TH_Lead();

        Test.startTest();
        
        System.runAs(adminUser) {
            th.leadOppyMergeTraitement(mapLds);
        } 
        
        Test.stopTest();
        List<Opportunity> newOpps = [SELECT Id, Description, TECH_New_oppy_From_Lead__c FROM Opportunity];

        List<Opportunity> oppNewDescription = new List<Opportunity>();
        List<Opportunity> oppNoDescription = new List<Opportunity>();

        for(Opportunity opp : newOpps) {
            if(opp.Description != null) {
                oppNewDescription.add(opp);
            } else {
                oppNoDescription.add(opp);
            }
        }

        System.assertEquals(3, oppNewDescription.size(), '3 oppys should have description field');
        System.assertEquals(2, oppNoDescription.size(), '2 oppys should have description field');
    }


    @isTest static void affectLeadTelemarketingGroupTest() {
        List<Lead> lds = new List<Lead>();
        for(Integer i = 0; i < 10; i++) {
            lds.add(new UTIL_TestFactory.LeadFactory().createLead('Test'));
        }

        Group grpTelemark = new Group(Name = 'Telemarketing Leads', DeveloperName = 'Telemarketing_Leads');

        System.runAs(adminUser) {
            insert grpTelemark;
            insert lds;
        }

        List<Lead> ldsTest = [SELECT Id, Marketing_Status__c, Status, OwnerId FROM Lead];

        
        Map<Id, Lead> ldsMapTest = new Map<Id, Lead>(ldsTest.clone());
        Integer i = 0;
        for(Lead ld : ldsTest) {
            ld.Marketing_Status__c = 'AQL';
            if(Math.mod(i, 2) == 0) {
                ld.Marketing_Status__c = 'AQL';
                ld.Status = 'New';   
            } else {
                ld.Status = 'In Progress'; 
            }
            i++;
        }

        TH_Lead th = new TH_Lead();

        Test.startTest();

        th.affectLeadTelemarketingGroup(ldsTest, null, grpTelemark.Id);

        Test.stopTest();

        Integer nbChange = 0;

        Integer nbNoChange = 0;

        for(Lead ld : ldsTest) {
            System.debug(ld.Status);
            System.debug(ld.OwnerId);
            if(ld.Status == 'In buffer' && ld.OwnerId == grpTelemark.Id) {
                nbChange++;
            } else {
                nbNoChange++;
            }
        }
        System.assertEquals(5, nbChange, '5 lead should changed by method');
        System.assertEquals(5, nbNoChange, '5 lead should not changed by method');

    }

   @isTest static void computeBufferNameTest() {
       
       Group grpTelemark = new Group(Name = 'Telemarketing Leads', DeveloperName = 'Telemarketing_Leads');

        System.runAs(adminUser) {
            insert grpTelemark;
        }

        List<Lead> lds = new List<Lead>();

        Lead ld;
        for(Integer i = 0 ; i < 150 ; i++) {

            if(i < 100) {
                ld = new Lead(OwnerId = grpTelemark.Id);
            } else {
                ld = new Lead();
            }
            switch on i {
                when 0,1,2,3,4,5,6,7,8,9 {
                    if(Math.mod(i, 9) == 0) {
                        ld.Expertise__c = '110';
                    } else if (Math.mod(i, 8) == 0) {
                        ld.Expertise__c = '350';
                    } else if (Math.mod(i, 7) == 0) {
                        ld.Expertise__c = '100';
                    } else if (Math.mod(i, 6) == 0) {
                        ld.Expertise__c = '999';
                    } else if (Math.mod(i, 5) == 0) {
                        ld.Expertise__c = '370';
                    } else if (Math.mod(i, 4) == 0) {
                        ld.Expertise__c = '360';
                    } else {
                        ld.Expertise__c = null;
                    }
                }
                when 10,11,12,13,14,15,16,17,18,19 {
                    ld.Expertise__c = '320';

                    if(Math.mod(i, 5) == 0) {
                        ld.CountryCode = 'FR';
                    } else if (Math.mod(i, 4) == 0) {
                        ld.CountryCode = 'VE';
                    } else if (Math.mod(i, 3) == 0) {
                        ld.CountryCode = 'CA';
                    } else if (Math.mod(i, 2) == 0) {
                        ld.CountryCode = 'US';
                    } else {
                        ld.CountryCode = null;
                    }
                }
                when 20,21,22,23,24,25,26,27,28,29 {
                    ld.Expertise__c = '310';

                    if(Math.mod(i, 3) == 0) {
                        ld.CountryCode = 'ES';
                    } else if (Math.mod(i, 2) == 0) {
                        ld.CountryCode = 'FR';
                    } else {
                        ld.CountryCode = null;
                    }
                    
                }
                when 30,31,32,33,34,35,36,37,38,39 {
                    ld.Expertise__c = '200';
                    ld.Marketing_Campaign__c = 'testVRtest';

                    if(Math.mod(i, 3) == 0) {
                        ld.Marketing_Campaign__c = 'testVaRtest';
                    } else if (Math.mod(i, 2) == 0) {
                        ld.CountryCode = 'TN';
                    } else {
                        ld.CountryCode = 'CA';
                    }
                    
                }
                when 40,41,42,43,44,45,46,47,48,49 {
                    ld.Expertise__c = '340';
                    ld.Marketing_Campaign__c = 'testVRtest';

                    if(Math.mod(i, 3) == 0) {
                        ld.Marketing_Campaign__c = 'testVaRtest';
                    }
                    
                }
                when 50,51,52,53,54,55,56,57,58,59 {
                    ld.Expertise__c = '380';

                    if(Math.mod(i, 9) == 0) {
                        ld.CountryCode = 'FR';
                    } else if (Math.mod(i, 8) == 0) {
                        ld.CountryCode = 'JM';
                    } else if (Math.mod(i, 6) == 0) {
                        ld.CountryCode = 'US';
                    } else if (Math.mod(i, 5) == 0) {
                        ld.CountryCode = 'CH';
                    } else if (Math.mod(i, 4) == 0) {
                        ld.CountryCode = 'LU';
                    } else {
                        ld.CountryCode = 'NO';
                    }  
                }
            }

            lds.add(ld);
        }

        TH_Lead th = new TH_Lead();

        Test.startTest();
        th.computeBufferName(lds, grpTelemark.Id);
        Test.stopTest();

        Map<String, Integer> mapNbBuffer = new Map<String, Integer>();

        for(Lead led : lds) {
            if(mapNbBuffer.containsKey(led.Buffer_Name__c)) {
                mapNbBuffer.put(led.Buffer_Name__c, mapNbBuffer.get(led.Buffer_Name__c) + 1);
            } else {
                mapNbBuffer.put(led.Buffer_Name__c, 1);
            }
        }

        System.assertEquals(50, mapNbBuffer.get(null), '50 leads should not have buffer name');
        System.assertEquals(2, mapNbBuffer.get('HCM Canada - USA'), '2 leads should be HCM Canada - USA');
        //System.assertEquals(3, mapNbBuffer.get('HCM Iberia - Latam'), '3 leads should be HCM Iberia - Latam');
        System.assertEquals(3, mapNbBuffer.get('Partner Marketing leads - ERP'), '3 leads should be Partner Marketing leads - ERP');
        System.assertEquals(4, mapNbBuffer.get('Partner Marketing leads - Retail'), '3 leads should be Partner Marketing leads - Retail');
        System.assertEquals(3, mapNbBuffer.get('Retail International'), '3 leads should be Retail International');
        System.assertEquals(3, mapNbBuffer.get('TAX Spain'), '3 leads should be TAX Spain');
        System.assertEquals(1, mapNbBuffer.get('Talentsoft Benelux'), '3 leads should be Talentsoft Benelux');
        System.assertEquals(2, mapNbBuffer.get('Talentsoft DACH'), '3 leads should be Talentsoft DACH');
        System.assertEquals(5, mapNbBuffer.get('Talentsoft Nordics'), '3 leads should be Talentsoft Nordics');
        System.assertEquals(74, mapNbBuffer.get('Telemarketing France'), '74 leads should be Telemarketing France');

   }
}