unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Nature</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Competitor__c/Account_Competitor__c.object-meta.xml
<CustomObject>
    <label>Account Competitor</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Account Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Competitor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Competitors</relationshipLabel>
    <relationshipName>Account_Competitors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Competitor__c/fields/Core_Business__c.field-meta.xml
<CustomField>
    <fullName>Core_Business__c</fullName>
    <label>Core Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Core_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AccountCoreBusiness__c/AccountCoreBusiness__c.object-meta.xml
<CustomObject>
    <label>Account Core Business</label>
    <nameField>
        <displayFormat>ACB-{000000}</displayFormat>
        <label>Account Core Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Core Business</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AccountCoreBusiness__c/fields/AccountExpertise__c.field-meta.xml
<CustomField>
    <fullName>AccountExpertise__c</fullName>
    <label>Account Expertise</label>
    <referenceTo>Account_Expertise__c</referenceTo>
    <relationshipLabel>Account Core Business</relationshipLabel>
    <relationshipName>Account_Core_Business</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AccountCoreBusiness__c/fields/CoreBusiness__c.field-meta.xml
<CustomField>
    <fullName>CoreBusiness__c</fullName>
    <label>Core Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Core_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Target_Accounts__c/Target_Accounts__c.object-meta.xml
<CustomObject>
    <label>PAC / Accounts</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Target Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAC / Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Target_Accounts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PAC / Accounts</relationshipLabel>
    <relationshipName>Plan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Target_Accounts__c/fields/Targeting_Plan__c.field-meta.xml
<CustomField>
    <fullName>Targeting_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Targeting Plan</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>PAC inactif</errorMessage>
        <filterItems>
            <field>Targeting_Plan__c.End_Date__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>Targeting_Plan__c.Date_du_jour__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Targeting_Plan__c</referenceTo>
    <relationshipLabel>PAC / Accounts</relationshipLabel>
    <relationshipName>Plan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Targeting_Plan__c/Targeting_Plan__c.object-meta.xml
<CustomObject>
    <description>Plans d'action commerciaux</description>
    <label>Targeting Plan</label>
    <nameField>
        <label>Targeting Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targeting Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Targeting_Plan__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date de fin du PAC</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Targeting_Plan__c/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Targeting_Plan__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date de lancement du PAC</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Nature.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PRO</fullName>
        <default>true</default>
        <label>PROSPECT</label>
    </customValue>
    <customValue>
        <fullName>CLI</fullName>
        <label>CUSTOMER</label>
    </customValue>
    <customValue>
        <fullName>EXCLI</fullName>
        <label>EX CUSTOMER</label>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
        <isActive>false</isActive>
        <label>Client</label>
    </customValue>
    <customValue>
        <fullName>Ex-Client</fullName>
        <isActive>false</isActive>
        <label>Ex-Client</label>
    </customValue>
    <masterLabel>Account Nature</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/LTN006_AccMassAssignment_TEST.cls
/**
* @author Jeetesh- Comforth
* @date 30/06/20
* @description Test class for LTN006_AccMassAssignment
*/
@isTest
private class LTN006_AccMassAssignment_TEST {
    
    static User adminUser;
    static list<Account> lstAcc;
    static list<Account_Expertise__c> lstAccExp;
    static list<Account_Competitor__c> lstAccCom;
    static list<AccountCoreBusiness__c> lstAccCoreBus;
    static Targeting_Plan__c tarPlan;
    
    static{
        adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
        
        System.runAs(adminUser){
            
            Integer nbBulkDataAcc=10, nbBulkDataAccExp=10, nbBulkDataAccCom=10;
            
            //1. Insert Account
            lstAcc = new list<Account>();
            for(Integer i=0;i< nbBulkDataAcc; i++){
                Account acc = new Account();
                acc.Name = 'Test Acc' + i;
                acc.ERP_Number__c = '9867196' + i;
                acc.Nature__c = 'PRO';
                acc.BillingStreet = 'Rue de la Victoire';
                acc.BillingCity = 'Paris';
                acc.BillingCountry ='France';
                acc.BillingPostalCode = '78000';
                lstAcc.add(acc);
            }
            insert lstAcc;
            system.debug('##lstAcc: '+ lstAcc);
            
            //2. Insert Account Expertise
            lstAccExp = new list<Account_Expertise__c>();
            for(Integer i=0;i< nbBulkDataAccExp; i++){
                Account_Expertise__c accExp = new Account_Expertise__c();
                accExp.Account__c = lstAcc[0].Id;
                accExp.Expertise__c = '110';
                lstAccExp.add(accExp);
            }
            insert lstAccExp;
            system.debug('##lstAccExp: '+ lstAccExp);
            
            //3. Insert Account Competitor
            lstAccCom = new list<Account_Competitor__c>();
            for(Integer i=0;i< nbBulkDataAccCom; i++){
                Account_Competitor__c accCom = new Account_Competitor__c();
                accCom.Account__c = lstAcc[0].Id;
                accCom.Core_Business__c = '110';
                lstAccCom.add(accCom);
            }
            insert lstAccCom;
            system.debug('##lstAccCom: '+ lstAccCom);
            
            //3. Insert Account Core Business
            lstAccCoreBus = new list<AccountCoreBusiness__c>();
            for(Integer i=0;i< nbBulkDataAccCom; i++){
                AccountCoreBusiness__c accCoreBus = new AccountCoreBusiness__c();
                accCoreBus.AccountExpertise__c = lstAccExp[0].Id;
                accCoreBus.CoreBusiness__c = '110';
                lstAccCoreBus.add(accCoreBus);
            }
            insert lstAccCoreBus;
            system.debug('##lstAccCoreBus: '+ lstAccCoreBus);
            
            //4. Insert Targeting Plan
            tarPlan = new Targeting_Plan__c();
            tarPlan.Name = 'Test TarPlan';
            tarPlan.Expertise__c = '110';
            tarPlan.Sales_Purpose__c = '613';
            tarPlan.Start_Date__c = system.today();
            tarPlan.End_Date__c = system.today() + 30;
            
            insert tarPlan;
            system.debug('##tarPlan: '+ tarPlan);
        }
    }
    
    /**
    * @author Jeetesh- Comforth
    * @date 30/06/20
    * @description Get filtered accounts
    */
    @isTest
    static void filteredAccs(){
        system.runAs(adminUser){
            
            list<Account> lstAccFiltered = new list<Account>();
            
            string strFilter = ' Nature__c IN ( \'PRO\' )';
            string strFilterAccExp = ' Expertise__c IN ( \'110\' )';
            string strFilterAccCom = ' Core_Business__c IN ( \'110\' )';
            string strFilterAccCoreBus = ' CoreBusiness__c IN ( \'110\' )';
            
            test.startTest();
            lstAccFiltered = LTN006_AccMassAssignment.getFilteredAccs(strFilter, strFilterAccExp, strFilterAccCom, strFilterAccCoreBus); 
            test.stopTest();
            
            system.assertEquals(1, lstAccFiltered.size(), 'Asserting that size of lstAccFiltered is 1');
        }
    }
    
    /**
    * @author Jeetesh- Comforth
    * @date 30/06/20
    * @description Get filtered accounts - string strFilter blank
    */
    @isTest
    static void accFilterBlank(){
        system.runAs(adminUser){
            
            list<Account> lstAccFiltered = new list<Account>();
            
            string strFilter = '';
            string strFilterAccExp = ' Expertise__c IN ( \'110\' )';
            string strFilterAccCom = ' Core_Business__c IN ( \'110\' )';
            string strFilterAccCoreBus = ' CoreBusiness__c IN ( \'110\' )';
            
            test.startTest();
            lstAccFiltered = LTN006_AccMassAssignment.getFilteredAccs(strFilter, strFilterAccExp, strFilterAccCom, strFilterAccCoreBus); 
            test.stopTest();
            
            system.assertEquals(1, lstAccFiltered.size(), 'Asserting that size of lstAccFiltered is 1');
        }
    }
    
    /**
    * @author Jeetesh- Comforth
    * @date 30/06/20
    * @description Get filtered accounts - strings strFilter and strFilterAccExp blank
    */
    @isTest
    static void accFilterAccExpBlank(){
        system.runAs(adminUser){
            
            list<Account> lstAccFiltered = new list<Account>();
            
            string strFilter = '';
            string strFilterAccExp = '';
            string strFilterAccCom = ' Core_Business__c IN ( \'110\' )';
            string strFilterAccCoreBus = ' CoreBusiness__c IN ( \'110\' )';
            
            test.startTest();
            lstAccFiltered = LTN006_AccMassAssignment.getFilteredAccs(strFilter, strFilterAccExp, strFilterAccCom, strFilterAccCoreBus); 
            test.stopTest();
            
            system.assertEquals(1, lstAccFiltered.size(), 'Asserting that size of lstAccFiltered is 1');
        }
    }
    
    /**
    * @author Jeetesh- Comforth
    * @date 30/06/20
    * @description Create PAC/Accounts
    */
    @isTest
    static void createPacAccs(){
        system.runAs(adminUser){
            
            list<String> accIds = new List<String>();
            string accId;
            
            for(Account acc : lstAcc){
                accId = acc.Id;
                accIds.add(accId);
            }
            
            test.startTest();
            LTN006_AccMassAssignment.createPacAccs(accIds, tarPlan.Id, adminUser.Id);
            test.stopTest();
            
            list<Target_Accounts__c> listTargetAcc = [Select Id From Target_Accounts__c];
                
            system.assertEquals(10, listTargetAcc.size(), 'Asserting that size of listTargetAcc is 10');
        }
    }
    
    /**
    * @author Jeetesh- Comforth
    * @date 03/07/20
    * @description Get DML Exception PAC/Accounts
    */
    @isTest
    static void errorPacAccs(){
        system.runAs(adminUser){
            
            list<String> accIds = new List<String>();
            string accId;
            
            for(Account acc : lstAcc){
                accId = acc.Id;
                accIds.add(accId);
            }
            
            LTN006_AccMassAssignment.createPacAccs(accIds, tarPlan.Id, adminUser.Id);
            
            test.startTest();
            
            try{
                 LTN006_AccMassAssignment.createPacAccs(accIds, tarPlan.Id, adminUser.Id);     
            }
            
            catch(Exception e){
                system.debug('##e: ' + e.getMessage());
            }
            
            test.stopTest();
            
            list<Target_Accounts__c> listTargetAcc = [Select Id From Target_Accounts__c];
                
            system.assertEquals(10, listTargetAcc.size(), 'Asserting that size of listTargetAcc is 10, thus no more Target Accounts have been created');
        }
    }
}