unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Business_Unit__c/fields/API_Code__c.field-meta.xml
<CustomField>
    <fullName>API_Code__c</fullName>
    <externalId>true</externalId>
    <label>API Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Business_Unit__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Business_Unit__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Requests_API_Properties__c/Customer_Requests_API_Properties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For OneNoteS Project &amp; Zuora API interface</description>
    <label>Customer Requests API Properties</label>
</CustomObject>

unpackaged/main/default/objects/Customer_Requests_API_Properties__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/CustomerRequest__c.object-meta.xml
<CustomObject>
    <label>Customer Request</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CustomerRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Lorem Ipsum</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Requests</relationshipLabel>
    <relationshipName>CustomerRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/CancellationDate__c.field-meta.xml
<CustomField>
    <fullName>CancellationDate__c</fullName>
    <description>Used for the manual customer request creation</description>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <summarizedField>InvoiceLine__c.CreditNoteAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLine__c.CustomerRequest__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation with Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/InvoiceLine__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLine__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/CustomerRequest__c.field-meta.xml
<CustomField>
    <fullName>CustomerRequest__c</fullName>
    <label>Customer Request</label>
    <referenceTo>CustomerRequest__c</referenceTo>
    <relationshipLabel>Invoices Lines</relationshipLabel>
    <relationshipName>InvoicesLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SubscriptionLine__c/SubscriptionLine__c.object-meta.xml
<CustomObject>
    <label>Subscription Line</label>
    <nameField>
        <label>Load Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SubscriptionLine__c/fields/CancellationDate__c.field-meta.xml
<CustomField>
    <fullName>CancellationDate__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SubscriptionLine__c/fields/CustomerRequest__c.field-meta.xml
<CustomField>
    <fullName>CustomerRequest__c</fullName>
    <label>Customer Request</label>
    <referenceTo>CustomerRequest__c</referenceTo>
    <relationshipLabel>Subscription Lines</relationshipLabel>
    <relationshipName>SubscriptionLines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>CASE( 
    TEXT(Agency__c),
'112', 'CPA',
'113', 'CPA',
'114', 'CPA',
'115', 'CPA',
'217', 'RETAIL',
'290', 'RETAIL',
'320', 'CPA',
'340', 'CPA',
'392', 'FINANCE',
'393', 'FINANCE',
'394', 'FINANCE',
'395', 'FINANCE',
'396', 'FINANCE',
'397', 'FINANCE',
'410', 'CPA',
'411', 'CPA',
'412', 'CPA',
'470', 'CPA',
'530', 'Other',
'549', 'RETAIL',
'550', 'RETAIL',
'552', 'RETAIL',
'555', 'RETAIL',
'556', 'RETAIL',
'557', 'RETAIL',
'560', 'RETAIL',
'563', 'HCM',
'583', 'RETAIL',
'585', 'HCM',
'714', 'HCM',
'715', 'HCM',
'800', 'FINANCE',
'803', 'SB',
'804', 'SB',
'805', 'FINANCE',
'808', 'FINANCE',
'809', 'RETAIL',
'810', 'FINANCE',
'811', 'FINANCE',
'812', 'HCM',
'813', 'HCM',
'814', 'FINANCE',
'815', 'FINANCE',
'816', 'FINANCE',
'818', 'CPA',
'819', 'FINANCE',
'822', 'FINANCE',
'823', 'HCM',
'824', 'HCM',
'825', 'HCM',
'826', 'HCM',
'829', 'CPA',
'830', 'CPA',
'831', 'SB',
'832', 'HCM',
'834', 'HCM',
'835', 'HCM',
'836', 'HCM',
'837', 'HCM',
'838', 'HCM',
'839', 'HCM',
'841', 'HCM',
'842', 'HCM',
'840', 'HCM',
'843', 'OTHER',
'844', 'RETAIL',
'845', 'FINANCE',
'846', 'FINANCE',
'847', 'FINANCE',
'849', 'FINANCE',
'850', 'FINANCE',
'852', 'FINANCE',
'853', 'FINANCE',
'854', 'FINANCE',
'855', 'HCM',
'856', 'SB',
'857', 'HCM',
'858', 'HCM',
'Not Assigned'
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <default>true</default>
        <label>Direct</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Mixed</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Partner</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Influencing Organization</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HCM</fullName>
    </customValue>
    <customValue>
        <fullName>TAX</fullName>
    </customValue>
    <customValue>
        <fullName>RETAIL</fullName>
    </customValue>
    <customValue>
        <fullName>ERP MIDDLE</fullName>
    </customValue>
    <customValue>
        <fullName>ERP HIGH</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Public</fullName>
    </customValue>
    <description>Plus utilisé - POC SFDC</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CustomerRequestsFormControllerTest.cls
/**
 * @author           : Soufiane LOGDALI soufiane.logdali@comforth-karoo.eu
 * created on  : 20/07/2022
**/


@IsTest 
private class CustomerRequestsFormControllerTest {
    private static User adminUser =  new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    @TestSetup static void setup(){

        List<Customer_Requests_API_Properties__c> customerRequestsAPIProperties = new List<Customer_Requests_API_Properties__c>();
        Customer_Requests_API_Properties__c customerRequestsAPIPropertie1 = new Customer_Requests_API_Properties__c();
		customerRequestsAPIPropertie1.Name ='Access_Token_Endpoint';
        customerRequestsAPIPropertie1.Value__c ='https://uat-cegid-oauth-provider.de-c1.eu1.cloudhub.io/v2/access-token';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie1);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie2 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie2.Name ='Client_Secret';
        customerRequestsAPIPropertie2.Value__c ='abc123456789';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie2);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie3 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie3.Name ='Client_Id';
        customerRequestsAPIPropertie3.Value__c ='efg123456789';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie3);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie4 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie4.Name ='InvoiceLines_Endpoint';
        customerRequestsAPIPropertie4.Value__c ='https://egid/api/exp-cegid-salesforce-api-acceptance/v1/invoiceLines';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie4);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie5 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie5.Name ='Subscriptions_Endpoint';
        customerRequestsAPIPropertie5.Value__c ='https://egid/api/exp-cegid-salesforce-api-acceptance/v1/subscriptions';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie5);
        
		insert customerRequestsAPIProperties ;
        
        Account acc = new Account();
        acc.Name='Test';
        acc.ERP_Number__c='98671965';
        acc.National_ID__c='12345677789999';
        acc.BillingCountry='France';
        acc.BillingPostalCode='12354';
        acc.BillingCity='Paris';
        acc.NumberOfEmployees=12;
        acc.AnnualRevenue=1234;
        insert acc;

        Business_Unit__c bu1 = new Business_Unit__c();
        bu1.Name = 'CPA';
        bu1.BU__c = '110';
        bu1.API_Code__c = '110';
        insert bu1;

        Business_Unit__c bu2 = new Business_Unit__c();
        bu2.Name = 'SB';
        bu2.BU__c = '100';
        bu2.API_Code__c = '100';
        insert bu2;

        CustomerRequest__c customerRequest1 = new CustomerRequest__c();
        customerRequest1.Account__c=acc.Id;
        customerRequest1.Type__c='Credit Note';
        insert customerRequest1;

        CustomerRequest__c customerRequest2 = new CustomerRequest__c();
        customerRequest2.Account__c=acc.Id;
        customerRequest2.Type__c='Cancellation';
        insert customerRequest2;

    }
    
    @IsTest
    public static void testGetInvoiceLinesData() {
        System.runAs(adminUser){
            Test.setMock(HttpCalloutMock.class, new CustomerRequestsFormControllerMock('InvoiceLines'));
            Test.startTest();
            List<CustomerRequestsFormController.lineWrapper> data = CustomerRequestsFormController.getInvoiceLinesData('1111111', 'Saas', 'ZUORA', '100', 'EUR', 'AS001-BM66666Z66', 'F002-00222222', '20', '40', '2021-02-01', '2021-11-01', 'MPI AUTO', '25');
            Test.stopTest();
            System.assertNotEquals(null, data, 'Asserting that data is not null');
        }
    } 
    
    @IsTest
    public static void testGetSubscriptionLinesData() {
        System.runAs(adminUser){
            Test.setMock(HttpCalloutMock.class, new CustomerRequestsFormControllerMock('SubscriptionLines'));
            Test.startTest();
            List<CustomerRequestsFormController.lineWrapper> data = CustomerRequestsFormController.getSubscriptionLinesData('1111111', 'ZUORA', 'EUR', '100', '25');
            Test.stopTest();
            System.assertNotEquals(null, data, 'Asserting that data is not null');
        }
    } 

    @IsTest
    public static void testCRUDInvoiceLines() {

        CustomerRequest__c customerRequest = [SELECT Id FROM CustomerRequest__c WHERE Type__c = 'Credit Note'];

        System.runAs(adminUser){
            Test.startTest();
            CustomerRequestsFormController.saveLines(customerRequest.Id, '[{"amount":"27","buOffer":"130","calculatedBu":"SB","startDate":"2021-09-01","endDate":"2021-09-30","loadName":"chargeNameTest","contractNumber":"AS001-BM66666Z66","domain":"Saas","lineDate":"2021-05-11","lineName":"FA002-002222221","lineNumber":"FA002-00222222","name":"1","origin":"ZUORA","sectorAgency3Part":"831","tierslivre":"MPI AUTO"},{"amount":"20.0000","buOffer":"130","calculatedBu":"SB","startDate":"2021-09-01","endDate":"2021-09-30","loadName":"chargeNameTest","contractNumber":"AS001-BM66666Z66","domain":"Saas","lineDate":"2021-05-11","lineName":"FA002-002222222","lineNumber":"FA002-00222222","name":"2","origin":"ZUORA","sectorAgency3Part":"831","tierslivre":"MPI AUTO"}]', 'InvoiceLine','130');
            List<CustomerRequestsFormController.InvoiceLineWrapper> invoiceLines = CustomerRequestsFormController.getInvoiceLinesByCustomerRequestId(customerRequest.Id);
            System.assertNotEquals(null, invoiceLines, 'Asserting that invoiceLines is not null');
            System.assertEquals(27, invoiceLines[0].CreditNoteAmount);

            List<InvoiceLine__c> invoiceLine = new List<InvoiceLine__c>();
            invoiceLine = [SELECT CreditNoteAmount__c From InvoiceLine__c];
            system.debug('tkn invoiceLine.size()' + invoiceLine.size());
            String isUpdated =  CustomerRequestsFormController.updateInvoiceLines('[{"CreditNoteAmount":"25.00","InvoiceLineId":"' + invoiceLine[0].Id + '"}]');
            System.assertEquals('Success', isUpdated);
            InvoiceLine__c invoiceLineUpdated = [SELECT CreditNoteAmount__c From InvoiceLine__c WHERE CreditNoteAmount__c = 25.00];
            System.assertEquals(25.00, invoiceLineUpdated.CreditNoteAmount__c);
            String isDeleted =  CustomerRequestsFormController.deleteInvoiceLine(invoiceLineUpdated.Id);
            System.assertEquals('Success', isDeleted);
            Test.stopTest();
        }
    }

     
    @IsTest
    public static void testCRUDSubscriptionLines() {

        CustomerRequest__c customerRequest = [SELECT Id FROM CustomerRequest__c WHERE Type__c = 'Cancellation'];

        System.runAs(adminUser){
            Test.startTest();
            CustomerRequestsFormController.saveLines(customerRequest.Id, '[{"amount":"27.0000","buOffer":"130","calculatedBu":"SB","loadName":"NameTest","loadType":"chargeTypeTest","contractNumber":"AS001-BM66666Z66","lineDate":"2024-04-15","lineName":"AS001-BM66666Z661","lineNumber":"AS001-BM66666Z66","name":"888888","nextDateRenewal":"2023-01-01","quantity":"1.0000","startDate":"2022-01-01","unitPrice":"27","tierslivre":"MPI AUTO"},{"amount":"22.0000","buOffer":"130","calculatedBu":"SB","loadName":"NameTest2","loadType":"chargeTypeTest","contractNumber":"AS001-BM66666Z66","lineDate":"2024-04-15","lineName":"AS001-BM66666Z662","lineNumber":"AS001-BM66666Z66","name":"999999","nextDateRenewal":"2023-01-01","quantity":"1.0000","startDate":"2022-01-01","unitPrice":"27","tierslivre":"MPI AUTO"}]', 'SubscriptionLines', '');
            List<CustomerRequestsFormController.SubscriptionLineWrapper> subscriptionLines = CustomerRequestsFormController.getSubscriptionLinesByCustomerRequestId(customerRequest.Id);
            System.assertNotEquals(null, subscriptionLines, 'Asserting that subscriptionLines is not null');
            SubscriptionLine__c subscriptionLine = [SELECT CancellationDate__c, QuantityCancelled__c From SubscriptionLine__c WHERE Name = 'NameTest'];
            String isUpdated =  CustomerRequestsFormController.updateSubscriptionLines('[{"CancellationDate":"2024-01-01","QuantityCancelled":"1","SubscriptionLineId":"' + subscriptionLine.Id + '"}]');
            System.assertEquals('Success', isUpdated);
            SubscriptionLine__c subscriptionLineUpdated = [SELECT QuantityCancelled__c From SubscriptionLine__c WHERE Name = 'NameTest'];
            System.assertEquals(1, subscriptionLineUpdated.QuantityCancelled__c);
            String isDeleted =  CustomerRequestsFormController.deleteSubscriptionLine(subscriptionLineUpdated.Id);
            System.assertEquals('Success', isDeleted);
            Test.stopTest();
        }
    } 

    @IsTest
    public static void testGetDomainPicklist() {
        System.runAs(adminUser){

            Test.startTest();
            Map<String,String> domainsMap = CustomerRequestsFormController.getDomainPicklist();
            Test.stopTest();
            System.assertNotEquals(null, domainsMap, 'Asserting that domainsMap is not null');
        }
    } 

    @IsTest
    public static void testSearchLookUp() {
        System.runAs(adminUser){

            Test.startTest();
            List<CustomerRequestsFormController.ErpnumberWrapper> results = CustomerRequestsFormController.searchLookUp('986');
            Test.stopTest();
            System.assertNotEquals(null, results, 'Asserting that results is not null');
        }
    } 

    @IsTest
    public static void testGetBUExternalId() {
        System.runAs(adminUser){

            Business_Unit__c bu = [SELECT Id FROM Business_Unit__c Limit 1];

            Test.startTest();
            Business_Unit__c buExternalId = CustomerRequestsFormController.getBUExternalId(bu.Id);
            Test.stopTest();
            System.assertNotEquals(null, buExternalId, 'Asserting that buExternalId is not null');
        }
    }

    @IsTest
    public static void testGetBUIdByExternalId() {
        System.runAs(adminUser){
            Test.startTest();
            Map<Id, Business_Unit__c> buMap = CustomerRequestsFormController.getBUIdByExternalId(new List<String>{'100', '110'});
            Test.stopTest();
            System.assertNotEquals(null, buMap, 'Asserting that buMap is not null');
        }
    }
}