unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IntercommunityVATnumber__c.field-meta.xml
<CustomField>
    <fullName>IntercommunityVATnumber__c</fullName>
    <inlineHelpText>A tax Number or taxpayer identification number, also known as a TIN for short, is a number issued to organizations to track tax obligations and payments they make
Do not enter any spaces in the field.</inlineHelpText>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Siren_Siret__c.field-meta.xml
<CustomField>
    <fullName>Siren_Siret__c</fullName>
    <description>Siren / Siret</description>
    <label>Siren/Siret</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Validated</fullName>
                <default>true</default>
                <label>To Be Validated</label>
            </value>
            <value>
                <fullName>In Progress Validation</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>To Be Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECH_Administrative_Compliance__c.field-meta.xml
<CustomField>
    <fullName>TECH_Administrative_Compliance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Administrative Compliance</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_Contact_Direct__c.field-meta.xml
<CustomField>
    <fullName>Tech_Contact_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech_Contact_Direct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TH_Account_TEST.cls
@isTest
public class TH_Account_TEST {

    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    static User salesUser = new UTIL_TestFactory.UserFactory().createUserCegidSales(); 
    /***BCR W-001709 ***/
    @isTest static void checkAdminComplianceTest() {

        List<Schema.PicklistEntry> accountBilCountCodeFieldValue = Schema.SObjectType.Account.fields.BillingCountryCode.getPicklistValues();

        List<Account> accs = new List<Account>();

        Account acc; 
        for(Schema.PicklistEntry pe : accountBilCountCodeFieldValue) {
            acc = new UTIL_TestFactory.AccountFactory().createAccount();
            acc.BillingCountryCode = pe.getValue();
            acc.ERP_Number__c = 'TESTERP';
            acc.Phone = '0143434543';
            acc.BillingStreet = 'Rue du Test';
            acc.BillingPostalCode = '69007';
            acc.BillingCity = 'LYON';
            acc.Status__c = 'Validated';
            acc.National_Id__c = '32345545656767';
            acc.IntercommunityVATnumber__c = 'Test';
            acc.Tech_Contact_Direct__c = true;
            
            if(acc.BillingCountryCode == 'FR') {

                acc.National_Id__c = '';

            } else if (acc.BillingCountryCode == 'GP') {

                acc.IntercommunityVATnumber__c = '';

            } else if(acc.BillingCountryCode == 'MC') {
                //accs.add(acc.clone(false, false, false, false));

                acc.National_Id__c = '';
                acc.IntercommunityVATnumber__c = '';

            } else if(acc.BillingCountryCode == 'SE') {

                acc.IntercommunityVATnumber__c = '';

            } else if(acc.BillingCountryCode == 'DK') {
                acc.Tech_Contact_Direct__c = false;
            }
 
           
            accs.add(acc);
        }

        
		System.debug('ACCS SIZE :'+ accs.size());

        Test.startTest();
            TH_Account thAcc = new TH_Account();

            thAcc.checkAdminCompliance(accs);
        Test.stopTest();
        
        Integer success = 0;
        for(Account acc1 : accs) {
            if(acc1.TECH_Administrative_Compliance__c == true) {
                success++;
            }
        }

        System.assertEquals(accs.size() - 4, success, 'incorrect number of sucess');
    }
    /***FIN BCR W-001709 ***/     
    
    /***BCR W-001705 ***/
    
    @isTest static void checkAccPermissionUpdate() {
        List<Account> accs = new List<Account>();
        Account acc; 
        for(Integer i = 0; i < 5; i++) {
            acc = new UTIL_TestFactory.AccountFactory().createAccount();
            acc.National_Id__c = '3234554565676'+i;
            acc.BillingCountryCode = 'FR';
            acc.ERP_Number__c = 'TESTER'+i;
            acc.Phone = '0143434543';
            acc.BillingStreet = 'Rue du Test'+i;
            acc.BillingPostalCode = '69007';
            acc.BillingCity = 'LYON'+i;
            acc.IntercommunityVATnumber__c = 'TESTVAT';
            acc.Siren_Siret__c = '';
            accs.add(acc);
        }

        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
    
        insert salesUser;

        List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5];
        UserTerritory2Association usrTerrAsso = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=allOrgTerritories[2].Id);

        System.runAs(adminUser) {
            insert bypass;
            insert accs;
            insert usrTerrAsso;
        }

        List<Account> existingAccs = [SELECT Id, Name, BillingStreet FROM Account];
        System.debug('Existing' + existingAccs);
        existingAccs[0].BillingStreet = 'TestModify';
        existingAccs[1].BillingStreet = 'TestModify';
        existingAccs[1].OwnerId = salesUser.Id;
        List<Database.SaveResult> results;
        CheckRecursivCall.alreadySeenRecords.clear();
        Test.startTest();
        System.runAs(salesUser) {
            results = Database.update(existingAccs, false);   
        }  
        Test.stopTest();
        System.debug(results);
    }
    /*** FIN BCR W-001705 */

    /**Coverage existing class BCR */
    @isTest static void afterInsertTest() {
        List<Account> accs = new List<Account>();
        Account acc; 
        for(Integer i = 5; i < 10; i++) {
            acc = new UTIL_TestFactory.AccountFactory().createAccount();
            acc.National_Id__c = '3234554565676'+i;
            acc.BillingCountryCode = 'FR';
            acc.ERP_Number__c = 'TESTER'+i;
            acc.Phone = '0143434543';
            acc.BillingStreet = 'Rue du Test'+i;
            acc.BillingPostalCode = '69007';
            acc.BillingCity = 'LYON'+i;
            acc.IntercommunityVATnumber__c = 'TESTVAT';
            acc.Siren_Siret__c = '';
            accs.add(acc);
        }

        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
        System.runAs(adminUser) {
            insert bypass;
        }
        List<Database.SaveResult> results;
        Test.startTest();
        System.runAs(adminUser) {
            results = Database.insert(accs, false);    
        }  
        Test.stopTest();
        System.debug(results);
    }

    /**FIN Coverage existing class BCR */
    @isTest static void extractSObjectTerritoryHierarchyTest() {
        List<Account> accs = new List<Account>();
        Account acc; 
        for(Integer i = 50; i < 100; i++) {
            acc = new UTIL_TestFactory.AccountFactory().createAccount();
            acc.National_Id__c = '3234554565676'+i;
            acc.BillingCountryCode = 'FR';
            acc.ERP_Number__c = 'TESTER'+i;
            acc.Phone = '0143434543';
            acc.BillingStreet = 'Rue du Test'+i;
            acc.BillingPostalCode = '69007';
            acc.BillingCity = 'LYON'+i;
            acc.IntercommunityVATnumber__c = 'TESTVAT';
            acc.Siren_Siret__c = '';
            accs.add(acc);
        }

        List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5 ];
        List<ObjectTerritory2Association> sObjsTerrAssos = new List<ObjectTerritory2Association>();

        
        System.runAs(adminUser) {
            
            insert accs;
        }

        for(Integer i = 0; i < 20; i++) {
            sObjsTerrAssos.add(new ObjectTerritory2Association(ObjectId = accs[i].Id, Territory2Id=allOrgTerritories[0].Id, AssociationCause='Territory2Manual'));
            sObjsTerrAssos.add(new ObjectTerritory2Association(ObjectId = accs[i].Id, Territory2Id=allOrgTerritories[1].Id, AssociationCause='Territory2Manual'));
        }
        for(Integer i = 20; i < 30; i++) {
            sObjsTerrAssos.add(new ObjectTerritory2Association(ObjectId = accs[i].Id, Territory2Id=allOrgTerritories[2].Id, AssociationCause='Territory2Manual'));
            sObjsTerrAssos.add(new ObjectTerritory2Association(ObjectId = accs[i].Id, Territory2Id=allOrgTerritories[3].Id, AssociationCause='Territory2Manual'));
        }
        for(Integer i = 30; i < 40; i++) {
            sObjsTerrAssos.add(new ObjectTerritory2Association(ObjectId = accs[i].Id, Territory2Id=allOrgTerritories[4].Id, AssociationCause='Territory2Manual'));
            
        }

        System.runAs(adminUser) {
            insert sObjsTerrAssos;
        }

        Test.startTest();
            Map<Id, Account> accsMap = new Map<Id, Account>([SELECT Id FROM Account]);
            Map<Id, Set<Id>> results =  new TH_Account().extractSObjectTerritoryHierarchy(accsMap.keySet());
            System.debug(results);
        Test.stopTest();

        System.assertEquals(40, results.size(), 'Map Size should be 40');

    }

    @isTest static void testIsAccountOwnerInRightTerritory() {
        List<Account> accs = new List<Account>();
        Account acc; 
        for(Integer i = 0; i < 5; i++) {
            acc = new UTIL_TestFactory.AccountFactory().createAccount();
            acc.National_Id__c = '3234554565676'+i;
            acc.BillingCountryCode = 'FR';
            acc.ERP_Number__c = 'TESTER'+i;
            acc.Phone = '0143434543';
            acc.BillingStreet = 'Rue du Test'+i;
            acc.BillingPostalCode = '69007';
            acc.BillingCity = 'LYON'+i;
            acc.IntercommunityVATnumber__c = 'TESTVAT';
            acc.Siren_Siret__c = '';
            accs.add(acc);
        }

        System.runAs(adminUser) {
            
            insert accs;
        }

        System.runAs(adminUser){  
              
            Map<Id, Account> accMap = new Map<Id, Account>([select id,Name from Account]);  
            
            // Perform test
            Test.startTest();  
            TH_Account.IsAccountOwnerInRightTerritory(accMap.keySet());             
            Test.stopTest();
            //System.assert(result.isSuccess());
        }
    }              
}