unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IntercommunityVATnumber__c.field-meta.xml
<CustomField>
    <fullName>IntercommunityVATnumber__c</fullName>
    <inlineHelpText>A tax Number or taxpayer identification number, also known as a TIN for short, is a number issued to organizations to track tax obligations and payments they make
Do not enter any spaces in the field.</inlineHelpText>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Siren_Siret__c.field-meta.xml
<CustomField>
    <fullName>Siren_Siret__c</fullName>
    <description>Siren / Siret</description>
    <label>Siren/Siret</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Validated</fullName>
                <default>true</default>
                <label>To Be Validated</label>
            </value>
            <value>
                <fullName>In Progress Validation</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>To Be Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_Contact_Direct__c.field-meta.xml
<CustomField>
    <fullName>Tech_Contact_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech_Contact_Direct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Customer_Reference__c/Customer_Reference__c.object-meta.xml
<CustomObject>
    <label>Customer Reference</label>
    <nameField>
        <displayFormat>Ref-{000000000}</displayFormat>
        <label>Customer Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer References</relationshipLabel>
    <relationshipName>Customer_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Reference__c/fields/Contact_of_reference__c.field-meta.xml
<CustomField>
    <fullName>Contact_of_reference__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact of reference</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer References</relationshipLabel>
    <relationshipName>Customer_References</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Reference__c/fields/Core_Business__c.field-meta.xml
<CustomField>
    <fullName>Core_Business__c</fullName>
    <label>Core Business</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Line__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Core_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Reference__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Reference__c/fields/Type_of_reference__c.field-meta.xml
<CustomField>
    <fullName>Type_of_reference__c</fullName>
    <label>Type of reference</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing testimonial</fullName>
            </value>
            <value>
                <fullName>Prospect call</fullName>
            </value>
            <value>
                <fullName>Recommendation score</fullName>
            </value>
            <value>
                <fullName>Marketing event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Core_Business__c.field-meta.xml
<CustomField>
    <fullName>Core_Business__c</fullName>
    <label>Core Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Core_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Product Line is inactive.</errorMessage>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Customer_ReferenceTrigger_Test.cls
@isTest
public  class Customer_ReferenceTrigger_Test {

    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    static User salesUser = new UTIL_TestFactory.UserFactory().createUserCegidSales(); 

    @isTest static void beforeInsertTest() {

        List<Schema.PicklistEntry> accountBilCountCodeFieldValue = Schema.SObjectType.Account.fields.BillingCountryCode.getPicklistValues();
        Account acc;
        acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.ERP_Number__c = 'TESTERP';
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test';
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON';
        acc.Status__c = 'Validated';
        acc.National_Id__c = '32345545656767';
        acc.IntercommunityVATnumber__c = 'Test';
        acc.Tech_Contact_Direct__c = true;

        insert salesUser;

        List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5];
        UserTerritory2Association usrTerrAsso = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=allOrgTerritories[2].Id);
        

        System.runAs(adminUser) {
            insert acc;
            insert usrTerrAsso;
        }

        ObjectTerritory2Association objTerrAsso = new ObjectTerritory2Association(AssociationCause = 'Territory2Manual', ObjectId = acc.Id, Territory2Id=allOrgTerritories[2].Id);

        System.runAs(adminUser) {
            insert objTerrAsso;
        }

        List<Customer_Reference__c> crs = new List<Customer_Reference__c>();

        

        for(Integer i = 0; i < 30; i++) {
            crs.add(new Customer_Reference__c(Account__c = acc.Id));
        }

        List<Database.SaveResult> results;
        Test.startTest();
        System.runAs(salesUser) {
            results = Database.insert(crs, false);
        }
               
        Test.stopTest();
    }

    @isTest static void beforeUpdateTest() {
        List<Schema.PicklistEntry> accountBilCountCodeFieldValue = Schema.SObjectType.Account.fields.BillingCountryCode.getPicklistValues();
        Account acc;
        acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.ERP_Number__c = 'TESTUERP';
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test';
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON';
        acc.Status__c = 'Validated';
        acc.National_Id__c = '32345545656767';
        acc.IntercommunityVATnumber__c = 'Test';
        acc.Tech_Contact_Direct__c = true;

        insert salesUser;

        List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5];
        UserTerritory2Association usrTerrAsso = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=allOrgTerritories[3].Id);
        

        System.runAs(adminUser) {
            insert acc;
            insert usrTerrAsso;
        }

        Contact ct = new UTIL_TestFactory.ContactFactory().createContact(acc.Id);
        
        insert ct;
           

        ObjectTerritory2Association objTerrAsso = new ObjectTerritory2Association(AssociationCause = 'Territory2Manual', ObjectId = acc.Id, Territory2Id=allOrgTerritories[3].Id);

        System.runAs(adminUser) {
            insert objTerrAsso;
        }

        List<Customer_Reference__c> crs = new List<Customer_Reference__c>();

        /*Product2 prd = new UTIL_TestFactory.ProductFactory().createProduct('Product', null);

        insert prd;*/

        for(Integer i = 0; i < 30; i++) {
            crs.add(new Customer_Reference__c(Account__c = acc.Id, Product_Line__c='297',
                                              Core_Business__c='140', Type_of_reference__c='NPS', Contact_of_reference__c=ct.Id));
        }

        insert crs;

        List<Customer_Reference__c> crsUpdate = [SELECT Id FROM Customer_Reference__c];

        List<Database.SaveResult> results;
        Test.startTest();
        System.runAs(salesUser) {
            results = Database.update(crsUpdate, false);
        }
               
        Test.stopTest();
    }

    @isTest static void beforeDeleteTest() {
        List<Schema.PicklistEntry> accountBilCountCodeFieldValue = Schema.SObjectType.Account.fields.BillingCountryCode.getPicklistValues();
        Account acc;
        acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.ERP_Number__c = 'TESTUERP';
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test';
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON';
        acc.Status__c = 'Validated';
        acc.National_Id__c = '32345545656767';
        acc.IntercommunityVATnumber__c = 'Test';
        acc.Tech_Contact_Direct__c = true;

        insert salesUser;

        List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5];
        UserTerritory2Association usrTerrAsso = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=allOrgTerritories[3].Id);
        

        System.runAs(adminUser) {
            insert acc;
            insert usrTerrAsso;
        }

        Contact ct = new UTIL_TestFactory.ContactFactory().createContact(acc.Id);
        
        insert ct;
           

        ObjectTerritory2Association objTerrAsso = new ObjectTerritory2Association(AssociationCause = 'Territory2Manual', ObjectId = acc.Id, Territory2Id=allOrgTerritories[3].Id);

        System.runAs(adminUser) {
            insert objTerrAsso;
        }

        List<Customer_Reference__c> crs = new List<Customer_Reference__c>();

        /*Product2 prd = new UTIL_TestFactory.ProductFactory().createProduct('Product', null);

        insert prd;*/

        for(Integer i = 0; i < 30; i++) {
            crs.add(new Customer_Reference__c(Account__c = acc.Id, Product_Line__c='297',
                                              Core_Business__c='140', Type_of_reference__c='NPS', Contact_of_reference__c=ct.Id));
        }

        insert crs;

        List<Customer_Reference__c> crsDelete = [SELECT Id FROM Customer_Reference__c];

        List<Database.DeleteResult> results;
        Test.startTest();
        System.runAs(salesUser) {
            results = Database.delete(crsDelete, false);
        }
               
        Test.stopTest();
    }

    @isTest static void AfterDeleteTest() {
        List<Schema.PicklistEntry> accountBilCountCodeFieldValue = Schema.SObjectType.Account.fields.BillingCountryCode.getPicklistValues();
        Account acc;
        acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.ERP_Number__c = 'TESTUERP';
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test';
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON';
        acc.Status__c = 'Validated';
        acc.National_Id__c = '32345545656767';
        acc.IntercommunityVATnumber__c = 'Test';
        acc.Tech_Contact_Direct__c = true;

        insert salesUser;

        List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5];
        UserTerritory2Association usrTerrAsso = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=allOrgTerritories[3].Id);
        

        System.runAs(adminUser) {
            insert acc;
            insert usrTerrAsso;
        }

        Contact ct = new UTIL_TestFactory.ContactFactory().createContact(acc.Id);
        
        insert ct;
           

        ObjectTerritory2Association objTerrAsso = new ObjectTerritory2Association(AssociationCause = 'Territory2Manual', ObjectId = acc.Id, Territory2Id=allOrgTerritories[3].Id);

        System.runAs(adminUser) {
            insert objTerrAsso;
        }

        List<Customer_Reference__c> crs = new List<Customer_Reference__c>();

        /*Product2 prd = new UTIL_TestFactory.ProductFactory().createProduct('Product', null);

        insert prd;*/

        for(Integer i = 0; i < 30; i++) {
            crs.add(new Customer_Reference__c(Account__c = acc.Id, Product_Line__c='297',
                                              Core_Business__c='140', Type_of_reference__c='NPS', Contact_of_reference__c=ct.Id));
        }

        insert crs;

        List<Customer_Reference__c> crsDelete = [SELECT Id FROM Customer_Reference__c];

        List<Database.DeleteResult> results;
        Test.startTest();
        System.runAs(salesUser) {
            results = Database.delete(crsDelete, false);
        }
               
        Test.stopTest();
    }

    /*public override void mainEntry(TriggerParameters tp) {
        System.debug('BEFORE INSERT HANDLER START');
        process((List<Customer_Reference__c>)tp.newList);
        System.debug('BEFORE INSERT HANDLER END');
    }
    
    private void process(List<Customer_Reference__c> newList) {
    
        this.bulkbeforeProcessing(newList);
    
        for(Customer_Reference__c cRef : newList) {
            Customer_ReferenceHelper.checkAccPermissionInsertUpdate(cRef, this.connectedWithProfile, this.terrUserIds, this.accWithTerritoriesHieriarchy);
        }
    }
    
    
    private void bulkbeforeProcessing(List<Customer_Reference__c> newList) {
        this.connectedWithProfile = Customer_ReferenceHelper.getUserWithProfile(UserInfo.getUserId());
        this.terrUserIds = Customer_ReferenceHelper.getTerritoryUserIds(UserInfo.getUserId());
        Set<Id> accIds = new Set<Id>();
    
        for(Customer_Reference__c cRef : newList) {
            accIds.add(cRef.Account__c);
        }
    
        this.accWithTerritoriesHieriarchy = Customer_ReferenceHelper.extractSObjectTerritoryHierarchy(accIds);
        /*@isTest static void checkAccPermissionUpdate() {
    List<Account> accs = new List<Account>();
    Account acc; 
    for(Integer i = 0; i < 5; i++) {
        acc = new UTIL_TestFactory.AccountFactory().createAccount();
        acc.National_Id__c = '3234554565676'+i;
        acc.BillingCountryCode = 'FR';
        acc.ERP_Number__c = 'TESTER'+i;
        acc.Phone = '0143434543';
        acc.BillingStreet = 'Rue du Test'+i;
        acc.BillingPostalCode = '69007';
        acc.BillingCity = 'LYON'+i;
        acc.IntercommunityVATnumber__c = 'TESTVAT';
        acc.Siren_Siret__c = '';
        accs.add(acc);
    }

    BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);

    insert salesUser;

    List<Territory2> allOrgTerritories = [SELECT Id, ParentTerritory2Id, Name FROM Territory2 WHERE Territory2Model.State = 'Active' LIMIT 5];
    UserTerritory2Association usrTerrAsso = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=allOrgTerritories[2].Id);

    System.runAs(adminUser) {
        insert bypass;
        insert accs;
        insert usrTerrAsso;
    }

    List<Account> existingAccs = [SELECT Id, Name, BillingStreet FROM Account];
    System.debug('Existing' + existingAccs);
    existingAccs[0].BillingStreet = 'TestModify';
    existingAccs[1].BillingStreet = 'TestModify';
    existingAccs[1].OwnerId = salesUser.Id;
    List<Database.SaveResult> results;
    CheckRecursivCall.alreadySeenRecords.clear();
    Test.startTest();
    System.runAs(salesUser) {
        results = Database.update(existingAccs, false);   
    }  
    Test.stopTest();
    System.debug(results);
}*/
}