unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/apps_credentials__mdt/apps_credentials__mdt.object-meta.xml
<CustomObject>
    <label>App credential</label>
    <pluralLabel>apps credentials</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/apps_credentials__mdt/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>Client_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/apps_credentials__mdt/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>Client_secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/apps_credentials__mdt/fields/grant_type__c.field-meta.xml
<CustomField>
    <fullName>grant_type__c</fullName>
    <label>Grant_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/apps_credentials__mdt/fields/scope__c.field-meta.xml
<CustomField>
    <fullName>scope__c</fullName>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/apps_credentials__mdt/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>Url</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/AP05_RelatedListAccSituation.cls
/**
 * @author Akshi Boojhawon - Comforth
 * @date 2020-07-17
 * @description controller class for LC01_RelatedListAccountingSituation
 */
public class AP05_RelatedListAccSituation {

    @AuraEnabled
    public static Map <string,object> fetchData(Id recordId) {
        apps_credentials__mdt appCred= apps_credentials__mdt.getInstance('Vue360SouscriptionToken');
        apps_credentials__mdt appCredVue360= apps_credentials__mdt.getInstance('Vue360_AstonURL');


        
        Map <string,object> mapToken = new Map<string,object>();
        Map <string,object> mapAston = new Map<string,object>();

        Account acc= [select Id,ERP_Number__c from Account where Id =: recordId];
        string erp_Number = acc.ERP_Number__c;
        
        Http httpToken = new Http();
        HttpRequest req = new HttpRequest();
        
        string strUrl= appCred.url__c +'?'+'client_id='+appCred.client_id__c+'&client_secret='+appCred.client_secret__c+'&grant_type='+appCred.grant_type__c+'&scope='+appCred.scope__c;
        system.debug(strUrl);
        req.setEndpoint(strUrl);

        //req.setEndpoint(system.Label.Vue360SouscriptionToken);
        req.setMethod('POST');
        HttpResponse res = httpToken.send(req);
        string TokenResponse = res.getBody();
        mapToken=(Map<String, Object>) JSON.deserializeUntyped(TokenResponse);
        if(mapToken.containsKey('access_token')){
            String Token = string.valueof(mapToken.get('access_token'));
            
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            
            request.setEndpoint(appCredVue360.url__c+erp_Number+'/recovery-status');
            //request.setEndpoint(system.Label.Vue360_AstonURL+erp_Number+'/recovery-status');
            request.setMethod('GET');
            request.setHeader('Authorization','Bearer '+Token);
            HttpResponse response = http.send(request);
            
            if(response.getStatusCode()==200){
                string returnData= response.getBody();
                if(returnData!=null){
                    mapAston= (Map<String, Object>) JSON.deserializeUntyped(returnData);
                    return mapAston;
                }else{
                    return new Map <String, Object>{
                    'error' => system.Label.Error_Message_WS
                    };
                }
            }else{
                return new Map <String, Object>{
                    'error' => system.Label.Error_Message_WS
                };
            }
        } else {
            return new Map <String, Object>{
                'error' => system.Label.AuthentificationFailed
            };
        }
        
    }
}