unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/AP03_RelatedListParc_TEST.cls
/***
* @author      Comforth - SRA
* @date        08/06/2020
* @description Test class for AP03_RelatedListParc
***/
@isTest
public class AP03_RelatedListParc_TEST {
    
    @testSetup static void setup(){
        
        Account acc1 = new UTIL_TestFactory.AccountFactory().createAccount();
        acc1.ERP_Number__c='90131522';
        acc1.National_ID__c='12345677789999';
        acc1.BillingCountry='France';
        acc1.BillingPostalCode='12354';
        acc1.BillingCity='Paris';
        acc1.NumberOfEmployees=12;
        acc1.AnnualRevenue=1234;
        insert acc1;
        
    }
    
    static testMethod void testFetchData() {
        User u = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
        insert u;
        
        Account accTest = [select id,Name from Account where Name LIKE 'test Comforth%'];
        
        Test.setMock(HttpCalloutMock.class, new AP03_RelatedListParc_MOCK());
        Test.startTest();
        AP03_RelatedListParc.fetchData(accTest.Id);
        Test.stopTest();
        
    }
}