unpackaged/main/default/objects/Account/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>To obtain the 'ERP Number, the following fields must be filled in :
- Account Name
- Account Type
- National ID (Siret for accounts in France)
- Industry code
- Billing Address
- Phone
- Annual Revenue
- No. of Employees</inlineHelpText>
    <label>ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>AV-{0}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <summarizedField>CreditNoteLine__c.CreditNoteAmount__c</summarizedField>
    <summaryForeignKey>CreditNoteLine__c.CreditNote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/CustomerRequest__c.field-meta.xml
<CustomField>
    <fullName>CustomerRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Request</label>
    <referenceTo>CustomerRequest__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLine__c/CreditNoteLine__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Credit Note Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLine__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Credit Note Lines</relationshipLabel>
    <relationshipName>CreditNotesLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLine__c/fields/InvoiceLine__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line</label>
    <referenceTo>InvoiceLine__c</referenceTo>
    <relationshipLabel>Credit Notes Lines</relationshipLabel>
    <relationshipName>CreditNotesLines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLine__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Requests_API_Properties__c/Customer_Requests_API_Properties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For OneNoteS Project &amp; Zuora API interface</description>
    <label>Customer Requests API Properties</label>
</CustomObject>

unpackaged/main/default/objects/Customer_Requests_API_Properties__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/CustomerRequest__c.object-meta.xml
<CustomObject>
    <label>Customer Request</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CustomerRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Lorem Ipsum</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Requests</relationshipLabel>
    <relationshipName>CustomerRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <summarizedField>InvoiceLine__c.CreditNoteAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLine__c.CustomerRequest__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation with Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLine__c/InvoiceLine__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLine__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/CustomerRequest__c.field-meta.xml
<CustomField>
    <fullName>CustomerRequest__c</fullName>
    <label>Customer Request</label>
    <referenceTo>CustomerRequest__c</referenceTo>
    <relationshipLabel>Invoices Lines</relationshipLabel>
    <relationshipName>InvoicesLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoices Lines</relationshipLabel>
    <relationshipName>InvoicesLines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/invoiceItemId__c.field-meta.xml
<CustomField>
    <fullName>invoiceItemId__c</fullName>
    <label>invoiceItemId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/LoadName__c.field-meta.xml
<CustomField>
    <fullName>LoadName__c</fullName>
    <label>Load Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Origin</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <default>true</default>
        <label>Direct</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Mixed</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Partner</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Influencing Organization</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Origin.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>XRP</fullName>
    </customValue>
    <customValue>
        <fullName>ZUORA</fullName>
    </customValue>
    <customValue>
        <fullName>SIC</fullName>
    </customValue>
    <masterLabel>Origin</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM025_CreditNoteLineTest.cls
/** 
  @File Name          : SM025_CreditNoteLineTest
  @Description        : test class for SM025_CreditNoteLine 
  @Author             : JDA   
  @Group              : Comforth_Easyfront
  @Last Modified By   : 
  @Last Modified On   : 
  @Modification Log   : 
  Ver       Date            Author      		    Modification
  ---    -----------       -------           ------------------------ 
  1.0    27/02/2023         JDA                 Initial Version
  ---    -----------       -------           ------------------------ 
**/
@isTest
public class SM025_CreditNoteLineTest {

    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    @isTest static void testCreditNoteLineTriggerWithoutZuoraAsOrigin(){

        Account acc = new Account();
        acc.Name='Test';
        acc.ERP_Number__c='98671965';
        acc.National_ID__c='12345677789999';
        acc.BillingCountry='France';
        acc.BillingPostalCode='12354';
        acc.BillingCity='Paris';
        acc.NumberOfEmployees=12;
        acc.AnnualRevenue=1234;
        insert acc;

        
        CustomerRequest__c customerRequest1 = new CustomerRequest__c();
        customerRequest1.Account__c=acc.Id;
        customerRequest1.Type__c='Credit Note';
        customerRequest1.Comment__c ='Test update';
        insert customerRequest1;
      
        CreditNote__c creditNote = new CreditNote__c();
        creditNote.Subsidiary__c ='CEGID SA';
        insert creditNote;

        Invoice__c invoice = new Invoice__c();
        insert invoice;

     


        InvoiceLine__c invoiceLineItem = new InvoiceLine__c();
        invoiceLineItem.Amount__c = 10000;
        invoiceLineItem.Invoice__c = invoice.id;
        invoiceLineItem.CustomerRequest__c = customerRequest1.id;
        invoiceLineItem.invoiceItemId__c ='A526489424';
        invoiceLineItem.Quantity__c =2;
        invoiceLineItem.StartDate__c = System.today();
        invoiceLineItem.EndDate__c= System.today().addDays(10);
        invoiceLineItem.LoadName__c ='SKU 300';
        insert invoiceLineItem;
 

        CreditNoteLine__c creditNoteLine = new CreditNoteLine__c();
        creditNoteLine.CreditNoteAmount__c = 500;
        creditNoteLine.CreditNote__c = creditNote.Id;
        creditNoteLine.InvoiceLine__c = invoiceLineItem.Id;



        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CustomerRequestsFormControllerMock('Access_Token_Endpoint'));
        Test.setMock(HttpCalloutMock.class, new CreditNoteLineControllerMock());
        System.runAs(adminUser) {
            insert creditNoteLine;
        }
        Test.stopTest();

        
    }
    @isTest static void testCreditNoteLineTriggerWithZuoraAsOrigin(){
      
       
        Account acc = new Account();
        acc.Name='Test';
        acc.ERP_Number__c='98671965';
        acc.National_ID__c='12345677789999';
        acc.BillingCountry='France';
        acc.BillingPostalCode='12354';
        acc.BillingCity='Paris';
        acc.NumberOfEmployees=12;
        acc.AnnualRevenue=1234;
        insert acc;

        
        CustomerRequest__c customerRequest1 = new CustomerRequest__c();
        customerRequest1.Account__c=acc.Id;
        customerRequest1.Type__c='Credit Note';
        customerRequest1.Comment__c ='Test update';
        insert customerRequest1;
      
        CreditNote__c creditNote2 = new CreditNote__c();
        creditNote2.Subsidiary__c ='CEGID SA';
        insert creditNote2;

        Invoice__c invoice = new Invoice__c();
        insert invoice;

        InvoiceLine__c invoiceLineItem = new InvoiceLine__c();
        invoiceLineItem.Amount__c = 10000;
        invoiceLineItem.Invoice__c = invoice.id;
        invoiceLineItem.CustomerRequest__c = customerRequest1.id;
        invoiceLineItem.invoiceItemId__c ='A526489424';
        invoiceLineItem.Quantity__c =2;
        invoiceLineItem.StartDate__c = System.today();
        invoiceLineItem.EndDate__c= System.today().addDays(10);
        invoiceLineItem.LoadName__c ='SKU 300';
        insert invoiceLineItem;
 

        CreditNoteLine__c creditNoteLine = new CreditNoteLine__c();
        creditNoteLine.CreditNoteAmount__c = 500;
        creditNoteLine.CreditNote__c = creditNote2.Id;
        creditNoteLine.Origin__c = 'ZUORA';
        creditNoteLine.InvoiceLine__c = invoiceLineItem.Id;


        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);

        List<Customer_Requests_API_Properties__c> customerRequestsAPIProperties = new List<Customer_Requests_API_Properties__c>();
        Customer_Requests_API_Properties__c customerRequestsAPIPropertie1 = new Customer_Requests_API_Properties__c();
		customerRequestsAPIPropertie1.Name ='Access_Token_Endpoint';
        customerRequestsAPIPropertie1.Value__c ='https://uat-cegid-oauth-provider.de-c1.eu1.cloudhub.io/v2/access-token';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie1);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie2 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie2.Name ='Client_Secret';
        customerRequestsAPIPropertie2.Value__c ='abc123456789';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie2);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie3 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie3.Name ='Client_Id';
        customerRequestsAPIPropertie3.Value__c ='efg123456789';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie3);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie4 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie4.Name ='InvoiceLines_Endpoint';
        customerRequestsAPIPropertie4.Value__c ='https://egid/api/exp-cegid-salesforce-api-acceptance/v1/invoiceLines';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie4);

        Customer_Requests_API_Properties__c customerRequestsAPIPropertie5 = new Customer_Requests_API_Properties__c();
        customerRequestsAPIPropertie5.Name ='Subscriptions_Endpoint';
        customerRequestsAPIPropertie5.Value__c ='https://egid/api/exp-cegid-salesforce-api-acceptance/v1/subscriptions';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie5);
        
        Customer_Requests_API_Properties__c customerRequestsAPIPropertie6 = new Customer_Requests_API_Properties__c();
		customerRequestsAPIPropertie6.Name ='CreditNote_Endpoint';
        customerRequestsAPIPropertie6.Value__c ='https://uat-cegid-oauth-provider.de-c1.eu1.cloudhub.io/v2/access-token2';
        customerRequestsAPIProperties.add(customerRequestsAPIPropertie6);
        
		insert customerRequestsAPIProperties ;
        
      
        Test.setMock(HttpCalloutMock.class, new CustomerRequestsFormControllerMock('Access_Token_Endpoint'));
        Test.setMock(HttpCalloutMock.class, new CustomerRequestsFormControllerMock('CreditNote_Endpoint'));

        System.runAs(adminUser) {
            insert bypass;
            insert creditNoteLine;
        }

        
    }
}