unpackaged/main/default/objects/Account/fields/IntercommunityVATnumber__c.field-meta.xml
<CustomField>
    <fullName>IntercommunityVATnumber__c</fullName>
    <inlineHelpText>A tax Number or taxpayer identification number, also known as a TIN for short, is a number issued to organizations to track tax obligations and payments they make
Do not enter any spaces in the field.</inlineHelpText>
    <label>Tax Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caractère actif / inactif du contact</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Function__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/merge_contact_done__e/merge_contact_done__e.object-meta.xml
<CustomObject>
    <label>merge contact done</label>
    <pluralLabel>merges contacts done</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/merge_contact_done__e/fields/Contact_To_be_deleted__c.field-meta.xml
<CustomField>
    <fullName>Contact_To_be_deleted__c</fullName>
    <label>Contact To be deleted</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/merge_contact_done__e/fields/Created_By_Id__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Id__c</fullName>
    <label>Created By Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/merge_contact_done__e/fields/Merged_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Merged_Contact_Id__c</fullName>
    <label>Merged Contact Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Bypass_Contact_Duplicate_Rule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Contact_Duplicate_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Contact duplicate rule</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass VR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Function.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting recoverings contact</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>After-Sales Service Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business app Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business Development Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Career Planning Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Directors</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Management</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Supervisory Board</fullName>
    </customValue>
    <customValue>
        <fullName>Chartered accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Accounting Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Digital Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Information Officer</fullName>
    </customValue>
    <customValue>
        <fullName>IT Dir.</fullName>
    </customValue>
    <masterLabel>Function</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finance and accounting</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Affairs</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and communication</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Representative</fullName>
    </customValue>
    <customValue>
        <fullName>Transversal</fullName>
    </customValue>
    <customValue>
        <fullName>NR</fullName>
        <isActive>false</isActive>
        <label>NR</label>
    </customValue>
    <masterLabel>Service</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_Contact_Test.cls
@isTest
public class TH_Contact_Test {

    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    @testSetup
    static void makeData() {

         adminUser.BypassVR__c = true;
         adminUser.Bypass_Contact_Duplicate_Rule__c = true;

         Account acc = new UTIL_TestFactory.AccountFactory().createAccount();
         acc.IntercommunityVATnumber__c = 'TestVAT';
         acc.National_ID__c = '12345690745678';
         List<Contact> cts = new List<Contact>();
        
         System.runAs(adminUser) {
             insert acc;
             for(Integer i = 0 ; i < 10 ; i++) {
                Contact ct = new UTIL_TestFactory.ContactFactory().createContact(acc.Id);
                ct.Active__c = true;
                ct.Salutation = 'Mr.';
                ct.Phone = '0123456789';
                cts.add(ct);
             }
             insert cts;
             System.debug('cts '+cts);
         }
        
         System.debug('BypassTrigger__c '+BypassTrigger__c.getOrgDefaults());

        BypassTrigger__c bypass = new BypassTrigger__c(Activatetrigger__c = true);
        insert bypass;
    }
    
    
    @isTest static void computeAccountTechContactDirectTest() {

    }

    @isTest static void beforeInsertTest() {
        List<Database.SaveResult> results;
        System.runAs(adminUser) {
        Account acc = [SELECT Id FROM Account LIMIT 1];

        List<Contact> cts = new List<Contact>();
        Contact c;
        for(Integer i = 0 ; i < 10 ; i++) {
            c = new Contact();
            c.LastName = 'LName'+System.now().millisecond()+i;
            c.FirstName = 'FName'+System.now().millisecond()+i;
            c.email = 'lname'+System.now().millisecond()+i+'@email.com';
            c.AccountId = acc.Id;
            c.Service__c = 'IT';
            c.Function__c = 'IT Dir.';
            cts.add(c);
        }

        
        Test.startTest();
        
            results = Database.insert(cts, false);    
        }  
        Test.stopTest();
        for(Database.SaveResult result : results) {
            System.assertEquals(result.isSuccess(), true, 'Result have to be a sucess');
        }
        
    }
    
    @isTest static void afterInsertTest() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact c;
        List<Contact> cts = new List<Contact>();
        for(Integer i = 0 ; i < 10 ; i++) {
            c = new Contact();
            c.LastName = 'LName'+System.now().millisecond()+i;
            c.FirstName = 'FName'+System.now().millisecond()+i;
            c.email = 'lname'+System.now().millisecond()+i+'@email.com';
            c.AccountId = acc.Id;
            c.Service__c = 'IT';
            c.Function__c = 'IT Dir.';
            cts.add(c);
        }

        List<Database.SaveResult> results;
        Test.startTest();
        System.runAs(adminUser) {
            results = Database.insert(cts, false);    
        }  
        Test.stopTest();
        for(Database.SaveResult result : results) {
            System.assertEquals(result.isSuccess(), true, 'Result have to be a sucess');
        }
    }

    @isTest static void afterUpdateTest() {
        List<Contact> cts = [SELECT Id, FirstName FROM Contact];
        Integer i = 0;
        for(Contact ct : cts) {
            ct.FirstName = ct.FirstName+'change'+i;
            i++;
        }

        List<Database.SaveResult> results;

        Test.startTest();
        System.runAs(adminUser) {
            results = Database.update(cts, false);   
        }  
        Test.stopTest();
        
        for(Database.SaveResult result : results) {
            System.debug('Error : '+ result.getErrors());
            //System.assertEquals(true, result.isSuccess(), 'Result have to be a sucess');
        }
    }

    @isTest static void afterDeleteTest() {
        List<Contact> cts = [SELECT Id, LastName FROM Contact];

        List<Database.DeleteResult> results;

        Test.startTest();
        System.runAs(adminUser) {
            results = Database.delete(cts, false);   
        }  
        Test.stopTest();
        
        for(Database.DeleteResult result : results) {
            System.assertEquals(true, result.isSuccess(), 'Result have to be a sucess');
        }
    }

    @isTest static void AsyncUpdateAndRedirectMergedContactTest() {

        List<Contact> cts = [SELECT Id, CreatedById FROM Contact];
        List<Contact> ctsToMerged = new List<Contact>();
        List<merge_contact_done__e> ctsMerge = new List<merge_contact_done__e>();
        List<Contact> ctsToDelete = new List<Contact>();

        for(Integer i; i < cts.size(); i++) {
            if(i < 5) {
                ctsToDelete.add(cts[i]);
            } else {
                ctsToMerged.add(cts[i]);
            }
        }

        for(Integer i; i < cts.size(); i++) {   
            ctsMerge.add(new merge_contact_done__e(Merged_Contact_Id__c = ctsToMerged[i].Id,
                                                   Contact_To_be_deleted__c = ctsToDelete[i].Id,
                                                   Created_By_Id__c = ctsToDelete[i].CreatedById));
        }

        TH_Contact.AsyncUpdateAndRedirectMergedContact asyncTest = new TH_Contact.AsyncUpdateAndRedirectMergedContact(ctsToMerged, ctsMerge, ctsToDelete);

       Test.startTest();
       ID jobID = System.enqueueJob(asyncTest);
       Test.StopTest();
       
    }
}