unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Cegid_solution__c.field-meta.xml
<CustomField>
    <fullName>Cegid_solution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cegid solution</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AccountCoreBusiness__c/AccountCoreBusiness__c.object-meta.xml
<CustomObject>
    <label>Account Core Business</label>
    <nameField>
        <displayFormat>ACB-{000000}</displayFormat>
        <label>Account Core Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Core Business</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AccountCoreBusiness__c/fields/AccountExpertise__c.field-meta.xml
<CustomField>
    <fullName>AccountExpertise__c</fullName>
    <label>Account Expertise</label>
    <referenceTo>Account_Expertise__c</referenceTo>
    <relationshipLabel>Account Core Business</relationshipLabel>
    <relationshipName>Account_Core_Business</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AccountCoreBusiness__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caractère actif / inactif du contact</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LeadOrigin__c.field-meta.xml
<CustomField>
    <fullName>LeadOrigin__c</fullName>
    <label>Lead Origin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Oppy_AutoCreated__c.field-meta.xml
<CustomField>
    <fullName>Oppy_AutoCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oppy AutoCreated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Oppy_converted_from_Lead__c.field-meta.xml
<CustomField>
    <fullName>Oppy_converted_from_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Opportunity is created after a Lead conversion, the field is checked.
Otherwise, it's unchecked.</description>
    <label>Oppy converted from Lead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Expertise__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TECHOwnerCalculated__c.field-meta.xml
<CustomField>
    <fullName>TECHOwnerCalculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECHOwnerCalculated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Line__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/SM001_Opportunity_TEST.cls
@isTest
public class SM001_Opportunity_TEST {
    /**
* @author Keshav - Comforth
* @date 2020-02-04
* @group UTIL
* @description Classe SM001_Opportunity_TEST
*/
    /**
* @File Name          : TH_Opportunity
* @Description        : Update owner field based on territory when an opportunity is created from a contact
* @Author             : SRA   
* @Group              : Comforth-Karoo
* @Last Modified By   : SRA
* @Last Modified On   : 31/07/2020
* @Modification Log   : 
* Ver       Date            Author      		    Modification
* ---    -----------       -------           ------------------------ 
* 1.0    31/07/2020         SRA              Initial Version
* ---    -----------       -------           ------------------------ 
**/
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    
    @testSetup static void setup(){
        System.runAs(adminUser){       
            
            insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
                
            Test.startTest();
            List<Account> listAcc = new List<Account>();
            List<Contact> listCon = new List<Contact>();
            List<Opportunity> listOppConverted = new List<Opportunity>();
            List<Opportunity> listOppAutoCreate = new List<Opportunity>();
            List<ObjectTerritory2Association> listOTA = new List<ObjectTerritory2Association>();
            List<Territory2> listTerritory = [Select Id , Expertise__c from Territory2 where  Expertise__c='200' AND Territory2Model.State = 'Active']; 
            
            listAcc.add(new UTIL_TestFactory.AccountFactory().createAccount());
            listAcc[0].National_ID_Exception__c ='Empty on loading';
            listAcc[0].BillingPostalCode ='75008';
            listAcc[0].BillingCountry ='France';
            listAcc[0].BillingCity ='Paris';
            listAcc[0].No_of_Employees_Group__c =12;
            listAcc[0].No_of_Stores__c =2;
            listAcc[0].NumberOfEmployees =12;
            insert listAcc;
            
            Account_Expertise__c accShare = new Account_Expertise__c();
            accShare.Account__c=listAcc[0].Id;
            accShare.Expertise__c='200';
            accShare.Cegid_solution__c=true;
            insert accShare;
            
            listCon.add(new UTIL_TestFactory.ContactFactory().createContact(listAcc[0].id));   
            listCon[0].Salutation ='MR';
            listCon[0].Expertise__c='200';
            listCon[0].Active__c=True;
            listCon[0].Email='test@test.com';
            listCon[0].LeadOrigin__c='Sales';
            insert listCon;
            
            listOTA.add(new UTIL_TestFactory.ObjectTerritory2AssociationFactory().createObjectTerritory2Association(listAcc[0].Id,listTerritory[0].Id));
            Insert listOTA;
            
            Test.stopTest();
        }
    }
    
    static testMethod void testPackage() {
        
        List<Account> listAcc = [SELECT id from Account];
        
        List<Opportunity> listOppAutoCreate = new List<Opportunity>();
        listOppAutoCreate.add(new UTIL_TestFactory.OpportunityFactory().createOpportunity(listAcc[0].Id,false,true));
            listOppAutoCreate[0].Expertise__c='200';
            listOppAutoCreate[0].Oppy_AutoCreated__c = true;
        
        System.runAs(adminUser) {
            Test.startTest();
            Insert listOppAutoCreate;
            Test.stopTest();
        }
    }
    
    static testMethod void testConvertedLead() {
        
        List<Account> listAcc = [SELECT id from Account];
        
        List<Opportunity> listOppConverted = new List<Opportunity>();
        listOppConverted.add(new UTIL_TestFactory.OpportunityFactory().createOpportunity(listAcc[0].Id,True,false));
            listOppConverted[0].Expertise__c='200';
            listOppConverted[0].TECHOwnerCalculated__c = False;
            listOppConverted[0].Oppy_converted_from_Lead__c=True;
        
        System.runAs(adminUser) {
            Test.startTest();
            Insert listOppConverted;
            Test.stopTest();
        }
    }
    
    static testMethod void testCalculateOpportunitySubSalesPurpose() {
        
        List<Account> listAcc = [SELECT id from Account];
        Account_Expertise__c ae = new Account_Expertise__c(Account__c = listAcc[0].Id, Expertise__c = '200');
        insert ae;
        AccountCoreBusiness__c acb1 = new AccountCoreBusiness__c(AccountExpertise__c = ae.Id, ProductLine__c='046');
        insert acb1;
        AccountCoreBusiness__c acb2 = new AccountCoreBusiness__c(AccountExpertise__c = ae.Id, ProductLine__c='046');
        insert acb2;
        Product_Line__c pl = new Product_Line__c(API_Code__c = '046', Name = 'Test');
        insert pl;
        
        List<Opportunity> listOppConverted = new List<Opportunity>();
        listOppConverted.add(new UTIL_TestFactory.OpportunityFactory().createOpportunity(listAcc[0].Id,True,false));
            listOppConverted[0].Expertise__c='200';
        	listOppConverted[0].Product_Line__c='046';
            listOppConverted[0].Sales_Purpose__c = '411';
        
        System.runAs(adminUser) {
            Test.startTest();
            Insert listOppConverted;
            Test.stopTest();
        }
    }
}