unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/TerritoryCode__c.field-meta.xml
<CustomField>
    <fullName>TerritoryCode__c</fullName>
    <label>Territory Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>CASE( 
    TEXT(Agency__c),
'112', 'CPA',
'113', 'CPA',
'114', 'CPA',
'115', 'CPA',
'217', 'RETAIL',
'290', 'RETAIL',
'320', 'CPA',
'340', 'CPA',
'392', 'FINANCE',
'393', 'FINANCE',
'394', 'FINANCE',
'395', 'FINANCE',
'396', 'FINANCE',
'397', 'FINANCE',
'410', 'CPA',
'411', 'CPA',
'412', 'CPA',
'470', 'CPA',
'530', 'Other',
'549', 'RETAIL',
'550', 'RETAIL',
'552', 'RETAIL',
'555', 'RETAIL',
'556', 'RETAIL',
'557', 'RETAIL',
'560', 'RETAIL',
'563', 'HCM',
'583', 'RETAIL',
'585', 'HCM',
'714', 'HCM',
'715', 'HCM',
'800', 'FINANCE',
'803', 'SB',
'804', 'SB',
'805', 'FINANCE',
'808', 'FINANCE',
'809', 'RETAIL',
'810', 'FINANCE',
'811', 'FINANCE',
'812', 'HCM',
'813', 'HCM',
'814', 'FINANCE',
'815', 'FINANCE',
'816', 'FINANCE',
'818', 'CPA',
'819', 'FINANCE',
'822', 'FINANCE',
'823', 'HCM',
'824', 'HCM',
'825', 'HCM',
'826', 'HCM',
'829', 'CPA',
'830', 'CPA',
'831', 'SB',
'832', 'HCM',
'834', 'HCM',
'835', 'HCM',
'836', 'HCM',
'837', 'HCM',
'838', 'HCM',
'839', 'HCM',
'841', 'HCM',
'842', 'HCM',
'840', 'HCM',
'843', 'OTHER',
'844', 'RETAIL',
'845', 'FINANCE',
'846', 'FINANCE',
'847', 'FINANCE',
'849', 'FINANCE',
'850', 'FINANCE',
'852', 'FINANCE',
'853', 'FINANCE',
'854', 'FINANCE',
'855', 'HCM',
'856', 'SB',
'857', 'HCM',
'858', 'HCM',
'Not Assigned'
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassPB__c.field-meta.xml
<CustomField>
    <fullName>BypassPB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass PB</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass VR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassWF__c.field-meta.xml
<CustomField>
    <fullName>BypassWF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass WF</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <label>Direct Sales Force</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect Sales Force</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Inside Sales</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Consultants</label>
    </customValue>
    <customValue>
        <fullName>006</fullName>
        <label>C.A.T.</label>
    </customValue>
    <customValue>
        <fullName>007</fullName>
        <label>Non-activity sales</label>
    </customValue>
    <customValue>
        <fullName>008</fullName>
        <label>Intra-group sales</label>
    </customValue>
    <customValue>
        <fullName>009</fullName>
        <label>Interactive sales</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_UserTerritory2Association_TEST.cls
@isTest
public with sharing class TH_UserTerritory2Association_TEST {    

    private static String SYSTEM_ADMINISTRATOR_PROFILE_NAME = 'System Administrator';
    private static String SYSTEM_ADMINISTRATOR_PROFILE_NAME_FR = 'Administrateur système';   
    private static String CEGID_TELEMARKETING_PROFILE_NAME = 'Cegid Telemarketing';
    
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();  

    @testSetup
    static void setup() {
    
        List<Account> accounts = new List<Account>();
        List<User> users = new List<User>();        
        
        // insert 100 users
        for (Integer i=0;i<10;i++) {
            users.add(new User(
                alias = 'Test',
                email = i+'test.magellan-admin@example.com',
                emailencodingkey = 'UTF-8',
                BypassPB__c = true,
                BypassVR__c = true,
                BypassWF__c = true,
                lastname = 'testAdmin'+i,
                languagelocalekey = 'fr',
                localesidkey = 'fr_FR',
                profileid = [
                    SELECT Id
                    FROM Profile
                    WHERE Name = :CEGID_TELEMARKETING_PROFILE_NAME
                    LIMIT 1
                ][0].Id,
                timezonesidkey = 'Europe/Paris',
                username = 'test.magellan-admin1' + System.now().millisecond()
                + UserInfo.getOrganizationId() + '@example.com'
            ));
        }
        insert users;   
        
        // insert 100 accounts
        for (Integer i=0;i<10;i++) {
            accounts.add(new Account(	
            Name= 'Test Account AZA2'+i,
            National_ID_Exception__c ='Empty on loading',
            BillingPostalCode ='75009',
            BillingCountry ='France',
            BillingCity ='Paris',
            No_of_Employees_Group__c =15,
            No_of_Stores__c =7,
            NumberOfEmployees =14,
            //National_ID__c='1012151415124'+i,
            OwnerId = users.get(i).Id
                                   ));
            
            
        }
        insert accounts;          
    }

    @isTest static void testInsert() {
        System.runAs(adminUser){ 
        String CEGID_TELEMARKETING_PROFILE_NAME = 'Cegid Telemarketing';
        List<ObjectTerritory2Association> objectTerritory2Associations = new List<ObjectTerritory2Association>();
        List<UserTerritory2Association> userTerritory2Associations = new List<UserTerritory2Association>();
        List<Territory2> territories = new List<Territory2>();
        
        Territory2Model territoryModel = [select Id,Name From Territory2Model  Where State <> 'Archived' limit 1];

        Territory2Type territoryType = [select Id,MasterLabel From Territory2Type where MasterLabel='Hierarchy Territory' limit 1]; 
        // insert 10 Territories
        for (Integer i=0;i<10;i++) {
            Integer j = 1;
            if(i<9){
            j = i + 1;    
            }

            territories.add(new Territory2(Name = 'Cegid Test'+i,
            TerritoryCode__c ='344'+i,
            DeveloperName= 'Cegid_Test'+i,
            Territory2ModelId=territoryModel.Id,
            BU__c='105',                                      
            Channel__c='00'+j,
            Territory2TypeId=territoryType.Id));
        }        
        insert territories;
        
        // find the account just inserted. add objectTerritory2Association for each
       List<id> usersId = new List<id>();
        Integer j = 0;
        for (Account account : [select Id, Name, OwnerId from account]) {
            System.debug('TEST objectTerritory2Associations : account OwnerId :'+account.OwnerId);
            System.debug('TEST objectTerritory2Associations : territories Id :'+territories.get(j).Id);
            
            objectTerritory2Associations.add(new ObjectTerritory2Association(Territory2Id=territories.get(j).Id,
                                             ObjectId=account.Id,
                                             AssociationCause = 'Territory2Manual'));
            usersId.add(account.OwnerId);
            j++;
        }
        insert objectTerritory2Associations;
       
       
       for (Integer i=0;i<10;i++) {
           System.debug('TEST userTerritory2Associations : territories Id :'+territories.get(i).Id);
                userTerritory2Associations.add(new UserTerritory2Association(
                Territory2Id =territories.get(i).Id,
                UserId = usersId.get(i)
            ));
        }        

        Test.startTest();

        List<Database.SaveResult> result = Database.insert(userTerritory2Associations);
        Test.stopTest();
        
       }
     }

    @isTest static void testDelete() {
        System.runAs(adminUser){ 
        String CEGID_TELEMARKETING_PROFILE_NAME = 'Cegid Telemarketing';
        List<ObjectTerritory2Association> objectTerritory2Associations = new List<ObjectTerritory2Association>();
        List<UserTerritory2Association> userTerritory2Associations = new List<UserTerritory2Association>();
        List<Territory2> territories = new List<Territory2>();
        
        Territory2Model territoryModel = [select Id,Name From Territory2Model Where State <> 'Archived' limit 1];

        Territory2Type territoryType = [select Id,MasterLabel From Territory2Type where MasterLabel='Hierarchy Territory' limit 1]; 
        Profile  profile  = [SELECT Id FROM Profile WHERE Name = :CEGID_TELEMARKETING_PROFILE_NAME LIMIT 1 ];
        List<User> users = [Select Id From User where profileid = :profile.Id];
        // insert 10 Territories
        for (Integer i=0;i<10;i++) {
            Integer j = 1;
            if(i<9){
            j = i + 1;    
            }

            territories.add(new Territory2(Name = 'Cegid Test'+i,
            TerritoryCode__c ='344'+i,
            DeveloperName= 'Cegid_Test'+i,
            Territory2ModelId=territoryModel.Id,
            BU__c='105',                                      
            Channel__c='00'+j,
            Territory2TypeId=territoryType.Id));
        }
        System.debug('TEST territories :: '+territories.size());        
        insert territories;
        
        // find the account just inserted. add objectTerritory2Association for each
        Integer j = 0;
        for (Account account : [select Id, Name, OwnerId from account]) {
            objectTerritory2Associations.add(new ObjectTerritory2Association(Territory2Id=territories.get(j).Id,
                                             ObjectId=account.Id,
                                             AssociationCause = 'Territory2Manual'));
            j++;
        }
        System.debug('TEST objectTerritory2Associations :: '+objectTerritory2Associations.size());    
        insert objectTerritory2Associations;
        
        for (Integer i=0;i<10;i++) {
                userTerritory2Associations.add(new UserTerritory2Association(
                Territory2Id =territories.get(i).Id,
                UserId = users.get(i).Id
            ));
        }
		insert userTerritory2Associations;            
        System.debug('userTerritory2Associations Size :: '+userTerritory2Associations.size());    
            
                      
        Test.startTest();

            
        List<UserTerritory2Association> listUserTerr = [select Id from UserTerritory2Association where Territory2.Territory2Model.State <> 'Archived' and User.ProfileId <> :profile.Id];
                              
		System.debug('listUserTerr size :: '+listUserTerr.get(0).Id);
        Database.DeleteResult result = Database.delete(listUserTerr.get(0));
        Test.stopTest();

       }
     }
}