unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Competitors__c.field-meta.xml
<CustomField>
    <fullName>Competitors__c</fullName>
    <label>Competitors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitor</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Forecast_Category_EDIT__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Category_EDIT__c</fullName>
    <description>Duplicate field to allow picklist dependency</description>
    <label>Forecast Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upside</fullName>
                <default>true</default>
                <label>Upside</label>
            </value>
            <value>
                <fullName>Probable</fullName>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/Saas_Amount__c.field-meta.xml
<CustomField>
    <fullName>Saas_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Saas Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/globalValueSets/Competitor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>15FIVE</fullName>
    </customValue>
    <customValue>
        <fullName>360L</fullName>
    </customValue>
    <customValue>
        <fullName>365 TALENTS</fullName>
    </customValue>
    <customValue>
        <fullName>AAREON</fullName>
    </customValue>
    <customValue>
        <fullName>ACCOUNTIFY</fullName>
    </customValue>
    <customValue>
        <fullName>ACCOUNTOR</fullName>
    </customValue>
    <customValue>
        <fullName>ACD GROUPE</fullName>
    </customValue>
    <customValue>
        <fullName>ADEQUASYS</fullName>
    </customValue>
    <customValue>
        <fullName>ADP</fullName>
    </customValue>
    <customValue>
        <fullName>AGIRIS</fullName>
    </customValue>
    <customValue>
        <fullName>ALPHA3I</fullName>
    </customValue>
    <customValue>
        <fullName>ALTAYS</fullName>
    </customValue>
    <customValue>
        <fullName>AMELKIS</fullName>
    </customValue>
    <customValue>
        <fullName>Apisoft</fullName>
    </customValue>
    <customValue>
        <fullName>Apologic</fullName>
    </customValue>
    <customValue>
        <fullName>APTOS</fullName>
    </customValue>
    <customValue>
        <fullName>ARAGON</fullName>
    </customValue>
    <customValue>
        <fullName>ARC LOGICIELS</fullName>
    </customValue>
    <customValue>
        <fullName>ARTICULATE</fullName>
    </customValue>
    <customValue>
        <fullName>AUTEL/BEST STORE</fullName>
    </customValue>
    <customValue>
        <fullName>AVATURE</fullName>
    </customValue>
    <customValue>
        <fullName>AVELON RMS</fullName>
    </customValue>
    <customValue>
        <fullName>AXWAY</fullName>
    </customValue>
    <customValue>
        <fullName>BAISON</fullName>
    </customValue>
    <customValue>
        <fullName>BAMBOO HR</fullName>
    </customValue>
    <customValue>
        <fullName>BANQUE POPULAIRE</fullName>
    </customValue>
    <customValue>
        <fullName>BEARINGPOINT</fullName>
    </customValue>
    <customValue>
        <fullName>BEEBOLE</fullName>
    </customValue>
    <customValue>
        <fullName>BERGER LEVRAULT</fullName>
    </customValue>
    <customValue>
        <fullName>BIZNEO</fullName>
    </customValue>
    <masterLabel>Competitor</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/TH_OpportunityLineItem_TEST.cls
@isTest
public class TH_OpportunityLineItem_TEST {
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator(); 

    @testSetup static void setup() {
        System.runAs(adminUser) {       
            
            insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
            
            
            
            Test.startTest();
            List<Account> accs = new List<Account>();
            for(Integer i = 0 ; i < 5 ; i++) {
                Account acc = new Account();
                acc.Name= 'Test Account AZA2 '+i;
                acc.National_ID_Exception__c ='Empty on loading';
                acc.BillingPostalCode ='75009';
                acc.BillingCountry ='France';
                acc.BillingCity ='Paris';
                acc.No_of_Employees_Group__c = 15;
                acc.No_of_Stores__c = 7;
                acc.NumberOfEmployees = 14;

                accs.add(acc);
            }
                        

            insert accs;
                  
            Opportunity oppToInsert = new Opportunity();
            oppToInsert.Name='test azas2';
            oppToInsert.AccountId=accs[0].Id;
            oppToInsert.StageName='G - MQL';
            oppToInsert.Sales_Purpose__c='121';
            oppToInsert.CurrencyIsoCode='EUR';
            oppToInsert.Forecast_Category_EDIT__c='Omitted';
            oppToInsert.CloseDate=date.today();
            oppToInsert.LeadSource='Sales Prospecting';
            oppToInsert.Competitors__c = 'ADP';  
            
            insert oppToInsert;

            Product2 pdct = new Product2(Name='testProduct');

            insert pdct;

            PricebookEntry pbe = new PricebookEntry(IsActive= true, Product2Id = pdct.Id, Pricebook2Id = Test.getStandardPricebookId(), UnitPrice = 400);

            insert pbe;
        }
    }

    @isTest static void computeSaasAmountTest() {

        List<OpportunityLineItem> oppLines = new List<OpportunityLineItem>();
        Integer nbLigne = 10;
        for(Integer i = 0; i < nbLigne; i++) {
            oppLines.add(new OpportunityLineItem(Saas_Amount__c = 0));
        }

        new TH_OpportunityLineItem().computeSaasAmount(oppLines);
        

    }
    @isTest static void beforeInsertTEST() {
        List<Opportunity> opps = [SELECT Id FROM Opportunity];
        List<PricebookEntry> pbes = [SELECT Id FROM PricebookEntry];

        List<OpportunityLineItem> oppLines = new List<OpportunityLineItem>();
        Integer nbLigne = 100;
        for(Integer i = 0; i < nbLigne; i++) {
            oppLines.add(new OpportunityLineItem(OpportunityId = opps[0].Id, Quantity=3, TotalPrice = 500,  PricebookEntryId= pbes[0].Id));
        }


        Test.startTest();    
        List<Database.SaveResult> results = Database.insert(oppLines, false);
        Test.stopTest();

        System.debug(results);

    }

    @isTest static void beforeUpdateTEST() {
        List<Opportunity> opps = [SELECT Id FROM Opportunity];
        List<PricebookEntry> pbes = [SELECT Id FROM PricebookEntry];

        List<OpportunityLineItem> oppLines = new List<OpportunityLineItem>();
        Integer nbLigne = 100;
        for(Integer i = 0; i < nbLigne; i++) {
            
            oppLines.add(new OpportunityLineItem(OpportunityId = opps[0].Id, Quantity=3, TotalPrice = 500, PricebookEntryId= pbes[0].Id));
        }

        insert oppLines;


        for(OpportunityLineItem oppLine : oppLines) {
            oppLine.Quantity = 5;
        }

        Test.startTest();    
        List<Database.SaveResult> results = Database.update(oppLines, false);
        Test.stopTest();

        System.debug(results);

    }
    
}