unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <formula>CASE (TEXT(Opportunity__r.Expertise__c), 
						"110","CPA",
						"350","ERP High",
						"340","ERP Middle",
						"320","HCM",
						"200","Retail",
						"100","SMB",
						"310","TAX",
						""
						)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Expertise</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Opportunity__r.Product_Line__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Product Line</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <defaultValue>TODAY() + 7</defaultValue>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Forecast_Category_EDIT__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Category_EDIT__c</fullName>
    <description>Duplicate field to allow picklist dependency</description>
    <label>Forecast Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upside</fullName>
                <default>true</default>
                <label>Upside</label>
            </value>
            <value>
                <fullName>Probable</fullName>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Expertise__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Line__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/SM010_Case_TEST.cls
@isTest
public class SM010_Case_TEST {
/**
 * @File Name          : SM010_Case_TEST
 * @Description        : Update Opportunity Team Member if a user is the owner of the case.
 * @Author             : SRA   
 * @Group              : Comforth-Karoo
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * ---    -----------       -------           ------------------------ 
 * 1.0    01/12/2020         SRA              Initial Version
 * ---    -----------       -------           ------------------------ 
**/
    
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static User adminUser2 = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    
    @testSetup static void setup(){
        System.runAs(adminUser){       
            
            insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
                
            Test.startTest();
            List<Account> listAcc = new List<Account>();
            List<Contact> listCon = new List<Contact>();
            List<Opportunity> listOppConverted = new List<Opportunity>();
            List<Opportunity> listOppAutoCreate = new List<Opportunity>();
            List<ObjectTerritory2Association> listOTA = new List<ObjectTerritory2Association>();
            List<Territory2> listTerritory = [Select Id , Expertise__c from Territory2 where  Expertise__c='200']; 
            
            listAcc.add(new UTIL_TestFactory.AccountFactory().createAccount());
            listAcc[0].National_ID_Exception__c ='Empty on loading';
            listAcc[0].BillingPostalCode ='75008';
            listAcc[0].BillingCountry ='France';
            listAcc[0].BillingCity ='Paris';
            listAcc[0].No_of_Employees_Group__c =12;
            listAcc[0].No_of_Stores__c =2;
            listAcc[0].NumberOfEmployees =12;
            insert listAcc;
            
            Opportunity opp = New Opportunity();
            opp.Name='test';
            opp.AccountId=listAcc[0].Id;
            opp.StageName='G - MQL';
            opp.Sales_Purpose__c='121';
            opp.CurrencyIsoCode='EUR';
            opp.Forecast_Category_EDIT__c='Omitted';
            opp.CloseDate=date.today();
            opp.LeadSource='Sales Prospecting';
            
            insert opp;
            
            Case case1 = new Case();
            case1.Subject='Test';
            case1.Description='test';
            case1.Type= 'Demonstration';
            case1.ClosedDate=date.TODAY();
            case1.Scheduled_Date__c=date.TODAY();
            //case1.Expertise__c='ERP High';
            //case1.Product_Line__c='021';
            case1.Sales_Purpose__c='121';
            case1.Opportunity__c=opp.Id;
            
            insert case1;
            
            Test.stopTest();
        }
    }
    
    static testMethod void testPackage() {
        
        insert adminUser2;
        
        List<Case> listCase = [SELECT id,OwnerId from Case];
        system.debug('listCase[0].OwnerId'+listCase[0].OwnerId);
        system.debug('adminUser2.Id'+adminUser2.Id);
        listCase[0].OwnerId=adminUser2.Id;
        
        System.runAs(adminUser) {
            Test.startTest();
            Update listCase;
            Test.stopTest();
        }
    }
}