unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/MRR__c.field-meta.xml
<CustomField>
    <fullName>MRR__c</fullName>
    <description>Monthly Recurring Revenue</description>
    <label>MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Function__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/Recommendation_score__c.object-meta.xml
<CustomObject>
    <description>Cet objet permet de récupérer les information NPS des contacts depuis Qualtrics.</description>
    <label>Recommendation score</label>
    <nameField>
        <displayFormat>Survey- {000000000}</displayFormat>
        <label>Recommendation score name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Recommendation_score__c/fields/Asked_to_be_contacted_back__c.field-meta.xml
<CustomField>
    <fullName>Asked_to_be_contacted_back__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Question only asked if recommendation score ≤ 6. Customer confirms if he/she wants to be contacted back or not</inlineHelpText>
    <label>Asked to be contacted back</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Recommandations_scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/fields/Recommendation_score__c.field-meta.xml
<CustomField>
    <fullName>Recommendation_score__c</fullName>
    <inlineHelpText>Customer's answer to the question : would you like to recommend Cegid (scale from 0 to 10)</inlineHelpText>
    <label>Recommendation score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/fields/Team_in_charge_of_contacting_back__c.field-meta.xml
<CustomField>
    <fullName>Team_in_charge_of_contacting_back__c</fullName>
    <label>Team in charge of contacting back</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>No call back required</fullName>
            </value>
            <value>
                <fullName>CSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>CASE( 
    TEXT(Agency__c),
'112', 'CPA',
'113', 'CPA',
'114', 'CPA',
'115', 'CPA',
'217', 'RETAIL',
'290', 'RETAIL',
'320', 'CPA',
'340', 'CPA',
'392', 'FINANCE',
'393', 'FINANCE',
'394', 'FINANCE',
'395', 'FINANCE',
'396', 'FINANCE',
'397', 'FINANCE',
'410', 'CPA',
'411', 'CPA',
'412', 'CPA',
'470', 'CPA',
'530', 'Other',
'549', 'RETAIL',
'550', 'RETAIL',
'552', 'RETAIL',
'555', 'RETAIL',
'556', 'RETAIL',
'557', 'RETAIL',
'560', 'RETAIL',
'563', 'HCM',
'583', 'RETAIL',
'585', 'HCM',
'714', 'HCM',
'715', 'HCM',
'800', 'FINANCE',
'803', 'SB',
'804', 'SB',
'805', 'FINANCE',
'808', 'FINANCE',
'809', 'RETAIL',
'810', 'FINANCE',
'811', 'FINANCE',
'812', 'HCM',
'813', 'HCM',
'814', 'FINANCE',
'815', 'FINANCE',
'816', 'FINANCE',
'818', 'CPA',
'819', 'FINANCE',
'822', 'FINANCE',
'823', 'HCM',
'824', 'HCM',
'825', 'HCM',
'826', 'HCM',
'829', 'CPA',
'830', 'CPA',
'831', 'SB',
'832', 'HCM',
'834', 'HCM',
'835', 'HCM',
'836', 'HCM',
'837', 'HCM',
'838', 'HCM',
'839', 'HCM',
'841', 'HCM',
'842', 'HCM',
'840', 'HCM',
'843', 'OTHER',
'844', 'RETAIL',
'845', 'FINANCE',
'846', 'FINANCE',
'847', 'FINANCE',
'849', 'FINANCE',
'850', 'FINANCE',
'852', 'FINANCE',
'853', 'FINANCE',
'854', 'FINANCE',
'855', 'HCM',
'856', 'SB',
'857', 'HCM',
'858', 'HCM',
'Not Assigned'
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Function.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting recoverings contact</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>After-Sales Service Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business app Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business Development Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Career Planning Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Directors</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Management</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Supervisory Board</fullName>
    </customValue>
    <customValue>
        <fullName>Chartered accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Accounting Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Digital Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Information Officer</fullName>
    </customValue>
    <customValue>
        <fullName>IT Dir.</fullName>
    </customValue>
    <masterLabel>Function</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finance and accounting</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Affairs</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and communication</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Representative</fullName>
    </customValue>
    <customValue>
        <fullName>Transversal</fullName>
    </customValue>
    <customValue>
        <fullName>NR</fullName>
        <isActive>false</isActive>
        <label>NR</label>
    </customValue>
    <masterLabel>Service</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_RecommendationScore_Test.cls
@isTest
public class TH_RecommendationScore_Test {

    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();        
    static User salesUser = new UTIL_TestFactory.UserFactory().createUserCegidSales();
    static User salesUser2 = new UTIL_TestFactory.UserFactory().createUserCegidSales();
    static User salesUser3 = new UTIL_TestFactory.UserFactory().createUserCegidSales();

    @isTest static void generateTaskTest() {
        
        Id TERR_TYPE = [SELECT Id FROM Territory2Type Limit 1].Id;
        Id TERR_MODEL = [SELECT Id FROM Territory2Model][1].Id;
        
        //BU Finance test
        Account acc1_Finance = new Account();
        acc1_Finance.Name= 'Test Account 1 CSM CAP'+System.now().millisecond();
        acc1_Finance.National_ID_Exception__c ='Empty on loading';
        acc1_Finance.BillingPostalCode ='75009';
        acc1_Finance.BillingCountry ='France';
        acc1_Finance.BillingCity ='Paris';
        acc1_Finance.No_of_Employees_Group__c = 15;
        acc1_Finance.No_of_Stores__c = 7;
        acc1_Finance.NumberOfEmployees = 14;
                        
        insert acc1_Finance;

		Contact c1_Finance = new Contact(LastName = 'LName'+System.now().millisecond(),
                                         FirstName = 'FName'+System.now().millisecond(),
                                         Salutation='Mr.',
                                         email = 'lname'+System.now().millisecond()+'@email.com',
                                         AccountId = acc1_Finance.Id,
                                         Service__c = 'IT',
                                         Function__c = 'IT Dir.');

        insert c1_Finance;
        //
        
        //BU Other test
        Account acc2 = new Account();
        acc2.Name= 'Test Account 2 CSM CAP'+System.now().millisecond();
        acc2.National_ID_Exception__c ='Empty on loading';
        acc2.BillingPostalCode ='69100';
        acc2.BillingCountry ='France';
        acc2.BillingCity ='Lyon';
        acc2.No_of_Employees_Group__c = 24;
        acc2.No_of_Stores__c = 6;
        acc2.NumberOfEmployees = 44;
                        
        insert acc2;

		Contact c2 = new Contact(LastName = 'LName'+System.now().millisecond(),
                                 FirstName = 'FName'+System.now().millisecond(),
                                 Salutation='Mr.',
                                 email = 'lname'+System.now().millisecond()+'@email.com',
                                 AccountId = acc2.Id,
                                 Service__c = 'IT',
                                 Function__c = 'IT Dir.');

        insert c2;
        //
        
        //Create Terrs and Account Expertise
        List<Account_Expertise__c> accExper = new List<Account_Expertise__c>();
        
        accExper.add(new Account_Expertise__c(Account__c=acc1_Finance.Id, MRR__c = 2000, Expertise__c='350'));
        accExper.add(new Account_Expertise__c(Account__c=acc1_Finance.Id, MRR__c = 3400, Expertise__c='360'));
        accExper.add(new Account_Expertise__c(Account__c=acc2.Id, MRR__c = 3434, Expertise__c='380'));
        
        insert accExper;
        
        System.runAs(adminUser) {
            
            insert salesUser;
            insert salesUser2;
            insert salesUser3;
        
            List<Territory2> accTerrs = new List<Territory2>();
            
            accTerrs.add(new Territory2(DeveloperName='CSM1_TEST', BU__c = '316', Expertise__c = '360', Name='CSM1_TEST', Territory2ModelId=TERR_MODEL, Territory2TypeId=TERR_Type));
            accTerrs.add(new Territory2(DeveloperName='CSM2_TEST', BU__c = '319', Expertise__c = '380', Name='CSM2_TEST', Territory2ModelId=TERR_MODEL, Territory2TypeId=TERR_Type));
            accTerrs.add(new Territory2(DeveloperName='CSM3_TEST', BU__c = '316', Expertise__c = '350', Name='CSM3_TEST', Territory2ModelId=TERR_MODEL, Territory2TypeId=TERR_Type));
            
            insert accTerrs;
        
            List<ObjectTerritory2Association> objTerrAssos = new List<ObjectTerritory2Association>();
            
            objTerrAssos.add(new ObjectTerritory2Association(Territory2Id = accTerrs[0].Id, ObjectId = acc1_Finance.Id, AssociationCause='Territory2Manual'));
            objTerrAssos.add(new ObjectTerritory2Association(Territory2Id = accTerrs[2].Id, ObjectId = acc1_Finance.Id, AssociationCause='Territory2Manual'));
            objTerrAssos.add(new ObjectTerritory2Association(Territory2Id = accTerrs[1].Id, ObjectId = acc2.Id, AssociationCause='Territory2Manual'));
            
            insert objTerrAssos;
            
            List<UserTerritory2Association> userForAccMRR = new List<UserTerritory2Association>();
            
            userForAccMRR.add(new UserTerritory2Association(Territory2Id = accTerrs[0].Id, UserId = salesUser.Id, RoleInTerritory2='CSM'));
            userForAccMRR.add(new UserTerritory2Association(Territory2Id = accTerrs[0].Id, UserId = salesUser3.Id, RoleInTerritory2='CSM'));
            userForAccMRR.add(new UserTerritory2Association(Territory2Id = accTerrs[1].Id, UserId = salesUser2.Id, RoleInTerritory2='CSM'));
            
            insert userForAccMRR;
            
        }
        //

        List<Recommendation_score__c> rcScores = new List<Recommendation_score__c>();

        rcScores.add(new Recommendation_score__c(Contact__c = c1_Finance.Id,
                                                 Asked_to_be_contacted_back__c = true,
                                                 Recommendation_score__c = 8,
                                                 Team_in_charge_of_contacting_back__c = 'CSM'));
        
        rcScores.add(new Recommendation_score__c(Contact__c = c2.Id,
                                                 Asked_to_be_contacted_back__c = true,
                                                 Recommendation_score__c = 8,
                                                 Team_in_charge_of_contacting_back__c = 'CSM'));
        
        insert rcScores;
        
        List<Recommendation_score__c> rcScores2Update = new List<Recommendation_score__c>();
        rcScores = [SELECT Contact__c, 
                    Asked_to_be_contacted_back__c,
                    Recommendation_score__c,
                    Team_in_charge_of_contacting_back__c 
                    FROM Recommendation_score__c];         
        
        for(Recommendation_score__c rcScore : rcScores) {
            rcScore.Recommendation_score__c = 2; 
            rcScores2Update.add(rcScore);
        }

        Test.startTest();
        	List<Database.SaveResult> results = Database.update(rcScores2Update, false);
        Test.stopTest();

    }

}