unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Participant__c/fields/CartItemId__c.field-meta.xml
<CustomField>
    <fullName>CartItemId__c</fullName>
    <label>CartItemId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Civilite__c.field-meta.xml
<CustomField>
    <fullName>Civilite__c</fullName>
    <label>Civilité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>Prénom</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <default>true</default>
        <label>Direct</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Mixed</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Partner</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Influencing Organization</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/B2B_AddParticipants_TEST.cls
/***
* @author      : Trilochnah - Comforth Karoo
* @date		   : 25/10/21
* @description : Test class for B2B_AddParticipants
***/

@isTest
public class B2B_AddParticipants_TEST {
    //private static User adminUser =  new TestDataFactory.UserFactory().createRunningUserAdministrator();
    private static User adminUser =  new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    static User testUser;
    static WebCart webcart1;
    static Account acc1;
    static Participant__c participant1;
    static CartItem cartItem1;
    static CartDeliveryGroup cartDeliveryGroup1;
    static BypassTrigger__c bypasstrigger;
    static WebStore webStore1;
    
    static{       
        System.runAs(adminUser){
            //Insert BypassTrigger__c
            bypasstrigger = new BypassTrigger__c(
                Activatetrigger__c=true,
                SetupOwnerId=Userinfo.getOrganizationId()
            );
            insert bypasstrigger;
            
            system.debug('##bypasstrigger ' + bypasstrigger);
            
            // Insert Account
            acc1 = new Account(
                Name = 'Acc1',
                Type__c='001',
                BillingStreet = 'Test',
                BillingCity = 'Test',
                BillingCountry = 'Italy',
                BillingPostalCode = '12345',
                National_ID_Exception__c='Creation In progress'
                
            );
            insert acc1;
            
            //Insert webstore
            webStore1 = new WebStore(
                Name='testwebstore'
                
            );
            insert webStore1;
            
            // Insert WebCart
            webcart1 = new WebCart(
                Name = 'Cart1',
                Status='Closed',
                AccountId=acc1.id,
                WebStoreId= webStore1.Id         
            );
            insert webcart1;  
            
            // Insert cartDeliveryGroup
            cartDeliveryGroup1 = new CartDeliveryGroup(
                Name='Default Delivery',
                CartId=webcart1.Id
            );
            insert cartDeliveryGroup1;
            
            //Insert cart item
            CartItem cartItem1 = new CartItem(
                CartId=webcart1.Id, 
                Sku='SKU_Test1', 
                Quantity=3.0,
                SalesPrice=400,
                Type='Product', 
                Name='TestProduct', 
                CartDeliveryGroupId=cartDeliveryGroup1.Id
            );
            insert cartItem1;
            
            //Insert participants
            participant1 = new Participant__c(
                Name='testP1',
                Civilite__c ='Mr',
                Prenom__c = 'Test',
                EmailAddress__c='test1@test.test', 
                CartItemId__c=cartItem1.Id          
            );
            insert participant1;
            
            
        }
    }
    /***
    * @author      : Trilochnah - Comforth Karoo
    * @date		   : 25/10/21
    * @description : Updating Status to 'Active'
    ***/
    static testMethod void testResetCartStatus() {
        
        System.runAs(adminUser){
            
            webcart1.Status='Active';
            
            Test.startTest();
            B2B_AddParticipants.resetCartStatus(webcart1.id);                        
            Test.stopTest();
            
            WebCart wc = [SELECT Id,Name,Status FROM WebCart WHERE Id =:webcart1.Id];
            
            System.assertEquals('Active', wc.Status, 'Asserting that WebCart Status is not active');
            
        }
    }
    /***
    * @author      : Trilochnah - Comforth Karoo
    * @date		   : 28/10/21
    * @description : Updating Status to 'Active'
    ***/
    static testMethod void testGetParticipantRow() {
        
        System.runAs(adminUser){
            
            webcart1.Status='Active';
            
            Test.startTest();
            B2B_AddParticipants.getParticipantRow(webcart1.Id);                       
            Test.stopTest();
            
            WebCart wc = [SELECT Id,Name,Status FROM WebCart WHERE Id =:webcart1.Id];
            
            System.assertEquals('Active', wc.Status, 'Asserting that WebCart Status is not active');
            
        }
    }
    
    /***
    * @author      : Trilochnah - Comforth Karoo
    * @date		   : 28/10/21
    * @description :
    ***/
    static testMethod void testDeleteAllParticipant() {
        
        System.runAs(adminUser){
            
            List<Id> listCartIds = new List<Id>();
            
            CartItem ct = [SELECT Id FROM CartItem];
            
            listCartIds.add(ct.Id);
            
            
            Test.startTest();
            Boolean b = B2B_AddParticipants.deleteAllParticipant(listCartIds);
            Test.stopTest();
            
            System.assertEquals(true,b, 'Asserting that list of participant is less than zero');
            
        }
    }
    
    /***
    * @author      : Trilochnah - Comforth Karoo
    * @date		   : 28/10/21
    * @description :
    ***/
    static testMethod void testDeleteParticipantByIds() {
        
        System.runAs(adminUser){
            
            List<string> listParticipantIds = new List<string>();
            
            Participant__c pt = [SELECT Id FROM Participant__c LIMIT 1];
            
            CartItem ct=[SELECT Id FROM CartItem LIMIT 1 ];
            
            listParticipantIds.add(ct.Id + '-' + pt.Id);
            
            system.debug('##listP  ' + listParticipantIds );
            
            Test.startTest();
            B2B_AddParticipants.deleteParticipantByIds(listParticipantIds,'525632222255523', '525632222255523', webcart1.id);
            Test.stopTest();
            
           // System.assertEquals();
            
        }
    }
}