unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Function__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>Used to calculate the Buynig persona used to target Campaigns</description>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lead_s_Chosen_Solution__c.field-meta.xml
<CustomField>
    <fullName>Lead_s_Chosen_Solution__c</fullName>
    <label>Lead's Chosen Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chosen_Solution</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID Exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>Controlilng field to select Fonction</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Competitors__c.field-meta.xml
<CustomField>
    <fullName>Competitors__c</fullName>
    <label>Competitors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitor</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Forecast_Category_EDIT__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Category_EDIT__c</fullName>
    <description>Duplicate field to allow picklist dependency</description>
    <label>Forecast Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upside</fullName>
                <default>true</default>
                <label>Upside</label>
            </value>
            <value>
                <fullName>Probable</fullName>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <description>la raison de la perte de l'opportunité</description>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Competition choosen</fullName>
            </value>
            <value>
                <fullName>Project postponed</fullName>
            </value>
            <value>
                <fullName>Legal Terms</fullName>
            </value>
            <value>
                <fullName>Financial Terms</fullName>
            </value>
            <value>
                <fullName>Features</fullName>
            </value>
            <value>
                <fullName>Lost of project</fullName>
            </value>
            <value>
                <fullName>Group Centralisation</fullName>
            </value>
            <value>
                <fullName>Change of governance</fullName>
            </value>
            <value>
                <fullName>Economic context</fullName>
            </value>
            <value>
                <fullName>No budget</fullName>
            </value>
            <value>
                <fullName>Client budget not adapted</fullName>
            </value>
            <value>
                <fullName>Product features</fullName>
            </value>
            <value>
                <fullName>Duplicate opportunity</fullName>
            </value>
            <value>
                <fullName>International scope</fullName>
            </value>
            <value>
                <fullName>Customer financial situation</fullName>
            </value>
            <value>
                <fullName>Other provider choosen</fullName>
            </value>
            <value>
                <fullName>Deployment time</fullName>
            </value>
            <value>
                <fullName>UX product ergonomic</fullName>
            </value>
            <value>
                <fullName>Price too high</fullName>
            </value>
            <value>
                <fullName>Reputation</fullName>
            </value>
            <value>
                <fullName>Services offered</fullName>
            </value>
            <value>
                <fullName>Incomplete data</fullName>
            </value>
            <value>
                <fullName>Cannot be reached</fullName>
            </value>
            <value>
                <fullName>Wrong coordinates</fullName>
            </value>
            <value>
                <fullName>Non commercial opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/User/fields/BypassPB__c.field-meta.xml
<CustomField>
    <fullName>BypassPB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass PB</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass VR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/BypassWF__c.field-meta.xml
<CustomField>
    <fullName>BypassWF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass WF</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Chosen_Solution.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing Industry</fullName>
    </customValue>
    <customValue>
        <fullName>TPE &amp; Association</fullName>
    </customValue>
    <masterLabel>Chosen Solution</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Competitor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>15FIVE</fullName>
    </customValue>
    <customValue>
        <fullName>360L</fullName>
    </customValue>
    <customValue>
        <fullName>365 TALENTS</fullName>
    </customValue>
    <customValue>
        <fullName>AAREON</fullName>
    </customValue>
    <customValue>
        <fullName>ACCOUNTIFY</fullName>
    </customValue>
    <customValue>
        <fullName>ACCOUNTOR</fullName>
    </customValue>
    <customValue>
        <fullName>ACD GROUPE</fullName>
    </customValue>
    <customValue>
        <fullName>ADEQUASYS</fullName>
    </customValue>
    <customValue>
        <fullName>ADP</fullName>
    </customValue>
    <customValue>
        <fullName>AGIRIS</fullName>
    </customValue>
    <customValue>
        <fullName>ALPHA3I</fullName>
    </customValue>
    <customValue>
        <fullName>ALTAYS</fullName>
    </customValue>
    <customValue>
        <fullName>AMELKIS</fullName>
    </customValue>
    <customValue>
        <fullName>Apisoft</fullName>
    </customValue>
    <customValue>
        <fullName>Apologic</fullName>
    </customValue>
    <customValue>
        <fullName>APTOS</fullName>
    </customValue>
    <customValue>
        <fullName>ARAGON</fullName>
    </customValue>
    <customValue>
        <fullName>ARC LOGICIELS</fullName>
    </customValue>
    <customValue>
        <fullName>ARTICULATE</fullName>
    </customValue>
    <customValue>
        <fullName>AUTEL/BEST STORE</fullName>
    </customValue>
    <customValue>
        <fullName>AVATURE</fullName>
    </customValue>
    <customValue>
        <fullName>AVELON RMS</fullName>
    </customValue>
    <customValue>
        <fullName>AXWAY</fullName>
    </customValue>
    <customValue>
        <fullName>BAISON</fullName>
    </customValue>
    <customValue>
        <fullName>BAMBOO HR</fullName>
    </customValue>
    <customValue>
        <fullName>BANQUE POPULAIRE</fullName>
    </customValue>
    <customValue>
        <fullName>BEARINGPOINT</fullName>
    </customValue>
    <customValue>
        <fullName>BEEBOLE</fullName>
    </customValue>
    <customValue>
        <fullName>BERGER LEVRAULT</fullName>
    </customValue>
    <customValue>
        <fullName>BIZNEO</fullName>
    </customValue>
    <masterLabel>Competitor</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Function.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting recoverings contact</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>After-Sales Service Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business app Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business Development Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Career Planning Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Directors</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Management</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Supervisory Board</fullName>
    </customValue>
    <customValue>
        <fullName>Chartered accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Accounting Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Digital Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Information Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Personnel Dir.</fullName>
    </customValue>
    <masterLabel>Function</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finance and accounting</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Affairs</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and communication</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Representative</fullName>
    </customValue>
    <customValue>
        <fullName>Transversal</fullName>
    </customValue>
    <customValue>
        <fullName>NR</fullName>
        <isActive>false</isActive>
        <label>NR</label>
    </customValue>
    <masterLabel>Service</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_FutureMethods_TEST.cls
@isTest
public class TH_FutureMethods_TEST {
    
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();

    private static String CEGID_TELEMARKETING_PROFILE_NAME = 'Cegid Telemarketing';

    @testSetup static void setup(){
        System.runAs(adminUser){       
            
            insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
                
   
            Account acc = new Account();
            acc.Name= 'Test Account AZA2';
            acc.National_ID_Exception__c ='Empty on loading';
            acc.BillingPostalCode ='75009';
            acc.BillingCountry ='France';
            acc.BillingCity ='Paris';
            acc.No_of_Employees_Group__c =15;
            acc.No_of_Stores__c =7;
            acc.NumberOfEmployees =14;            

            insert acc;
                  
            Opportunity oppToInsert = New Opportunity();
            oppToInsert.Name='test azas2';
            oppToInsert.AccountId=acc.Id;
            oppToInsert.StageName='G - MQL';
            oppToInsert.Sales_Purpose__c='121';
            oppToInsert.CurrencyIsoCode='EUR';
            oppToInsert.Forecast_Category_EDIT__c='Omitted';
            oppToInsert.CloseDate=date.today();
            oppToInsert.LeadSource='Sales Prospecting';
            oppToInsert.Competitors__c = 'ADP';  
            
            insert oppToInsert;
               
            ////// 
            List<Account> accounts = new List<Account>();
            List<User> users = new List<User>();        
            
            // insert 100 users
            for (Integer i=0;i<10;i++) {
                users.add(new User(
                    alias = 'Test',
                    email = i+'test.magellan-admin@example.com',
                    emailencodingkey = 'UTF-8',
                    BypassPB__c = true,
                    BypassVR__c = true,
                    BypassWF__c = true,
                    lastname = 'testAdmin'+i,
                    languagelocalekey = 'fr',
                    localesidkey = 'fr_FR',
                    profileid = [
                        SELECT Id
                        FROM Profile
                        WHERE Name = :CEGID_TELEMARKETING_PROFILE_NAME
                        LIMIT 1
                    ][0].Id,
                    timezonesidkey = 'Europe/Paris',
                    username = 'test.magellan-admin1' + System.now().millisecond()
                    + UserInfo.getOrganizationId() + '@example.com'
                ));
            }
            insert users;   
            
            // insert 100 accounts
            for (Integer i=0;i<10;i++) {
                accounts.add(new Account(	
                Name= 'Account userTerritory2Associations AZA'+i,
                National_ID_Exception__c ='Empty on loading',
                BillingPostalCode ='75009',
                BillingCountry ='France',
                BillingCity ='Paris',
                No_of_Employees_Group__c =15,
                No_of_Stores__c =7,
                NumberOfEmployees =14,
                //National_ID__c='1012151415124'+i,
                OwnerId = users.get(i).Id
                                       ));
                
                
            }
            insert accounts;          
        }
    }

    static testMethod void testUpdateOppyAndAccount() {
        System.runAs(adminUser){  
            Opportunity opp = [select id,Name from Opportunity where Name LIKE 'test azas2'];        
            System.debug('Update Opp ');
            opp.StageName = 'Closed Lost';
            opp.Loss_Reason__c = 'Competition choosen';            
            opp.Competitors__c = 'ADP;APTOS';
              
            Account acc = [select id,Name from Account where Name LIKE 'Test Account AZA2'];  
            acc.Name = 'Test Account AZA2 Update'; 
            
            // Perform test
            Test.startTest();            
            Database.SaveResult result = Database.update(opp, false);
            Database.SaveResult resultAcc = Database.update(acc, false);
            Test.stopTest();
            System.assert(result.isSuccess());
        }               
    }


     static testMethod void testCreateLeadWithTelemarketingProfile() {
        System.runAs(createUserTelemarketing()){  
            
            List<Account> accInserted = [Select Id From Account Where Name Like 'Test Account AZA2'];

            Account acc = new Account();
            if(accInserted == null || accInserted.size() == 0){

                acc.Name= 'Test Account AZA2';
                acc.National_ID_Exception__c ='Empty on loading';
                acc.BillingPostalCode ='75009';
                acc.BillingCountry ='France';
                acc.BillingCity ='Paris';
                acc.No_of_Employees_Group__c =15;
                acc.No_of_Stores__c =7;
                acc.NumberOfEmployees =14;            
                acc.Type ='Partner';    

                insert acc;
            }else{
                acc = accInserted[0];
            }

            RecordType recordTypeLeadTelemarketing = [Select Id From RecordType Where Name = 'Lead Telemarketing'];                          
            List<Lead> existedLead = [Select Status, Email From Lead Where Status <> 'Assigned' AND Status <> 'In Progress' AND Status <> 'Qualified'];
            
            Lead l = new Lead();
            if(existedLead == null || existedLead.size() == 0){                           
                l.FirstName='Test1111';
                l.LastName='Test1111';
                l.Service__c='HR';
                l.Function__c='Personnel Dir.';
                l.Status='Assigned';
                l.Company='test';
                l.Email='email@hello.com';
                l.RecordTypeId = recordTypeLeadTelemarketing.Id;
                l.Lead_s_Chosen_Solution__c = 'CPA';
                l.ImpartnerPRM__IsDealRegistration__c = false;
                l.ImpartnerPRM__PartnerAccount__c = acc.Id;
                
                Insert l;    
                
                Lead leadToUpdate = [Select Status From Lead Where Id=:l.Id];
                leadToUpdate.Status = 'New';
                update leadToUpdate;
            }

            Lead lead = new Lead();
            lead.FirstName='Test1112';
            lead.LastName='Test1112';
            lead.Service__c='HR';
            lead.Function__c='Personnel Dir.';
            lead.Status='Assigned';
            lead.Company='test 2';
            if(existedLead == null || existedLead.size() == 0){ 
            lead.Email='email@hello.com';
            }
            else{
            lead.Email=existedLead[0].Email;    
            }            
            lead.RecordTypeId = recordTypeLeadTelemarketing.Id;
            lead.Lead_s_Chosen_Solution__c = 'CPA';
            lead.ImpartnerPRM__IsDealRegistration__c = false;
            lead.ImpartnerPRM__PartnerAccount__c = acc.Id;            
            
            // Perform test
            Test.startTest();
            
            Database.SaveResult result = Database.insert(lead, false);
            Test.stopTest();
              for(Database.Error err : result.getErrors()) {
            		System.debug('The following error has occurred.');                    
            		System.debug(err.getStatusCode() + ': ' + err.getMessage());
            		System.debug('Lead fields that affected this error: ' + err.getFields());
        	}
            //System.assert(result.isSuccess());
        }               
    }

    public static User createUserTelemarketing() {
        /**
        * @description Crée un utilisateur de IM Partner
        */            
        User userImPartner = new User(
            alias = 'TestTele',
            email = 'testTele.sales@example.com',
            emailencodingkey = 'UTF-8',
            BypassPB__c = true,
            BypassVR__c = true,
            BypassWF__c = true,
            lastname = 'testsales',
            languagelocalekey = 'fr',
            localesidkey = 'fr_FR',
            profileid = [
                SELECT Id
                FROM Profile
                WHERE Name = :CEGID_TELEMARKETING_PROFILE_NAME
                LIMIT 1
            ][0].Id,
            timezonesidkey = 'Europe/Paris',
            username = 'test.impartner' + System.now().millisecond()
            + UserInfo.getOrganizationId() + '@example.com'
        );
        return userImPartner;
    }
    
     static testMethod void testIsOppyOwnerIsActifMemberOfTerritory() {
        System.runAs(adminUser){  
              
            List<Opportunity> oppyList = [select id,Name from Opportunity];  
            
            // Perform test
            Test.startTest();    
            Set<Id> oppiesId = new Set<Id>();
			for(Opportunity oppy : oppyList){                    
                    oppiesId.add(oppy.Id);
                }
            TH_FutureMethods.isOppyOwnerIsActifMemberOfTerritory(oppiesId);             
            Test.stopTest();
            //System.assert(result.isSuccess());
        }               
    }

}