unpackaged/main/default/objects/Account/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <inlineHelpText>Registration number of the company with the authorities of the country where it is located. For example, for France, this is the Siret and for Spain the CIF.</inlineHelpText>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID or Tax Number exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Employees_Group__c.field-meta.xml
<CustomField>
    <fullName>No_of_Employees_Group__c</fullName>
    <description>Number of Employees of the Group (Accounts)</description>
    <label>No. of Employees (Group)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <inlineHelpText>For Prospect Accounts, total number of stores of the brand. For Customer Accounts, number of stores with a Cegid Retail Solution.</inlineHelpText>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Activatetrigger__c.field-meta.xml
<CustomField>
    <fullName>Activatetrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Mkto_email_invalid__c.field-meta.xml
<CustomField>
    <fullName>Mkto_email_invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Invalid (CRM)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Mkto_email_invalid__c.field-meta.xml
<CustomField>
    <fullName>Mkto_email_invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Invalid (CRM)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/National_ID__c.field-meta.xml
<CustomField>
    <fullName>National_ID__c</fullName>
    <description>National ID of the account. For France it's the SIRET</description>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/National_ID_Exception__c.field-meta.xml
<CustomField>
    <fullName>National_ID_Exception__c</fullName>
    <label>National ID Exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>National_ID_Exception</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stores__c</fullName>
    <label>No. of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/CommercialOrganization__c.field-meta.xml
<CustomField>
    <fullName>CommercialOrganization__c</fullName>
    <label>Commercial Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commercial_Organization</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Competitors__c.field-meta.xml
<CustomField>
    <fullName>Competitors__c</fullName>
    <label>Competitors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitor</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Forecast_Category_EDIT__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Category_EDIT__c</fullName>
    <description>Duplicate field to allow picklist dependency</description>
    <label>Forecast Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upside</fullName>
                <default>true</default>
                <label>Upside</label>
            </value>
            <value>
                <fullName>Probable</fullName>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <description>la raison de la perte de l'opportunité</description>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Competition choosen</fullName>
            </value>
            <value>
                <fullName>Project postponed</fullName>
            </value>
            <value>
                <fullName>Legal Terms</fullName>
            </value>
            <value>
                <fullName>Financial Terms</fullName>
            </value>
            <value>
                <fullName>Features</fullName>
            </value>
            <value>
                <fullName>Lost of project</fullName>
            </value>
            <value>
                <fullName>Group Centralisation</fullName>
            </value>
            <value>
                <fullName>Change of governance</fullName>
            </value>
            <value>
                <fullName>Economic context</fullName>
            </value>
            <value>
                <fullName>No budget</fullName>
            </value>
            <value>
                <fullName>Client budget not adapted</fullName>
            </value>
            <value>
                <fullName>Product features</fullName>
            </value>
            <value>
                <fullName>Duplicate opportunity</fullName>
            </value>
            <value>
                <fullName>International scope</fullName>
            </value>
            <value>
                <fullName>Customer financial situation</fullName>
            </value>
            <value>
                <fullName>Other provider choosen</fullName>
            </value>
            <value>
                <fullName>Deployment time</fullName>
            </value>
            <value>
                <fullName>UX product ergonomic</fullName>
            </value>
            <value>
                <fullName>Price too high</fullName>
            </value>
            <value>
                <fullName>Reputation</fullName>
            </value>
            <value>
                <fullName>Services offered</fullName>
            </value>
            <value>
                <fullName>Incomplete data</fullName>
            </value>
            <value>
                <fullName>Cannot be reached</fullName>
            </value>
            <value>
                <fullName>Wrong coordinates</fullName>
            </value>
            <value>
                <fullName>Non commercial opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Territory2/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/CommercialOrganization__c.field-meta.xml
<CustomField>
    <fullName>CommercialOrganization__c</fullName>
    <label>Commercial Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commercial_Organization</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>CASE( 
    TEXT(Agency__c),
'112', 'CPA',
'113', 'CPA',
'114', 'CPA',
'115', 'CPA',
'217', 'RETAIL',
'290', 'RETAIL',
'320', 'CPA',
'340', 'CPA',
'392', 'FINANCE',
'393', 'FINANCE',
'394', 'FINANCE',
'395', 'FINANCE',
'396', 'FINANCE',
'397', 'FINANCE',
'410', 'CPA',
'411', 'CPA',
'412', 'CPA',
'470', 'CPA',
'530', 'Other',
'549', 'RETAIL',
'550', 'RETAIL',
'552', 'RETAIL',
'555', 'RETAIL',
'556', 'RETAIL',
'557', 'RETAIL',
'560', 'RETAIL',
'563', 'HCM',
'583', 'RETAIL',
'585', 'HCM',
'714', 'HCM',
'715', 'HCM',
'800', 'FINANCE',
'803', 'SB',
'804', 'SB',
'805', 'FINANCE',
'808', 'FINANCE',
'809', 'RETAIL',
'810', 'FINANCE',
'811', 'FINANCE',
'812', 'HCM',
'813', 'HCM',
'814', 'FINANCE',
'815', 'FINANCE',
'816', 'FINANCE',
'818', 'CPA',
'819', 'FINANCE',
'822', 'FINANCE',
'823', 'HCM',
'824', 'HCM',
'825', 'HCM',
'826', 'HCM',
'829', 'CPA',
'830', 'CPA',
'831', 'SB',
'832', 'HCM',
'834', 'HCM',
'835', 'HCM',
'836', 'HCM',
'837', 'HCM',
'838', 'HCM',
'839', 'HCM',
'841', 'HCM',
'842', 'HCM',
'840', 'HCM',
'843', 'OTHER',
'844', 'RETAIL',
'845', 'FINANCE',
'846', 'FINANCE',
'847', 'FINANCE',
'849', 'FINANCE',
'850', 'FINANCE',
'852', 'FINANCE',
'853', 'FINANCE',
'854', 'FINANCE',
'855', 'HCM',
'856', 'SB',
'857', 'HCM',
'858', 'HCM',
'Not Assigned'
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>SDR</fullName>
            </value>
            <value>
                <fullName>CSM</fullName>
            </value>
            <value>
                <fullName>EuroCRM</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Alliances</fullName>
            </value>
            <value>
                <fullName>Transversal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Value</fullName>
    </customValue>
    <customValue>
        <fullName>Volume</fullName>
        <default>true</default>
        <label>Volume</label>
    </customValue>
    <masterLabel>Business</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Competitor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>15FIVE</fullName>
    </customValue>
    <customValue>
        <fullName>360L</fullName>
    </customValue>
    <customValue>
        <fullName>365 TALENTS</fullName>
    </customValue>
    <customValue>
        <fullName>AAREON</fullName>
    </customValue>
    <customValue>
        <fullName>ACCOUNTIFY</fullName>
    </customValue>
    <customValue>
        <fullName>ACCOUNTOR</fullName>
    </customValue>
    <customValue>
        <fullName>ACD GROUPE</fullName>
    </customValue>
    <customValue>
        <fullName>ADEQUASYS</fullName>
    </customValue>
    <customValue>
        <fullName>ADP</fullName>
    </customValue>
    <customValue>
        <fullName>AGIRIS</fullName>
    </customValue>
    <customValue>
        <fullName>ALPHA3I</fullName>
    </customValue>
    <customValue>
        <fullName>ALTAYS</fullName>
    </customValue>
    <customValue>
        <fullName>AMELKIS</fullName>
    </customValue>
    <customValue>
        <fullName>Apisoft</fullName>
    </customValue>
    <customValue>
        <fullName>Apologic</fullName>
    </customValue>
    <customValue>
        <fullName>APTOS</fullName>
    </customValue>
    <customValue>
        <fullName>ARAGON</fullName>
    </customValue>
    <customValue>
        <fullName>ARC LOGICIELS</fullName>
    </customValue>
    <customValue>
        <fullName>ARTICULATE</fullName>
    </customValue>
    <customValue>
        <fullName>AUTEL/BEST STORE</fullName>
    </customValue>
    <customValue>
        <fullName>AVATURE</fullName>
    </customValue>
    <customValue>
        <fullName>AVELON RMS</fullName>
    </customValue>
    <customValue>
        <fullName>AXWAY</fullName>
    </customValue>
    <customValue>
        <fullName>BAISON</fullName>
    </customValue>
    <customValue>
        <fullName>BAMBOO HR</fullName>
    </customValue>
    <customValue>
        <fullName>BANQUE POPULAIRE</fullName>
    </customValue>
    <customValue>
        <fullName>BEARINGPOINT</fullName>
    </customValue>
    <customValue>
        <fullName>BEEBOLE</fullName>
    </customValue>
    <customValue>
        <fullName>BERGER LEVRAULT</fullName>
    </customValue>
    <customValue>
        <fullName>BIZNEO</fullName>
    </customValue>
    <masterLabel>Competitor</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/National_ID_Exception.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Creation In progress</fullName>
    </customValue>
    <customValue>
        <fullName>Empty on loading</fullName>
    </customValue>
    <customValue>
        <fullName>COM (New Caledonia or French Polynesia)</fullName>
        <isActive>false</isActive>
        <label>COM (New Caledonia or French Polynesia)</label>
    </customValue>
    <customValue>
        <fullName>Association</fullName>
        <isActive>false</isActive>
        <label>Association</label>
    </customValue>
    <masterLabel>National ID Exception</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/TH_Opportunity_TEST.cls
@isTest
public class TH_Opportunity_TEST {
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();        
    static User salesUser = new UTIL_TestFactory.UserFactory().createUserCegidSales();
    static User salesUser2 = new UTIL_TestFactory.UserFactory().createUserCegidSales();
    static User salesUser3 = new UTIL_TestFactory.UserFactory().createUserCegidSales();
    
    @testSetup static void setup() {
        System.runAs(adminUser) {       
            
            insert new BypassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), Activatetrigger__c = True);
            
            
            
            Test.startTest();
            List<Account> accs = new List<Account>();
            for(Integer i = 0 ; i < 5 ; i++) {
                Account acc = new Account();
                acc.Name= 'Test Account AZA2 '+i;
                acc.National_ID_Exception__c ='Empty on loading';
                acc.BillingPostalCode ='75009';
                acc.BillingCountry ='France';
                acc.BillingCity ='Paris';
                acc.No_of_Employees_Group__c = 15;
                acc.No_of_Stores__c = 7;
                acc.NumberOfEmployees = 14;

                accs.add(acc);
            }
                        

            insert accs;
                  
            Opportunity oppToInsert = New Opportunity();
            oppToInsert.Name='test azas2';
            oppToInsert.AccountId=accs[0].Id;
            oppToInsert.StageName='G - MQL';
            oppToInsert.Sales_Purpose__c='121';
            oppToInsert.CurrencyIsoCode='EUR';
            oppToInsert.Forecast_Category_EDIT__c='Omitted';
            oppToInsert.CloseDate=date.today();
            oppToInsert.LeadSource='Sales Prospecting';
            oppToInsert.Competitors__c = 'ADP';  
            
            insert oppToInsert;

            List<User> users = new List<User>();
        
            for(Integer i = 0 ; i < 5 ; i++) {
                User u = new UTIL_TestFactory.UserFactory().createUserCegidSales();
                u.IsActive = true;
                users.add(u);
            }

            insert users;
            List<Territory2> terr2s = [SELECT Id, DeveloperName 
            FROM Territory2
            WHERE Territory2Model.state = 'Active'
            LIMIT 5];
            List<ObjectTerritory2Association> objTerrAssos = new List<ObjectTerritory2Association>();
        for(Integer i = 0 ; i < 5 ; i++) {
            objTerrAssos.add(new ObjectTerritory2Association(Territory2Id = terr2s[i].Id, ObjectId = accs[i].Id, AssociationCause='Territory2Manual'));
        }

        insert objTerrAssos;
               
            Test.stopTest();
        }
    }
    
   /*     static testMethod void testCheckValidEmailDecisionMaker(){      	
            System.runAs(adminUser){      
        List<Opportunity> oppList = [select Id,Name,StageName From Opportunity  Where stageName != 'Closed Won' Limit 1] ;
        List<Contact> contactList = [select id,name,Mkto_email_invalid__c from contact Limit 1];
        
        System.debug('contact = '+contactList); 
        List<OpportunityContactRole> oppyRoleList = new List<OpportunityContactRole>();
        List<Opportunity> oppListToUpdate  = new List<Opportunity>();
        List<Contact> ContactListToUpdate  = new List<Contact>();
        for (Opportunity opp : oppList) {
           opp.StageName ='D - Draw up the solution';
           for (Contact contact : contactList) {
            oppyRoleList.add(new OpportunityContactRole(OpportunityId = opp.Id ,ContactId = contact.Id,Role ='Decision Maker'));
            contact.Mkto_email_invalid__c = true ;
            ContactListToUpdate.add(contact) ; 
          //  continue ;   
           } 
           oppListToUpdate.add(opp);

        }
            List<Account> listAcc = [Select Id, Name From Account Limit 1];
            Opportunity opp = New Opportunity();
            opp.Name='test';
            opp.AccountId=listAcc[0].Id;
            opp.StageName='G - MQL';
            opp.Sales_Purpose__c='121';
            opp.CurrencyIsoCode='EUR';
            opp.Forecast_Category_EDIT__c='Omitted';
            opp.CloseDate=date.today();
            opp.LeadSource='Sales Prospecting';
            //
            Test.startTest();
            insert opp;
            insert oppyRoleList ;
            update ContactListToUpdate ;
             try {
        		update oppListToUpdate ;         
             } catch (DmlException e) {
                 String message = e.getMessage();
       			// System.assert(e.getMessage().contains(System.Label.VR_checkEmailValidDecisionMaker), 'message=' + e.getMessage());
             }
             Test.stopTest();   
            }
    }*/

        @isTest static void testUpdateWinningCompetitor() {
        System.runAs(adminUser){  
            Opportunity opp = [SELECT id, Name FROM Opportunity WHERE Name LIKE 'test azas2'];        
            System.debug('Update Opp ');
            opp.StageName = 'Closed Lost';
            opp.Loss_Reason__c = 'Competition choosen';            
            opp.Competitors__c = 'ADP;APTOS';
              
            
            // Perform test
            Test.startTest();
            
            Database.SaveResult result = Database.update(opp, false);
            Test.stopTest();
            //System.assert(result.isSuccess());
        }               
    }

    //AZI - W-001685
    
     static testMethod void testCheckContactBeforValidateTheSolutionStage() {
        System.runAs(adminUser){ 
     		//Add  Territory2
            List<Territory2> terrList = [Select Id From Territory2  where Territory2Model.State <> 'Archived'];
            terrList[0].Business__c = 'Value';

            update terrList[0];

            Opportunity opp = [select StageName, Territory2Id, Sales_Purpose__c from Opportunity where Name LIKE 'test azas2'];        
            System.debug('Update Opp ');
            opp.StageName = 'C - Validate the solution';
            opp.Territory2Id = terrList[0].Id;
            opp.Sales_Purpose__c = 'Renew';
            
            // Perform test
            Test.startTest();
            
            Database.SaveResult result = Database.update(opp, false);
            Test.stopTest();
            //System.assert(result.isSuccess());
        }               
    }
    //END AZI - W-001685    

    private static void affectLeadSourceFromUserTypeData() {
        
        insert salesUser;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Ecosystem_Relationships_Management'];
        insert new PermissionSetAssignment(AssigneeId = salesUser.id, PermissionSetId = ps.Id);    
        
        List<Territory2Model> terrModels = [SELECT Id FROM Territory2Model WHERE DeactivatedDate = null];
        List<Territory2Type> terrTypes = [SELECT Id FROM Territory2Type];
        Territory2 terrTest = new Territory2(Name = 'Test', DeveloperName = 'Test', Expertise__c='110', territory2ModelId=terrModels[0].Id, Territory2TypeId=terrTypes[0].Id);

        insert terrTest;
        
        UserTerritory2Association usrTerr = new UserTerritory2Association(UserId = salesUser.Id, Territory2Id=terrTest.Id);

        insert usrTerr;
        
    }

    

    @isTest static void affectLeadSourceFromUserTypeSDRTest() {
        affectLeadSourceFromUserTypeData();

        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 100 ; i++) {
            opps.add(new Opportunity(Name = 'Test opp '+i, AccountId = acc.Id, StageName = 'G - Sales Ready'));
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        salesUser.Sale_Type__c = 'SDR';

        System.debug(salesUser);
        Test.startTest();
        System.runAs(salesUser) {
            thOpp.affectLeadSourceFromUserType(opps);
        }
        Test.stopTest();
    }

    @isTest static void affectLeadSourceFromUserTypeNoSDRTest() {
        affectLeadSourceFromUserTypeData();

        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 100 ; i++) {
            opps.add(new Opportunity(Name = 'Test opp '+i, AccountId = acc.Id, StageName = 'G - Sales Ready'));
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
        System.runAs(salesUser) {
            thOpp.affectLeadSourceFromUserType(opps);
        }
        Test.stopTest();

        Integer nbOppLSourcePartner = 0;

        for(Opportunity opp : opps) {
            if(opp.LeadSource == 'Partner') {
                nbOppLSourcePartner++;
            }
        }

        System.assertEquals(100, nbOppLSourcePartner, 'There are 100 opp with Lead source = partner');
    }

    @isTest static void affectLeadSourceFromUserTypeNoSDRNoPartnerTest() {
        affectLeadSourceFromUserTypeData();

        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 100 ; i++) {
            opps.add(new Opportunity(Name = 'Test opp '+i, AccountId = acc.Id, StageName = 'G - Sales Ready'));
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
        System.runAs(salesUser2) {
            thOpp.affectLeadSourceFromUserType(opps);
        }
        Test.stopTest();

        
    }

    @isTest static void affectLeadSourceFromUserTypeExpertiseMatchOppTest() {

        Account acc = new Account();
        acc.Name= 'TestAccount 6';
        acc.BillingPostalCode ='69006';
        acc.BillingCountryCode ='AD';
        acc.National_ID__c = '012563412563799';
        acc.BillingCity ='Lyon';
        acc.No_of_Employees_Group__c =60;
        acc.No_of_Stores__c =1;
        acc.NumberOfEmployees =90;            

        System.runAs(adminUser) {
            insert acc;
        }

        Account_Expertise__c accExp = new Account_Expertise__c(Account__c = acc.Id, expertise__c = '110');
        insert accExp;
        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 100 ; i++) {
            opps.add(new Opportunity(Name = 'Test opp '+i, AccountId = acc.Id, StageName = 'G - Sales Ready', expertise__c = '110'));
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
        System.runAs(salesUser2) {
            thOpp.affectLeadSourceFromUserType(opps);
        }
        Test.stopTest();

        Integer nbOppLSourceNull = 0;

        for(Opportunity opp : opps) {
            if(opp.LeadSource == null && opp.Sales_purpose__c == null) {
                nbOppLSourceNull++;
            }
        }

        System.assertEquals(100, nbOppLSourceNull, 'There are 100 opp with Lead source = null and Sales prupose = null');
    }

    @isTest static void affectLeadSourceFromUserTypeExpertiseNoMatchOppTest() {

        Account acc = new Account();
        acc.Name= 'TestAccount 3';
        acc.BillingPostalCode ='69006';
        acc.BillingCountryCode ='AD';
        acc.National_ID__c = '012563412563299';
        acc.BillingCity ='Lyon';
        acc.No_of_Employees_Group__c =60;
        acc.No_of_Stores__c =1;
        acc.NumberOfEmployees =90;            

        System.runAs(adminUser) {
            insert acc;
        }

        Account_Expertise__c accExp = new Account_Expertise__c(Account__c = acc.Id, expertise__c = '110');
        insert accExp;
        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 100 ; i++) {
            opps.add(new Opportunity(Name = 'Test opp '+i+System.now().millisecond(), AccountId = acc.Id, StageName = 'G - Sales Ready'));
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
        System.runAs(salesUser2) {
            thOpp.affectLeadSourceFromUserType(opps);
        }
        Test.stopTest();
        Integer nbOppCrossSell = 0;

        for(Opportunity opp : opps) {
            if(opp.LeadSource == 'Sales Cross Sell' && opp.Sales_purpose__c == '121') {
                nbOppCrossSell++;
            }
        }

        //System.assertEquals(100, nbOppCrossSell, 'There are 100 opp with Cross-sell and Sales prupose = 121');
    }

    @isTest static void affectLeadSourceFromUserTypeNothingTest() {

        Account acc = new Account();
        acc.Name= 'TestAccount 2';
        acc.BillingPostalCode ='69006';
        acc.BillingCountryCode ='AD';
        acc.National_ID__c = '012563412563298';
        acc.BillingCity ='Lyon';
        acc.No_of_Employees_Group__c =60;
        acc.No_of_Stores__c =1;
        acc.NumberOfEmployees =90;            

        System.runAs(adminUser) {
            insert acc;
        }
        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 100 ; i++) {
            opps.add(new Opportunity(Name = 'Test opp '+i, AccountId = acc.Id, StageName = 'G - Sales Ready'));
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
        System.runAs(salesUser2) {
            thOpp.affectLeadSourceFromUserType(opps);
        }
        Test.stopTest();

        Integer nbOppCrossSell = 0;

        for(Opportunity opp : opps) {
            if(opp.LeadSource == 'Sales Cross Sell' && opp.Sales_purpose__c == '121') {
                nbOppCrossSell++;
            }
        }

        //System.assertEquals(100, nbOppCrossSell, 'There are 100 opp with Cross-sell and Sales prupose = 121');
    }

    @isTest static void updateOppyAttributesTest() {
        Territory2 terr = [SELECT Id,
                                  BU__c, 
                                  CommercialOrganization__c,
                                  Sales_Region__c, 
                                  Job__c, 
                                  TerritoryCode__c,
                                  Channel__c,
                                  Agency__c 
                           FROM Territory2
                           LIMIT 1];
        Opportunity opp1 = new Opportunity();
        Opportunity opp2 = new Opportunity();
        User usr1 = new User(Sale_Type__c = 'Inside Sales', Agency__c = '552');
        User usr2 = new User(Sale_Type__c = 'SDR', Agency__c = '217');

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
            thOpp.updateOppyAttributes(opp1, terr, usr1);
            thOpp.updateOppyAttributes(opp2, terr, usr2);
        Test.stopTest();

        system.assertEquals(terr.Id, opp1.territory2Id, 'Opp1 Terr ID missmatch');
        system.assertEquals(terr.BU__c, opp1.BU__c, 'Opp1 BU__c missmatch');
        system.assertEquals(terr.CommercialOrganization__c, opp1.CommercialOrganization__c, 'Opp1 CommercialOrganization__c missmatch');
        system.assertEquals(terr.Sales_Region__c, opp1.Sales_Region__c, 'Opp1 Sales_Region__c missmatch');
        system.assertEquals(terr.Job__c, opp1.Job__c, 'Opp1 Job__c missmatch');
        system.assertEquals(terr.TerritoryCode__c, opp1.TerritoryCode__c, 'Opp1 TerritoryCode__c missmatch');
        system.assertEquals('003', opp1.Channel__c, 'Opp1 Channel__c missmatch');
        system.assertEquals(usr1.Agency__c, opp1.Agency__c, 'Opp1 Agency__c missmatch');

        system.assertEquals(terr.Id, opp2.territory2Id, 'Opp2 Terr ID missmatch');
        system.assertEquals(terr.BU__c, opp2.BU__c, 'Opp2 BU__c missmatch');
        system.assertEquals(terr.CommercialOrganization__c, opp2.CommercialOrganization__c, 'Opp2 CommercialOrganization__c missmatch');
        system.assertEquals(terr.Sales_Region__c, opp2.Sales_Region__c, 'Opp2 Sales_Region__c missmatch');
        system.assertEquals(terr.Job__c, opp2.Job__c, 'Opp2 Job__c missmatch');
        system.assertEquals(terr.TerritoryCode__c, opp2.TerritoryCode__c, 'Opp2 TerritoryCode__c missmatch');
        system.assertEquals(terr.Channel__c, opp2.Channel__c, 'Opp2 Channel__c missmatch');
        system.assertEquals(terr.Agency__c, opp2.Agency__c, 'Opp2 Agency__c missmatch');
    }

    @isTest static void oppyTerritoryCalculationOnInsertTest() {
        
        insert salesUser3;
        insert adminUser;
        
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 10];

        System.debug(users);
        List<Territory2> terr2s = [SELECT Id, DeveloperName 
                                   FROM Territory2
                                   WHERE Territory2Model.state = 'Active'
                                   LIMIT 5];
        
        List<UserTerritory2Association> userTerrAssos = new List<UserTerritory2Association>();
        for(Integer i = 0 ; i < 5 ; i++) {
            userTerrAssos.add(new UserTerritory2Association(Territory2Id = terr2s[i].Id, UserId = salesUser3.Id, RoleInTerritory2='Opportunity Owner'));
        }

        
        insert userTerrAssos;
        
        
       /* List<Account> accs = new List<Account>();
        for(Integer i = 0; i < 5 ; i++) {
            accs.add(new Account(Name='Acc name '+i, National_ID_Exception__c='	Creation In progress', BillingPostalCode ='69006', 
            BillingCountryCode ='AD',
            BillingCity = 'Lyon'));
        }

        insert accs;*/
        List<Account> accs = [SELECT Id FROM Account LIMIT 5];

        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 150 ; i++) {
            if(i < 30) {
                opps.add(new Opportunity(AccountId = accs[0].Id, OwnerId = adminUser.Id));
            } else if(i >= 30 && i < 60) {
                opps.add(new Opportunity(AccountId = accs[1].Id, OwnerId = salesUser3.Id));
            } else if(i >= 60 && i < 90) {
                opps.add(new Opportunity(AccountId = accs[2].Id, OwnerId = adminUser.Id));
            } else if(i >= 90 && i < 120) {
                opps.add(new Opportunity(AccountId = accs[3].Id, OwnerId = adminUser.Id));
            } else if(i >= 120 && i < 150) {
                opps.add(new Opportunity(AccountId = accs[4].Id, OwnerId = adminUser.Id));
            }
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
            thOpp.oppyTerritoryCalculation(opps, true);
        Test.stopTest();

    }

    @isTest static void oppyTerritoryCalculationOnUpdateTest() {
        
        insert salesUser3;
        insert adminUser;
        
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 10];

        System.debug(users);
        List<Territory2> terr2s = [SELECT Id, DeveloperName 
                                   FROM Territory2
                                   WHERE Territory2Model.state = 'Active'
                                   LIMIT 5];
        
        List<UserTerritory2Association> userTerrAssos = new List<UserTerritory2Association>();
        for(Integer i = 0 ; i < 5 ; i++) {
            userTerrAssos.add(new UserTerritory2Association(Territory2Id = terr2s[i].Id, UserId = salesUser3.Id, RoleInTerritory2='Opportunity Owner'));
        }

        
        insert userTerrAssos;
        
        
       /* List<Account> accs = new List<Account>();
        for(Integer i = 0; i < 5 ; i++) {
            accs.add(new Account(Name='Acc name '+i, National_ID_Exception__c='	Creation In progress', BillingPostalCode ='69006', 
            BillingCountryCode ='AD',
            BillingCity = 'Lyon'));
        }

        insert accs;*/
        List<Account> accs = [SELECT Id FROM Account LIMIT 5];

        
        List<Opportunity> opps = new List<Opportunity>();

        for(Integer i = 0 ; i < 150 ; i++) {
            if(i < 30) {
                opps.add(new Opportunity(AccountId = accs[0].Id, OwnerId = adminUser.Id));
            } else if(i >= 30 && i < 60) {
                opps.add(new Opportunity(AccountId = accs[1].Id, OwnerId = salesUser3.Id));
            } else if(i >= 60 && i < 90) {
                opps.add(new Opportunity(AccountId = accs[2].Id, OwnerId = adminUser.Id));
            } else if(i >= 90 && i < 120) {
                opps.add(new Opportunity(AccountId = accs[3].Id, OwnerId = adminUser.Id));
            } else if(i >= 120 && i < 150) {
                opps.add(new Opportunity(AccountId = accs[4].Id, OwnerId = adminUser.Id));
            }
        }

        TH_Opportunity thOpp = new TH_Opportunity();

        Test.startTest();
            thOpp.oppyTerritoryCalculation(opps, false);
        Test.stopTest();

    }
}