unpackaged/main/default/objects/Account/fields/Referral_Customer__c.field-meta.xml
<CustomField>
    <fullName>Referral_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Referral Customer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Customer_Reference__c/Customer_Reference__c.object-meta.xml
<CustomObject>
    <label>Customer Reference</label>
    <nameField>
        <displayFormat>Ref-{000000000}</displayFormat>
        <label>Customer Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer References</relationshipLabel>
    <relationshipName>Customer_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/Customer_RefAfterDeleteTriggerHandler.cls
public class Customer_RefAfterDeleteTriggerHandler extends TriggerHandlerBase {
    private Map<Id, List<Customer_Reference__c>> customerRefsByAcc;
    

    public override void mainEntry(TriggerParameters tp) {
        System.debug('AFTER DELETE HANDLER START');
		process((Map<Id, Customer_Reference__c>)tp.oldMap);
        System.debug('AFTER DELETE HANDLER END');
	}
	
	private void process(Map<Id, Customer_Reference__c> oldMap) {

        this.bulkbeforeProcessing(oldMap);

		for(Customer_Reference__c cRef : oldMap.values()) {
            Customer_ReferenceHelper.updateCustomerReferalOnAcc(cRef, this.customerRefsByAcc, this.sObjectsToUpdate);
		}

        this.updateObjects();
	}
	

    private void bulkbeforeProcessing(Map<Id, Customer_Reference__c> oldMap) {
       Set<Id> accIds = new Set<Id>();
       this.customerRefsByAcc = new Map<Id, List<Customer_Reference__c>>();

       for(Customer_Reference__c cRef : oldMap.values()) {
        accIds.add(cRef.Account__c);
        if(!this.customerRefsByAcc.containsKey(cRef.Account__c)) {
            this.customerRefsByAcc.put(cRef.Account__c, new List<Customer_Reference__c>());
        }
        
       }
       System.debug(accIds);

       for(Customer_Reference__c cRef : [SELECT Id FROM Customer_Reference__c WHERE Account__r.Referral_Customer__c =: true  AND Id != :oldMap.keySet() AND Account__c =: accIds]) {
        
        this.customerRefsByAcc.get(cRef.Account__c).add(cRef);
       }
       System.debug(this.customerRefsByAcc);

    }
}