unpackaged/main/default/objects/Account/fields/Tech_Contact_Direct__c.field-meta.xml
<CustomField>
    <fullName>Tech_Contact_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech_Contact_Direct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_Nb_Contact__c.field-meta.xml
<CustomField>
    <fullName>Tech_Nb_Contact__c</fullName>
    <description>Nombre de contacts (directs ou indirects) à la fois actifs et compliants.
Champ mis à jour dans la classe TH_Contact et dans les Flows ACR_OnCreate et ACR_OnDelete.</description>
    <label>Tech Nb Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caractère actif / inactif du contact</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Compliant__c.field-meta.xml
<CustomField>
    <fullName>Compliant__c</fullName>
    <description>Compliance to authorize opportunity / quote creation</description>
    <formula>AND (
				NOT(ISBLANK( TEXT(Salutation ))),
				NOT(ISBLANK( LastName )),
				NOT(ISBLANK( FirstName )),
				NOT(ISBLANK( Email )), 
			 OR (	NOT(ISBLANK( Phone )), 
								 NOT(ISBLANK(MobilePhone  )), 
							  NOT(ISBLANK( Direct_Phone__c ))
							),								  
				NOT(ISBLANK(TEXT(Service__c ))),
				NOT(ISBLANK(TEXT(Function__c)))
				)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Compliant</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_created_from_Lead__c.field-meta.xml
<CustomField>
    <fullName>Contact_created_from_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact created from Lead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Mkto_marketo_sync__c.field-meta.xml
<CustomField>
    <fullName>Mkto_marketo_sync__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Sync to Marketo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/TECH_Email__c.field-meta.xml
<CustomField>
    <fullName>TECH_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>TECH Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/TECH_Force_MKT_Sync_False__c.field-meta.xml
<CustomField>
    <fullName>TECH_Force_MKT_Sync_False__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Force MKT Sync False</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Customer_User.recordType-meta.xml
<RecordType>
    <fullName>Customer_User</fullName>
    <active>true</active>
    <label>Customer User</label>
</RecordType>

unpackaged/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <label>Function</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Function__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Function__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>Used to calculate the Buynig persona used to target Campaigns</description>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lead_non_AQL__c.field-meta.xml
<CustomField>
    <fullName>Lead_non_AQL__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if a contact has already been created from a lead conversion. If a new lead is created and the same email adress is found on an existing contact, the checkbox is turned to true.</description>
    <label>Lead non AQL</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Mkto_marketo_sync__c.field-meta.xml
<CustomField>
    <fullName>Mkto_marketo_sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync to Marketo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>Controlilng field to select Fonction</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/merge_contact_done__e/merge_contact_done__e.object-meta.xml
<CustomObject>
    <label>merge contact done</label>
    <pluralLabel>merges contacts done</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/merge_contact_done__e/fields/Contact_To_be_deleted__c.field-meta.xml
<CustomField>
    <fullName>Contact_To_be_deleted__c</fullName>
    <label>Contact To be deleted</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/merge_contact_done__e/fields/Created_By_Id__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Id__c</fullName>
    <label>Created By Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/merge_contact_done__e/fields/Merged_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Merged_Contact_Id__c</fullName>
    <label>Merged Contact Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/globalValueSets/Function.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting recoverings contact</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Admin. &amp; Financial Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>After-Sales Service Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Dir.</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business app Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Business Development Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>Career Planning Mgr.</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Directors</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Board Management</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman Supervisory Board</fullName>
    </customValue>
    <customValue>
        <fullName>Chartered accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Accounting Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Digital Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chief Information Officer</fullName>
    </customValue>
    <masterLabel>Function</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Finance and accounting</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Affairs</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and communication</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Representative</fullName>
    </customValue>
    <customValue>
        <fullName>Transversal</fullName>
    </customValue>
    <customValue>
        <fullName>NR</fullName>
        <isActive>false</isActive>
        <label>NR</label>
    </customValue>
    <masterLabel>Service</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_Contact.cls
/**
 * @File Name          : TH_Contact
 * @Description        : Update Opportunity Team Member with Case Owner  
 * @Author             : SRA   
 * @Group              : Comforth-Karoo
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * ---    -----------       -------           ------------------------ 
 * 1.0    01/12/2020         SRA              Initial Version
 * ---    -----------       -------           ------------------------ 
 * 1.5    09/03/2022         BCR              handle afterUpdate/delete with contact direct management
 * ---    -----------       -------           ------------------------  
**/
public without sharing class TH_Contact extends TriggerHandler {
    /**
* @author
* @date
* @description Constructor
* @return void
*/
    public TH_Contact() {
    }
    
    /**
* @author
* @date
* @description Handler Method for after Insert Event
* @return void
*/
    public override void beforeInsert() {
        system.debug('TH_Contact beforeInsert');
        List<Contact> listContact= new List<Contact>();
        computeSameEmailCustomerUser((List<Contact>)Trigger.new);
        affectTechEmail((List<Contact>)Trigger.new);

        for(Contact con:(List<Contact>)Trigger.new){
			system.debug('New con'+ con);
            
            if(!con.Contact_created_from_Lead__c){
                listContact.add(con);
        	}
        } 
        
        if(listContact.size()>0){
            system.debug('listContact'+listContact);
            
            try{
                SM011_Contact.convertLeadError(listContact);
            }
            catch(Exception e){
                System.debug('Testing Error Message');
            }finally{
                System.debug('TestFinally');
            } 
        }
    }
    
    public override void afterInsert() {
        system.debug('TH_Contact afterInsert');
        set<Id> setContactId = new set<Id>();
        Map<Id,String> mapContactEmail = New Map<Id,String>();

        
        for(Contact con:(List<Contact>)Trigger.New){
            system.debug('con after Insert' + con.Id);
            mapContactEmail.put(con.Id,con.Email);
            setContactId.add(con.Id);
            
        } 
        if(setContactId.size()>0){
            SM011_Contact.convertLead(setContactId, mapContactEmail);
        }
        computeAccountTechContactDirect((Map<Id, Contact>) Trigger.newMap, null);
        updateNbContacts((Map<Id, Contact>) Trigger.newMap, null, false);
        //checkIfcontactAlreadyExist((Map<Id, Contact>) Trigger.newMap, null);
        mergedContacts((Map<Id, Contact>) Trigger.newMap);
        convertLeadContactNonAQL((Map<Id, Contact>)Trigger.newMap);
       
    }


    public override void beforeUpdate() {
        System.debug('TH_Contact BeforeUpdate');
        Map<Id, Contact> contsToBeProcess = (Map<Id, Contact>)CheckRecursivCall.checkRunOnce(Trigger.newMap, System.TriggerOperation.BEFORE_UPDATE); 
        if(contsToBeProcess.isEmpty()) {//Control recursiv call from trigger
            System.debug('No ct to be processed');
        } else {
            affectTechEmail(contsToBeProcess.values());
        }
    }

    /**
    * @author BCR
    * @date   09/03/2022
    * @description Handler Method for after Update Event
    * @return void
    */
    public override void afterUpdate() {
        System.debug('TH_Contact afterUpdate');
        Map<Id, Contact> contsToBeProcess = (Map<Id, Contact>)CheckRecursivCall.checkRunOnce(Trigger.newMap, System.TriggerOperation.AFTER_UPDATE); 
        if(contsToBeProcess.isEmpty()) {//Control recursiv call from trigger
            System.debug('No ct to be processed');
        } else {
            computeAccountTechContactDirect(contsToBeProcess, (Map<Id, Contact>) Trigger.oldMap);
            updateNbContacts((Map<Id, Contact>) Trigger.newMap, (Map<Id, Contact>) Trigger.oldMap, false);
            //checkIfcontactAlreadyExist(contsToBeProcess, (Map<Id, Contact>) Trigger.oldMap);
        }

    }

    /**
    * @author MAIT
    * @date   12/09/2022
    * @description Handler Method for before Delete Event
    * @return void
    */
    public override void beforeDelete() {
        System.debug('TH_Contact beforeDelete');
        updateNbContacts((Map<Id, Contact>) Trigger.oldMap, null, true);
    }

    /**
    * @author BCR
    * @date   09/03/2022
    * @description Handler Method for after Delete Event
    * @return void
    */
    public override void afterDelete() {
        System.debug('TH_Contact afterDelete');
        computeAccountTechContactDirect(null, (Map<Id, Contact>) Trigger.oldMap);
        updateNbContacts((Map<Id, Contact>) Trigger.oldMap, null, true);
    }

    /**
    * @author BCR
    * @date   10/02/2023
    * @description fill TECH Email field
    * @return void
    */
    public void affectTechEmail(List<Contact> cts) {
        for(Contact ct : cts) {
            ct.TECH_Email__c = ct.email;
        }
    }

    /**BCR W-1781 start */
    public void computeSameEmailCustomerUser(List<Contact> cts) {
        Set<String> ctEmails = new Set<String>();
        Map<String, Contact> ctsByEmail = new Map<String, Contact>();

        for(Contact ct : cts) {
            ctEmails.add(ct.email);
        }

        List<Contact> ctsDouble = [SELECT Id, Email FROM Contact WHERE Email IN:ctEmails AND RecordType.DeveloperName = 'Customer_User'];

        if(cts.size() > 0) {
            for(Contact ct : ctsDouble) {
                ctsByEmail.put(ct.email, ct);
            }

            for(Contact ct : cts) {
                if(ctsByEmail.containsKey(ct.email)) {
                    ct.email = ct.email+'.tmp';
                    ct.TECH_Force_MKT_Sync_False__c = true;
                    ct.Mkto_marketo_sync__c = false;
                }
            }
        }
    }

    /**
    * @author BCR
    * @date   10/02/2023
    * @description methode to merge customer user and sales user with same email
    * @return void
    */
    public static void mergedContacts(Map<Id, Contact> ctsMap) {
        Map<String, Contact> ctsByEmail = new Map<String, Contact>();

        for(Contact ct : ctsMap.values()) {
            System.debug('mail :'+ct.email);
            if(ct.email.endsWith('.tmp')) {
                ctsByEmail.put(ct.Email.removeEnd('.tmp'), ct);
            }
        }
        System.debug('Map : '+ctsByEmail);
        List<Contact> cts = [SELECT Id, Service__c, Function__c, Email FROM Contact WHERE Email IN:ctsByEmail.keySet() AND RecordType.DeveloperName = 'Customer_User'];
        Map<String, Schema.SObjectField> fieldApiName = Schema.SObjectType.Contact.fields.getMap();
        System.debug(cts);

        if(cts.size() > 0) {
            List<merge_contact_done__e> ctsMerge = new List<merge_contact_done__e>();
            for(Contact ct : cts) {   
                for(Schema.SObjectField field : fieldApiName.values()) {
                    if(field.getDescribe().isUpdateable() && !field.getDescribe().isCalculated() && field.getDescribe().getName() != 'email' && field.getDescribe().getName() != 'Mkto_marketo_sync__c' && ctsByEmail.get(ct.email).get(field) != null) { 
                      ct.put(field, ctsByEmail.get(ct.email).get(field));
                    }
                }
                ctsMerge.add(new merge_contact_done__e(Merged_Contact_Id__c = ct.Id,
                                                       Contact_To_be_deleted__c = ctsByEmail.get(ct.email).Id,
                                                       Created_By_Id__c = ctsByEmail.get(ct.email).createdById));
            }

            ID jobID = System.enqueueJob(new AsyncUpdateAndRedirectMergedContact(cts, ctsMerge, ctsByEmail.values()));
        }
    }

/**
    * @author TMG
    * @date   08/03/2023
    * @description fill TECH Lead non AQL
    * @return void
    */
    
// US W-002334
public static void convertLeadContactNonAQL(Map<Id, Contact> conts){
    set<String> setContactEmail = new set<String>();

    for (Contact cont : conts.values() ){
        setContactEmail.add(cont.Email);
    }
    
    system.debug('FIRST DEBUG : ' + conts.values());
    
    Map<Id, Lead> leds = new Map<Id, Lead>([SELECT Id, Email, Status, Lead_non_AQL__c, RecordType.Name FROM Lead WHERE Email IN: setContactEmail AND (Status = 'New' OR Status = 'Closed - Not Converted' OR Status = 'Closed - Converted Lead')]);   
    
    system.debug('SECOND DEBUG: ' + conts.values());
    system.debug(leds.values());
    system.debug(leds.size());
    
    for (Lead led : leds.values()){
            if(!led.Lead_non_AQL__c){
            system.debug('What is this place ?');
            led.Lead_non_AQL__c = true;
        }

    }

    update leds.values();

}    
    
    
    @TestVisible
    private class AsyncUpdateAndRedirectMergedContact implements Queueable {
        private List<Contact> cts;
        private List<merge_contact_done__e> ctsMerge;
        private List<Contact> ctsToDelete;

        public AsyncUpdateAndRedirectMergedContact(List<Contact> cts, List<merge_contact_done__e> ctsMerge, List<Contact> ctsToDelete) {
            this.cts = cts;
            this.ctsMerge = ctsMerge;
            this.ctsToDelete = ctsToDelete;

        }

        public void execute(QueueableContext context) {
            update this.cts;

            List<Database.SaveResult> results = EventBus.publish(this.ctsMerge);
    
            for (Database.SaveResult sr : results) {
                if (sr.isSuccess()) {
                    System.debug('Successfully published event.');
                } else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Error returned: ' +
                                    err.getStatusCode() +
                                    ' - ' +
                                    err.getMessage());
                    }
                }       
            }

            delete ctsToDelete;
        }
    }

    
    /**
    * @author BCR
    * @date   09/03/2022
    * @description methode to compute Tech_Contact_Direct__c field on contact parent Account
    * @return void
    */
    @TestVisible
    private void computeAccountTechContactDirect(Map<Id, Contact> newMap, Map<Id, Contact> oldMap) {
        Set<Account> accToUpdate = new Set<Account>();
        List<AccountContactRelation> accContRelats;

        Set<Id> contacts = new Set<Id>();

        if(newMap != null && oldMap == null) { //check if insert 
            accContRelats = [SELECT Id, IsDirect, ContactId, AccountId, Account.Tech_Contact_Direct__c
                                                     FROM AccountContactRelation 
                                                     WHERE ContactId = :newMap.keySet()
                                                     AND IsDirect = true]; //Get all account contact relationshit link to contact with isDirect = true

            for(AccountContactRelation accContRelat : accContRelats) {
                if(accContRelat.Account.Tech_Contact_Direct__c == false) {
                    //for every account if Tech_Contact_Direct__c == false and if contacts which are inserting are direct => pass Tech_Contact_Direct__c to true
                    accToUpdate.add(new Account(Id = accContRelat.AccountId, Tech_Contact_Direct__c = true));
                }
            }
        } else if(oldMap != null) {
            Map<Id, List<Boolean>> contactByAccount = new Map<Id, List<Boolean>>();
            Set<Id> accIds = new Set<Id>();
            if(newMap == null && oldMap != null) {
                for(Contact ct : oldMap.values()) {
                    accIds.add(ct.AccountId);
                }
            } else if(newMap != null && oldMap != null) {
                for(Contact ct : newMap.values()) { 
                    if(ct.AccountId != oldMap.get(ct.Id).AccountId) {
                        accIds.add(ct.AccountId);
                        accIds.add(oldMap.get(ct.Id).AccountId);
                    }
                }
                System.debug('contact update accIDS : '+accIds);
            }
            

            Map<Id, Account> accs = new Map<Id, Account>([SELECT Id, Tech_Contact_Direct__c FROM Account WHERE Id = :accIds]);
            System.debug('acc : '+accs);

            accContRelats = [SELECT Id, IsDirect, ContactId, AccountId, Account.Tech_Contact_Direct__c
                             FROM AccountContactRelation 
                             WHERE AccountId = :accs.keySet()];

                             System.debug('acc relation : '+accContRelats);

            for(AccountContactRelation accContRelat : accContRelats) {
                if(!contactByAccount.containsKey(accContRelat.AccountId)) {
                    contactByAccount.put(accContRelat.AccountId, new List<Boolean>());
                }
                contactByAccount.get(accContRelat.AccountId).add(accContRelat.IsDirect);
            }

            System.debug('Contact by Account '+contactByAccount);

            for(Account acc : accs.values()) {
                System.debug('acc :'+acc);
                System.debug('contactByAccount :'+contactByAccount);
                System.debug(contactByAccount.containsKey(acc.Id));

                if(acc.Tech_Contact_Direct__c == true && !contactByAccount.containsKey(acc.Id)) { //Delete scenario when 0 contacts are found on the account
                    System.debug('DELETE SCENARIO');

                    accToUpdate.add(new Account(Id = acc.Id, Tech_Contact_Direct__c = false));
                } else if(contactByAccount.containsKey(acc.Id)) {
                    System.debug('NON DELETE SCENARIO');
                    if(acc.Tech_Contact_Direct__c == false && contactByAccount.get(acc.Id).contains(true)) {
                        System.debug('SCENARIO FALSE => TRUE');
                        accToUpdate.add(new Account(Id = acc.Id, Tech_Contact_Direct__c = true));
                    } else if(acc.Tech_Contact_Direct__c == true && !contactByAccount.get(acc.Id).contains(true) ) {
                        System.debug('SCENARIO TRUE => FALSE');
                        accToUpdate.add(new Account(Id = acc.Id, Tech_Contact_Direct__c = false));
                    }
                    
                }  
            }
            System.debug('Acc to update : '+accToUpdate);
        }
        if(accToUpdate.size() > 0) {
            SBQQ.TriggerControl.disable();
            update new List<Account>(accToUpdate);
            SBQQ.TriggerControl.enable();
        }
    }

    private void updateNbContacts(Map<Id, Contact> data, Map<Id, Contact> oldData, Boolean del) {

        Map<Id, List<Id>> mapAccountToContacts = new Map<Id, List<Id>>();
        Map<Id, List<Id>> mapAccountMinusOne = new Map<Id, List<Id>>();

        List<Id> contactsIds = new List<Id>(data.keySet());

        List<AccountContactRelation> lstACR = Database.query('SELECT '+String.join(new List<String>(Schema.getGlobalDescribe().get('AccountContactRelation').getDescribe().fields.getMap().keySet()), ', ')+' FROM AccountContactRelation WHERE ContactId IN :contactsIds');

        for(AccountContactRelation acr: lstACR) {
            Contact oldCt = (oldData != null) ? oldData.get(acr.ContactId) : null;
            Contact ct = data.get(acr.ContactId);
            if((ct.Active__c && ct.Compliant__c && oldCt == null) || (oldCt != null && ct.Active__c && ct.Compliant__c && (oldCt.Active__c != ct.Active__c || oldCt.Compliant__c != ct.Compliant__c))) {
                if(mapAccountToContacts.containsKey(acr.AccountId)) {
                    List<Id> tmp = mapAccountToContacts.get(acr.AccountId);
                    tmp.add(ct.Id);
                    mapAccountToContacts.put(acr.AccountId, tmp);
                } else {
                    mapAccountToContacts.put(acr.AccountId, new List<Id>{ct.Id});
                }
            } else if(oldCt != null && ((oldCt.Active__c && !ct.Active__c) || (oldCt.Compliant__c && !ct.Compliant__c))) {
                if(mapAccountMinusOne.containsKey(acr.AccountId)) {
                    List<Id> tmp = mapAccountMinusOne.get(acr.AccountId);
                    tmp.add(ct.Id);
                    mapAccountMinusOne.put(acr.AccountId, tmp);
                } else {
                    mapAccountMinusOne.put(acr.AccountId, new List<Id>{ct.Id});
                }
            }
        }

        List<Id> accsIds = new List<Id>(mapAccountToContacts.keySet());
        accsIds.addAll(new List<Id>(mapAccountMinusOne.keySet()));
        List<Account> lstAccs = Database.query('SELECT '+String.join(new List<String>(Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().keySet()), ', ')+' FROM Account WHERE Id IN :accsIds');

        List<Account> accsToUpdate = new List<Account>();

        for(Account acc: lstAccs) {
            if(acc.TECH_Nb_Contact__c == null) {
                acc.TECH_Nb_Contact__c = 0;
            }
            if(del) {
                if(mapAccountToContacts.containsKey(acc.Id))
                    acc.TECH_Nb_Contact__c -= mapAccountToContacts.get(acc.Id).size();
            } else {
                System.Debug(mapAccountMinusOne);
                if(mapAccountMinusOne.containsKey(acc.Id))
                    acc.TECH_Nb_Contact__c -= mapAccountMinusOne.get(acc.Id).size();
                
                if(mapAccountToContacts.containsKey(acc.Id))
                    acc.TECH_Nb_Contact__c += mapAccountToContacts.get(acc.Id).size();
            }
            accsToUpdate.add(acc);
        }

        if(accsToUpdate.size() > 0) {
            SBQQ.TriggerControl.disable();
            update accsToUpdate;
            SBQQ.TriggerControl.enable();
        }

    }

    
}