unpackaged/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/MRR__c.field-meta.xml
<CustomField>
    <fullName>MRR__c</fullName>
    <description>Monthly Recurring Revenue</description>
    <label>MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/Recommendation_score__c.object-meta.xml
<CustomObject>
    <description>Cet objet permet de récupérer les information NPS des contacts depuis Qualtrics.</description>
    <label>Recommendation score</label>
    <nameField>
        <displayFormat>Survey- {000000000}</displayFormat>
        <label>Recommendation score name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Recommendation_score__c/fields/Asked_to_be_contacted_back__c.field-meta.xml
<CustomField>
    <fullName>Asked_to_be_contacted_back__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Question only asked if recommendation score ≤ 6. Customer confirms if he/she wants to be contacted back or not</inlineHelpText>
    <label>Asked to be contacted back</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Recommandations_scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/fields/Recommendation_score__c.field-meta.xml
<CustomField>
    <fullName>Recommendation_score__c</fullName>
    <inlineHelpText>Customer's answer to the question : would you like to recommend Cegid (scale from 0 to 10)</inlineHelpText>
    <label>Recommendation score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Recommendation_score__c/fields/Team_in_charge_of_contacting_back__c.field-meta.xml
<CustomField>
    <fullName>Team_in_charge_of_contacting_back__c</fullName>
    <label>Team in charge of contacting back</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>No call back required</fullName>
            </value>
            <value>
                <fullName>CSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>CASE( 
    TEXT(Agency__c),
'112', 'CPA',
'113', 'CPA',
'114', 'CPA',
'115', 'CPA',
'217', 'RETAIL',
'290', 'RETAIL',
'320', 'CPA',
'340', 'CPA',
'392', 'FINANCE',
'393', 'FINANCE',
'394', 'FINANCE',
'395', 'FINANCE',
'396', 'FINANCE',
'397', 'FINANCE',
'410', 'CPA',
'411', 'CPA',
'412', 'CPA',
'470', 'CPA',
'530', 'Other',
'549', 'RETAIL',
'550', 'RETAIL',
'552', 'RETAIL',
'555', 'RETAIL',
'556', 'RETAIL',
'557', 'RETAIL',
'560', 'RETAIL',
'563', 'HCM',
'583', 'RETAIL',
'585', 'HCM',
'714', 'HCM',
'715', 'HCM',
'800', 'FINANCE',
'803', 'SB',
'804', 'SB',
'805', 'FINANCE',
'808', 'FINANCE',
'809', 'RETAIL',
'810', 'FINANCE',
'811', 'FINANCE',
'812', 'HCM',
'813', 'HCM',
'814', 'FINANCE',
'815', 'FINANCE',
'816', 'FINANCE',
'818', 'CPA',
'819', 'FINANCE',
'822', 'FINANCE',
'823', 'HCM',
'824', 'HCM',
'825', 'HCM',
'826', 'HCM',
'829', 'CPA',
'830', 'CPA',
'831', 'SB',
'832', 'HCM',
'834', 'HCM',
'835', 'HCM',
'836', 'HCM',
'837', 'HCM',
'838', 'HCM',
'839', 'HCM',
'841', 'HCM',
'842', 'HCM',
'840', 'HCM',
'843', 'OTHER',
'844', 'RETAIL',
'845', 'FINANCE',
'846', 'FINANCE',
'847', 'FINANCE',
'849', 'FINANCE',
'850', 'FINANCE',
'852', 'FINANCE',
'853', 'FINANCE',
'854', 'FINANCE',
'855', 'HCM',
'856', 'SB',
'857', 'HCM',
'858', 'HCM',
'Not Assigned'
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <default>true</default>
        <label>Direct</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Mixed</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Partner</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Influencing Organization</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_RecommendationScore.cls
/**
 * @description       : 
 * @author            : MAIT - @moidriss
 * @group             : 
 * @last modified on  : 05-12-2023
 * @last modified by  : MAIT - @moidriss
**/
public with sharing class TH_RecommendationScore extends TriggerHandler {
    public override void afterUpdate() {
        Map<Id, Recommendation_score__c> rcScoresToBeProcess = (Map<Id, Recommendation_score__c>)CheckRecursivCall.checkRunOnce(Trigger.newMap, System.TriggerOperation.AFTER_UPDATE);     
        if(rcScoresToBeProcess.isEmpty()) {
            System.debug('No Recommendation_score__c to be processed');
        } else {
            generateTask(rcScoresToBeProcess.values(), (Map<Id, Recommendation_score__c>) Trigger.oldMap);
        }
    }

    public void generateTask(List<Recommendation_score__c> rcScores, Map<Id, Recommendation_score__c> oldMap) {
        Set<Id> contactIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Map<Id, Account> contactAccount = new Map<Id, Account>();
        List<Task> tsks = new List<Task>();
        Map<Id, Set<Id>> accByTerrs = new Map<Id, Set<Id>>();
        Set<Id> terrIds = new Set<Id>();
        Map<Id, Id> csmUserByTerr = new Map<Id, Id>();
        Map<Id, Id> accMrrToUserCSM = new Map<Id, Id>();

        List<String> buToGroup = new List<String>{
            '350',
            '340',
            '310',
            '360',
            '370'
        };

        for(Recommendation_score__c rcScore : rcScores) {
            if(rcScore.Recommendation_score__c <= 6 && rcScore.Asked_to_be_contacted_back__c && rcScore.Team_in_charge_of_contacting_back__c == 'CSM' && 
              (oldMap.get(rcScore.Id).Recommendation_score__c > 6 || !oldMap.get(rcScore.Id).Asked_to_be_contacted_back__c || oldMap.get(rcScore.Id).Team_in_charge_of_contacting_back__c != 'CSM')) {
                contactIds.add(rcScore.Contact__c);
            }
        }

        for(AccountContactRelation accCont : [SELECT AccountId, Account.OwnerId, ContactId 
                                              FROM AccountContactRelation 
                                              WHERE IsDirect = true AND ContactId IN : contactIds]) {
            contactAccount.put(accCont.ContactId, new Account(Id = accCont.AccountId, ownerId = accCont.Account.ownerId));
            accIds.add(accCont.AccountId);
        }

        //US 2484: MIAT => MRR for Finance
        List<Account_Expertise__c> allAccsExpertise = [SELECT Account__c, MRR__c, Expertise__c
                                                        FROM Account_Expertise__c 
                                                        WHERE Account__c IN :accIds];
        
        Map<Id, Decimal> accToFinanceMrr = new Map<Id, Decimal>();

        for(Account_Expertise__c accExp: allAccsExpertise) {
            if(buToGroup.contains(accExp.Expertise__c)) {
                if(!accToFinanceMrr.containsKey(accExp.Account__c)) {
                    accToFinanceMrr.put(accExp.Account__c, accExp.MRR__c);
                } else {
                    Decimal currentMrr = accToFinanceMrr.get(accExp.Account__c);
                    currentMrr += accExp.MRR__c;
                    accToFinanceMrr.put(accExp.Account__c, currentMrr);
                }
            }
        }

        System.debug(accToFinanceMrr);

        List<ObjectTerritory2Association> accTerrs = [SELECT Id, ObjectId, Territory2Id 
                                                      FROM ObjectTerritory2Association 
                                                      WHERE ObjectId IN : accIds 
                                                      ];

        for(ObjectTerritory2Association accTerr : accTerrs) {
            terrIds.add(accTerr.Territory2Id);
            if(!accByTerrs.containsKey(accTerr.ObjectId)) {
                accByTerrs.put(accTerr.ObjectId, new Set<Id>());
            }
            accByTerrs.get(accTerr.ObjectId).add(accTerr.Territory2Id);
        }

        System.debug(accByTerrs);

        //Amine
        Map<Id, Id> usersIdToTerr = new Map<Id, Id>();
        List<String> csmTerrExpertise = new List<String>();
        //

            List<UserTerritory2Association> userTerrs = [SELECT UserId, Territory2Id, Territory2.expertise__c 
                                                        FROM UserTerritory2Association 
                                                        WHERE Territory2Id IN : terrIds
                                                        AND RoleInTerritory2 ='CSM' ];
        
        System.debug(userTerrs);
       	Set<Id> terrCSM = new Set<Id>();
        
        for(UserTerritory2Association usrTerr : userTerrs) {
            //Amine
            usersIdToTerr.put(usrTerr.UserId, usrTerr.Territory2Id);
            terrCSM.add(usrTerr.Territory2Id);
            csmTerrExpertise.add(usrTerr.Territory2.expertise__c);
            //
            csmUserByTerr.put(usrTerr.Territory2Id, usrTerr.userId);
        }

        System.debug(csmTerrExpertise);
        System.debug(usersIdToTerr);

        //Amine
        //Organizing CSMs for Account
        Map<Id, Set<Id>> accsToCSM = new Map<Id, Set<Id>>();

        for(Id userId: usersIdToTerr.keySet()) {
            for(ObjectTerritory2Association accTerr : accTerrs) {
                if(accTerr.Territory2Id == usersIdToTerr.get(userId)) {
                    if(!accsToCSM.containsKey(accTerr.ObjectId)) {
                        accsToCSM.put(accTerr.ObjectId, new Set<Id>());
                    }
                    accsToCSM.get(accTerr.ObjectId).add(userId);
                    break;
                }
            }
        }

        System.debug(accsToCSM);

        //Baptiste
        List<Id> accsExpertiseIds = new List<Id>(); //List to Set

        //Check number of CSM
        for(Id accId: accsToCSM.keySet()){
            if(accsToCSM.get(accId).size() > 1) {
                accsExpertiseIds.add(accId);
            }
        }

        Map<Id, String> accToSecondMaxMRR = new Map<Id, String>(); 

        System.debug(accsExpertiseIds);

        //Getting Expertise and Organizing by MAX MRR
        if(accsExpertiseIds != null && accsExpertiseIds.size() > 0) {
            List<Account_Expertise__c> accsExpertise = [SELECT Account__c, MRR__c, Expertise__c
                                                        FROM Account_Expertise__c 
                                                        WHERE Account__c IN : accsExpertiseIds
                                                        AND (Expertise__c IN :csmTerrExpertise OR Expertise__c IN :buToGroup)];

            System.debug(accsExpertise);
                                                    
            Map<Id, Decimal> accToMaxMRR = new Map<Id, Decimal>();
            Map<Id, String> accToMaxMRRExpertise = new Map<Id, String>();

            //Group Expertise by Account
            Map<Id, List<Account_Expertise__c>> accToExpertises = new Map<Id, List<Account_Expertise__c>>();
            for(Account_Expertise__c accExp: accsExpertise) {
                if(accToExpertises.containsKey(accExp.Account__c)) {
                    accToExpertises.get(accExp.Account__c).add(accExp);
                } else {
                    accToExpertises.put(accExp.Account__c, new List<Account_Expertise__c>{accExp});
                }
            }

            System.debug(accToExpertises);

            //Seeking BU Grouping
            List<Id> accIdsBUFinance = new List<Id>();
            for(Id acc: accToExpertises.keySet()) {
                Decimal maxMRR = 0;
                for(Account_Expertise__c accExp: accToExpertises.get(acc)){
                    System.debug(accExp.Expertise__c + ' ' + accExp.MRR__c);
                    if(!buToGroup.contains(accExp.Expertise__c)) {
                        //Calculating Max MRR
                        if(accExp.MRR__c > maxMRR) {
                            maxMRR = accExp.MRR__c;
                            accToMaxMRRExpertise.put(acc, accExp.Expertise__c);
                        }
                    }
                }
                
                System.debug('sumMRR => '+accToFinanceMrr.get(acc));
                System.debug('maxMRR => '+maxMRR);

                if(accToFinanceMrr.get(acc) > maxMRR) {
                    accToSecondMaxMRR.put(acc, accToMaxMRRExpertise.get(acc));
                    maxMRR = accToFinanceMrr.get(acc);
                    accToMaxMRRExpertise.put(acc, '316');
                }

                accToMaxMRR.put(acc, maxMRR);
                
                System.debug('acc => '+acc);
                System.debug('accToMaxMRR => '+accToMaxMRR);
                System.debug('accToMaxMRRExpertise => '+accToMaxMRRExpertise);
            }

            //Organizing by MAX MRR - Obsolete
            // for(Account_Expertise__c accExp: accsExpertise) {
            //     if((accToMaxMRRExpertise.containsKey(accExp.Account__c) && accExp.MRR__c > accToMaxMRR.get(accExp.Account__c)) || !accToMaxMRRExpertise.containsKey(accExp.Account__c)) {
            //         accToMaxMRR.put(accExp.Account__c, accExp.MRR__c);
            //         accToMaxMRRExpertise.put(accExp.Account__c, accExp.Expertise__c);
            //     }
            // }

            List<Id> accsFromMRR = new List<Id>(accToMaxMRRExpertise.keySet());//:List to Set
            Map<Id, Id> terrsToAccMrr = new Map<Id, Id>();

            //Requery Terr for Accs concerned
            List<ObjectTerritory2Association> accTerrsForMrr = [SELECT Id, ObjectId, Territory2Id, Territory2.Name, Territory2.Expertise__c, Territory2.BU__c
                                                                FROM ObjectTerritory2Association 
                                                                WHERE ObjectId IN :accsFromMRR];

            //Reorganize terr By Account from Expertise (MAX MRR)
            for(Id accIdMrr: accsFromMRR) {
                for(ObjectTerritory2Association accTerr: accTerrsForMrr) {
                    System.debug('accTerr.Territory2Id => '+accTerr.Territory2Id);
                    System.debug('accTerr.Territory2.BU__c => '+accTerr.Territory2.BU__c);
                    System.debug('accTerr.Territory2.Name => '+accTerr.Territory2.Name);
                    if(accTerr.ObjectId == accIdMrr && accTerr.Territory2.BU__c == accToMaxMRRExpertise.get(accIdMrr) && terrCSM.contains(accTerr.Territory2Id)) {
                        terrsToAccMrr.put(accIdMrr, accTerr.Territory2Id);
                        break;
                    }
                    
                    if(accTerr.ObjectId == accIdMrr && accTerr.Territory2.Expertise__c == accToMaxMRRExpertise.get(accIdMrr) && terrCSM.contains(accTerr.Territory2Id)) {
                        terrsToAccMrr.put(accIdMrr, accTerr.Territory2Id);
                        break;
                    }
                }

                if(!terrsToAccMrr.containsKey(accIdMrr)) {
                    for(ObjectTerritory2Association accTerr: accTerrsForMrr) {
                        if(accTerr.ObjectId == accIdMrr && accTerr.Territory2.Expertise__c == accToSecondMaxMRR.get(accIdMrr)) {
                            terrsToAccMrr.put(accIdMrr, accTerr.Territory2Id);
                            break;
                        }
                    }
                }
            }

            List<Id> accsMrrTerrs = new List<Id>(terrsToAccMrr.values());
			System.debug('accsMrrTerrs => '+accsMrrTerrs);
            
            //Requery Users For MRR => possbility tu use pre queried Users ?
            if(accsMrrTerrs != null && accsMrrTerrs.size() > 0) {
                List<UserTerritory2Association> userForAccMRR = [SELECT UserId, Territory2Id 
                                                                 FROM UserTerritory2Association 
                                                                 WHERE Territory2Id IN :accsMrrTerrs
                                                                 AND RoleInTerritory2 ='CSM' ORDER BY User.Name ASC];
                    
                System.debug('userForAccMRR => '+userForAccMRR);
                for(Id accId: terrsToAccMrr.keySet()) {
                    for(UserTerritory2Association userMrrAssociation: userForAccMRR /*userTerrs*/) {
                        System.debug('userMrrAssociation.Territory2Id => '+userMrrAssociation.Territory2Id);
                        System.debug('terrsToAccMrr.get(accId) => '+terrsToAccMrr.get(accId));
                        System.debug('userMrrAssociation.UserId => '+userMrrAssociation.UserId);
                        if(userMrrAssociation.Territory2Id == terrsToAccMrr.get(accId)) {
                            accMrrToUserCSM.put(accId, userMrrAssociation.UserId);
                        }
                    }
                }
            }
        }
        //Amine => This is bad for performance CPU TimeOut will increase considerably :(, could not find another way to do it.. Hope it helps
        //

        System.debug(userTerrs);

        for(Id idCont : contactIds) {
            Id taskOwnerId;
            //Baptiste à voir si ça fonctionne
            if(accsToCSM.get(contactAccount.get(idCont).Id).size() > 1) {
                taskOwnerId = accMrrToUserCSM.get(contactAccount.get(idCont).Id);
            } else {
                if(accByTerrs.containsKey(contactAccount.get(idCont).Id)) {
                    for(Id terrId : accByTerrs.get(contactAccount.get(idCont).Id)) {
                        if(csmUserByTerr.containsKey(terrId)) {
                            taskOwnerId = csmUserByTerr.get(terrId);
                        }
                    }
                    if(taskOwnerId == null) {
                        taskOwnerId = contactAccount.get(idCont).OwnerId;
                    }
                } else {
                    taskOwnerId = contactAccount.get(idCont).OwnerId;
                }
            }
            //
            
            tsks.add(new Task(Subject='Recommendation survey – call back', Type__c = 'Make a Call', SubType__c='Survey', WhoId=idCont, WhatId = contactAccount.get(idCont).Id,OwnerId = taskOwnerId, Status = 'Open', ActivityDate = Date.today() + 7, Description='Following the recommendation survey, this respondent asked to be contacted back. Please call this contact back'));
        }
        System.debug(tsks);
        
        if(tsks.size() > 0) {
            insert tsks;
        } 
    }   
}