unpackaged/main/default/objects/Product2/fields/Buying_Metric__c.field-meta.xml
<CustomField>
    <fullName>Buying_Metric__c</fullName>
    <label>Buying Metric</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metric</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Marketing_Status__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Status__c</fullName>
    <description>Marketing Status</description>
    <label>Marketing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marketing_Status_Product</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Possible_Billing_Modes__c.field-meta.xml
<CustomField>
    <fullName>Possible_Billing_Modes__c</fullName>
    <label>Possible Billing Modes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Mode</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Package.recordType-meta.xml
<RecordType>
    <fullName>Package</fullName>
    <active>true</active>
    <label>Package</label>
</RecordType>

unpackaged/main/default/globalValueSets/Billing_Mode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consumption</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Rate</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Rate and Excess Consumption</fullName>
    </customValue>
    <customValue>
        <fullName>One Shot</fullName>
    </customValue>
    <masterLabel>Billing Mode</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Marketing_Status_Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketable</fullName>
    </customValue>
    <customValue>
        <fullName>Non_marketable</fullName>
        <default>true</default>
        <label>Non-marketable</label>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Marketing Status Product</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ReportComponentController_TEST.cls
@isTest
private class ReportComponentController_TEST {
    static Id RecordTypeIdProductPackage = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Package').getRecordTypeId();
    
    @isTest(SeeAllData=true) static void getReportMetadata_validID(){
        Report aReport = [ SELECT Id, Name, DeveloperName FROM Report where name LIKE 'Parent Products %' limit 1];
        system.System.debug('aReport' + aReport) ;
        Product2 pro = new Product2(Name = 'testpro', recordtypeid = RecordTypeIdProductPackage, Buying_Metric__c = '100', Possible_Billing_Modes__c='Consumption', Marketing_Status__c = 'Marketable', SBQQ__ChargeType__c = 'One-Time' , IsActive = true);
        insert pro;
        //Product2 pro = new UTIL_TestFactory.ProductFactory().createProduct('Package', 'List');
        //insert pro;
        Test.startTest();
        String reportJSON = ReportComponentController.getReportMetadata(aReport.Id, pro.Id);
        Test.stopTest();
        
        Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(reportJSON);
        Map<String, Object> reportMetadata = (Map<String, Object>)m.get('reportMetadata');
        System.assertEquals( aReport.Name, reportMetadata.get('name'), 'The correct report should be returned' );
    }
    
    @isTest static void getReportMetadata_invalidID(){
        Id bogusId = '00Q000000000000';
        Product2 pro = new Product2(Name = 'testpro', recordtypeid = RecordTypeIdProductPackage, Buying_Metric__c = '100', Possible_Billing_Modes__c='Consumption', Marketing_Status__c = 'Marketable', SBQQ__ChargeType__c = 'One-Time' , IsActive = true);
        insert pro;
        //Product2 pro = new UTIL_TestFactory.ProductFactory().createProduct('Package', 'List');
        //insert pro;
        NoDataFoundException expectedEx;
        String reportJSON;
        try{
            Test.startTest();
            reportJSON = ReportComponentController.getReportMetadata(bogusId,pro.Id);
            Test.stopTest();
        } catch( NoDataFoundException ex ){
            expectedEx = ex;
        }
        
        System.assertEquals( null, reportJSON, 'No report json should be returned' );
        System.assertNotEquals( null, expectedEx, 'An exception should been thronw to be handled by the front-end' );
    }
}