unpackaged/main/default/objects/Product2/fields/Catalog__c.field-meta.xml
<CustomField>
    <fullName>Catalog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Catalog</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Max_Trainee__c.field-meta.xml
<CustomField>
    <fullName>Max_Trainee__c</fullName>
    <label>Max Trainee</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/OPCA_Eligible__c.field-meta.xml
<CustomField>
    <fullName>OPCA_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPCA Eligible</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Realization_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Realization_Conditions__c</fullName>
    <label>Realization Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Schedulable__c.field-meta.xml
<CustomField>
    <fullName>Schedulable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Planifiable</description>
    <label>Schedulable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Term__c.field-meta.xml
<CustomField>
    <fullName>Service_Term__c</fullName>
    <description>Modalité de la prestation</description>
    <label>Service Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Term</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tech_HasOnSiteArticle__c.field-meta.xml
<CustomField>
    <fullName>Tech_HasOnSiteArticle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>W-001172 - if true, replicate Tech_HasOnSiteArticle__c from SBQQ__ProductOption__c  onto product2</description>
    <label>Tech_HasOnSiteArticle</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tech_ParentHasOnSiteArticle__c.field-meta.xml
<CustomField>
    <fullName>Tech_ParentHasOnSiteArticle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech_ParentHasOnSiteArticle</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <label>Article</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/globalValueSets/Service_Term.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Days</fullName>
    </customValue>
    <customValue>
        <fullName>Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Fee</fullName>
    </customValue>
    <masterLabel>Service Term</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM007_FlagProductHasOnSiteArticle.cls
/**
 * @author Shamina M - Comforth Karoo
 * @date 2020-09-14
 * @modified 2020-11-06
 * @description Update parent Product2 checkbox Tech_HasOnSiteArticle__c,Catalog__c
 *              based on equivalent flag on SBQQ__ProductOption__c (US W-001172) 
 *              Added to handle update on Product2(Product) when Product2(Article) flags have changed (US W-001416)
*/
public with sharing class SM007_FlagProductHasOnSiteArticle {
    /**
     * @author Shamina M - Comforth Karoo
     * @date 2020-09-14
     * @description update product2 checkbox Tech_HasOnSiteArticle__c, Catalog__c if same checkbox applicable on child product option
     * @param setIdProd2ConfSKU product2 ids (SBQQ__ConfiguredSKU__c)
     */
    public static void updateHasOnSiteArticle(Set<Id> setIdProd2ConfSKU){
        List<Product2> listProdToUpdate = new List<Product2>();
       //Add conditions Tech_ParentHasOnSiteArticle=False
        for( Product2 prod: [SELECT Id,Tech_ParentHasOnSiteArticle__c,Tech_HasOnSiteArticle__c,Schedulable__c,
                (Select ID,Tech_HasOnSiteArticle__c,Catalog__c,OPCA_Eligible__c,SBQQ__OptionalSKU__c,Schedulable__c,Service_Term__c,Duration__c,Max_Trainee__c,Realization_Conditions__c 
                    FROM SBQQ__Options__r 
                    WHERE  SBQQ__ConfiguredSKU__r.Family = '140' 
                    LIMIT 1
                ) 
            FROM Product2  
            WHERE /*Family != '140' ANDTech_ParentHasOnSiteArticle__c= false AND*/ Id IN :setIdProd2ConfSKU]){
            if(prod.SBQQ__Options__r.size()> 0){
                for(SBQQ__ProductOption__c prodOpt: prod.SBQQ__Options__r){
                    
                    system.debug('------prodOpT'+ prodOpt);
                    system.debug('------prod'+ prod);
                    prod.Tech_HasOnSiteArticle__c = prodOpt.Tech_HasOnSiteArticle__c;
                    system.debug('------prod.Tech_HasOnSiteArticle__c' + prod.Tech_HasOnSiteArticle__c);
                    prod.Realization_Conditions__c = prodOpt.Realization_Conditions__c;
                    prod.Catalog__c = prodOpt.Catalog__c;
                    prod.OPCA_Eligible__c = prodOpt.OPCA_Eligible__c;
                    prod.Schedulable__c = prodOpt.Schedulable__c;
                    prod.Service_Term__c = prodOpt.Service_Term__c;
                    prod.Duration__c = prodOpt.Duration__c;
                    //max trainee
                    prod.Max_Trainee__c  = prodOpt.Max_Trainee__c;
                    
                    system.debug('------prod.maxTraine' + prod.Max_Trainee__c);
                    system.debug('------prodOpT.maxTraine' + prodOpt.Max_Trainee__c);
                    
                    system.debug('------testParent------' + prod.Tech_ParentHasOnSiteArticle__c);
                    prod.Tech_ParentHasOnSiteArticle__c=true;
                    system.debug('------testParentAfter------' + prod.Tech_ParentHasOnSiteArticle__c);
                } 
            }else{
                prod.Tech_HasOnSiteArticle__c = false;
                prod.Catalog__c = false;
                prod.OPCA_Eligible__c = false;
                prod.Schedulable__c = false;
                prod.Duration__c = 0;
                prod.Realization_Conditions__c = null;  // ACO le 07/07/22 pour répondre au Bug 1808
                prod.Service_Term__c = null; // ACO le 07/07/22 pour répondre au Bug 1808
                prod.Max_Trainee__c = null; // ACO le 13/09/22 pour répondre au Bug 1801
            }
            listProdToUpdate.add(prod);
        }

        if(Product2.sObjectType.getDescribe().isUpdateable()){
            update listProdToUpdate;
        }
        

    }
    
    //creation methode 'ResetParentHAsonSiteArticle' qui va query product 
    /*for( Product2 prod: [SELECT Id,Tech_ParentHasOnSiteArticle__c,Tech_HasOnSiteArticle__c,Schedulable__c,
                (Select ID,Tech_HasOnSiteArticle__c,Catalog__c,OPCA_Eligible__c,SBQQ__OptionalSKU__c,Schedulable__c,Service_Term__c,Duration__c,Max_Trainee__c,Realization_Conditions__c 
                    FROM SBQQ__Options__r 
                    WHERE (Tech_HasOnSiteArticle__c = true OR Catalog__c = true OR OPCA_Eligible__c = true OR Schedulable__c = true OR Duration__c != null)
                    LIMIT 1
                ) 
            FROM Product2  
            WHERE Tech_ParentHasOnSiteArticle__c= true AND Id IN :setIdProd2ConfSKU]){ ==> update le champs ParentHAsOnsiteArticle
*/

    /**
     * @author Shamina M - Comforth Karoo
     * @date 2020-11-06
     * @description Update related Product2(Product) when Product2(Article) flags have changed (US W-001416)
     * @param setArticlesIds set product2 ids (Article)
     */
    public static void updatedRelatedProducts(Set<Id> setArticlesIds){
        system.debug('updatedRelatedProducts : ');
        Set<Id> setIdProd2ConfSKU = new Set<Id>();
        //Find related Product2(Product) to the Product2(Article) that were updated
        for(SBQQ__ProductOption__c prodOp : [Select ID,SBQQ__ConfiguredSKU__c
                    FROM SBQQ__ProductOption__c 
                    WHERE SBQQ__OptionalSKU__c IN :setArticlesIds //can be null in delete trigger context
                    AND SBQQ__ConfiguredSKU__r.RecordTypeId = :TH_Product2.PRODUCT_RECTYPEID]){
            setIdProd2ConfSKU.add(prodOp.SBQQ__ConfiguredSKU__c);          
        }
        system.debug('setIdProd2ConfSKU : ' + setIdProd2ConfSKU.size());

        updateHasOnSiteArticle(setIdProd2ConfSKU);
    }
}