unpackaged/main/default/objects/Product2/fields/Catalog__c.field-meta.xml
<CustomField>
    <fullName>Catalog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Catalog</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Max_Trainee__c.field-meta.xml
<CustomField>
    <fullName>Max_Trainee__c</fullName>
    <label>Max Trainee</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/OPCA_Eligible__c.field-meta.xml
<CustomField>
    <fullName>OPCA_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPCA Eligible</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Product Line is inactive.</errorMessage>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Realization_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Realization_Conditions__c</fullName>
    <label>Realization Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Schedulable__c.field-meta.xml
<CustomField>
    <fullName>Schedulable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Planifiable</description>
    <label>Schedulable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Term__c.field-meta.xml
<CustomField>
    <fullName>Service_Term__c</fullName>
    <description>Modalité de la prestation</description>
    <label>Service Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Term</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/StructureLevel2__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel2__c</fullName>
    <description>Structure d'activité NIV 2</description>
    <label>StructureLevel2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel2</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <label>Article</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Service_Term.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Days</fullName>
    </customValue>
    <customValue>
        <fullName>Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Fee</fullName>
    </customValue>
    <masterLabel>Service Term</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TH_Product2.cls
/**
 * @author Shamina M - Comforth Karoo
 * @date 2020-11-06
 * @description TH_Product2 - Handler class for Product2 trigger
 * @modification 1/19/2021 new Method in AfterUpdate by Kmm B-0992 B-0484
 *              
*/
public without sharing class TH_Product2 extends TriggerHandler{

    public static final Id ARTICLE_RECTYPEID =Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Article').getRecordTypeId();
    public static final Id PRODUCT_RECTYPEID =Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Product').getRecordTypeId();

    /**
     * @author Shamina M - Comforth Karoo
     * @date 2020-11-06
     * @description afterUpdate logic          
    */
    public override void afterUpdate() {
        Set<Id> setArticlesIds = new Set<Id>();
        Set<id> setProductIds = new Set<Id>();//B-0992 B-0484
        for(Product2 prod:(List<Product2>)Trigger.new){
            Product2 oldProd = (Product2)trigger.oldMap.get(prod.Id);
            //US W-001416 - handle update on products when article flags have changed
            if(canTriggerByFeature('FlagHasOnSiteArticle__c') && 
                prod.RecordTypeId == ARTICLE_RECTYPEID &&
                (prod.Realization_Conditions__c != oldProd.Realization_Conditions__c ||
                prod.Catalog__c != oldProd.Catalog__c ||
                prod.Schedulable__c != oldProd.Schedulable__c ||
                prod.OPCA_Eligible__c != oldProd.OPCA_Eligible__c || 
                prod.Service_Term__c != oldProd.Service_Term__c ||
                prod.Max_Trainee__c != oldProd.Max_Trainee__c || //B-1825
                prod.Duration__c != oldProd.Duration__c)){
                setArticlesIds.add(prod.Id);
            } 
            
            //B-0992 B-0484
            if( prod.Family != oldProd.Family || prod.StructureLevel2__c != oldProd.StructureLevel2__c 
            || prod.IsActive != oldProd.IsActive || prod.Product_Line__c != oldProd.Product_Line__c){
                setProductIds.add(prod.Id);
            }
        }
        
        if(setArticlesIds.size()>0){
            SM007_FlagProductHasOnSiteArticle.updatedRelatedProducts(setArticlesIds);
        }

        if(setProductIds.size()>0){
            SM015_FindCorrectAttachedDocument.updateLinkProduct(setProductIds);
        }

    }

    /**
     * @author Shamina M - Comforth Karoo
     * @date 2020-11-06
     * @description afterDelete logic          
    */
    public override void afterDelete() {
        Set<Id> setArticlesIds = new Set<Id>();
        for(Product2 oldProd:(List<Product2>)Trigger.old){
            //US W-001416 - handle update on products when article flags have changed
            if(canTriggerByFeature('FlagHasOnSiteArticle__c') && 
                oldProd.RecordTypeId == ARTICLE_RECTYPEID /*&&
                (oldProd.Realization_Conditions__c == 'On Site' ||
                oldProd.Catalog__c == true ||
                oldProd.OPCA_Eligible__c == true)*/){
                setArticlesIds.add(oldProd.Id);
            }             
        }
        
        if(setArticlesIds.size()>0){
            //sending null param to get SOQL query result because SBQQ__OptionalSKU__c field will be reset to null on SBQQ__ProductOption__c records 
            SM007_FlagProductHasOnSiteArticle.updatedRelatedProducts(null);
        }
    }
}