unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Product Line is inactive.</errorMessage>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Book__c.field-meta.xml
<CustomField>
    <fullName>Service_Book__c</fullName>
    <label>Service Book</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Levels__c.field-meta.xml
<CustomField>
    <fullName>Service_Levels__c</fullName>
    <label>Service Levels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/StructureLevel2__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel2__c</fullName>
    <description>Structure d'activité NIV 2</description>
    <label>StructureLevel2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel2</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/TECHServiceBook__c.field-meta.xml
<CustomField>
    <fullName>TECHServiceBook__c</fullName>
    <label>TECH_Service Book</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM005_AttachedDocument.cls
/**
* @author Keshav - Comforth
* @date 2020-06-04
* @modified 2020-06-08
* @group TH_AttachedDocument
* @object Attached Document
* @description 
* @modification 7/2/2020 IsActive = true for product By Kmm
*/
public class SM005_AttachedDocument {
    
    public static void insertGeneralTermsAndConditionsLinkToProduct(Map<String,Set<String>> mapDocumentLinks, List<Product2> listproduct){
        
        for(product2 pro:listproduct){
            //Init field
            pro.General_Terms_And_Conditions__c = '';
            Set<String> setDocLinks = new Set<String>();
            
            if(mapDocumentLinks.containsKey('Lvl1_'+pro.Family)){
                setDocLinks.addAll(mapDocumentLinks.get('Lvl1_'+pro.Family));
            }
            if(mapDocumentLinks.containsKey('Lvl1_'+pro.Family+'Lvl2_'+pro.StructureLevel2__c)){
                setDocLinks.addAll(mapDocumentLinks.get('Lvl1_'+pro.Family+'Lvl2_'+pro.StructureLevel2__c));
            }
            if(!setDocLinks.isEmpty()){
                pro.General_Terms_And_Conditions__c = String.join(new List<String>(setDocLinks),';');
            }
            
        }
        update listproduct;
    }
    
    public static void insertServiceBookLinkToProduct(Map<String,Map<String,Set<String>>> mapDocumentLinks, Map<String,String> mapDocumentNameLink, List<Product2> listproduct){
        
        for(product2 pro:listproduct){
            //Init fields to update
            pro.TECHServiceBook__c = '';
            pro.Service_Book__c = '';
            
            Set<String> setDocLinks = new Set<String>();
            if(mapDocumentLinks.get('Lvl1_'+pro.Family+'Pl_'+pro.Product_Line__c).containsKey('EmptyIsAll')){
                setDocLinks.addAll(mapDocumentLinks.get('Lvl1_'+pro.Family+'Pl_'+pro.Product_Line__c).get('EmptyIsAll'));
            }
            if(pro.Service_Levels__c != null){
                for(String serlvl:pro.Service_Levels__c.split(';')){
                    if(mapDocumentLinks.get('Lvl1_'+pro.Family+'Pl_'+pro.Product_Line__c).containsKey(serlvl)){
                        setDocLinks.addAll(mapDocumentLinks.get('Lvl1_'+pro.Family+'Pl_'+pro.Product_Line__c).get(serlvl));
                    }
                }
            }
         	//Fill fields
            pro.TECHServiceBook__c = String.join(new List<String>(setDocLinks),';');
            for(String docLink:setDocLinks){
                system.debug('docLink : ' + docLink);
                pro.Service_Book__c +=  '<a href="'+ docLink +'">' + mapDocumentNameLink.get(docLink) +'</a><BR/>';
            }
        }
        
        update listproduct;
    }
}