unpackaged/main/default/objects/Product2/fields/Transversal_Theme_Discount_Max_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Transversal_Theme_Discount_Max_Level_2__c</fullName>
    <description>Used to fill in the maximal discount allowed for the 'Transversal Theme' line, for the Validation Group Level 2</description>
    <label>Transversal Theme Discount Max - Level 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Transversal_Theme_Discount_Max_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Transversal_Theme_Discount_Max_Level_3__c</fullName>
    <description>Used to fill in the maximal discount allowed for the 'Transversal Theme' line, for the Validation Group Level 3</description>
    <label>Transversal Theme Discount Max - Level 3</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Transversal_Theme__c/Transversal_Theme__c.object-meta.xml
<CustomObject>
    <description>Object which acts as a liaison between Products and Transversal Themes</description>
    <label>Transversal Theme</label>
    <nameField>
        <displayFormat>LTT-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transversal Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transversal_Theme__c/fields/Discount_Max_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Discount_Max_Level_2__c</fullName>
    <description>Used to fill in the maximal discount allowed for each 'Transversal Theme' value, for the Validation Group Level 2</description>
    <label>Discount Max - Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Transversal_Theme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Discount_Max</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transversal_Theme__c/fields/Discount_Max_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Discount_Max_Level_3__c</fullName>
    <description>Used to fill in the maximal discount allowed for each 'Transversal Theme' value, for the Validation Group Level 3</description>
    <label>Discount Max - Level 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Transversal_Theme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Discount_Max</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transversal_Theme__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product which needs to be linked to a Transversal Theme</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Linked_Transversal_Themes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transversal_Theme__c/fields/Transversal_Theme__c.field-meta.xml
<CustomField>
    <fullName>Transversal_Theme__c</fullName>
    <description>Transversal Theme which will be linked to the Product</description>
    <label>Transversal Theme</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transversal_Theme</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Discount_Max.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>35</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <description>Used in Product Discount Max picklists</description>
    <masterLabel>Discount Max</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/DiscountWorkflowUtils.cls
public class DiscountWorkflowUtils{
    
    public static void updateProductsWithNewMaxDiscounts(Set<Id> productIds){
        // Retrieve all the information we need regarding the Transversal Themes linked to the Products coming from the Trigger
        List<AggregateResult> transversalThemes = [Select MIN(Discount_Max_Level_2__c) DiscountMaxLevel2, 
                                                   MIN(Discount_Max_Level_3__c) DiscountMaxLevel3, Product__c
                                                   From Transversal_Theme__c
                                                   Where Product__c IN :productIds
                                                   Group by Product__c];
        
		System.debug('>>>> DiscountWorkflowUtils.updateProductsWithNewMaxDiscounts transversalThemes = ' + transversalThemes);        
        
        // Creation of two maps which will contain, for each Product, the max discount obtained from the query,
        // respectively for the Validation Group Level 2 and the Validation Group Level 3
        Map<Id, String> discountMaxLevel2ByProduct = new Map<Id, String>();
        Map<Id, String> discountMaxLevel3ByProduct = new Map<Id, String>();
        
        // For each Transversal Theme in the obtained List, put the retrieved Max Discounts into the Maps along with the 
        // associated Product Id, which will be used as the key
        for(AggregateResult theme : transversalThemes){
            discountMaxLevel2ByProduct.put((Id)theme.get('Product__c'), String.valueOf(theme.get('DiscountMaxLevel2')));
            discountMaxLevel3ByProduct.put((Id)theme.get('Product__c'), String.valueOf(theme.get('DiscountMaxLevel3'))); 
        }
        
        // Prepare a List with all the Products that need to be updated with the new Max Discounts
        List<Product2> productsToUpdate = new List<Product2>();
        for(Id productId : productIds){
            Product2 product = new Product2(Id = productId,
                                            Transversal_Theme_Discount_Max_Level_2__c = discountMaxLevel2ByProduct.get(productId),
                                            Transversal_Theme_Discount_Max_Level_3__c = discountMaxLevel3ByProduct.get(productId));
            productsToUpdate.add(product);
        }
        
        // Try to update the Products
        try{
            Update productsToUpdate;
        }
        catch(DmlException exc){
            System.debug('>>>> <!ERROR!> DiscountWorkflowUtils.updateProductsWithNewMaxDiscounts Failed Update <!ERROR!>' + exc.getMessage());
        }
    }
}