unpackaged/main/default/objects/CreditNoteLine__c/CreditNoteLine__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Credit Note Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLine__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TH_CreditNoteLine.cls
/**
 * @author Soufiane LOGDALI - Comforth Karoo
 * @date 17/10/20200
 * @description Trigger handler class for CreditNoteLine__c
*/

public with sharing class TH_CreditNoteLine extends TriggerHandler {

    public override void afterInsert() {
        system.debug('TH_CreditNoteLine afterInsert');
        Set<Id> creditNoteLineIds= new Set<Id>();
        for(CreditNoteLine__c cnl:(List<CreditNoteLine__c>)Trigger.New){
			system.debug('New Credit Note Line : '+ cnl);
            
            if(cnl.Origin__c == 'ZUORA'){
                creditNoteLineIds.add(cnl.Id);
        	}
        }
        system.debug('TH_CreditNoteLine creditNoteLineIds : '+ creditNoteLineIds);
        
        if(creditNoteLineIds.size()>0){
            SM025_CreditNoteLine.postCreditNoteLine(creditNoteLineIds);
        }
    }
}