unpackaged/main/default/objects/Service_Level_Price__c/Service_Level_Price__c.object-meta.xml
<CustomObject>
    <label>Service Level Price</label>
    <nameField>
        <displayFormat>LvlSP-{000000000}</displayFormat>
        <label>Service Level Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Level Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/RegularPrice__c.field-meta.xml
<CustomField>
    <fullName>RegularPrice__c</fullName>
    <label>Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/TECH_ProductGolbalPricing__c.field-meta.xml
<CustomField>
    <fullName>TECH_ProductGolbalPricing__c</fullName>
    <formula>Product__r.Product_Line__r.Global_Pricing_Management__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_ProductGolbalPricing</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TH_ServiceLevelPrice.cls
/**
* @author Keshav M - Comforth Karoo
* @date 2021-07-01
* @description Trigger handler class for Service_Level_Price__c
*/
public with sharing class TH_ServiceLevelPrice extends TriggerHandler{
    //Bypass
    public static Set<String> setBypassMethods = new Set<String>();
    
    public override void beforeInsert() {
        SM021_UpdateServiceLevelPrice.checkSLPSize((List<Service_Level_Price__c>)Trigger.new);
    }
    
    public override void afterInsert() {
        system.debug('isBypassed before insert: ' + isBypassed('TH_ServiceLevelPriceAfterInsert'));
        if(isBypassed('TH_ServiceLevelPriceAfterInsert')){
            return;
        }
        
        bypass('TH_ServiceLevelPriceAfterInsert');
        
        Set<Id> productIds = new Set<Id>();
        Set<Id> setDefaultIds = new Set<Id>();
        Map<Id,Decimal> mapProductPrice = new Map<Id,Decimal>();
        List<Service_Level_Price__c> listNewslp = new list<Service_Level_Price__c>();
        
        for(Service_Level_Price__c slp:(List<Service_Level_Price__c>)Trigger.new){
            productIds.add(slp.Product__c);
            if(slp.TECH_ProductGolbalPricing__c && slp.Price_Book__c != SM021_UpdateServiceLevelPrice.STANDARDPRICEBOOKID){
                listNewslp.add(slp);
            }
            
            system.debug('slp.Default__c :' + slp.Default__c);
            if(slp.Default__c){
                setDefaultIds.add(slp.Id);
                mapProductPrice.put(slp.Product__c,slp.RegularPrice__c);
            }
        }
        
        if(productIds.size()>0){
            SM021_UpdateServiceLevelPrice.productServiceLevelUpdate(productIds);
        }
        
        if(mapProductPrice.size()>0){
            SM023_UpdatePriceBookEntry.productPriceUpdate(mapProductPrice);
            
        }
        
        if(setDefaultIds.size()>0){
            SM023_UpdatePriceBookEntry.deactivatingDefault(setDefaultIds,productIds);
        }
        
        if(listNewslp.size()>0){
          SM021_UpdateServiceLevelPrice.slpPriceUpdate(listNewslp);  
        }
       
    }
    
    public override void afterUpdate() {
        system.debug('isBypassed  after Update: ' + isBypassed('TH_ServiceLevelPriceAfterUpdate'));
        if(isBypassed('TH_ServiceLevelPriceAfterUpdate')){
            return;
        }
        bypass('TH_ServiceLevelPriceAfterUpdate');
        
        Set<Id> productIds = new Set<Id>();
        Set<Id> setDefaultIds = new Set<Id>();
        Map<Id,Decimal> mapProductPrice = new Map<Id,Decimal>();
        Map<Id,Decimal> mapProductPriceDelete = new Map<Id,Decimal>();
        List<Service_Level_Price__c> listNewslp = new list<Service_Level_Price__c>();
        
        
        for(Service_Level_Price__c slp:(List<Service_Level_Price__c>)Trigger.new){
            Service_Level_Price__c oldSlp = (Service_Level_Price__c)trigger.oldMap.get(slp.Id);
            productIds.add(slp.Product__c);
            
            if(slp.TECH_ProductGolbalPricing__c && slp.Price_Book__c != SM021_UpdateServiceLevelPrice.STANDARDPRICEBOOKID/*&& slp.RegularPrice__c != oldSlp.RegularPrice__c*/){
                listNewslp.add(slp);
            }
            
            if(slp.Default__c){
                setDefaultIds.add(slp.Id);
                mapProductPrice.put(slp.Product__c,slp.RegularPrice__c);
            }else{
                mapProductPriceDelete.put(slp.Product__c,slp.RegularPrice__c);
            }
        }
        
        if(productIds.size()>0){
            SM021_UpdateServiceLevelPrice.productServiceLevelUpdate(productIds);
        }
        
        if(mapProductPrice.size()>0){
            SM023_UpdatePriceBookEntry.productPriceUpdate(mapProductPrice);
        }
        
        if(mapProductPriceDelete.size()>0){
            SM023_UpdatePriceBookEntry.deletePBE(mapProductPriceDelete);
        }
        
        if(setDefaultIds.size()>0){
            SM023_UpdatePriceBookEntry.deactivatingDefault(setDefaultIds,productIds);
        }
        
        if(listNewslp.size()>0){
          SM021_UpdateServiceLevelPrice.slpPriceUpdate(listNewslp);  
        }
        
        
    }
    
    public override void afterDelete() {
        Set<Id> productIds = new Set<Id>();
        Map<Id,Decimal> mapProductPriceDelete = new Map<Id,Decimal>();
        
        for(Service_Level_Price__c slp:(List<Service_Level_Price__c>)Trigger.old){
            productIds.add(slp.Product__c);
            mapProductPriceDelete.put(slp.Product__c,slp.RegularPrice__c);
        }
        
        if(productIds.size()>0){
            SM021_UpdateServiceLevelPrice.productServiceLevelUpdate(productIds);
        }
        
        if(mapProductPriceDelete.size()>0){
            SM023_UpdatePriceBookEntry.deletePBE(mapProductPriceDelete);
        }
    }
}