unpackaged/main/default/objects/Customer_Reference__c/Customer_Reference__c.object-meta.xml
<CustomObject>
    <label>Customer Reference</label>
    <nameField>
        <displayFormat>Ref-{000000000}</displayFormat>
        <label>Customer Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer References</relationshipLabel>
    <relationshipName>Customer_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/Customer_RefBeforeDeleteTriggerHandler.cls
public class Customer_RefBeforeDeleteTriggerHandler extends TriggerHandlerBase {
    private User connectedWithProfile;
    private Set<Id> terrUserIds;
    private Map<Id, Set<Id>> accWithTerritoriesHieriarchy;
    

    public override void mainEntry(TriggerParameters tp) {
        System.debug('BEFORE DELETE HANDLER START');
		process((Map<Id, Customer_Reference__c>)tp.oldMap);
        System.debug('BEFORE DELETE HANDLER END');
	}
	
	private void process(Map<Id, Customer_Reference__c> oldMap) {

        this.bulkbeforeProcessing(oldMap);

		for(Customer_Reference__c cRef : oldMap.values()) {
            Customer_ReferenceHelper.checkAccPermissionInsertUpdate(cRef, this.connectedWithProfile, this.terrUserIds, this.accWithTerritoriesHieriarchy);
		}
	}
	

    private void bulkbeforeProcessing(Map<Id, Customer_Reference__c> newMap) {
        this.connectedWithProfile = Customer_ReferenceHelper.getUserWithProfile(UserInfo.getUserId());
        this.terrUserIds = Customer_ReferenceHelper.getTerritoryUserIds(UserInfo.getUserId());
        Set<Id> accIds = new Set<Id>();

        for(Customer_Reference__c cRef : newMap.values()) {
            accIds.add(cRef.Account__c);
        }

        this.accWithTerritoriesHieriarchy = Customer_ReferenceHelper.extractSObjectTerritoryHierarchy(accIds);

    }
}