unpackaged/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Cegid Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cegid Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricebook2/fields/Cegid_Entity__c.field-meta.xml
<CustomField>
    <fullName>Cegid_Entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cegid Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Entity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Sales_Purposes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purposes__c</fullName>
    <description>This field is linked to the filter done with “Add Product” button in quote”</description>
    <inlineHelpText>This field is linked to the filter done with “Add Product” button in quote”</inlineHelpText>
    <label>Quote's Sales Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <label>Article</label>
</RecordType>

unpackaged/main/default/objects/Service_Level_Price__c/Service_Level_Price__c.object-meta.xml
<CustomObject>
    <label>Service Level Price</label>
    <nameField>
        <displayFormat>LvlSP-{000000000}</displayFormat>
        <label>Service Level Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Level Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <label>Lower Bound</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Sales_Purposes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purposes__c</fullName>
    <label>Sales Purposes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <label>Upper Bound</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/DuplicateServiceLevelPrice_TEST.cls
/**
 * @description       : Test for Class: DuplicateServiceLevelPrice
 * @author            : Ratish ISURI
 * @group             : Comforth-Karoo
 * @created date 	  :	2022-09-23
 * @last modified on  : 2022-09-23
 * @last modified by  : Ratish ISURI
**/
@isTest
private class DuplicateServiceLevelPrice_TEST {
    
    @TestSetup
    static void makeData(){
        
        //create std pricebook
        PriceBook2 standardPricebook = new UTIL_TestFactory.PricebookFactory().activateStdPriceBook();
        
        User u = new UTIL_TestFactory.UserFactory().createUserCegidSales();
        insert u;
        User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
        System.runAs(adminUser){ 
            Entity__c  cegidEntity =  new UTIL_TestFactory.EntityFactory().createEntity();
            insert    cegidEntity;  
            
            Pricebook2 priceBook = new Pricebook2(
            Name = 'Example Price Book',
            Description = 'This is the Price Book description.',
            IsActive = true,
            Cegid_Entity__c = cegidEntity.Id,
            Currency__c = 'EUR'
            );
            insert priceBook;
              
            //create product2
            List<Product2> listProduct = new List<Product2>();
            
            Product2 prod = new UTIL_TestFactory.ProductFactory().createProduct('Article', 'List');
            prod.currencyIsoCode = 'EUR';
            listProduct.add(prod);

            Product2 prod2 = new UTIL_TestFactory.ProductFactory().createProduct('Article', 'Block');
            prod2.currencyIsoCode = 'EUR';
            listProduct.add(prod2);
            
            insert listProduct;
            
            // insert pbe with standard pb
            List<PricebookEntry> listPBE = new List<PricebookEntry>();
            for(Integer i=0; i<2;i++ ){
                PricebookEntry pbe = new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(standardPricebook.id, listProduct[i].id);
                pbe.CurrencyIsoCode = 'EUR';
                listPBE.add(pbe);
            }
            insert listPBE;
            
            //insert  pbe with custom pb
            PricebookEntry pbe = new UTIL_TestFactory.PricebookFactory().createPriceBookEntry(pricebook.id, listProduct[1].id);
            pbe.CurrencyIsoCode = 'EUR';
            listPBE.add(pbe);
            insert listPBE[2];
        } 
    }

    @IsTest
    static void testWithStdPBAndRTList(){
        PricebookEntry PE = [SELECT Pricebook2Id, Product2Id FROM PricebookEntry WHERE Product2.SBQQ__PricingMethod__c = 'List' LIMIT 1];

        DuplicateServiceLevelPrice.flowInputs inputs = new DuplicateServiceLevelPrice.flowInputs();
        inputs.objServiceLevelPrice = new UTIL_TestFactory.ServiceLevelPriceFactory().createServiceLevelPrice(
                                                                PE.Product2Id,
                                                                PE.Pricebook2Id, 
                                                                'List Pricing',
                                                                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage').Id 
                                                                );
        inputs.objServiceLevelPrice.Lower_Bound__c = 10.00;
        inputs.objServiceLevelPrice.Upper_Bound__c = 20.00;
        inputs.objServiceLevelPrice.Sales_Purposes__c += ';111';
        inputs.productRT = 'Article';


        List<DuplicateServiceLevelPrice.flowInputs> inputVariables = new List<DuplicateServiceLevelPrice.flowInputs>();
        inputVariables.add(inputs);
       

        // Assert data does not exist before execution
        Integer numOfSLPBeforeExecute = [SELECT COUNT() FROM Service_Level_Price__c];
        System.assertEquals(0, numOfSLPBeforeExecute, 'Num of SLP should be 0 before execution');

        User contextuser = [SELECT Id FROM User WHERE UserName LIKE 'test.sales%'];
        
        Test.startTest();
        System.runAs(contextuser){
            DuplicateServiceLevelPrice.CreateServiceLevelPrice(inputVariables);
        }
        Test.stopTest();
     
        // 1 SLP for each sales purpose
        Integer numOfSLPAfterExecute = [SELECT COUNT() FROM Service_Level_Price__c];
        System.assertEquals(2, numOfSLPAfterExecute, 'Num of SLP should be 2 after execution');

    }

    @IsTest
    static void testWithCustomPBAndRTBlock(){
        PricebookEntry PE = [SELECT Pricebook2Id, Product2Id FROM PricebookEntry WHERE Product2.SBQQ__PricingMethod__c = 'Block' AND Pricebook2.IsStandard = FALSE LIMIT 1];
        
        User contextuser = [SELECT Id FROM User WHERE UserName LIKE 'test.sales%'];

        
        DuplicateServiceLevelPrice.flowInputs inputs = new DuplicateServiceLevelPrice.flowInputs();
        inputs.objServiceLevelPrice = new UTIL_TestFactory.ServiceLevelPriceFactory().createServiceLevelPrice(
                                                                PE.Product2Id,
                                                                PE.Pricebook2Id,
                                                                'Block Pricing',
                                                                new UTIL_TestFactory.DiscountSchFactory().createDiscountSch('Range','Percentage').Id
                                                                );
        inputs.objServiceLevelPrice.Lower_Bound__c = 10.00;
        inputs.objServiceLevelPrice.Upper_Bound__c = 20.00;
        inputs.productRT = 'Block';

        List<DuplicateServiceLevelPrice.flowInputs> inputVariables = new List<DuplicateServiceLevelPrice.flowInputs>();
        inputVariables.add(inputs);

        // Assert data does not exist before execution
        Integer numOfSLPBeforeExecute = [SELECT COUNT() FROM Service_Level_Price__c];
        System.assertEquals(0, numOfSLPBeforeExecute, 'Num of SLP should be 0 before execution');

        Test.startTest();
        System.runAs(contextuser){
            DuplicateServiceLevelPrice.CreateServiceLevelPrice(inputVariables);
        }
        Test.stopTest();

        Integer numOfSLPAfterExecute = [SELECT COUNT() FROM Service_Level_Price__c];
        System.assertEquals(1, numOfSLPAfterExecute, 'Num of SLP should be 1 after execution');

        
    }
}