unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>806</fullName>
                <label>3COM</label>
            </value>
            <value>
                <fullName>104</fullName>
                <label>ABEL</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>ACER</label>
            </value>
            <value>
                <fullName>216</fullName>
                <label>ACRONIS</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>ACUMATICA</label>
            </value>
            <value>
                <fullName>401</fullName>
                <label>ADAPTEC</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>ADOBE</label>
            </value>
            <value>
                <fullName>213</fullName>
                <label>AGYSOFT</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>ALP</label>
            </value>
            <value>
                <fullName>209</fullName>
                <label>ALTARES</label>
            </value>
            <value>
                <fullName>244</fullName>
                <label>AMADEUS</label>
            </value>
            <value>
                <fullName>843</fullName>
                <label>AMPHORA</label>
            </value>
            <value>
                <fullName>242</fullName>
                <label>ARKHINEO</label>
            </value>
            <value>
                <fullName>601</fullName>
                <label>ARKOON</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>ASTECH</label>
            </value>
            <value>
                <fullName>204</fullName>
                <label>AURES</label>
            </value>
            <value>
                <fullName>835</fullName>
                <label>AUTHENTIFICATION</label>
            </value>
            <value>
                <fullName>899</fullName>
                <label>AUTRES</label>
            </value>
            <value>
                <fullName>402</fullName>
                <label>AXIS</label>
            </value>
            <value>
                <fullName>113</fullName>
                <label>AZUR</label>
            </value>
            <value>
                <fullName>750</fullName>
                <label>BELKIN</label>
            </value>
            <value>
                <fullName>202</fullName>
                <label>BEWAN</label>
            </value>
            <value>
                <fullName>349</fullName>
                <label>BGE</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>BINTEC</label>
            </value>
            <value>
                <fullName>214</fullName>
                <label>BODET SOFTWARE</label>
            </value>
            <value>
                <fullName>231</fullName>
                <label>Bridge</label>
            </value>
            <value>
                <fullName>234</fullName>
                <label>BROADBEAN</label>
            </value>
            <value>
                <fullName>114</fullName>
                <label>BUSINESS OBJECT</label>
            </value>
            <value>
                <fullName>207</fullName>
                <label>C3S</label>
            </value>
            <value>
                <fullName>032</fullName>
                <label>CANON</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Buying_Metric__c.field-meta.xml
<CustomField>
    <fullName>Buying_Metric__c</fullName>
    <label>Buying Metric</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metric</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Core_Business__c.field-meta.xml
<CustomField>
    <fullName>Core_Business__c</fullName>
    <label>Core Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Core_Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Functional_Level__c.field-meta.xml
<CustomField>
    <fullName>Functional_Level__c</fullName>
    <label>Functional Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Functional_Level</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Metric__c.field-meta.xml
<CustomField>
    <fullName>Metric__c</fullName>
    <description>Metric</description>
    <label>Metric</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Metric</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/NoRoyalty__c.field-meta.xml
<CustomField>
    <fullName>NoRoyalty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Royalty</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Offer</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Operating_Typology__c.field-meta.xml
<CustomField>
    <fullName>Operating_Typology__c</fullName>
    <label>Operating Typology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operating_Typology</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Purchasing_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchasing_Price__c</fullName>
    <label>Purchasing Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <description>Numéro de référence du produit</description>
    <formula>IF(CONTAINS(ProductID__c , 'GENERIC'), ProductID__c, IF(RecordType.DeveloperName = 'Package', 'K'+ ReferenceSequence__c, Left(RecordType.DeveloperName,1)+ ReferenceSequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/StructureLevel2__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel2__c</fullName>
    <description>Structure d'activité NIV 2</description>
    <label>StructureLevel2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel2</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <label>Article</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Package.recordType-meta.xml
<RecordType>
    <fullName>Package</fullName>
    <active>true</active>
    <label>Package</label>
</RecordType>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/globalValueSets/Functional_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Start</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <masterLabel>Functional Level</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Operating_Typology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100</fullName>
        <label>Main</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Module</label>
    </customValue>
    <customValue>
        <fullName>300</fullName>
        <label>Unité d&apos;oeuvre</label>
    </customValue>
    <masterLabel>Operating Typology</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LC002_ProductReport.cls
/**
 * @author Keshav - Comforth Dev Team
 * @date 2020-02
 * @group Cegid
 * @description  class for LC002_ProductReport 
 * 
 * Si on part d’un Article : On affiche des Packages (Name de SBQQ__ConfiguredSKU__c), et reference_Number (à la place de Id) et Metric, Operating Typology, Functional, Functional Level, Brand, Offer, Product Line, StructureLevel1, StructureLevel2.
 * Si on part d’un Package : On affiche des Articles (Name de SBQQ_OptionalSKU__c), et Reference_Number et No Royalties, Brand, Buying Metric, Supplier Id, Purchasing Price. 
 */


public class LC002_ProductReport {
    @AuraEnabled 
    public static List<sObject> getProducts(String productId, String recType){
        
        if(recType == 'Article'){
            List<Product2> lisPro = [SELECT Name,Id,
                                     (SELECT SBQQ__ConfiguredSKU__c, Id,Name,SBQQ__OptionalSKU__r.Id,SBQQ__ConfiguredSKU__r.Id,SBQQ__ConfiguredSKU__r.Reference_Number__c,SBQQ__ConfiguredSKU__r.Name, tolabel(SBQQ__OptionalSKU__r.Metric__c), tolabel(SBQQ__ConfiguredSKU__r.Operating_Typology__c),tolabel(SBQQ__ConfiguredSKU__r.Core_Business__c),
                                      tolabel(SBQQ__ConfiguredSKU__r.Functional_Level__c), tolabel(SBQQ__ConfiguredSKU__r.Brand__c), tolabel(SBQQ__ConfiguredSKU__r.Offer__c),tolabel(SBQQ__ConfiguredSKU__r.Family),
                                      tolabel(SBQQ__ConfiguredSKU__r.StructureLevel2__c),SBQQ__OptionalSKU__r.Buying_Metric__c,SBQQ__OptionalSKU__r.Purchasing_Price__c,SBQQ__OptionalSKU__r.NoRoyalty__c
                                      FROM SBQQ__OptionalFor__r) 
                                     FROM Product2
                                     WHERE Id in (SELECT SBQQ__ConfiguredSKU__c from SBQQ__ProductOption__c WHERE SBQQ__OptionalSKU__c =: productId AND SBQQ__OptionalSKU__r.RecordType.DeveloperName =: recType) 
                                    ];
            
            List<sObject> listObj = new List<sObject>();
            for(Product2 p:lisPro){
                if(!p.SBQQ__OptionalFor__r.isEmpty()) {
                    listObj.addAll(p.SBQQ__OptionalFor__r);
                } 
            }
            return listObj;
            
        }else if(recType == 'Package'){
            List<Product2> lisPro =  [ SELECT Name,Id,
                                      (SELECT SBQQ__OptionalSKU__c, Id,Name,SBQQ__ConfiguredSKU__r.Id,SBQQ__OptionalSKU__r.Id,SBQQ__OptionalSKU__r.Reference_Number__c,SBQQ__OptionalSKU__r.Name, tolabel(SBQQ__ConfiguredSKU__r.Metric__c), SBQQ__ConfiguredSKU__r.Operating_Typology__c,SBQQ__ConfiguredSKU__r.Core_Business__c,
                                       SBQQ__ConfiguredSKU__r.Functional_Level__c, tolabel(SBQQ__OptionalSKU__r.Brand__c), SBQQ__ConfiguredSKU__r.Offer__c,SBQQ__ConfiguredSKU__r.Family,
                                       SBQQ__ConfiguredSKU__r.StructureLevel2__c,tolabel(SBQQ__OptionalSKU__r.Buying_Metric__c),SBQQ__OptionalSKU__r.Purchasing_Price__c,SBQQ__OptionalSKU__r.NoRoyalty__c 
                                       FROM SBQQ__Options__r) 
                                      FROM Product2
                                      WHERE Id in (SELECT SBQQ__OptionalSKU__c from SBQQ__ProductOption__c WHERE SBQQ__ConfiguredSKU__c =: productId AND SBQQ__ConfiguredSKU__r.RecordType.DeveloperName =: recType)
                                     ];
            
            List<sObject> listObj = new List<sObject>();
            for(Product2 p:lisPro){
                if(!p.SBQQ__Options__r.isEmpty()) {
                    listObj.addAll(p.SBQQ__Options__r);
                } 
            }
            return listObj;
        }
        return null;
        
    }
    
    @AuraEnabled
    public static Map<String, Object> getObjMetadata() { 
        return CEGID_UTIL.getMetadata();
    }
}