unpackaged/main/default/objects/Contact/fields/Mkto_email_invalid__c.field-meta.xml
<CustomField>
    <fullName>Mkto_email_invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Invalid (CRM)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Forecast_Category_EDIT__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Category_EDIT__c</fullName>
    <description>Duplicate field to allow picklist dependency</description>
    <label>Forecast Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upside</fullName>
                <default>true</default>
                <label>Upside</label>
            </value>
            <value>
                <fullName>Probable</fullName>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/CheckValidEmailDecisionMakerTest.cls
@isTest(SeeAllData=true)
public with sharing class CheckValidEmailDecisionMakerTest {
    static User adminUser = new UTIL_TestFactory.UserFactory().createRunningUserAdministrator();
    
         static testMethod void CheckValidEmailDecisionMaker(){
      	 System.debug('Start ');    
        Test.startTest();
         System.runAs(adminUser){
		
                 
        List<Opportunity> oppList = [select Id,Name,StageName From Opportunity  Where stageName != 'Closed Won' Limit 1] ;
        List<Contact> contactList = [select id,name,Mkto_email_invalid__c from contact Limit 1];
        
        System.debug('contact = '+contactList); 
        List<OpportunityContactRole> oppyRoleList = new List<OpportunityContactRole>();
        List<Opportunity> oppListToUpdate  = new List<Opportunity>();
        List<Contact> ContactListToUpdate  = new List<Contact>();
        for (Opportunity opp : oppList) {
           opp.StageName ='D - Draw up the solution';
           for (Contact contact : contactList) {
            oppyRoleList.add(new OpportunityContactRole(OpportunityId = opp.Id ,ContactId = contact.Id,Role ='Decision Maker'));
            contact.Mkto_email_invalid__c = true ;
            ContactListToUpdate.add(contact) ; 
          //  continue ;   
           } 
           oppListToUpdate.add(opp);

        }
      	 List<Account> listAcc = [Select Id, Name From Account Limit 1];
         Opportunity opp = New Opportunity();
         opp.Name='test';
         opp.AccountId=listAcc[0].Id;
         opp.StageName='G - MQL';
         opp.Sales_Purpose__c='121';
         opp.CurrencyIsoCode='EUR';
         opp.Forecast_Category_EDIT__c='Omitted';
         opp.CloseDate=date.today();
         opp.LeadSource='Sales Prospecting';
         insert opp;
        insert oppyRoleList ;
        update ContactListToUpdate ;
             try {
        		update oppListToUpdate ;         
             } catch (DmlException e) {
                 String message = e.getMessage();
       			 System.assert(e.getMessage().contains(System.Label.VR_checkEmailValidDecisionMaker), 'message=' + e.getMessage());
             }   
        
        }
        Test.stopTest();
        
    }
}