unpackaged/main/default/objects/PricebookEntry/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <formula>Product2.Reference_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <description>Numéro de référence du produit</description>
    <formula>IF(CONTAINS(ProductID__c , 'GENERIC'), ProductID__c, IF(RecordType.DeveloperName = 'Package', 'K'+ ReferenceSequence__c, Left(RecordType.DeveloperName,1)+ ReferenceSequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Levels__c.field-meta.xml
<CustomField>
    <fullName>Service_Levels__c</fullName>
    <label>Service Levels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Service_Level_Price__c/Service_Level_Price__c.object-meta.xml
<CustomObject>
    <label>Service Level Price</label>
    <nameField>
        <displayFormat>LvlSP-{000000000}</displayFormat>
        <label>Service Level Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Level Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Conversion_rate__c.field-meta.xml
<CustomField>
    <fullName>Conversion_rate__c</fullName>
    <formula>CURRENCYRATE(TEXT(CurrencyIsoCode))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conversion rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Discount_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Discount_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discount Schedule</label>
    <referenceTo>SBQQ__DiscountSchedule__c</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <label>Lower Bound</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Max_UpperBound__c.field-meta.xml
<CustomField>
    <fullName>Max_UpperBound__c</fullName>
    <formula>BLANKVALUE(Upper_Bound__c, 999999999999999)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max UpperBound</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Maximum_Price__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Price__c</fullName>
    <inlineHelpText>In the case of Excess Charge for a Product with Excess Pricing Method Type equals to 'Capped', it is necessary to fill a Maximum Price on the Charge Service Level Price Records OR a Product Maximum Quantity.</inlineHelpText>
    <label>Maximum Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Percent_of_Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Target_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Percent of Target Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Level Prices (Percent of Target Product)</relationshipLabel>
    <relationshipName>Service_Level_Prices1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Percent_of_Total_Field__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Total_Field__c</fullName>
    <label>Percent of Total Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Percent_of_Total_Field</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Price_by_SLP__c.field-meta.xml
<CustomField>
    <fullName>Price_by_SLP__c</fullName>
    <formula>true</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price by SLP</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Level Prices</relationshipLabel>
    <relationshipName>Service_Level_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <formula>Product__r.Reference_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/RegularPrice__c.field-meta.xml
<CustomField>
    <fullName>RegularPrice__c</fullName>
    <label>Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <label>Service Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Level_Price__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <label>Upper Bound</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Percent_of_Total_Field.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waterfall_Gross_Total__c</fullName>
        <label>Gross</label>
    </customValue>
    <customValue>
        <fullName>NetTotal_Display__c</fullName>
        <label>Net</label>
    </customValue>
    <masterLabel>Percent of Total Field</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/SM021_UpdateServiceLevelPrice.cls
/**
* @author Keshav M - Comforth Karoo
* @date 2021-07-01
*/
public class SM021_UpdateServiceLevelPrice {
    
    public static final String STANDARDPRICEBOOKID = getStdPriceBook();//System.Label.Standard_Pricebook_ID;
    
    public static Id getStdPriceBook() {
        return [select Id, Name, IsActive from PriceBook2 where IsStandard=True LIMIT 1].Id;   
    }
    
    public static void checkSLPSize(List<Service_Level_Price__c> listSLP){
        
        set<Id> productIds = new set<Id>();
        
        for(Service_Level_Price__c slp:listSLP){
            productIds.add(slp.Product__c);
        }
        
        List<Service_Level_Price__c> listSLPExt = [SELECT Id, Product__c,Service_Level__c FROM Service_Level_Price__c WHERE Product__c IN:productIds];
        
        if(listSLPExt.size() == 0){
            for(Service_Level_Price__c slp:listSLP){
                slp.Default__c = true;
            }
        }
    }
    
    public static void productServiceLevelUpdate(Set<Id> productIds){ 
        //Contains all serviceLevelPrice Value
        Set<String> setServiceLevelPrice = new Set<String>();
        
        //Get All Service Level Price which has the same product 
        List<Service_Level_Price__c> listSLP = [SELECT Id, Product__c,Service_Level__c FROM Service_Level_Price__c WHERE Product__c IN:productIds];
        List<Product2> listProdToUpdate = [SELECT Id,Service_Levels__c FROM Product2 where Id IN:productIds];
        for(Service_Level_Price__c slp:listSLP){
            String serviceLevel = slp.Service_Level__c;
            setServiceLevelPrice.addAll(serviceLevel.split(';'));
        }
        
        for(Product2 pro:listProdToUpdate){
            pro.Service_Levels__c = null;
            pro.Service_Levels__c = String.join(new List<String>(setServiceLevelPrice),';');
        }
        
        update listProdToUpdate;
        
    }
    /**
     * @author Keshav M - Comforth Karoo
     * @date 2021-8-9
     * @description Update SlpPricing           
    */
    Public static void slpPriceUpdate(List<Service_Level_Price__c> listSLP){
        system.debug('slpPriceUpdate'); 
        
        set<Id> setPricebook2Id = new set<Id>();
        set<Id> setProduct2Id = new set<Id>();
        set<Id> setPBIds = new set<Id>();
        set<String> setServiceLevelPrice = new set<String>();
        set<decimal> setLowerBound = new set<decimal>();
        set<decimal> setUpperBound= new set<decimal>();
        set<String> setSalesPurpose = new set<String>();
        
        //Update List
        list<Service_Level_Price__c> listSLPToUpdate = new list<Service_Level_Price__c>();
        list<Service_Level_Price__c> listSLPToCreate = new list<Service_Level_Price__c>();
        
        list<Service_Level_Price__c> listSLPToUpsert = new list<Service_Level_Price__c>();
        
        
        for(Service_Level_Price__c slp:listSLP){
            setPricebook2Id.add(slp.Price_Book__c);
            setProduct2Id.add(slp.Product__c);
            setServiceLevelPrice.add(slp.Service_Level__c);
            setLowerBound.add(slp.Lower_Bound__c);
            setUpperBound.add(slp.Upper_Bound__c);
            setSalesPurpose.add(slp.Sales_Purpose__c);
        }
        
        //Get other non-standard pricebooks
        for(PricebookEntry PE:[SELECT Id,Pricebook2Id,Name, pricebook2.Name FROM PricebookEntry 
                               WHERE Product2Id IN:setProduct2Id AND Pricebook2Id NOT IN:setPricebook2Id AND Pricebook2Id !=:STANDARDPRICEBOOKID]){
                                   setPBIds.add(PE.Pricebook2Id);
                                   system.debug('PE : ' + PE.pricebook2.Name);
                               }
        
        //Get SLP record Which different PriceBooks
        List<Service_Level_Price__c> listSLPLoop = [SELECT Id,Price_Book__c,Product__c,Service_Level__c,Lower_Bound__c,Upper_Bound__c,Sales_Purpose__c 
                                                    FROM Service_Level_Price__c WHERE Price_Book__c IN:setPBIds AND Product__c IN:setProduct2Id 
                                                    AND Service_Level__c IN:setServiceLevelPrice AND Lower_Bound__c IN:setLowerBound AND Upper_Bound__c IN:setUpperBound 
                                                    AND Sales_Purpose__c IN:setSalesPurpose]; 
        system.debug('listSLPLoop ' + listSLPLoop.size());
        system.debug('setPBIds ' + setPBIds.size());
        //Creation of Record && Update 
        for(Service_Level_Price__c slp:listSLP){
            //if(slp.Price_Book__c != STANDARDPRICEBOOKID){
            if(listSLPLoop.size()>0){
                //Handle Update
                for(Service_Level_Price__c slpUpdate:listSLPLoop){
                    slpUpdate.RegularPrice__c = slp.RegularPrice__c;
                    listSLPToUpdate.add(slpUpdate);
                    //listSLPToUpsert.add(slpUpdate);
                }
            }else{
                //Handle Creation
                for(Id pb2Id:setPBIds){
                    system.debug('pb2Id :' + pb2Id);
                    Service_Level_Price__c objslp = new Service_Level_Price__c(
                        Lower_Bound__c = slp.Lower_Bound__c,
                        Discount_Schedule__c = slp.Discount_Schedule__c,
                        //Conversion_rate__c = slp.Conversion_rate__c,
                        //Max_UpperBound__c = slp.Max_UpperBound__c,
                        Maximum_Price__c = slp.Maximum_Price__c,
                        Percent__c = slp.Percent__c,
                        Percent_of_Target_Product__c = slp.Percent_of_Target_Product__c,
                        Percent_of_Total_Field__c = slp.Percent_of_Total_Field__c,
                        Price_Book__c = pb2Id,
                        //Price_by_SLP__c = slp.Price_by_SLP__c,
                        Product__c = slp.Product__c,
                        //Reference_Number__c = slp.Reference_Number__c,
                        RegularPrice__c = slp.RegularPrice__c,
                        Sales_Purpose__c = slp.Sales_Purpose__c,
                        Upper_Bound__c = slp.Upper_Bound__c
                    );
                     listSLPToCreate.add(objslp);
                }                
            }
        //}
        }
        system.debug('listSLPToUpsert :' + listSLPToUpsert.size());
        for(Service_Level_Price__c sl:listSLPToUpsert){
            system.debug('sl : '+ sl.Id);
        }
        if(listSLPToCreate.size()>0){
            TriggerHandler.bypass('TH_ServiceLevelPriceAfterInsert');
            insert listSLPToCreate;
        }
        
        if(listSLPToUpdate.size()>0){
            TriggerHandler.bypass('TH_ServiceLevelPriceAfterUpdate');
            update listSLPToUpdate;
        }
        
               
    }
}