unpackaged/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Participant__c/fields/CartItemId__c.field-meta.xml
<CustomField>
    <fullName>CartItemId__c</fullName>
    <label>CartItemId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/classes/TH_Participant.cls
/**
* @author Keshav - Comforth Karoo
* @date 2021-08-26
* @description Trigger handler class for Participant__c
*/
public  with sharing class TH_Participant extends TriggerHandler{
    
    public override void beforeInsert(){
        Boolean createParticipant = false;
        for(participant__c par:(List<participant__c>)Trigger.new){
            if(par.CartItemId__c != null && par.EmailAddress__c != null){
                createParticipant = true;
            }
        }
        
        if(createParticipant){
            SM022_CheckDuplicateParticipant.DuplicateVerification(Trigger.New);
        }
    }
    
    public override void beforeUpdate() {
        Boolean createParticipant = false;
        for(participant__c par:(List<participant__c>)Trigger.new){
            participant__c oldpar = (participant__c)trigger.oldMap.get(par.Id);
            if(par.CartItemId__c != null && par.EmailAddress__c != null && par.EmailAddress__c != oldpar.EmailAddress__c){
                createParticipant = true;
            }
        }
        
        if(createParticipant){
            SM022_CheckDuplicateParticipant.DuplicateVerification(Trigger.New);
        }
    }
    
}