unpackaged/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Participant__c/fields/CartItemId__c.field-meta.xml
<CustomField>
    <fullName>CartItemId__c</fullName>
    <label>CartItemId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Participant__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>Prénom</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SM022_CheckDuplicateParticipant.cls
/**
* @author Keshav - Comforth Karoo
* @date 2021-08-26
* @description Check Duplicate 
*/

public class SM022_CheckDuplicateParticipant {
    
    public static void DuplicateVerification(List<Participant__c> listParticipant){
        set <String> setEmailAdd = new set<String>();
        set <String> setCartId = new set<String>();
        for(Participant__c part:listParticipant){
            setEmailAdd.add(part.CartItemId__c);
        }
        
        List<Participant__c> lisExtPart = [SELECT Id,CartItemId__c,Name,Prenom__c,EmailAddress__c 
                                         FROM Participant__c WHERE CartItemId__c IN:setEmailAdd];
        system.debug('lisExtPart : ' + lisExtPart);
        if(lisExtPart.size()>0){
            set<String> setDuplicateAccProdL = new set<String>();
            for(Participant__c part:lisExtPart){
                setDuplicateAccProdL.add(part.CartItemId__c+'-'+part.EmailAddress__c);
            }
            
            for(Participant__c exii:listParticipant){
                if(setDuplicateAccProdL.contains(exii.CartItemId__c+'-'+exii.EmailAddress__c)){
                    for(Participant__c newPart:listParticipant){
                        newPart.addError('Merci de bien vouloir saisir un e-mail distinct pour chaque participant à une session de formation.');
                    }
                }
            }
        }
        
    }
}