unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>AV-{0}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <summarizedField>CreditNoteLine__c.CreditNoteAmount__c</summarizedField>
    <summaryForeignKey>CreditNoteLine__c.CreditNote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/CustomerRequest__c.field-meta.xml
<CustomField>
    <fullName>CustomerRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Request</label>
    <referenceTo>CustomerRequest__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/tech_SendCreditNoteToCustomer__c.field-meta.xml
<CustomField>
    <fullName>tech_SendCreditNoteToCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tech_SendCreditNoteToCustomer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLine__c/CreditNoteLine__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Credit Note Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLine__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Credit Note Lines</relationshipLabel>
    <relationshipName>CreditNotesLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLine__c/fields/InvoiceLine__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line</label>
    <referenceTo>InvoiceLine__c</referenceTo>
    <relationshipLabel>Credit Notes Lines</relationshipLabel>
    <relationshipName>CreditNotesLines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/CustomerRequest__c.object-meta.xml
<CustomObject>
    <label>Customer Request</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CustomerRequest__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <summarizedField>InvoiceLine__c.CreditNoteAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLine__c.CustomerRequest__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CustomerRequest__c/fields/CreditNoteReason3__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteReason3__c</fullName>
    <label>Credit Note Reason 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CreditNoteReason2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CreditNoteReason3</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLine__c/InvoiceLine__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLine__c/fields/CreditNoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteAmount__c</fullName>
    <label>Credit Note Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/CustomerRequest__c.field-meta.xml
<CustomField>
    <fullName>CustomerRequest__c</fullName>
    <label>Customer Request</label>
    <referenceTo>CustomerRequest__c</referenceTo>
    <relationshipLabel>Invoices Lines</relationshipLabel>
    <relationshipName>InvoicesLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoices Lines</relationshipLabel>
    <relationshipName>InvoicesLines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/invoiceItemId__c.field-meta.xml
<CustomField>
    <fullName>invoiceItemId__c</fullName>
    <label>invoiceItemId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/LoadName__c.field-meta.xml
<CustomField>
    <fullName>LoadName__c</fullName>
    <label>Load Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLine__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ons_EntityMatchingTable__mdt/ons_EntityMatchingTable__mdt.object-meta.xml
<CustomObject>
    <label>Entity Matching Table</label>
    <pluralLabel>Entity Matching Tables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ons_EntityMatchingTable__mdt/fields/EntityCode__c.field-meta.xml
<CustomField>
    <fullName>EntityCode__c</fullName>
    <label>EntityCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SM025_CreditNoteLine.cls
/**
 * @author Soufiane LOGDALI - Comforth Karoo
 * @date 17/10/20200
 * @description Trigger SM for CreditNoteLine__c
*/

public with sharing class SM025_CreditNoteLine {

    public static void postCreditNoteLine(Set<Id> creditNoteLineIds) {
        Map<String,Map<Id,CreditNoteLineController.InvoicePostWrapper>> mapCreditNoteLine = new Map<String,Map<Id,CreditNoteLineController.InvoicePostWrapper>>{};
        Map<String,Map<Id,List<Id>>> mapCreditNoteLineIds = new Map<String,Map<Id,List<Id>>>{};
        List<CreditNoteLine__c> listCreditNoteLine = [SELECT CreditNoteAmount__c, 
                                        CreditNote__c, CreditNote__r.CustomerRequest__r.Comment__c, CreditNote__r.tech_SendCreditNoteToCustomer__c,
                                        CreditNote__r.CustomerRequest__r.CreditNoteReason3__c, CreditNote__r.CustomerRequest__r.Subsidiary__c, 
                                        InvoiceLine__r.Invoice__r.Name, InvoiceLine__r.invoiceItemId__c, InvoiceLine__r.Quantity__c, 
                                        InvoiceLine__r.LoadName__c, InvoiceLine__r.StartDate__c, InvoiceLine__r.EndDate__c 
                                        FROM CreditNoteLine__c WHERE Id IN :creditNoteLineIds];
        system.debug('postCreditNoteLine listCreditNoteLine : '+ listCreditNoteLine);
        system.debug('postCreditNoteLine listCreditNoteLine testing [0] Invoice__r.Name : '+ listCreditNoteLine[0].InvoiceLine__r.Invoice__r.Name);
        
        List<ons_EntityMatchingTable__mdt> entityMatchingTable = [SELECT Label, EntityCode__c FROM ons_EntityMatchingTable__mdt ];
        Map<String, String> entityMap = new Map<String, String>();    
        for(ons_EntityMatchingTable__mdt entity: entityMatchingTable){
            entityMap.put(entity.Label, entity.EntityCode__c);
        }
        System.debug('entityMap : '+ entityMap);

        for(CreditNoteLine__c creditNoteLine: listCreditNoteLine){
            System.debug('Subsidiary__c : '+ entityMap.get(creditNoteLine.CreditNote__r.CustomerRequest__r.Subsidiary__c));
            CreditNoteLineController.InvoiceItemsPostWrapper item = new CreditNoteLineController.InvoiceItemsPostWrapper();
            item.amount = creditNoteLine.CreditNoteAmount__c;
            item.comment = '';
            item.invoiceItemId = creditNoteLine.InvoiceLine__r.invoiceItemId__c;
            item.quantity = creditNoteLine.InvoiceLine__r.Quantity__c;
            item.serviceStartDate = String.valueOf(creditNoteLine.InvoiceLine__r.StartDate__c);
            item.serviceEndDate = String.valueOf(creditNoteLine.InvoiceLine__r.EndDate__c);
            item.skuName = creditNoteLine.InvoiceLine__r.LoadName__c;
            item.unitOfMeasure = '';

            if(mapCreditNoteLine.get(creditNoteLine.InvoiceLine__r.Invoice__r.Name) == null){
                List<CreditNoteLineController.InvoiceItemsPostWrapper> items = new List<CreditNoteLineController.InvoiceItemsPostWrapper>();
                items.add(item);

                CreditNoteLineController.InvoicePostWrapper invoicePost = new CreditNoteLineController.InvoicePostWrapper();
                invoicePost.autoApplyToInvoiceUponPosting = false;
                invoicePost.autoPost = true;
                invoicePost.visibleClient = creditNoteLine.CreditNote__r.tech_SendCreditNoteToCustomer__c ? 'Oui' : 'Non';
                invoicePost.comment = creditNoteLine.CreditNote__r.CustomerRequest__r.Comment__c;
                invoicePost.effectiveDate = (String.valueOf(date.today())).SubStringBefore(' ');
                invoicePost.taxAutoCalculation = true;
                invoicePost.excludeFromAutoApplyRules = false;
                ///invoicePost.motif = '003| AA - Avoir pour Refacturation';
                invoicePost.motif = creditNoteLine.CreditNote__r.CustomerRequest__r.CreditNoteReason3__c;
                ///invoicePost.entity = '002';
                invoicePost.entity = entityMap.get(creditNoteLine.CreditNote__r.CustomerRequest__r.Subsidiary__c);
                invoicePost.items = items;
                invoicePost.reasonCode = 'Write-off';

                mapCreditNoteLine.put(creditNoteLine.InvoiceLine__r.Invoice__r.Name, new Map<Id, CreditNoteLineController.InvoicePostWrapper>{creditNoteLine.CreditNote__c => invoicePost});
                mapCreditNoteLineIds.put(creditNoteLine.InvoiceLine__r.Invoice__r.Name, new Map<Id, List<Id>>{creditNoteLine.CreditNote__c => new List<Id> { creditNoteLine.Id }});
            } else{
                ((mapCreditNoteLine.get(creditNoteLine.InvoiceLine__r.Invoice__r.Name)).get(creditNoteLine.CreditNote__c)).items.add(item);
                ((mapCreditNoteLineIds.get(creditNoteLine.InvoiceLine__r.Invoice__r.Name)).get(creditNoteLine.CreditNote__c)).add(creditNoteLine.Id);
            }
        }

        system.debug('postCreditNoteLine mapCreditNoteLine : '+ mapCreditNoteLine);
        system.debug('postCreditNoteLine mapCreditNoteLineIds : '+ mapCreditNoteLineIds);
        

        for (String invoiceName: mapCreditNoteLine.keyset()){
            system.debug('postCreditNoteLine map loop invoiceName : '+ invoiceName);
            for (Id CreditNoteId: (mapCreditNoteLine.get(invoiceName)).keyset()){
                system.debug('postCreditNoteLine map loop CreditNoteId : '+ CreditNoteId);
                system.debug('postCreditNoteLine map loop Value : '+ (mapCreditNoteLine.get(invoiceName)).get(CreditNoteId));

                //CreditNoteLineController.postCreditNoteLine(String.valueOf((mapCreditNoteLine.get(invoiceName)).get(CreditNoteId)), invoiceName);           
                
                String invoicePost = JSON.serialize((mapCreditNoteLine.get(invoiceName)).get(CreditNoteId));  
                system.debug('Before post invoicePost : '+ invoicePost);
                system.debug('Before post invoicePost.length() : '+ invoicePost.length());

                system.debug('List Ids to send : '+ (mapCreditNoteLineIds.get(invoiceName)).get(CreditNoteId));

                CreditNoteLineController.postCreditNoteLine(invoicePost, invoiceName, (mapCreditNoteLineIds.get(invoiceName)).get(CreditNoteId));   
                
                
                for (Integer i = 0; i < invoicePost.length(); i=i+300) {
                    Integer iEffectiveEnd = (i+300 > (invoicePost.length()) ? invoicePost.length()-1 : i+300);
                    System.debug(invoicePost.substring(i,iEffectiveEnd));
                }
     
            }
        }
    }
}