unpackaged/main/default/objects/OpportunityLineItem/fields/Saas_Amount__c.field-meta.xml
<CustomField>
    <fullName>Saas_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Saas Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Saas_Amount_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Saas_Amount_Calculated__c</fullName>
    <formula>IF(
SBQQ__QuoteLine__r.TECH_Subscription_Term_Formula__c &gt; 0,
IF(
SBQQ__QuoteLine__r.TECH_Subscription_Term_Formula__c &gt; 12,
SBQQ__QuoteLine__r.SBQQ__NetTotal__c * 12 / SBQQ__QuoteLine__r.TECH_Subscription_Term_Formula__c,
SBQQ__QuoteLine__r.SBQQ__NetTotal__c
),
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saas Amount Calculated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/TECH_IsOppyPrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>TECH_IsOppyPrimaryQuote__c</fullName>
    <formula>Opportunity.SBQQ__PrimaryQuote__r.SBQQ__Primary__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Is Oppy Primary Quote</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TH_OpportunityLineItem.cls
/**
 * @author Easyfront Consulting - MLE
 * @date 28/07/2022
 * @description Trigger handler class for OpportunityLineItem
*/
public with sharing class TH_OpportunityLineItem extends TriggerHandler{
    /**
     * @author Easyfront Consulting - MLE
     * @date 28/07/2022
     * @description afterInsert logic          
    */
    public override void afterInsert() {
        Set<Id> oppIds = new Set<Id>();
        for(OpportunityLineItem oli:(List<OpportunityLineItem>)Trigger.new){    
            //US W-000834                         
            if(canTriggerByFeature('CalculateOppyEstProjectWorkload__c') && oli.TECH_IsOppyPrimaryQuote__c){
                oppIds.add(oli.OpportunityId);              
            }
        }
        
        if(!oppIds.isEmpty()){
            SM009_CalcEstProjectWorkload.calcOLIProjectWorkload(oppIds);
        }
        
    }
    
    /**
     * @author Shamina M - Comforth Karoo
     * @date 2020-11-11
     * @description beforeUpdate logic          
    */
    public override void beforeUpdate() {
        Map<Id, OpportunityLineItem> oppyLinesToBeProcess = (Map<Id, OpportunityLineItem>) CheckRecursivCall.checkRunOnce(Trigger.newMap, System.TriggerOperation.BEFORE_UPDATE);
        computeSaasAmount(oppyLinesToBeProcess.values());
    }

    /**
     * @author Easyfront Consulting - MLE
     * @date 28/07/2022
     * @description afterUpdate logic          
    */
    public override void afterUpdate() {
        system.debug('AFTER UPDATE HERE !!');
        Set<Id> oppIds = new Set<Id>();
        for(OpportunityLineItem oli:(List<OpportunityLineItem>)Trigger.new){ 
            OpportunityLineItem oldOppLine = (OpportunityLineItem)trigger.oldMap.get(oli.Id);
            //US W-000834                         
            if(canTriggerByFeature('CalculateOppyEstProjectWorkload__c') && oli.TECH_IsOppyPrimaryQuote__c && oli.TECH_IsOppyPrimaryQuote__c != oldOppLine.TECH_IsOppyPrimaryQuote__c){
                oppIds.add(oli.OpportunityId);    
                system.debug('oli.OpportunityId '+oli.OpportunityId);
            }
        }
        
        if(!oppIds.isEmpty()){
            SM009_CalcEstProjectWorkload.calcOLIProjectWorkload(oppIds);
        }
    }
    
    /**
     * @author Easyfront Consulting - MLE
     * @date 28/07/2022
     * @description afterDelete logic          
    */
    public override void afterDelete() {
        Set<Id> oppIds = new Set<Id>();
        for(OpportunityLineItem oli:(List<OpportunityLineItem>)Trigger.old){    
            //US W-000834                         
            if(canTriggerByFeature('CalculateOppyEstProjectWorkload__c') && oli.TECH_IsOppyPrimaryQuote__c){
                oppIds.add(oli.OpportunityId);              
            }
        }
        
        if(!oppIds.isEmpty()){
            SM009_CalcEstProjectWorkload.calcOLIProjectWorkload(oppIds);
        }
    }
    
    public void computeSaasAmount(List<OpportunityLineItem> oppLines) {
        for(OpportunityLineItem oppLine : oppLines) {
            oppLine.Saas_Amount__c = oppLine.Saas_Amount_Calculated__c;
        }
    }

}