unpackaged/main/default/objects/Attached_Document__c/Attached_Document__c.object-meta.xml
<CustomObject>
    <label>Attached Document</label>
    <nameField>
        <label>Attached Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attached Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attached_Document__c/fields/Document_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Link__c</fullName>
    <label>Document Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/StructureLevel1__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel1__c</fullName>
    <description>Used to link the Documents with the right Products</description>
    <label>StructureLevel1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StructureLevel1</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/StructureLevel2__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel2__c</fullName>
    <description>Used to link the Documents with the right Products</description>
    <label>StructureLevel2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StructureLevel1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel2</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/StructureLevel2__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel2__c</fullName>
    <description>Structure d'activité NIV 2</description>
    <label>StructureLevel2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel2</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/globalValueSets/StructureLevel1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>Licenses</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>Maintenance</label>
    </customValue>
    <customValue>
        <fullName>130</fullName>
        <label>Saas</label>
    </customValue>
    <customValue>
        <fullName>140</fullName>
        <label>Professional services</label>
    </customValue>
    <customValue>
        <fullName>190</fullName>
        <label>Hardware</label>
    </customValue>
    <customValue>
        <fullName>400</fullName>
        <isActive>false</isActive>
        <label>Prestation Distributeur</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Assistance Progiciel</label>
    </customValue>
    <customValue>
        <fullName>550</fullName>
        <isActive>false</isActive>
        <label>Assistance Système</label>
    </customValue>
    <customValue>
        <fullName>750</fullName>
        <isActive>false</isActive>
        <label>Location</label>
    </customValue>
    <customValue>
        <fullName>800</fullName>
        <isActive>false</isActive>
        <label>Outsourcing</label>
    </customValue>
    <customValue>
        <fullName>900</fullName>
        <isActive>false</isActive>
        <label>Divers</label>
    </customValue>
    <customValue>
        <fullName>M01</fullName>
        <isActive>false</isActive>
        <label>Marketing - Cegid Planning</label>
    </customValue>
    <customValue>
        <fullName>700</fullName>
        <isActive>false</isActive>
        <label>Consommable</label>
    </customValue>
    <customValue>
        <fullName>300</fullName>
        <isActive>false</isActive>
        <label>Prestation Editeur</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <isActive>false</isActive>
        <label>Logiciel</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <isActive>false</isActive>
        <label>Progiciel</label>
    </customValue>
    <customValue>
        <fullName>000</fullName>
        <isActive>false</isActive>
        <label>Matériel</label>
    </customValue>
    <customValue>
        <fullName>Hardware and Other</fullName>
        <isActive>false</isActive>
        <label>Hardware and Other</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>StructureLevel1</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/APB001_InsertTermsLinkToProduct.cls
/**
* @author Easyfront
* @date 23/01/2023
* @description : Use to insert the Attached Document link on related product
*/
global without sharing class APB001_InsertTermsLinkToProduct implements Database.Batchable<sObject> {
    global List<Attached_Document__c> listAttachedDoc;
    global Map<String,Set<String>> mapDocumentLinks;
    global Set<String> setStruc1;
    global Set<String> setStruc2;
    
    global APB001_InsertTermsLinkToProduct(List<Attached_Document__c> listAttachedDoc){
        Set<String> setStruc1 = new Set<String>();
        Set<String> setStruc2 = new Set<String>();
        Map<String,Set<String>> mapDocumentLinks = new Map<String,Set<String>>();
        
        //Get Struture Level 1 & 2 to retreive all related attached documents & products
        for(Attached_Document__c attDoc:listAttachedDoc){
            setStruc1.add(attDoc.StructureLevel1__c);
            if(attDoc.StructureLevel2__c != null){
                setStruc2.add(attDoc.StructureLevel2__c);
            }
            mapDocumentLinks.put('Lvl1_'+attDoc.StructureLevel1__c+'Lvl2_'+attDoc.StructureLevel2__c, new Set<String>()); //Init map (included deleted documents)
        }
        List<Attached_Document__c> listAttachedDocuments = [SELECT Id, StructureLevel1__c, StructureLevel2__c, Document_Link__c FROM Attached_Document__c 
                                                            WHERE StructureLevel1__c IN: setStruc1 AND RecordTypeId =: TH_AttachedDocument.rtGeneralTerms];
        if(!listAttachedDocuments.isEmpty()){
            for(Attached_Document__c attDoc:listAttachedDocuments){
                 if(attDoc.StructureLevel2__c != null){
                        if(mapDocumentLinks.containsKey('Lvl1_'+attDoc.StructureLevel1__c+'Lvl2_'+attDoc.StructureLevel2__c)){
                            mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c+'Lvl2_'+attDoc.StructureLevel2__c).add(attDoc.Document_Link__c);
                        }else{
                            mapDocumentLinks.put('Lvl1_'+attDoc.StructureLevel1__c+'Lvl2_'+attDoc.StructureLevel2__c, new Set<String>{attDoc.Document_Link__c});
                        }
                 }else{
                     if(mapDocumentLinks.containsKey('Lvl1_'+attDoc.StructureLevel1__c)){
                         mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c).add(attDoc.Document_Link__c);
                     }else{
                         mapDocumentLinks.put('Lvl1_'+attDoc.StructureLevel1__c, new Set<String>{attDoc.Document_Link__c});
                     }
                 }
            }
        }
        
        //Assign variables
        this.mapDocumentLinks = mapDocumentLinks;
        this.setStruc1 = setStruc1;
        this.setStruc2 = setStruc2;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Get products for these Structure Level 1 & 2
        if(!setStruc2.isEmpty()){
            return Database.getQueryLocator([SELECT id , name, Family, StructureLevel2__c, General_Terms_And_Conditions__c from product2 
                                             WHERE Family IN:setStruc1 
                                             AND IsActive = true
                                             AND StructureLevel2__c IN:setStruc2
                                             AND RecordTypeId =: TH_AttachedDocument.rtProduct]);  
        }else{
            return Database.getQueryLocator([SELECT id , name, Family, StructureLevel2__c, General_Terms_And_Conditions__c from product2 
                                             WHERE Family IN:setStruc1 
                                             AND IsActive = true
                                             AND RecordTypeId =: TH_AttachedDocument.rtProduct]);  
        }
        
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        system.debug('scope batch >>>> '+scope);
        if(!scope.isEmpty()){
           SM005_AttachedDocument.insertGeneralTermsAndConditionsLinkToProduct(mapDocumentLinks, scope);
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
    
}