unpackaged/main/default/objects/Attached_Document__c/Attached_Document__c.object-meta.xml
<CustomObject>
    <label>Attached Document</label>
    <nameField>
        <label>Attached Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attached Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attached_Document__c/fields/Document_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Link__c</fullName>
    <label>Document Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Attached Documents</relationshipLabel>
    <relationshipName>Attached_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <label>Service Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/StructureLevel1__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel1__c</fullName>
    <description>Used to link the Documents with the right Products</description>
    <label>StructureLevel1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StructureLevel1</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/StructureLevel2__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel2__c</fullName>
    <description>Used to link the Documents with the right Products</description>
    <label>StructureLevel2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StructureLevel1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel2</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/recordTypes/General_Terms_And_Conditions.recordType-meta.xml
<RecordType>
    <fullName>General_Terms_And_Conditions</fullName>
    <active>true</active>
    <label>General Terms and Conditions</label>
</RecordType>

unpackaged/main/default/objects/Attached_Document__c/recordTypes/Service_Book.recordType-meta.xml
<RecordType>
    <fullName>Service_Book</fullName>
    <active>true</active>
    <label>Service Book</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Product Line is inactive.</errorMessage>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Book__c.field-meta.xml
<CustomField>
    <fullName>Service_Book__c</fullName>
    <label>Service Book</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Levels__c.field-meta.xml
<CustomField>
    <fullName>Service_Levels__c</fullName>
    <label>Service Levels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/StructureLevel2__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel2__c</fullName>
    <description>Structure d'activité NIV 2</description>
    <label>StructureLevel2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>StructureLevel2</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/TECHServiceBook__c.field-meta.xml
<CustomField>
    <fullName>TECHServiceBook__c</fullName>
    <label>TECH_Service Book</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/StructureLevel1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>Licenses</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>Maintenance</label>
    </customValue>
    <customValue>
        <fullName>130</fullName>
        <label>Saas</label>
    </customValue>
    <customValue>
        <fullName>140</fullName>
        <label>Professional services</label>
    </customValue>
    <customValue>
        <fullName>190</fullName>
        <label>Hardware</label>
    </customValue>
    <customValue>
        <fullName>400</fullName>
        <isActive>false</isActive>
        <label>Prestation Distributeur</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Assistance Progiciel</label>
    </customValue>
    <customValue>
        <fullName>550</fullName>
        <isActive>false</isActive>
        <label>Assistance Système</label>
    </customValue>
    <customValue>
        <fullName>750</fullName>
        <isActive>false</isActive>
        <label>Location</label>
    </customValue>
    <customValue>
        <fullName>800</fullName>
        <isActive>false</isActive>
        <label>Outsourcing</label>
    </customValue>
    <customValue>
        <fullName>900</fullName>
        <isActive>false</isActive>
        <label>Divers</label>
    </customValue>
    <customValue>
        <fullName>M01</fullName>
        <isActive>false</isActive>
        <label>Marketing - Cegid Planning</label>
    </customValue>
    <customValue>
        <fullName>700</fullName>
        <isActive>false</isActive>
        <label>Consommable</label>
    </customValue>
    <customValue>
        <fullName>300</fullName>
        <isActive>false</isActive>
        <label>Prestation Editeur</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <isActive>false</isActive>
        <label>Logiciel</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <isActive>false</isActive>
        <label>Progiciel</label>
    </customValue>
    <customValue>
        <fullName>000</fullName>
        <isActive>false</isActive>
        <label>Matériel</label>
    </customValue>
    <customValue>
        <fullName>Hardware and Other</fullName>
        <isActive>false</isActive>
        <label>Hardware and Other</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>StructureLevel1</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM015_FindCorrectAttachedDocument.cls
/**
* @author Keshav - Comforth
* @date 2021-19-01
* @modified 
* @group TH_Product2
* @object Product2
* @description 
*/
public class SM015_FindCorrectAttachedDocument {

    public static void updateLinkProduct(Set<Id> setProductIds){
        system.debug('updateLinkProduct');
        // Retrieve the RecordType Ids
        Id rtGeneralTerms = Schema.SObjectType.Attached_Document__c.getRecordTypeInfosByDeveloperName().get('General_Terms_And_Conditions').getRecordTypeId();    
        Id rtServiceBook = Schema.SObjectType.Attached_Document__c.getRecordTypeInfosByDeveloperName().get('Service_Book').getRecordTypeId();
        List<Product2> listProdToUpdate = new List<Product2>();
        List<Attached_Document__c> listAttDoc = new List<Attached_Document__c>();
        Set<String> setStruc1 = new Set<String>();
        Set<String> setStruc2 = new Set<String>();
        Set<Id> setProductLine = new Set<Id>();
        Set<String> setServiceLevel = new Set<String>();

        List<Product2> listProduct2 = [SELECT Id,Name,Family,StructureLevel2__c,General_Terms_And_Conditions__c,Product_Line__c,Service_Levels__c  From Product2 where Id IN :setProductIds];

        for(Product2 pro:listProduct2){
            setStruc1.add(pro.Family);
            setStruc2.add(pro.StructureLevel2__c);
            String productService = pro.Service_Levels__c;
            setServiceLevel.addAll(productService.split(';'));
            setProductLine.add(pro.Product_Line__c);
        }

        if(setStruc1.size()>0 && setStruc2.size()>0){

            set<String> setDocLink = new set<String>();

            for(Product2 p:listProduct2){
                p.General_Terms_And_Conditions__c = null;
                for(Attached_Document__c attDoc:[SELECT Id,StructureLevel1__c,StructureLevel2__c,Document_Link__c 
                FROM Attached_Document__c  WHERE StructureLevel1__c IN:setStruc1 AND StructureLevel2__c IN:setStruc2 AND RecordTypeId =:rtGeneralTerms]){

                    if(attDoc.Document_Link__c != null){
                        setDocLink.add(attDoc.Document_Link__c);
                    }

                    if(p.Family == attDoc.StructureLevel1__c && p.StructureLevel2__c == attDoc.StructureLevel2__c ){
                        p.General_Terms_And_Conditions__c = String.join(new List<String>(setDocLink),';');
                    }else{
                        p.General_Terms_And_Conditions__c = null;
                    }
                }
            }

            
        }

        if(setStruc1.size()>0 && setServiceLevel.Size()>0 && setProductLine.size()>0){

            List<String> listService = new List<String>(setServiceLevel);
            List<Attached_Document__c> listAttch = new List<Attached_Document__c>();
            String queryString = 'SELECT Id,Name,StructureLevel1__c,StructureLevel2__c,Document_Link__c,Service_Level__c,Product_Line__c from Attached_Document__c WHERE StructureLevel1__c IN :setStruc1 AND RecordTypeId =:rtServiceBook AND Product_Line__c IN :setProductLine AND Service_Level__c INCLUDES(';
            for(String includeValue :listService)
            queryString += '\'' + includeValue + '\'' + ',';
            queryString = queryString.removeEnd(',') +')';
            system.debug('queryString' + queryString);
            listAttch = (List<Attached_Document__c>)Database.query(queryString);

            system.debug('listAttachedDoc ' + listAttch);

            for(Product2 p:listProduct2){
                for(Attached_Document__c attachedDoc:listAttch){
                  

                    set<String> setDocLink = new set<String>();
                    if(attachedDoc.Document_Link__c != null){
                        setDocLink.add(attachedDoc.Document_Link__c);
                    }

                    if(attachedDoc.StructureLevel1__c == p.Family && attachedDoc.Product_Line__c == p.Product_Line__c){
                        p.TECHServiceBook__c = String.join(new List<String>(setDocLink),';');
                        p.Service_Book__c = '';
                        for(String docLink:setDocLink){
                            p.Service_Book__c += p.Service_Book__c +  '<a href="'+ docLink +'">' + attachedDoc.Name +'</a><BR/>';
                        }
                    }
                }
            }
        }

        if(listProduct2.Size() > 0){
            update listProduct2;
        }

    }

}