unpackaged/main/default/objects/Attached_Document__c/Attached_Document__c.object-meta.xml
<CustomObject>
    <label>Attached Document</label>
    <nameField>
        <label>Attached Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attached Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attached_Document__c/fields/Document_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Link__c</fullName>
    <label>Document Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Attached Documents</relationshipLabel>
    <relationshipName>Attached_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <label>Service Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attached_Document__c/fields/StructureLevel1__c.field-meta.xml
<CustomField>
    <fullName>StructureLevel1__c</fullName>
    <description>Used to link the Documents with the right Products</description>
    <label>StructureLevel1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StructureLevel1</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Product Line is inactive.</errorMessage>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Book__c.field-meta.xml
<CustomField>
    <fullName>Service_Book__c</fullName>
    <label>Service Book</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Service_Levels__c.field-meta.xml
<CustomField>
    <fullName>Service_Levels__c</fullName>
    <label>Service Levels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ServiceLevel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/TECHServiceBook__c.field-meta.xml
<CustomField>
    <fullName>TECHServiceBook__c</fullName>
    <label>TECH_Service Book</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/StructureLevel1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>Licenses</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>Maintenance</label>
    </customValue>
    <customValue>
        <fullName>130</fullName>
        <label>Saas</label>
    </customValue>
    <customValue>
        <fullName>140</fullName>
        <label>Professional services</label>
    </customValue>
    <customValue>
        <fullName>190</fullName>
        <label>Hardware</label>
    </customValue>
    <customValue>
        <fullName>400</fullName>
        <isActive>false</isActive>
        <label>Prestation Distributeur</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Assistance Progiciel</label>
    </customValue>
    <customValue>
        <fullName>550</fullName>
        <isActive>false</isActive>
        <label>Assistance Système</label>
    </customValue>
    <customValue>
        <fullName>750</fullName>
        <isActive>false</isActive>
        <label>Location</label>
    </customValue>
    <customValue>
        <fullName>800</fullName>
        <isActive>false</isActive>
        <label>Outsourcing</label>
    </customValue>
    <customValue>
        <fullName>900</fullName>
        <isActive>false</isActive>
        <label>Divers</label>
    </customValue>
    <customValue>
        <fullName>M01</fullName>
        <isActive>false</isActive>
        <label>Marketing - Cegid Planning</label>
    </customValue>
    <customValue>
        <fullName>700</fullName>
        <isActive>false</isActive>
        <label>Consommable</label>
    </customValue>
    <customValue>
        <fullName>300</fullName>
        <isActive>false</isActive>
        <label>Prestation Editeur</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <isActive>false</isActive>
        <label>Logiciel</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <isActive>false</isActive>
        <label>Progiciel</label>
    </customValue>
    <customValue>
        <fullName>000</fullName>
        <isActive>false</isActive>
        <label>Matériel</label>
    </customValue>
    <customValue>
        <fullName>Hardware and Other</fullName>
        <isActive>false</isActive>
        <label>Hardware and Other</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>StructureLevel1</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/APB002_InsertServiceBookLinkToProduct.cls
/**
* @author Easyfront
* @date 23/01/2023
* @description : Use to insert the Attached Document link on related product
*/
global without sharing class APB002_InsertServiceBookLinkToProduct implements Database.Batchable<sObject> {
    global List<Attached_Document__c> listAttachedDoc;
    global Map<String,Map<String,Set<String>>> mapDocumentLinks;
    global Map<String,String> mapDocumentNameLink;
    global Set<String> setStruc1;
    global Set<String> setProductLine;
    global Set<String> setServiceLevel;
    
    global APB002_InsertServiceBookLinkToProduct(List<Attached_Document__c> listAttachedDoc){
        Set<String> setStruc1 = new Set<String>();
        Set<String> setProductLine = new Set<String>();
        Map<String,Map<String,Set<String>>> mapDocumentLinks = new Map<String,Map<String,Set<String>>>();
        Map<String,String> mapDocumentNameLink = new Map<String,String>();
        
        //Get Struture Level 1 & Product Lines to retreive all related attached documents & products
        for(Attached_Document__c attDoc:listAttachedDoc){
            setStruc1.add(attDoc.StructureLevel1__c);
            setProductLine.add(attDoc.Product_Line__c);
            mapDocumentLinks.put('Lvl1_'+attDoc.StructureLevel1__c+'Pl_'+attDoc.Product_Line__c, new Map<String,Set<String>>()); //Init map (included deleted documents)
        }
        //Get all Attached Documents for these Structure Level 1 and Product Lines
        List<Attached_Document__c> listAttachedDocuments = [SELECT Id, StructureLevel1__c, Product_Line__c, Service_Level__c, Name, Document_Link__c FROM Attached_Document__c 
                                                            WHERE StructureLevel1__c IN: setStruc1 AND Product_Line__c IN: setProductLine  AND RecordTypeId =: TH_AttachedDocument.rtServiceBook];
        if(!listAttachedDocuments.isEmpty()){
            for(Attached_Document__c attDoc:listAttachedDocuments){
                mapDocumentNameLink.put(attDoc.Document_Link__c, attDoc.Name);
                if(attDoc.Service_Level__c != null){
                    for(String serlvl:attDoc.Service_Level__c.split(';')){
                        if(mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c+'Pl_'+attDoc.Product_Line__c).containsKey(serlvl)){
                            mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c+'Pl_'+attDoc.Product_Line__c).get(serlvl).add(attDoc.Document_Link__c);
                        }else{
                            mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c+'Pl_'+attDoc.Product_Line__c).put(serlvl, new Set<String>{attDoc.Document_Link__c});
                        }
                    }
                }else{
                    if(mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c+'Pl_'+attDoc.Product_Line__c).containsKey('EmptyIsAll')){
                        mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c+'Pl_'+attDoc.Product_Line__c).get('EmptyIsAll').add(attDoc.Document_Link__c);
                    }else{
                        mapDocumentLinks.get('Lvl1_'+attDoc.StructureLevel1__c+'Pl_'+attDoc.Product_Line__c).put('EmptyIsAll', new Set<String>{attDoc.Document_Link__c});
                    }
                }
            }
        }
        
        //Assign variables
        this.mapDocumentLinks = mapDocumentLinks;
        this.setStruc1 = setStruc1;
        this.setProductLine = setProductLine;
        this.mapDocumentNameLink = mapDocumentNameLink;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        return Database.getQueryLocator([SELECT id , name, Family, Service_Levels__c,TECHServiceBook__c, Service_Book__c,Product_Line__c 
                                         from product2 
                                         WHERE Family IN :setStruc1 
                                         AND IsActive = true
                                         AND Product_Line__c IN :setProductLine 
                                         AND RecordTypeId =: TH_AttachedDocument.rtProduct]);  
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        system.debug('scope batch >>>> '+scope);
        if(!scope.isEmpty()){
           SM005_AttachedDocument.insertServiceBookLinkToProduct(mapDocumentLinks, mapDocumentNameLink, scope);
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
    
}