unpackaged/main/default/objects/Account_Expertise__c/Account_Expertise__c.object-meta.xml
<CustomObject>
    <label>Account Expertise</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Expertise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expertises</relationshipLabel>
    <relationshipName>Account_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Account_Expertise__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AccountCoreBusiness__c/AccountCoreBusiness__c.object-meta.xml
<CustomObject>
    <label>Account Core Business</label>
    <nameField>
        <displayFormat>ACB-{000000}</displayFormat>
        <label>Account Core Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Core Business</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AccountCoreBusiness__c/fields/AccountExpertise__c.field-meta.xml
<CustomField>
    <fullName>AccountExpertise__c</fullName>
    <label>Account Expertise</label>
    <referenceTo>Account_Expertise__c</referenceTo>
    <relationshipLabel>Account Core Business</relationshipLabel>
    <relationshipName>Account_Core_Business</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AccountCoreBusiness__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <description>Agency (SRC) for OneNoteS Project</description>
    <label>Agency</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Agency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agency__c/fields/API_Code__c.field-meta.xml
<CustomField>
    <fullName>API_Code__c</fullName>
    <externalId>true</externalId>
    <label>API Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <defaultValue>"005"</defaultValue>
    <description>Used for Additionnal Order - W-002451</description>
    <label>Channel</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/CommercialOrganization__c.field-meta.xml
<CustomField>
    <fullName>CommercialOrganization__c</fullName>
    <label>Commercial Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commercial_Organization</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Job</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Oppy_AutoCreated__c.field-meta.xml
<CustomField>
    <fullName>Oppy_AutoCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oppy AutoCreated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Oppy_converted_from_Lead__c.field-meta.xml
<CustomField>
    <fullName>Oppy_converted_from_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Opportunity is created after a Lead conversion, the field is checked.
Otherwise, it's unchecked.</description>
    <label>Oppy converted from Lead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Expertise__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sales_Purpose__c</fullName>
    <label>Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Purpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SubSalesPurpose__c.field-meta.xml
<CustomField>
    <fullName>SubSalesPurpose__c</fullName>
    <label>Sub Sales Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSalesPurpose</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TECHOwnerCalculated__c.field-meta.xml
<CustomField>
    <fullName>TECHOwnerCalculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECHOwnerCalculated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TerritoryCode__c.field-meta.xml
<CustomField>
    <fullName>TerritoryCode__c</fullName>
    <label>Territory Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Oppy Sales Process</businessProcess>
    <description>'Classic' Opportunity</description>
    <label>Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Line__c/fields/Core__c.field-meta.xml
<CustomField>
    <fullName>Core__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Core</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product_Line__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/CommercialOrganization__c.field-meta.xml
<CustomField>
    <fullName>CommercialOrganization__c</fullName>
    <label>Commercial Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commercial_Organization</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Job</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Territory2/fields/TerritoryCode__c.field-meta.xml
<CustomField>
    <fullName>TerritoryCode__c</fullName>
    <label>Territory Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <label>Direct Sales Force</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Indirect Sales Force</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Inside Sales</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Consultants</label>
    </customValue>
    <customValue>
        <fullName>006</fullName>
        <label>C.A.T.</label>
    </customValue>
    <customValue>
        <fullName>007</fullName>
        <label>Non-activity sales</label>
    </customValue>
    <customValue>
        <fullName>008</fullName>
        <label>Intra-group sales</label>
    </customValue>
    <customValue>
        <fullName>009</fullName>
        <label>Interactive sales</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Expertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>110</fullName>
        <label>CPA</label>
    </customValue>
    <customValue>
        <fullName>350</fullName>
        <label>ERP High</label>
    </customValue>
    <customValue>
        <fullName>340</fullName>
        <label>ERP Middle</label>
    </customValue>
    <customValue>
        <fullName>320</fullName>
        <label>HCM</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>SMB</label>
    </customValue>
    <customValue>
        <fullName>310</fullName>
        <label>TAX</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>Out of Expertise</label>
    </customValue>
    <customValue>
        <fullName>360</fullName>
        <label>Treasury</label>
    </customValue>
    <customValue>
        <fullName>370</fullName>
        <label>Banking</label>
    </customValue>
    <customValue>
        <fullName>380</fullName>
        <label>Talent</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <isActive>false</isActive>
        <label>Education</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <isActive>false</isActive>
        <label>Portail TPE</label>
    </customValue>
    <masterLabel>Expertise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Job.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>099</fullName>
        <label>IA</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>IC</label>
    </customValue>
    <customValue>
        <fullName>101</fullName>
        <label>DA</label>
    </customValue>
    <customValue>
        <fullName>102</fullName>
        <label>DV</label>
    </customValue>
    <customValue>
        <fullName>103</fullName>
        <label>BUSINESS DEVELOPPER</label>
    </customValue>
    <customValue>
        <fullName>105</fullName>
        <label>-- Generic Sales Engineer</label>
    </customValue>
    <customValue>
        <fullName>107</fullName>
        <label>INSIDES SALES</label>
    </customValue>
    <customValue>
        <fullName>108</fullName>
        <label>Head of Telesales Group</label>
    </customValue>
    <customValue>
        <fullName>109</fullName>
        <label>CONSULTANT</label>
    </customValue>
    <customValue>
        <fullName>110</fullName>
        <label>Customer Service</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Sedentary Commercial</label>
    </customValue>
    <customValue>
        <fullName>113</fullName>
        <label>Sales Engineer Hunting</label>
    </customValue>
    <customValue>
        <fullName>114</fullName>
        <label>Sales Engineer Installed base</label>
    </customValue>
    <customValue>
        <fullName>115</fullName>
        <label>Mixed Sales Engineer</label>
    </customValue>
    <customValue>
        <fullName>116</fullName>
        <label>Sales Engineer CPA-Collaborative &amp; Presc</label>
    </customValue>
    <customValue>
        <fullName>117</fullName>
        <label>Sales Engineer CPA Migration SAAS</label>
    </customValue>
    <customValue>
        <fullName>118</fullName>
        <label>IS CPA Collaboratif &amp; Presc</label>
    </customValue>
    <customValue>
        <fullName>119</fullName>
        <label>IS CPA Migration SAAS</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>Customer Sucess</label>
    </customValue>
    <customValue>
        <fullName>999</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Digital CSM</label>
    </customValue>
    <customValue>
        <fullName>122</fullName>
        <label>SDR</label>
    </customValue>
    <customValue>
        <fullName>123</fullName>
        <label>ICS</label>
    </customValue>
    <masterLabel>Job</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sales_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>999</fullName>
        <label>All Sales Purpose</label>
    </customValue>
    <customValue>
        <fullName>121</fullName>
        <label>Cross-Sell</label>
    </customValue>
    <customValue>
        <fullName>613</fullName>
        <label>Migration OP/OP</label>
    </customValue>
    <customValue>
        <fullName>611</fullName>
        <label>Migration OP/SaaS</label>
    </customValue>
    <customValue>
        <fullName>612</fullName>
        <label>Migration SaaS/SaaS</label>
    </customValue>
    <customValue>
        <fullName>111</fullName>
        <label>Newcli</label>
    </customValue>
    <customValue>
        <fullName>511</fullName>
        <label>Renew</label>
    </customValue>
    <customValue>
        <fullName>411</fullName>
        <label>Upsell only</label>
    </customValue>
    <customValue>
        <fullName>To define</fullName>
        <isActive>false</isActive>
        <label>To define</label>
    </customValue>
    <masterLabel>Sales Purpose</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/SubSalesPurpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Upsell Only - More of the same</fullName>
    </customValue>
    <customValue>
        <fullName>Upsell Only - New Product</fullName>
    </customValue>
    <masterLabel>Sub Sales Purpose</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SM001_Opportunity.cls
/**
* @author Keshav - Comforth
* @date Creation 17 Jan-2020
* @description SM001_Opportunity
*              Assign Opportunity OWner based upon Territory
*/ 
/**
 * @File Name          : SM001_Opportunity
 * @Description        : Update owner field based on territory when an opportunity is created from a contact
 * @Author             : SRA   
 * @Group              : Comforth-Karoo
 * @Last Modified By   : SRA
 * @Last Modified On   : 31/07/2020
 * @Modification Log   : 
 * Ver       Date            Author                 Modification
 * ---    -----------       -------           ------------------------ 
 * 1.0    31/07/2020         SRA              Initial Version
 * ---    -----------       -------           ------------------------ 
**/
public class SM001_Opportunity {
    private static final String TERRITORY = 'Territory';
    private static final String TERRITORY_ASSOCIATION_MANUAL = 'Territory2AssociationManual';
    private static final String NO_TERRITORY = 'No Territory';
    private static final String OPPORTUNITY_OWNER = 'Opportunity Owner';
    
    @future
    public static void setOppOwner(set<Id> setOppId, set<Id> setAccId){
        
        //system.debug('listOppId'+setOppId);
        
        List<Opportunity> listOpp = [Select Id ,Name,Oppy_AutoCreated__c,AccountId,Territory2Id,Expertise__c,Oppy_converted_from_Lead__c from Opportunity where Id IN:setOppId ];
        system.debug('listOpp'+listOpp);
        
        // Create Set which store Account Territory Id
        Territory2 territoryObj = new Territory2();
        Set<Id> setAccTerritoryIds = new Set<Id>();
        Set<opportunity> setOpportunityUpdate = new Set<opportunity>();
        List<Opportunity> listOpportunityToUpdate = new List<Opportunity>();
        List<Opportunity> result = new List<Opportunity>();
        Map<Id, List<Id>> mapAccountShare = new Map<Id, List<Id>>();
        set<Id> userOrGroupIds = new set<Id>();
        Map<Id, Id> mapGroup = new Map<Id, Id>();
        Map<Id, Territory2> mapUserTerritory = new Map<Id, Territory2>();
        Map<Id, UserTerritory2Association> mapUserTerritory2Association = new Map<Id,UserTerritory2Association>();
        
        // Query in Account Share object
        for(AccountShare objAcctShare : [SELECT Id, UserOrGroupId, AccountId 
                                         FROM AccountShare 
                                         WHERE (RowCause =:TERRITORY OR RowCause =:TERRITORY_ASSOCIATION_MANUAL) 
                                         AND AccountId IN :setAccId]){
                                             system.debug('objAcctShare'+objAcctShare);
                                             if(mapAccountShare.containsKey(objAcctShare.AccountId)){
                                                 mapAccountShare.get(objAcctShare.AccountId).add(objAcctShare.UserOrGroupId);
                                             }else{
                                                 mapAccountShare.put(objAcctShare.AccountId, new List<Id>{objAcctShare.UserOrGroupId});
                                             }
                                             
                                             userOrGroupIds.add(objAcctShare.UserOrGroupId);
                                             
                                         }  
        //system.debug('userOrGroupIds'+userOrGroupIds);
        // Query in Group object from where access RelatedId
        // Map of Group object
        for(Group objGroupRecord : [SELECT Id,Name, RelatedId ,DeveloperName 
                                    FROM Group 
                                    WHERE Type =:TERRITORY 
                                    AND Id IN : userOrGroupIds]){
                                        system.debug('objGroupRecord'+objGroupRecord);
            mapGroup.put(objGroupRecord.Id, objGroupRecord.RelatedId);         
        }
        //system.debug('mapGroup'+mapGroup);
        // Populate Territory details of assigned Territory of Account.
        // Query in Territory object
        Map<Id, Territory2> mapTerritories = new Map<Id, Territory2>([SELECT Id, Name, ParentTerritory2Id, ForecastUserId, Description, Agency__c,
                                                                      BU__c,Channel__c,CommercialOrganization__c,Job__c,Sales_Region__c,TerritoryCode__c,Expertise__c
                                                                      FROM Territory2 
                                                                      WHERE Id IN:mapGroup.Values() And Expertise__c=:listOpp[0].Expertise__c]);
        
        //system.debug('mapTerritories'+mapTerritories);
        // If the Id of NO TERRITORY is found on the Opp the owner of the opp will stay the same
        List<Territory2> listTerritory2 = [SELECT Id,DeveloperName ,Name 
                                           FROM Territory2 
                                           WHERE Name =:NO_TERRITORY limit 1];

        for(UserTerritory2Association uts:[SELECT Id, RoleInTerritory2, Territory2Id, UserId 
                                           FROM UserTerritory2Association  
                                           WHERE Territory2Id IN:mapTerritories.keySet() 
                                           AND  RoleInTerritory2 =:OPPORTUNITY_OWNER]){
            mapUserTerritory2Association.put(uts.Territory2Id,uts);
        }
        //system.debug('mapUserTerritory2Association'+mapUserTerritory2Association);
        
        for(Opportunity opp:listOpp){
            //system.debug('opp'+opp);
            if(mapAccountShare.containsKey(opp.AccountId)){
                for(Id userGroupId: mapAccountShare.get(opp.AccountId)){
                    //system.debug('userGroupId'+userGroupId);
                    Id territoryId = mapGroup.get(userGroupId);
    
                    if(mapTerritories.containsKey(territoryId)){
                        territoryObj = mapTerritories.get(territoryId);
                    }
                    else{
                        territoryObj = mapTerritories.get(opp.Territory2Id);
                    }
                    //system.debug('opp.Oppy_AutoCreated__c'+opp.Oppy_AutoCreated__c);
                    //system.debug('opp.Territory2Id'+opp.Territory2Id);
                    //system.debug('territoryObj'+territoryObj);
                    //system.debug('listTerritory2'+listTerritory2);
                    if(opp.Oppy_AutoCreated__c == true || (opp.Territory2Id != listTerritory2[0].Id && opp.Territory2Id != null && opp.Territory2Id == territoryObj.Id)){
                        if(territoryObj != null && mapUserTerritory2Association.get(territoryObj.Id) != null){ 
                            system.debug('territoryObj'+territoryObj);
                            system.debug('mapUserTerritory2Association'+mapUserTerritory2Association);
                            UserTerritory2Association ut2a = mapUserTerritory2Association.get(territoryObj.Id);
                            if(opp.Oppy_converted_from_Lead__c ){
                                opp.TECHOwnerCalculated__c = true;
                            }
                            opp.OwnerId = ut2a.UserId;
                            //removed from Process builder 
                            opp.BU__c = territoryObj.BU__c;
                            opp.CommercialOrganization__c = territoryObj.CommercialOrganization__c;
                            opp.Agency__c =territoryObj.Agency__c;
                            opp.Job__c = territoryObj.Job__c;
                            opp.Channel__c = territoryObj.Channel__c;
                            opp.Sales_Region__c = territoryObj.Sales_Region__c;
                            
                            listOpportunityToUpdate.add(opp);
                        }
                    } else if(opp.Territory2Id == listTerritory2[0].Id && opp.Territory2Id != null){
                        //System.debug('***ESLE IF');
                        if(opp.Oppy_converted_from_Lead__c ){
                            opp.TECHOwnerCalculated__c = true;
                            listOpportunityToUpdate.add(opp);
                        }
                    }
                    
                }
            }
        }
        setOpportunityUpdate.addAll(listOpportunityToUpdate);
        result.addAll(setOpportunityUpdate);
        if(result.size()>0){
            update result;
        }
    }
    
    /**
 	* @author Easyfront Consulting
 	* @date 2023-04-26
 	* @description Method to calculate "Sub Sales Purpose" on Opportunity for Upsell Only Sales Purpose
    * @details Call by TH_Opportunity > W-002573
	*/
    public static void calculateOpportunitySubSalesPurpose(Set<Id> setOppIds){
        Set<String> setProductLineCode = new Set<String>();
        Set<Id> setAccountId = new Set<Id>();
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        Map<Id, Set<String>> mapAccountProductLine = new Map<Id, Set<String>>(); //Use to know if the related account has Product Line into AccountCoreBusiness
        Map<String, Boolean> mapCoreProductLine = new Map<String, Boolean>(); //Use to know if the product line is Core
        
        List<Opportunity> listOpp = [SELECT Id, Product_Line__c, AccountId, SubSalesPurpose__c, Sales_Purpose__c FROM Opportunity WHERE Id IN : setOppIds];
        For(Opportunity opp:listOpp){
            setProductLineCode.add(opp.Product_Line__c);
            setAccountId.add(opp.AccountId);
        }
        //Get related AccountCoreBusiness__c of the account and fill the map
        List<AccountCoreBusiness__c> listAccountCoreBusiness = [SELECT AccountExpertise__r.Account__c, ProductLine__c FROM AccountCoreBusiness__c 
                                                                WHERE AccountExpertise__r.Account__c IN : setAccountId AND ProductLine__c IN: setProductLineCode];
        if(!listAccountCoreBusiness.isEmpty()){
            for(AccountCoreBusiness__c acb:listAccountCoreBusiness){
                if(!mapAccountProductLine.containsKey(acb.AccountExpertise__r.Account__c)){
                    mapAccountProductLine.put(acb.AccountExpertise__r.Account__c, new Set<String>{acb.ProductLine__c});
                }else{
                    Set<String> setString = mapAccountProductLine.get(acb.AccountExpertise__r.Account__c);
                    setString.add(acb.ProductLine__c);
                    mapAccountProductLine.put(acb.AccountExpertise__r.Account__c, setString);
                }
            }
        }
        //Get Product Line and fill the map
        List<Product_Line__c> listProductLine = [SELECT Core__c, API_Code__c FROM Product_Line__c WHERE API_Code__c IN: setProductLineCode];
        if(!listProductLine.isEmpty()){
            for(Product_Line__c pl:listProductLine){
                mapCoreProductLine.put(pl.API_Code__c, pl.Core__c);
            }
        }
        system.debug('mapAccountProductLine '+mapAccountProductLine);
        system.debug('mapCoreProductLine '+mapCoreProductLine);
        
        //Fill "Sub Sales Purpose" on opp
        For(Opportunity opp:listOpp){
            if(opp.Sales_Purpose__c != '411'){
                opp.SubSalesPurpose__c = null;
            }else if(mapCoreProductLine.containsKey(opp.Product_Line__c) && mapCoreProductLine.get(opp.Product_Line__c) == false //Check product line is non-core
               && (!mapAccountProductLine.containsKey(opp.AccountId) || (mapAccountProductLine.containsKey(opp.AccountId) && !mapAccountProductLine.get(opp.AccountId).contains(opp.Product_Line__c)))){ //Check account don't have Product Line into "Account Core Business"
                   opp.SubSalesPurpose__c = 'Upsell Only - New Product';
               }else{
                   opp.SubSalesPurpose__c = 'Upsell Only - More of the same';
               }
            oppToUpdate.add(opp);
        }
        update oppToUpdate;
    }
}