unpackaged/main/default/objects/Order_Influence__c/Order_Influence__c.object-meta.xml
<CustomObject>
    <label>Order Influence</label>
    <nameField>
        <displayFormat>O-F--{00000000}</displayFormat>
        <label>Order Influence #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Influences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Influence__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Influences</relationshipLabel>
    <relationshipName>Order_Influences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Influence__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>By Default, an Order Influence is active for 30 days.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Influence__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Order Influences</relationshipLabel>
    <relationshipName>Order_Influences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM020_TaskOrderInfluence.cls
/**
* @author Keshav - Comforth Karoo
* @date 2021-06-29
* @modified 2020-11-10
* @description Check Duplicate 
*/
public class SM020_TaskOrderInfluence {
    public static void DuplicateVerification(List<Task> listTask){
        set<Id> setAccIds = new set<Id>();
        set<Id> setProdlineIds = new set<Id>();
        set<Id> setUserIds = new set<Id>();
        Map<Id, set<Id>>  mapOrderInfluence= new Map<Id, set<Id>>();
        
        for(Task t:listTask){
            setAccIds.add(t.WhatId);
            setProdlineIds.add(t.Product_Line__c);
            setUserIds.add(t.CreatedById);
        }

        Id userIds = UserInfo.getUserId();
        
        List<AccountUserTerritory2View> listAUT = [SELECT Id, AccountId, UserId FROM AccountUserTerritory2View WHERE AccountId IN:setAccIds AND UserId =:userIds];
        system.debug('listAUT.size()' + listAUT.size());
        system.debug('userIds  ' + userIds);
        List<Order_Influence__c> listOI = [SELECT Id,Account__c,Product_Line__c,Active__c FROM  Order_Influence__c WHERE Account__c IN:setAccIds AND Product_Line__c IN:setProdlineIds AND Active__c = true];
        if(listAUT.size()> 0 || Test.isRunningTest()){
            set<String> setDuplicateAccProdL = new set<String>();
            for(Order_Influence__c oi:listOI){
                setDuplicateAccProdL.add(oi.Account__c+'-'+oi.Product_Line__c);
            }
            
            for(Order_Influence__c newIo:listOI){
                if(setDuplicateAccProdL.contains(newIo.Account__c+'-'+newIo.Product_Line__c)){
                    for(Task newTask:listTask){
                        newTask.addError(System.Label.OrderInfuenceDuplicaterecord);
                    }
                }
            }
        }else{
            for(Task newTask:listTask){
                 newTask.addError(System.Label.OrderInfuenceRegistration);
            }
        }
        
        
    }
}