unpackaged/main/default/objects/Order_Influence__c/Order_Influence__c.object-meta.xml
<CustomObject>
    <label>Order Influence</label>
    <nameField>
        <displayFormat>O-F--{00000000}</displayFormat>
        <label>Order Influence #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Influences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Influence__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Order Influences</relationshipLabel>
    <relationshipName>Order_Influences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TH_Task.cls
/**
* @author Keshav - Comforth Karoo
* @date 2021-06-29
* @modified 2020-11-10
* @description Trigger handler class for Order_Influence__c
*/
public  with sharing class TH_Task extends TriggerHandler{
    public override void beforeInsert(){
        Boolean createOrderInf = false;
        for(Task t:(List<Task>)Trigger.new){
            if(t.Generates_Order_Influence__c == true && t.Product_Line__c != null){
                createOrderInf = true;
            }
        }
        
        if(createOrderInf){
           SM020_TaskOrderInfluence.DuplicateVerification(Trigger.New); 
        }
    }
}